### ISSUE TITLE
MonadCancel: New Typeclass Above Concurrent

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1016]
This would have `forceR`, `canceled`, `uncancelable`, and `onCancel`. The purpose to this is it generalizes things very slightly. More specifically, you can define this class for `StateT` and `RWST` (whereas you cannot define a sane `Concurrent` for these). This definition has value, too, since it allows `State`-using code to participate in cancelation semantics of some underlying `Concurrent` type, which is impossible at present.

In a sense, this would be the conceptual replacement for `Bracket`, and indeed, `bracket` would be a derived combinator on this typeclass.

**Comment by RaasAhsan** [comment]
Have you given any thought to `bracket` on `Sync`? Both [cats.effect.SyncIO](https://github.com/typelevel/cats-effect/blob/series/2.x/core/shared/src/main/scala/cats/effect/SyncIO.scala#L146) and [monix.eval.Coeval](https://github.com/monix/monix/blob/master/monix-eval/shared/src/main/scala/monix/eval/Coeval.scala#L466) define `bracket`.

If you take the perspective that `bracket` is an operation that guarantees safe acquisition and release even in the presence of exceptions, then it makes sense to define something like it on `Sync` too. The difference between that and `bracket` on the proposed typeclass is that the latter has extra machinery to handle cancellation, which I consider a kind of asynchronous exception.

The immediate problem I can see is: what does the `Sync.bracket` operation mean for a type that is also `Async` and `Concurrent`?

**Comment by djspiewak** [comment]
> Have you given any thought to bracket on Sync? Both cats.effect.SyncIO and monix.eval.Coeval define bracket.

My general thought is that I don't see how it's really all that different from `.attempt.flatTap(...)` (aside from potentially requiring less boxing). Like, you can define `bracket` for any `MonadError`; it doesn't add any power. I think part of the reason it exists on `SyncIO` and `Coeval` is the fact that CE2 put `Bracket` above `Sync`, meaning that you *have* to define it for `SyncIO` and `Coeval`.

I guess the real question is: how useful is that, really? I feel like `bracket` is more an operation that guarantees safe acquisition and release in the presence of short-circuiting, which can take on many forms (characterized by `forceR`). So perhaps from that standpoint it's useful to talk about it in `SyncIO`, though that sets up a weird situation where `SyncIO` can self-cancel, but cannot be canceled.

**Comment by LukaJCB** [comment]
We could also think about adding something like `forceR` to `MonadError` and in `MonadCancel` add a law that requires it to also handle the cancel case?

**Comment by djspiewak** [comment]
That's not a horrible approach tbh.
