### ISSUE TITLE
IOApp no longer shuts down its thread pools

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1018]
It uses global, which doesn't have a working `shutdown()`, meaning that `IOApp` actually can't shut its pools down. We should probably poke a hole in `IORuntime` for "unsafe shutdown" or something so that `IOApp` can actually do this, since it's probably the *only* place where we can safely shutdown global.

**Comment by mpilquist** [comment]
Why does it need to be shutdown? They are all daemon threads.

**Comment by djspiewak** [comment]
Basically just for build tools that don't play the same game that sbt does *now*. Sbt today uses `SecurityManager` hooks and side-effects to track every `Thread` created by processes, specifically so it can clean them up later. It didn't back in 0.13 though, and I don't know what other build tools do this. Any tool which "forks" by classloader trickery within a resident vm will need us to clean up the threads for them.

**Comment by RaasAhsan** [comment]
Might be related, but Ctrl+C in SBT (with or without forks) doesn't shut down any of my apps like I remember it doing in CE2

**Comment by djspiewak** [comment]
> Might be related, but Ctrl+C in SBT (with or without forks) doesn't shut down any of my apps like I remember it doing in CE2

Really? We actually test this in CI so I'm very surprised. :-)

**Comment by vasilmkd** [comment]
So the status on this is the following (asuming fork := false):

1. The Ctrl+C signal is properly detected by IOApps, and they stop in accordance.
2. This does not shutdown the global IORuntime because its shutdown method is a noop.
3. Running an IOApp again starts a new global IORuntime, it doesn't reuse the old one, so threads keep being spawned for each IOApp invocation in sbt.

**Comment by mpilquist** [comment]
Oh, that's no good... making shutdown a no-op was originally done to support calling `main(..)` from a REPL session. Not really a strong reason to keep that behavior as the default.

**Comment by vasilmkd** [comment]
I'm never sure if this behavior is depedent on specific versions of sbt, which makes me vary of attempting anything...

**Comment by djspiewak** [comment]
I *think* this is probably specific to sbt 1.4.x where x < 7. Cancelation in general didn't work on those versions. It's worth checking it on 1.4.7.

**Comment by vasilmkd** [comment]
I checked this on 1.4.7

**Comment by djspiewak** [comment]
Is this still broken?

**Comment by djspiewak** [comment]
I'm going to say "no", it's not broken, though I've seen some odd stuff with timers (see #2251).
