### ISSUE TITLE
Add cats.effect.unsafe.UnsafeRun to kernel

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1020]
Blegh…

In some cases where you're embedded into unsafe code which is running *you* and where you don't already have a natural runtime to fall back on, you need something like `UnsafeRun`. A good example of this is http4s-blaze. `Effect` doesn't solve this problem because the best http4s could do is pick a target effect type (say, `IO`) and convert `F` to `IO`, but then it needs an `IORuntime` in order to actually run that `IO`, and if someone is running in Monix or ZIO, they aren't likely to have one that makes sense.

`UnsafeRun` solves this problem at the cost of being really dumb and annoying, but sometimes you need it. `IOApp` should provide an instance for `IO`, with the constructor defined on `IORuntime`.

```scala
package cats.effect.unsafe

// intentionally incoherent
trait UnsafeRun[F[_]] {
  def unsafeRunFutureCancelable[A](fa: F[A]): (Future[A], () => Future[Unit])
}
```

**Comment by vasilmkd** [comment]
Picking this up.
