### ISSUE TITLE
Polling racePair

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1027]
`racePair` is inherently a leaky function since it returns a `Fiber` in its type signature. Because of that, we protect all invocations of `racePair` with `uncancelable` with the appropriate cancellations in place. For example, this is the definition of `raceOutcome`:
```scala
def raceOutcome[B](that: IO[B]): IO[Either[OutcomeIO[A @uncheckedVariance], OutcomeIO[B]]] =
  IO.uncancelable { _ =>
    racePair(that).flatMap {
      case Left((oc, f)) => f.cancel.as(Left(oc))
      case Right((f, oc)) => f.cancel.as(Right(oc))
    }
  }
```
Notice that in this definition (as well as `both`, `bothOutcome`, and `race`), `racePair` isn't wrapped in `poll`. It wasn't very obvious to me why we weren't doing this before, but why shouldn't we able to? If neither of the spawned fibers complete and we cancel, we should be able to cancel the entire operation. Additionally, `racePair` is internally defined in terms of `async` and registers a finalizer that cancels both fibers, but we don't really expose a library call that exercises that behavior.

Here's why we can't do it. Let's add a `poll` around `racePair` in the above definition:
```scala
def raceOutcome[B](that: IO[B]): IO[Either[OutcomeIO[A @uncheckedVariance], OutcomeIO[B]]] =
  IO.uncancelable { poll =>
    poll(racePair(that)).flatMap {
      case Left((oc, f)) => f.cancel.as(Left(oc))
      case Right((f, oc)) => f.cancel.as(Right(oc))
    }
  }
```
This looks like it should work, but this is in fact leaky as well. The problem lies in the operational semantics of `Async` and `Unmask` and how they interact. When `poll` is called, the argument is wrapped in an `Unmask` which drops the mask for the duration of the inner `IO`, allowing cancellation. After the inner `IO` completes, the mask is restored. On the other hand, when an `Async` completes, it pops its finalizer before re-entering the runloop. So if we happen to observe cancellation between the time the finalizer is popped and the time we restore the mask, we would end up leaking the `Fiber`.

The crux of the problem here is that the scope of unmasking by `poll` and the scope in which the async finalizer remains registered don't completely coincide, or at the very least, they don't share the same point of completion. In particular, the finalizer can be deregistered before we restore a mask.

I don't think this is a bug, but it certainly introduces some gaps where cancellation is conceptually appropriate but can't be finalized correctly.

**Comment by djspiewak** [comment]
This is a terrific observation and worth more thought. The present situation basically means that `race` and such are entirely uncancelable, which is really not great at all. Honestly, the fact that `onCancel` cannot be distributed inside of a `poll` is kind of annoying, and it makes me wonder if we need to special-case that in some way. Then again, doing so would be insufficient since what we're talking about here is async cancelation, so the finalizer isn't in an `onCancel` in the first place.

**Comment by djspiewak** [comment]
I don't have time to write this up more thoroughly, but I think the only answer to this from a theoretical standpoint is to say that a finalizer window is closed at the front and *open* at the back. By that I mean, it includes the bind which immediately follows it. There are some subtleties with this with respect to associativity though, and I'm not sure how the implementation would work, but it does give users a way of dealing with this problem in general.

Note that as a practical matter, I believe that we actually might not be able to observe cancelation in the window you reference, but it seems possible for other implementations.

**Comment by RaasAhsan** [comment]
Wouldn't that violate the monad identity laws?
```scala
poll(racePair(a, b).flatMap(identity)).flatMap(...) <-> poll(racePair(a, b)).flatMap(...)
```

**Comment by djspiewak** [comment]
Yeah I was thinking about that a fair bit. There's a similar problem with `map`. We effectively don't know where to "stop". It still feels though that there's something a little wrong about the fact that `onCancel(fa, fin1) *> onCancel(fb, fin2)` has an unavoidable gap.

**Comment by djspiewak** [comment]
Some operational analysis (specific to our `IO`; others may do it differently and this is worth thinking about in abstract as well):

1. The `async` in `RacePair` completes with a winner. This trips `loop` and `asyncContinue` and all that jazz
2. The very first thing `loop` does is drop the finalizer, which puts us into a critical section where we *might* leak a fiber. It has, however, acquired the runloop before it does this, meaning that we no longer need to worry about async cancelation, and only the cancel check at the front of each runloop iteration
3. `asyncContinue` checks cancelation. **At *this* point, if cancelation is visible, we leak**
4. `asyncContinue` bounces through the execution context and hits the continuation stack
5. The head of the continuation stack will be `UnmaskK`, which restores the mask and suppresses cancelation
6. *other continuations happen*
7. We eventually make it back to the runloop, which performs the cancelation check. We're masked now though, so it will be ignored

The only leak here is in **3**. This makes me wonder if we should perform the cancelation check *before* popping the finalizer.

**Comment by djspiewak** [comment]
I think all of this stuff is now fixed?
