### ISSUE TITLE
Create a migration guide

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1048]
We need to document all the changes we've made in operational terms, so that people know what new type class to use, what functions moved around, what semantics are new can old (especially this!), etc etc. Basically everything you need to know to upgrade to 3.0.

**Comment by Daenyth** [comment]
Collecting some notes as I go:


## unsafeToFuture()
```scala
import cats.effect.implicits._

def beforeF[F[_]: Effect, A](fa: F[A]): Future[A] = fa.ioIO.unsafeToFuture()
// Note: Using a `Dispatcher` resource is cheap - don't worry about it
def preferredAfterF[F[_]: Async, A](fa: F[A]): F[Future[A]] = Dispatcher[F].use(_.unsafeToFuture(fa))

// Note: It's not certain whether dispatcher passed implicitly will be the canonical style, or whether it will be explicit argument instead
def ifNeededAfterF[F[_], A](fa: F[A])(implicit D: Dispatcher[F]): Future[A] = d.unsafeToFuture(fa)


def beforeIO[A](ioa: IO[A]): Future[A] = ioa.unsafeToFuture()
def afterIO[A](ioa: IO[A]): IO[Future[A]] = Dispatcher[IO].use(_.unsafeToFuture(ioa))
def ifNeededAfterIO(ioa: IO[A])(implicit D: Dispatcher[IO]): Future[A] = D.unsafeToFuture(ioa)
```

## unsafeRunSync()
```scala
import cats.effect.implicits._

def beforeF[F[_]: Effect, A](fa: F[A]): A = fa.ioIO.unsafeRunSync()
// Avoid this pattern; instead wrap both the `unsafeRunSync` call *and* the thing that needs it, so that it can be contained within the scope of a `Dispatcher[F].use(...)` block.
def ifNeededAfter[F[_], A)(fa: F[A])(implicit D: Dispatcher[F]): A = D.unsafeRunSync(fa)

def beforeIO[A](ioa: IO[A]): A = ioa.unsafeRunSync()
def afterIO[A](ioa: IO[A]): A = ioa.unsafeRunSync()
```

## Async.fromFuture
```scala
def futureApi(): Future[Int]
def before[F[_]: Async: ContextShift]: F[Int] = Async.fromFuture(Sync[F].delay(futureApi()))
def after[F[_]: Async]: F[Int] = Async[F].fromFuture(Sync[F].delay(futureApi()))
```

## Async.async
```scala
def intCallback(cb: Either[Throwable, Int] => Unit): Unit

def before[F[_]: Async]: F[Int] = F.async[Int](cb => intCallback(cb))

// Note: 'async_', not 'async' - the 'async_' version preserves the old signature
def after[F[_]: Async]: F[Int] = F.async_[Int](cb => intCallback(cb))
```

## TestContext
```scala
// before; libraryDependencies on cats-effect-laws
import cats.effect.laws.util.TestContext

// after; libraryDependencies on cats-effect-testkit
import cats.effect.testkit.TestContext
```

**Comment by kubukoz** [comment]
just some ideas for now, I can expand them later. There's plenty left in the readme too:

ContextShift -> Async
Timer -> Temporal
Effect -> Dispatcher (UnsafeRun is gone)
Blocker -> Sync.blocking
Concurrent -> possibly Async or Sync, or even Spawn depending on usage
Bracket -> MonadCancel
shift -> cede (or nothing)
ExitCase -> Outcome/ExitCase
uncancelable -> uncancelable+poll
creating Ref/Deferred -> Ref.Make/Deferred.make
`Throwable` type aliases / `E`-parameterized typeclasses
getting a compute EC - Async

**Comment by bplommer** [comment]
`Semaphore#withPermit(...)` -> `Semaphore#permit.use(_ => ...)`

**Comment by kubukoz** [comment]
@bplommer hopefully that'll be made less cumbersome with #1338

**Comment by kubukoz** [comment]
If nobody beats me to it, I'll take this one of these days and make something structured.

Note to self: start with the new artifacts.

**Comment by kubukoz** [comment]
I have... a branch! And a heading!

![image](https://user-images.githubusercontent.com/894884/107156084-7e414500-697c-11eb-9076-78ec1cc77e7f.png)

**Comment by djspiewak** [comment]
The heading and first sentence are always the hardest part

**Comment by kubukoz** [comment]
Progress so far: https://github.com/typelevel/cats-effect/pull/1687
