### ISSUE TITLE
Create a migration scalafix

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1049]
I have no idea how scalafix stuff works, but given it's limitations, I do suspect it can handle most of the 2 -> 3 migration in many cases. At least it's worth a shot!

**Comment by fthomas** [comment]
I've a basic skeleton for the migration scalafix ready at https://github.com/typelevel/cats-effect/compare/series/3.x...fthomas:topic/scalafix which now needs to be filled with patches.

I'm aware of the following changes, that could be added to the scalafix:
* `Bracket -> MonadCancel`
* `Bracket#guarantee(a)(b) -> MonadCancel#guarantee(a, b)`

Which other changes should it rewrite?

**Comment by djspiewak** [comment]
Ooooooh huzzah!

Other random changes:

- `async` -> `async_` in many cases (and `cancelableF` -> `async`, as well as the other variations of it)
- `suspend` -> `defer`
- `F.uncancelable(fa)` -> `F.uncancelable(_ => fa)`
- `join` -> `joinAndEmbed` (actually `joinWithNever` - correction by @kubukoz)
- `ExitCase` -> `Outcome`
- Some package name changes (e.g. `Semaphore` was in `concurrent` and is now in `std`; `Ref` and `Deferred` are in `cats.effect`)
- `Resource#parZip` -> `both`
- Delete `ContextShift` entirely
- Delete `Blocker` entirely
- Any concrete-type implicit constraints (such as `Concurrent[IO]`) can be deleted entirely because they're now universally available
- `blocker.delay(...)` needs to be `Sync[F].blocking(...)`, though that might not be possible, depending on whether or not you can figure out the type of `blocker`
- It's too bad it's probably impossible to help people out with `ExecutionContext`s they've been passing around in lieu of the new `executionContext` effect
- `ContextShift[F].shift` -> `Spawn[F].cede`. This is a slightly weird one because `shift` also does other things, but I'd wager that 99% of the time when people use it, they mean what `cede` now does
- `async(...).guarantee(shift)` can just be `async(...)`
- There is some restructuring and renaming within the `Outcome` algebra vis-a-vis `ExitCase`. `Completed` vs `Succeeded(_)`, for example
- I don't think there's any way to automatically migrate `continual`

I think those are the biggest differences that can be automatically migrated? I'll probably think of some more things later.

**Comment by fthomas** [comment]
Thanks Daniel, this will keep me busy for a while. *rolling up my sleeves*

**Comment by djspiewak** [comment]
Thank you so much for tackling this!
