### ISSUE TITLE
Port CE2 IO optimizations to CE3 IO

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1055]
Cats Effect 2 IO introduced several optimizations that boosted performance of the runloop. Although it seems like Cats Effect 3 is already faster, we should consider whether any of those optimizations are worth porting. `redeem` and `attempt` requiring only one bind stack continuation is an important one that comes to mind for me.

**Comment by djspiewak** [comment]
Is this addressed by #1069?

**Comment by vasilmkd** [comment]
Any objections to closing this issue?
