### ISSUE TITLE
Set up a new documentation site

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1058]
Microsites is looking a little outdated compared to some of the newer static site generators. Docusaurus is one that's ridiculously easy to set up, has great interop with mdoc, and doesn't require you to install Ruby locally. 

Some concerns that we should address:
1. Cats Effect 2 and 3 are evolving on two different branches. How do we keep documentation for both series accessible while avoiding excessive maintenance overhead?
2. What framework should we use? Like I mentioned earlier, Docusaurus looks pretty nice, but might have to wrangle with it for our versioning needs. Jekyll, Hugo, Gatsby, Docsify are some others that I've seen
3. Features between versions can change drastically (even within the same series), so their documentation should be accessible separately.
4. GitHub Pages, Netlify etc?

Some Gitter conversations that we've had:
- https://gitter.im/typelevel/cats-effect-dev?at=5f165961a874ff08d28b9d51
- https://gitter.im/typelevel/cats-effect-dev?at=5f17b0999419f46bf5bf4ef8

**Comment by Avasil** [comment]
It's probably not the best place to discuss it but I was wondering if we could reuse more documentation in the Typelevel ecosystem.

There are a lot of similarities between effects, I imagine that CE3 and Monix Task will stay consistent in most of the aspects and the main difference with monix-bio will be error handling.

For instance, I have this [Resource Safety](https://bio.monix.io/docs/resource-safety) section in `monix-bio` docs. It could be exactly the same for CE2 IO and Monix Task, the only difference is code snippets.

There are more differences in error handling but there's still a lot to share and if there is a section about "typed" errors then it could use `Either` / `cats-mtl` / `IO[E, A]` in examples with references to each other and pros and cons of each method.

I would love it if we could find a way to do it. Ideally, it could be automated so it's not a nightmare to keep it up to date. I'm just throwing a random idea, I don't know how to do it yet. :D I feel like it would be much easier to produce high-quality documentation in the ecosystem given there aren't many people who write it and coming up with good examples can be a pain.
