### ISSUE TITLE
Would love to help maintain cats-effect.

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats-effect#107]
Per [discussion here](https://gitter.im/typelevel/cats-effect?at=5a4bd25281cd9a5d7ea244c0) I would love to help maintain cats-effect. Can I apply for maintainership?

**Comment by rossabaker** [comment]
:+1:

**Comment by ChristopherDavenport** [comment]
Also would like to make myself available in this regard. I keep track and attempt to stay informed in regard to all changes to cats-effect. I'd love to volunteer to help maintain.

**Comment by alexandru** [comment]
@kailuowang @ChristopherDavenport you're very welcome to join, but besides @djspiewak the project already has at least 3 declared and active maintainers, myself and @mpilquist, along with @rossabaker, and we also need Sonatype access.

**Comment by alexandru** [comment]
I've added a [comment on that JIRA](https://issues.sonatype.org/browse/OSSRH-4953?focusedCommentId=455276&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-455276) ticket.

**Comment by kailuowang** [comment]
I am going to close this for now. I agree with @alexandru that there are probably enough active maintainers at the moment. @ChristopherDavenport  if you are still interested becoming a maintainer, would you mind submit another issue? Thanks
