### ISSUE TITLE
new release number change?

### ISSUE THREAD

**Issue by ThStock** [typelevel/cats-effect#1071]
I've seen new version with an (for me) unknown pattern e.g. 3.0-8096649 ... are this still RC or final versions?

https://mvnrepository.com/artifact/org.typelevel/cats-effect

**Comment by Avasil** [comment]
It might be a snapshot from CE3 branch ( https://github.com/typelevel/cats-effect/tree/series/3.x) which is under active development

**Comment by djspiewak** [comment]
It's a snapshot. 😃 We have also released snapshots in the 2.x line, but much less often recently. Expect to start seeing milestones soon.
