### ISSUE TITLE
Replace CHM in tracing cache with thread unsafe hash table

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1076]
We don't actually need thread safety. We just need non-corruption in the event of concurrent writes, and we need barrier free optimized reads. We don't need to compute length, either. These properties can be achieved with a traditional collision-free hash table (where you grow on every collision) without any concurrent coordination or atomicity. In the event of a write conflict, one side loses data. However, it's just a cache, so the data will be recomputed.

The cache will be expected to converge very quickly to a state in which most of the program is indexed and cached. Once that happens, there are no further writes and thus reads should be barrier-free and require a minimum of instructions.

**Comment by RaasAhsan** [comment]
Relevent Gitter discussion: https://gitter.im/typelevel/cats-effect-dev?at=5f3403431f13b45edb71ccdd

**Comment by djspiewak** [comment]
This is done in series/3.x

**Comment by vasilmkd** [comment]
We tried it during the development cycle of tracing for CE3 and it wasn't faster.
