### ISSUE TITLE
Remove auto-supervision semantics in joinAndEmbedNever

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1082]
During migration efforts, people seem to be mostly using `joinAndEmbedNever` as a replacement for OG `join`, and honestly that makes a lot of sense. The current implementation attempts to self-cancel though, and while that's a useful semantic with some more machinery around it, it doesn't make sense as a replacement for CE2 `join`. I think it would be better to change `joinAndEmbedNever` to mirror CE2's semantics directly: skipping the self-cancelation and just sequencing `never` when the child fiber cancels.

**Comment by SystemFw** [comment]
Fixed by #1108
