### ISSUE TITLE
Set up infrastructure for new docs branch

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1083]
- [ ] Probably just a manually written GitHub Action which builds and pushes to gh-pages
- [ ] Submodules for series/2.x and series/3.x

**Comment by RaasAhsan** [comment]
The `docs` branch has a working deployment of Docusaurus. Several things we need to iron out:
1. Landing page contents
2. Versioned scaladocs
3. How we want to track different release series
