### ISSUE TITLE
Include IO.delay and IO.suspend in cached stack tracing

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1085]
`IO.delay` and `IO.suspend` both accept a thunk, which look like `=> A` and `=> IO[A]` respectively. The class for those thunks are stable to the constructor, so its class serves as a suitable cache key for cached stack tracing mode.

My only concern with this is performance (especially when tracing is disabled): `Delay` and `Suspend` start taking an extra constructor argument, so there's an object header size bump for both of them. But it really isn't that significant and I'm quite positive nobody will notice. #1076 will improve the situation a lot as well.

**Comment by djspiewak** [comment]
Fwiw, we are now doing exactly this.
