### ISSUE TITLE
Would love to help maintain #2

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/cats-effect#109]
I'd love to help maintain cats-effect as mentioned in #107. I'm pretty handy in a pinch and feel I can be of assistance as needed.

**Comment by alexandru** [comment]
:+1:

**Comment by alexandru** [comment]
@ChristopherDavenport I am not sure who has the capability of making you a collaborator, such that you can merge stuff.

@kailuowang can you do that?

**Comment by kailuowang** [comment]
I can't. cc @djspiewak, @larsrh, @milessabin

**Comment by larsrh** [comment]
Done.

**Comment by ChristopherDavenport** [comment]
Thank you all. Closing.
