### ISSUE TITLE
Improve performance of enhanced exceptions

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1090]
This is a followup for #1077. The machinery for enhanced exceptions relies on several `List` and `Array` functions to manipulate the stack trace of exceptions. There isn't going to be a noticeable performance hit for anyone, but I think we can probably write a more efficient implementation.

**Comment by adrian-2414745** [comment]
Any pointers here ?
My only idea is to use Scala's 2.13 new mutable.ArrayDeque

**Comment by djspiewak** [comment]
I love that we tagged this "good first issue" and then somehow managed to miss the comment of someone asking for tips on how to go about it. Go us! :-/

Glancing at `Tracing.augmentThrowable` in CE3, it appears that this was addressed when enhanced exceptions were reimplemented on that branch. I don't see any obvious way that performance can be improved.
