### ISSUE TITLE
Fix exhaustiveness issues in Resource on Dotty

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1096]
The warnings are legit. They should be fixed. Run `sbt ++0.26.0-RC1 coreJVM/compile` to reproduce.

**Comment by TimWSpence** [comment]
After discussion with @djspiewak we think this should probably be closed for now as we don't believe the issues are fixable whilst keeping our current variance semantics (discussion of this [here](https://gitter.im/lampepfl/dotty?at=5f3d25b08b8d4f633e003717))

The pattern match warnings are an actual bug in Dotty which is being tracked [here](https://github.com/lampepfl/dotty/issues/9603)

You can see my attempt to fix the other warnings (runtime typechecks) [here](https://github.com/typelevel/cats-effect/pull/1105) . Unfortunately, these cause 2.12 to lose its mind:

```
[error] /home/runner/work/cats-effect/cats-effect/core/shared/src/main/scala/cats/effect/Resource.scala:114:18: constructor cannot be instantiated to expected type;
[error]  found   : cats.effect.Resource.Allocate[F,A]
[error]  required: cats.effect.Resource[?G1,Any] where type ?G1 <: G (this is a GADT skolem)
[error]         case a @ Allocate(_) => {
[error]                  ^
[error] /home/runner/work/cats-effect/cats-effect/core/shared/src/main/scala/cats/effect/Resource.scala:127:18: constructor cannot be instantiated to expected type;
[error]  found   : cats.effect.Resource.Bind[F,S,A]
[error]  required: cats.effect.Resource[?G2,Any] where type ?G2 <: G (this is a GADT skolem)
[error]         case b @ Bind(_, _) => {
[error]                  ^
[error] /home/runner/work/cats-effect/cats-effect/core/shared/src/main/scala/cats/effect/Resource.scala:131:18: constructor cannot be instantiated to expected type;
[error]  found   : cats.effect.Resource.Suspend[F,A]
[error]  required: cats.effect.Resource[?G3,Any] where type ?G3 <: G (this is a GADT skolem)
[error]         case s @ Suspend(_) => {
```

So it seems that if we use the current runtime typecheck style then Dotty issues a warning but if we use actual pattern matching then 2.12 explodes. Therefore I think we're stuck with dotty warnings while we support 2.12 (unless someone can suggest a significantly different encoding)

**Comment by mpilquist** [comment]
@TimWSpence I think the approach you outlined is good. In fs2, I was able to get things cross compiling on 2.12/2.13/0.26 by (1) adding variance annotations to constructors when possible (2) keeping the type ascription matches and replacing the problematic type params with `_` and then casting inside the body of the case. You can see a lot of that in Algebra.scala in this PR: https://github.com/functional-streams-for-scala/fs2/pull/1973/files#diff-91195044dae5827508d46a79e123c46a

**Comment by SystemFw** [comment]
Feel free to have a look at #1102 as well if you want to have more fun with this. FYI, I think I've hit at least one case of the failure being non deterministic...

**Comment by TimWSpence** [comment]
Thanks @mpilquist and @SystemFw! I'll have a look next week :)
