### ISSUE TITLE
Add CE3 to the Dotty community build

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1097]
Helpful links:
1. https://github.com/lampepfl/dotty/tree/master/community-build
2. https://github.com/lampepfl/dotty/tree/master/community-build/test/scala/dotty/communitybuild#adding-your-project
3. https://docs.google.com/presentation/d/16CQXnPttM9CS4Lo-ZfEV6kw-Si2lXR9MwTJv1mvZLCI/edit#slide=id.p

**Comment by vasilmkd** [comment]
PR submitted.
https://github.com/lampepfl/dotty/pull/9784

**Comment by vasilmkd** [comment]
CE3 is officially a part of the dotty community build.
