### ISSUE TITLE
Configure sbt-scoverage + Codecov.io for test coverage

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#11]
Lets get some test coverage stats.

**Comment by djspiewak** [comment]
I don't have any overriding objections to this.  In general, I really dislike coverage tools.  The statistics they give are generally unhelpful: often misleading, seldom uncovering underlying issues, and can lead to unexpected tail-chasing to "make the numbers go up".  However, I acknowledge that my own use of these tools is not emblematic of everyone's.  :-)

If other people find value in hooking up coverage, then I have no objections.

**Comment by alexandru** [comment]
You're right that the statistics are sometimes misleading, but our target isn't perfect coverage, just *good enough* coverage.

In my experience coverage tools are helpful because they can point to untested problematic areas / branches. I've found some serious problems this way.

Also the tail-chasing you're mentioning is real, but it can lead to helpful tests or contributions from newcomers, which is cool.

If you don't want to bother with this ATM, that's fine, it's not an emergency.

**Comment by djspiewak** [comment]
I would merge a PR.  :-)

**Comment by rossabaker** [comment]
I've gotten some insight out of running codecov and a lot of irritation out
of it failing builds, particularly patch coverage. I prefer a configuration
where it's advisory instead of compulsory.
