### ISSUE TITLE
Possibly eliminate Resource.ExitCase

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1110]
In theory:

```scala
type ExitCase[E] = Outcome[Nothing, E, Nothing]
```

I would kinda like that to be the *actual* reality so we don't have two types floating around meaning almost the same thing.

**Comment by joroKr21** [comment]
Interesting, that kinda makes you want to have a covariant `Outcome` but it doesn't work because of `Completed` 🤔

**Comment by SystemFw** [comment]
I'm not sure I buy into this change. It feels like the change to Outcome is so big,  that you still have "two" types, except now one of them has a weird encoding rather than a straightforward ADT

**Comment by joroKr21** [comment]
It's a fun experiment. I don't know if it's useful for anything: #1114

**Comment by SystemFw** [comment]
Yeah, I commented after seeing the PR :)

It's nice to see that it's possible (btw, good job!), but it feels convoluted, it almost looks like newtype machinery

**Comment by djspiewak** [comment]
@SystemFw Conversely, having both `Outcome` and `ExitCase` feels like you have two mostly-overlapping types, with the only difference being that one cannot contain a value. I see that kind of situation and I get confused, as a consumer of the API, since I don't understand why they aren't unified in some way.

**Comment by SystemFw** [comment]
Yeah, it's definitely a bit annoying, although I think that as maintainers we get more annoyed by duplication. Worth reiterating for context that you can also make `Resource` work with `Outcome` left unchanged, at the cost of losing `mapK`.

The question is whether the duplication is more confusing than seeing `Outcome[Void, Throwable, Nothing]` (especially the `Void`). Semi-related question, is pattern matching affected by that encoding at all?

**Comment by djspiewak** [comment]
Okay almost everyone disagrees with me on this one. I'm going to put this one in the bucket of "would make Daniel happier but probably make everyone else less happy" and close it.
