### ISSUE TITLE
Lightweight async boundaries

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1118]
Unlike CE2, the CE3 `IO.Async` encoding internally shifts (i.e. resubmits to the executor) after returning from an asynchronous operation. This is great for fairness, but sometimes the extra shift is unnecessary, especially when we know that the asynchronous operation was already in the run-loop. A good example of this is `racePair`, where the winning fiber will resume the supervisor fiber's runloop *after* internally shifting. Internally shifting like this hurts the performance of most `Parallel` operations like `parMapN` and `parTraverse`, which are implemented in terms of `racePair`.

In the cases where we absolutely know we'll be returning from the runloop and don't necessarily have to shift, it might not be worth shifting at all. Assuming we don't shift, the obvious problem is stack safety, so we need to address that somehow. Some ideas:
1. ~The current runloop tracks a depth counter to guarantee stack safety on repeated `map` applications. Maybe we can reuse that, but we would probably have to define a separate one for async. After the max threshold is exceeded, we would just do a regular shift.~ This won't work because a runloop-local depth tracker doesn't account for stack frames introduced by another fiber.
2. CE2 uses a special trampolining `ExecutionContext` to resubmit certain async operations to.

Lightweight async boundaries should *not* be exposed in the public API at all! If we end up doing this, benchmarks are important!

This work relates to the outcomes of #1025 and #1095.

**Comment by djspiewak** [comment]
Btw an easy solution here is adding a Boolean to the IO.Async node. It would have a minor impact on construction costs, but would allow us to special case this for internal usage if we want to.

**Comment by djspiewak** [comment]
> If we end up doing this, benchmarks are important!

I agree on this point, though we already have benchmarks which cover the relevant cases here. We would definitely be able to see it `AsyncBenchmark`.

Regarding the stack safety issue, I agree that's something we should think about a bit. I *think* we'll be okay in all practical cases, and we could potentially address it more comprehensively in a follow-up PR. Alternatively, we could thread the trampoline counter through `async`, I think, and it wouldn't be the end of the world.

**Comment by vasilmkd** [comment]
I think this deserves a bit more recognition (benchmark results, especially `racePair`).
https://github.com/typelevel/cats-effect/pull/1134#issue-473475891

Just a bit more motivation. 😆

**Comment by RaasAhsan** [comment]
So I'm taking a look at this again and neither of these approaches seem very feasible because shifting takes place after a callback. In `racePair`, neither fibers are aware of each other, so we have to pass the child depth counters through two boundaries: through a fiber completion and through async. Both of these are kind of intertwined with the public API so that makes it more troublesome. 

The trampolined execution context also doesn't work unless we know the resumption occurred within the runloop (this is the key to solving this problem).

**Comment by djspiewak** [comment]
So if we manually trampoline (using defer) and don't shift, do the fibers actually need to be aware of each other? I'm specifically thinking of the async which they're racing to complete. Also a related question: is the work stealing pool aware of this particular situation? If it is, then it actually doesn't matter too much if we shift. We probably need to benchmark it
