### ISSUE TITLE
Thinking about Ref.access

### ISSUE THREAD

**Issue by SystemFw** [typelevel/cats-effect#1129]
These are semi random thoughts, but worth discussing in my opinion. Vaguely related to #1116 

Basically, what are your thoughts on `Ref.access`?
On one hand it's the most general method on current Ref, because it's the one that allows you to not loop automatically (unlike modify), so we cannot just take that power away, even though `access` is ~never used directly in the ecosystem I don't think.

On the other hand, the fact that it requires an internal `AtomicBoolean` per call irks me, and also causes things that implement `Ref`, like `fs2.Signal`, to require `Sync`.

The alternatives I can see are:
- keep `access` as is, `Signal` does not implement `Ref`.
- remove the `AtomicBoolean` from access (note: this was the case for several years and I don't think anyone was ever bitten by it, but strictly speaking the semantics described in the scaladoc require it).
- remove `access`, but expose `CAS` in `Ref`. Exposes reference equality.

Thoughts?

**Comment by RaasAhsan** [comment]
`access` did let us implement combinators like `updateMaybe` (after the `Ref` trait was defined) in a way that preserved compatibility, so it's definitely useful.

> On the other hand, the fact that it requires an internal AtomicBoolean per call irks me, and also causes things that implement Ref, like fs2.Signal, to require Sync.

Isn't `Sync` the least powerful class necessary to implement `Ref` anyways? e.g. you need to suspend `get` and `set` in `F`

**Comment by SystemFw** [comment]
> Isn't Sync the least powerful class necessary to implement Ref anyways? e.g. you need to suspend get and set in F

Not in this case. Signal is a composite structure that extends Ref, and can be implemented with `Allocate`, except for `access`, except I just realised another alternative, i.e. using a `Ref[Boolean]` :)

I still find the initial question interesting: we have swapped exposing Reference equality with requiring an AtomicBoolean

**Comment by SystemFw** [comment]
As it turns out this is not the a problem: Signal does not need its own check as the condition is already checked by the underlying Ref
