### ISSUE TITLE
Mk and MkIn

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1151]
Opened by #1145.  `Mk` and `MkIn` are classes that were used to create concurrent data structures like `Ref`, `Deferred`, `MVar` and `Semaphore`. As of #1145, they're no longer needed for `Ref` and `Deferred` since those a captured in the typeclass hierarchy now. This brings up several discussion points:
1. `Allocate` isn't capable of creating `Ref`s over `Sync` datatypes, since it's positioned below `Concurrent` in the hierarchy. The default implementation `SyncRef` only requires a `Sync` constraint though.
2. If we remove `Mk` and `MkIn` for `Ref` and `Deferred`, should they also be removed for `Semaphore` and `MVar`? Having disparities in constructors would arguably be confusing for users.
3. Do we need a replacement for `MkIn` in `Allocate`? Something like `def refIn[G[_]: Sync](a: A): G[Ref[F, A]]`

**Comment by SystemFw** [comment]
Quick thoughts:
1) this is the sticking point really. Either expose another named constructor that takes `Sync`, or we will need the equivalent of `Ref.Mk` to do prioritisation.
2) Yes they should for `Semaphore`, which is expressed with `Ref + Deferred`. What to do for `MVar` is kinda linked to its general fate, there is a good chance it will just disappear
3) I think the initial consensus was that they are not needed anymore

**Comment by djspiewak** [comment]
> this is the sticking point really. Either expose another named constructor that takes Sync, or we will need the equivalent of Ref.Mk to do prioritisation.

IMO, the answer here is to have the concrete constructors (i.e. `SyncRef`) take the appropriate constraint. So in other words, if you have a `Sync` and you want a `Ref`, you just don't get to use the abstraction. Not really a loss, since you already have a `Sync`.

> Yes they should for Semaphore, which is expressed with Ref + Deferred. What to do for MVar is kinda linked to its general fate, there is a good chance it will just disappear

Murder `MVar`. :-)

> I think the initial consensus was that they are not needed anymore

Yes! :-)

**Comment by SystemFw** [comment]
> Not really a loss, since you already have a Sync.

The fact that fs2 will need a `Ref.Mk` means it is a loss, but genuinely not sure if it's common enough to warrant `Ref.Mk` in cats-effect

**Comment by RaasAhsan** [comment]
I think we've addressed this with the new `Ref.Make` encoding
