### ISSUE TITLE
Make Ref and Deferred primitive in PureConc

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1153]
Opened by #1145. `PureConc` currently supports `MVar` as a primitive data structure. For the `Allocated` instance, we can derive `Ref` and `Deferred` from `MVar`, but there are safety concerns around deadlocking . Instead, we can define `Ref` and `Deferred` to be primitive in `PureConc` and derive `MVar` from it (if necessary). All of the uses of `MVar` that I know of should be substitutable by `Deferred`.

https://github.com/djspiewak/coop/blob/master/core/shared/src/main/scala/coop/MVar.scala

**Comment by djspiewak** [comment]
Still not convinced this is *strictly* needed, but I certainly have no objections to it. :-)

**Comment by djspiewak** [comment]
Going to close this one as "won't do". I hate `MVar` as much as anyone else, but it does suffice in this layer.
