### ISSUE TITLE
Proposal: Scheduler

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#116]
Any platform worth its salt will provide these fundamental operations for dealing with concurrency:

1. the ability to get the current time, usually as milliseconds since the epoch, useful in order to measure durations
2. thread / call-stack shifting — the ability to start executing something outside the current call-stack 
3. the ability to delay executing a task with a specified time duration

Any platform capable of asynchrony will provide these 3 fundamental capabilities and so must we.

Therefore, describing it as a type-class would be like this:

```scala
@typeclass trait Scheduler[F[_]] extends Async[F] {

  def currentTimeMillis: F[Long]

  def shift: F[Unit]

  def sleep(duration: Duration): F[Unit]
}
```

We could also think of it as a plain, parametrized data type:

```scala
trait Scheduler[F[_]] {

  def currentTimeMillis: F[Long]

  def shift: F[Unit]

  def sleep(duration: Duration): F[Unit]  
}
```

## Status Quo

**JavaScript**: 
 
- [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout) for (2) and (3)
- `new Date()` for getting the current timestamp
- [setInterval](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval) for repeated execution, but this can be expressed in terms of `setTimeout` + `new Date()`, so arguably these are the basic operations needed 😉

**Java**:

- `System.currentTimeMillis()` for (1)
- [Executor](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executor.html) for (2)
- [ScheduledExecutorService](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledExecutorService.html) for both (2) and (3)

Note that `ScheduledExecutorService` has the ability to do `scheduleAtFixedRate` (like JavaScript's `setInterval` above) and also `scheduleWithFixedDelay`. Both of these can be expressed just with simple `schedule` + `currentTimeMillis`.

**Scala**:

- `System.currentTimeMillis` for (1)
- [ExecutionContext](http://www.scala-lang.org/api/2.12.3/scala/concurrent/ExecutionContext.html) for (2)
- Scala does NOT have a standard answer for (3)

**Monix**:

- [Scheduler](https://monix.io/docs/2x/execution/scheduler.html), which can do (1), (2) and (3)
- `Task`, which can describe (1), (2) and (3) in a pure way

Monix's `Scheduler` might not be pure, but because it can do (1), (2) and (3) what this means is that in test we can *mock time* by means of [TestScheduler](https://github.com/monix/monix/blob/master/monix-execution/shared/src/main/scala/monix/execution/schedulers/TestScheduler.scala), such that time-based operators for `Task` or `Observable` become really easy to test.

**RxJava**:

- [Scheduler](http://reactivex.io/RxJava/javadoc/), which can also do (1), (2) and (3) — pretty similar

As an interesting titbit, Monix had the ability to give you the current time (e.g. `Scheduler.currentTimeMillis`) before RxJava 😉

## Use-cases

I have plenty of use-cases where I really need this in `Iterant`. Anything that involves time, for which I cannot use `System.currentTimeMillis`, let alone schedule a delay.

For example a method of throttling:

```scala
class Iterant[F[_], A] {

  def throttleFirst(period: FiniteDuration)(implicit F: Scheduler[F]): Iterant[F, A]
}
```

Or timed buffering:

```scala
class Iterant[F[_], A] {

  def bufferTimed(window: FiniteDuration)(implicit F: Scheduler[F]): Iterant[F, Seq[A]]
}
```

If I were to describe these operations for `Iterant` right now, I would have no choice but to specialize the implementation for `Task`.

## Possible Concerns

**Type-class would have coherence issues:** yes, but this could be an interface for a plain data type too.

**Is it too much?** — I don't think we can split these any further, because these operations are shipped together on all platforms and make sense together.

**Needs cancellable F?** — nope, it really doesn't. Delaying a task makes sense even without the ability to cancel it.

**Instance for cats.effect.IO is difficult to express?** — not really, we can keep a global `ScheduledExecutor` in the background, since you only really need one, that defers execution to your `ExecutionContext`. The only thing we'd need is the `ExecutionContext`.

But here's the best part about this: `IO` would no longer need to take an `ExecutionContext` for pure operations like `IO.shift`, it would take `Scheduler[IO]` instead and that instance can come from other places, like an underlying "RTS" (the way Scalaz 8 does it), thus decoupling these concerns.

And Monix's `Task` is able to define this instance without any implicit `ExecutionContext` or `Scheduler` needed, because it is able to describe all of them in a pure way already.

**Comment by SystemFw** [comment]
Does this need to be a typeclass? Scheduler in fs2 is a datatype (which for example can be shutdown), which would also fit better with the idea of having a TestScheduler (without incoherent instances)

**Comment by alexandru** [comment]
I've been going back and forth on this ... if you delete the `@typeclass` and the `extends Async[F]` parts, there would be much of a difference.

`shutdown` is a separate interface, because not all thread-pools can be shut down. In Monix I've taken the Java route, so I have `Scheduler` and `SchedulerService`.

**Comment by alexandru** [comment]
Your point on coherence is a very good one.

I have updated the description to admit a plain datatype.

**Comment by SystemFw** [comment]
I'm also still unconvinced (not opposed, but unconvinced) that this belongs to cats effect and not to each individual project, what would be the problem of defining it in Monix for example?
Also note that this formulation of Scheduler, as it stands:
- does not subsume all the ops that fs2 Scheduler has, so we will still need to expose our own Scheduler type)
- does not subsume all the used of `ec` either (we use `execute` as an implementation detail in the `async` parts), so we would still need to take both an `EC` and a `Scheduler`

**Comment by jcranky** [comment]
As a reason for why this belongs to cats-effect, it would useful in simple cases where you use only cats-effect, and need a scheduler. It would avoid having to add a whole streaming or task framework just for the scheduler.

**Comment by LukaJCB** [comment]
I think typeclass coherence is an important aspect, but I also think a typeclass for time based operations would be super useful. For example with just the `timeout` function, I'm now able to define methods like `delay`,  `retryForDuration` ,`retryExponentialBackout`. 

Not sure how well we can separate shifting from timeout.

**Comment by alexandru** [comment]
I would define my own pure `Scheduler`, however I'd rather avoid having a duplicate interface in cats-effect in the future.

In terms of scheduling stuff, these 3 operations are all you need and the rest can be derived (e.g. scheduling repeated tasks at fixed rate or delay).

Given that it's an interface, you can also extend it, the way we are extending `ExecutionContext`. The benefit of having `ExecutionContext` in the standard library is that Monix's `Scheduler` can be used whenever one is needed, so I can make people `import monix.execution.Scheduler.Implicits.global` instead of `scala.concurrent.ExecutionContext.Implicits.global` and not feel sorry for it.

So if we want to go low level, I don't see a problem in doing this:

```scala
def context: F[ExecutionContext]
```

**Comment by alexandru** [comment]
> Not sure how well we can separate shifting from timeout.

This `Scheduler` isn't about `timeout` btw, but about the general notion of sleeping for a given time span. `timeout` necessarily implies a race condition between `sleep` and something else and we can't safely describe that without cancellation, so I'd rather keep that out of this discussion.

That said, if we do end up with a `MonadCancel`, then this `Scheduler` type becomes even more useful.

**Comment by alexandru** [comment]
> As a reason for why this belongs to cats-effect, it would useful in simple cases where you use only cats-effect, and need a scheduler. It would avoid having to add a whole streaming or task framework just for the scheduler.

Take this with a grain of salt, as I'm biased since I naturally want people to use my stuff, however `cats-effect` as a library is primarily middleware to make stuff inter-operate and not necessarily a library with all the bells and whistles that people need.

Being middleware, the primary concern is stability, hence the surface area needs to be small, so in such a situation where you balance the needs of the library authors against the end users, if all other things are equal, the library authors should win. As otherwise `cats-effect` stops being useful as middleware.

And while I realize that this is an argument against this `Scheduler` type, I think a standard and pure `Scheduler` type really is needed.

**Comment by LukaJCB** [comment]
Sorry, by `timeout` I meant `sleep`

**Comment by jcranky** [comment]
> Take this with a grain of salt, as I'm biased since I naturally want people to use my stuff, however cats-effect as a library is primarily middleware to make stuff inter-operate and not necessarily a library with all the bells and whistles that people need.

Agreed. That is why I said _simple cases_ :)

**Comment by alexandru** [comment]
`Timer` is on master already due to #132.
