### ISSUE TITLE
Compile series/2.x on Dotty

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1166]

**Comment by vasilmkd** [comment]
I'd like to work on this.

**Comment by vasilmkd** [comment]
I started working on this. Unfortunately, `discipline-scalacheck` is not published for 0.27.0-RC1 which has Scala.js support. OTOH, if I disable Scala.js outright on 0.26.0, there is a mismatch between `cats` and `cats-effect` transitive dependencies.

**Comment by djspiewak** [comment]
So I forgot to add a prerequisite issue for this one. Writing it up right now. :-)
