### ISSUE TITLE
Proposal (2) 😀 cats-concurrent project, top level or sub-project of cats-effect

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#117]
I'm thinking that people need concurrency data types that use `cats-effect` type classes, but that we don't necessarily want to push in `cats-effect` in order to preserve the stability of the project, 
being a big believer in an a la carte approach.

I'm currently thinking of:

1. some `Scheduler` data type as outlined in #116 - now i'm thinking of renaming that to `Timer` 😀
2. `MVar`
3. `Ref`

Could be in the same repository, as a sub-project. Or it could be a new top-level Typelevel project.

**Comment by johnynek** [comment]
I think it should be a subproject of cats-effect. Many repos creates a lot of difficulty in publishing when new incompatible versions comes.

I think concurrent is so close to effect s submodule is very natural.

**Comment by alexandru** [comment]
When I opened this issue, I was thinking of `Timer`, which ended up in cats-effect proper. 

I think if we add a `concurrent` sub-project to `cats-effect` it will have the same stability requirements as `cats-effect`. Which actually isn't bad at all. So for now I'm abandoning such plans for a separate project. If something is truly needed, it probably belongs to cats-effect.
