### ISSUE TITLE
Add background forwarder in IO

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1175]
It is generally recommended to use `Concurrent.background` as opposed to `start` to spawn fibers because `start` is inherently unsafe and leaky. We should add a `background` combinator on the `IO` class for accessibility and discoverability.

**Comment by RaasAhsan** [comment]
Surprisingly this already existed

**Comment by djspiewak** [comment]
Shows how often I look at scaladoc! lol
