### ISSUE TITLE
Testkit documentation

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1210]
I don't think we have a documentation issue for this one. We should be able to backport anything we write about `TestContext` to CE2 as well.

**Comment by Kazark** [comment]
There are docs for [TestContext](https://typelevel.org/cats-effect/api/3.x/cats/effect/kernel/testkit/TestContext.html), but they are out of date as they reference `Timer`, which does not exist in CE3.

Or if you mean for the migration guide, I am slowly working through how to migrate them [here](https://stackoverflow.com/a/67592671/834176).

**Comment by djspiewak** [comment]
We have `TestControl` pretty well documented at this point.
