### ISSUE TITLE
start publishing builds against scala.js 1.0.0-M*

### ISSUE THREAD

**Issue by aappddeevv** [typelevel/cats-effect#122]
Request for publishing against these milestones and RCs so we can test our code.

**Comment by djspiewak** [comment]
This is very definitely on my TODO list. Unfortunately it's kind of not trivial for a number of reasons, mostly related to the fact that there's no direct way of integrating cross-building of this nature into a build.

**Comment by djneades** [comment]
The urgency of this has increased with the release of [Scala.js 1.0.0-RC](https://www.scala-js.org/news/2019/11/26/announcing-scalajs-1.0.0-RC1/) and a possible final release of 1.0.0 at the end of January 2020.

**Comment by djneades** [comment]
The release notes for Scala.js 1.0.0-RC have a suggestion for how to support cross building. See the heading [Cross-building for Scala.js 0.6.x and 1.x](http://www.scala-js.org/news/2019/11/26/announcing-scalajs-1.0.0-RC1#cross-building-for-scalajs-06x-and-1x).

**Comment by djspiewak** [comment]
Okay I'll start pushing on this in earnest. A more immediate issue though is that I do not believe cats-core has been published for 1.x, so that would be a dependency. Is there a ticket filed on that repo?

**Comment by djneades** [comment]
@djspiewak The [release notes for Cats 2.1.0](https://github.com/typelevel/cats/releases/tag/v2.1.0) state that it has support for Scala.js 1.0.0-RC2.

**Comment by cquiroz** [comment]
I didn't notice this issue. I sent a related PR #753
