### ISSUE TITLE
Expose Scheduler, compute and blocking pool from IORuntime

### ISSUE THREAD

**Issue by SystemFw** [typelevel/cats-effect#1227]

**Comment by djspiewak** [comment]
What use-case does this satisfy that things like `IO.executionContext` can't help with? Part of the concern here is that we *may* in the future go with a blocking pool which isn't directly an `ExecutionContext`. The API allows that right now, and there are some benefits. We've already swapped to a compute pool which isn't a *good* `ExecutionContext` (it works, but it's not a great situation, performance-wise; the compute pool is optimized assuming `IOFiber`).

**Comment by SystemFw** [comment]
ah my bad, I wrote it in a completely unclear way. I actually don't care about `EC` at all, I just put it there mechanically. I do want an easy way to create a Scheduler though, it's a niche case but it's annoying that there is nothing for that in the Scala ecosystem. The immediate need is in one of the tests for the new Async. It doesn't have to imply exposing the ones in Runtime, it could be just a constructor in the Scheduler companion, although experience with blaze and ec vs contextShift makes me thing exposing might be easier.

**Comment by djspiewak** [comment]
> The immediate need is in one of the tests for the new Async

Worth noting that the tests don't use an exposed `IORuntime` (they have their own internally managed one), so… exposing it from `IORuntime` itself is probably not what you want. :-) I'm okay with sticking some nicities on the `Scheduler` companion though.

I generally don't *want* people to use it, but you're right that there are no alternatives in the Scala ecosystem at present, which is deeply unfortunate. `scala.concurrent` should have this stuff.

**Comment by SystemFw** [comment]
> scala.concurrent should have this stuff.

Really wish it did

**Comment by viktorklang** [comment]
The reason why scala.concurrent does not (currently) have a mechanism for delaying effects (a Scheduler) is because of the difficulty of picking an implementation why does reasonably well in: accuracy, precision, scalability, and manageability.

**Comment by djspiewak** [comment]
> The reason why scala.concurrent does not (currently) have a mechanism for delaying effects (a Scheduler) is because of the difficulty of picking an implementation why does reasonably well in: accuracy, precision, scalability, and manageability.

@viktorklang I think that's a fair issue and it's 100% accurate. There are similar problems with any thread pool default. However, even just having an *abstraction* similar to `ExecutionContext` would help a lot. Right now, every framework has to create their own `Scheduler` trait, which is painfully annoying. `ExecutionContext` isn't perfect, and the default implementation is inappropriate for most frameworks that do complex things with the runtime (like Cats Effect), but at least the *abstraction* is quite good and immensely useful.

**Comment by viktorklang** [comment]
@djspiewak Having abstractions without implementations in the stdlib is generally problematic—how do you settle on the interface when there is no implementation(s) to compare etc. It's unfortunate that there is no good builtin, shared, scheduler in the jdk/jvm it would be easier to avoid jitter if people would avoid creating multiple schedulers.

**Comment by djspiewak** [comment]
So coming back to the OP issue… we actually already expose this stuff, though @alexandru makes an excellent point that we *shouldn't* be exposing the blocking pool. I'm going to open a new issue to track that.
