### ISSUE TITLE
Add a list of developers to the build file

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#1231]
Following up on https://github.com/typelevel/cats-effect/pull/1197#discussion_r492843677.

I'm using this issue to source and check people's GitHub and Twitter handles/email addresses to be included in the build information. I will update this post with people's information as I discover it, but please feel free to contribute your own information and/or verify that what I have found is correct and up to date. I will tag people that are relevant to this issue.

Also feel free to say that you want something not to be included.

Thank you all.

**Comment by vasilmkd** [comment]
Daniel Spiewak
GitHub: @djspiewak 
Twitter: @djspiewak
GitHub URL: https://github.com/djspiewak

Please let me know if this information is correct or if you would like something else included, like a different link or email address. Thank you.

**Comment by vasilmkd** [comment]
Fabio Labella
GitHub: @SystemFw
GitHub URL: https://github.com/SystemFw
I cannot find a Twitter handle or email address, so not sure what should be included here.

Please let me know if this information is correct or if you would like something else included, like a web link or an email address. Thank you.

**Comment by vasilmkd** [comment]
Raas Ahsan
GitHub: @RaasAhsan
Twitter: @RaasAhsan
GitHub URL: https://github.com/RaasAhsan

Please let me know if this information is correct or if you would like something else included, like a different link or email address. Thank you.

**Comment by vasilmkd** [comment]
Tim Spence
GitHub: @TimWSpence
Twitter: @timwspence
GitHub URL: https://github.com/TimWSpence

Please let me know if this information is correct or if you would like something else included, like a different link or email address. Thank you.

**Comment by vasilmkd** [comment]
Jakub Kozłowski
GitHub: @kubukoz 
Twitter: @kubukoz
GitHub URL: https://github.com/kubukoz

Please let me know if this information is correct or if you would like something else included, like a different link or email address. Thank you.

**Comment by vasilmkd** [comment]
Michael Pilquist
GitHub: @mpilquist 
Twitter: @mpilquist
GitHub URL: https://github.com/mpilquist

Please let me know if this information is correct or if you would like something else included, like a different link or email address. Thank you.

**Comment by vasilmkd** [comment]
Ben Plommer
GitHub: @bplommer 
Twitter: @bplommer
GitHub URL: https://github.com/bplommer

Please let me know if this information is correct or if you would like something else included, like a different link or email address. Thank you.

**Comment by vasilmkd** [comment]
Gabriel Volpe
GitHub: @gvolpe 
Twitter: @volpegabriel87
GitHub URL: https://github.com/gvolpe

Please let me know if this information is correct or if you would like something else included, like a different link or email address. Thank you.

**Comment by djspiewak** [comment]
Fabio doesn't have a Twitter account. Technically neither does Raas.
