### ISSUE TITLE
Copy embed machinery to Outcome

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1232]
`Concurrent#background` is a little annoying right now because it returns `F[Outcome[F, E, A]]` in its body. This is consistent with `join`, so that makes sense, but `join` also has `joinAndEmbed` and related, and there's no analogue of this for `Outcome`. It might make sense to add `embed` as a method on `Outcome` to help ease this a bit. The `joinAndEmbed` machinery could then delegate to this method + `flatten`.

Open for discussion. :-) Could also have a different variant of `background`.

**Comment by vasilmkd** [comment]
I looked at the code and this is how I view it. `joinAndEmbed` is just convenience around `Outcome#fold`. I don't think it makes sense adding `embed` directly to `Outcome` as it would be an alias for `fold`. To that end, I guess a better analogy would be `backgroundAndEmbed`?
