### ISSUE TITLE
Have a think about Effect

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1233]
Some wish its untimely demise. Others express fears about `IO`'s functionality. Ultimately, it may not serve a purpose, it hasn't shaped up the way that I had *hoped* it would, and it may actually just be in the way. It seems to make sense from a first-principles standpoint, but "seems" is the operative word. Needs thought.

**Comment by RaasAhsan** [comment]
I don't have any solutions in my head yet, but I can vocalize some concerns with it.

`Effect` in its current incarnation basically constrains effect types to the capabilities of the typeclass hierarchy; there's no way to map a constructor that isn't described by the hierarchy to some arbitrary effect type `G[_]`. As a concrete example, consider the `Trace` constructor from CE2's `IO` encoding. It's completely non-synthetic, which is to say that users explicitly request for it to appear in a program, so an implementation of `Effect#to` is required to map it to something.

**Comment by djspiewak** [comment]
> Effect in its current incarnation basically constrains effect types to the capabilities of the typeclass hierarchy

Exactly. And this is unintentional. At the *very* least, this needs to be softened.

**Comment by SystemFw** [comment]
Effect was deleted in #1253
