### ISSUE TITLE
Come up with a better module+package name than "concurrent"

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1236]
It's more of a grab-bag with the addition of `Console` and perhaps others. We should consider a more descriptive name.

**Comment by RaasAhsan** [comment]
I don't like any of these but they're obvious so I'll just throw them out.
1. `extras`
2. `util` or `utilities`
3. `std` or `standard`

It's useful to point out that this module/library may eventually see additional types and functions like:
1. Derived concurrent data structures like `Queue`, `ReentrantLock`, and others outlined in #1217
2. Java/Scala standard library wrappers for things like `Random`, `java.time`, `UUID`, etc.
3. Aforementioned `Console`
4. `Semaphore` is already there

**Comment by SystemFw** [comment]
We could consider several variations like `std`, `predef`, `prelude` (don't love them, but I like them better than the various `extras/util`)

**Comment by djspiewak** [comment]
My soft vote is for `std` for now. `predef` steps on Scala and sounds like something it isn't, and `prelude` does the same thing but with Haskell overtones.
