### ISSUE TITLE
Resource.makeMask

### ISSUE THREAD

**Issue by SystemFw** [typelevel/cats-effect#1255]
The design of `Resource` closely reflects the nature of `bracket` in CE2, in particular a `Resource.make` node translates to `bracket`. This is fine in a lot of cases, but it does force the `acquire` function to be uncancelable, which isn't great when using `Resource` with certain types of concurrent , e.g. `Resource.make(semaphore.acquire)(_ => semaphore.release)`.

This can be solved with ad-hoc techniques (see `Semaphore.withPermit` for an idea of how), but we can look for a more general solution that allows `make` to translate to both uninterruptible and interruptible `bracket`, by having it take a `Poll[F]`.

There is one significant caveat to this idea though: `Resource` is currently interpreted outside of cats-effect to integrate with other resource safety frameworks, which would now have to support both interruptible and uninterruptible acquires. A typical example would be `fs2`, and the work required to support the enhanced this is likely to be highly nontrivial.

**Comment by djspiewak** [comment]
Just to add a little fuel to the fire, I would consider this to be something that we absolutely need for 3.0.0, particularly since the algebra is open and we can't easily do it later. It doesn't block M1, but it should be considered a blocker for any RCs.
