### ISSUE TITLE
Refine resumption state check in IOCont implementation

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1260]
@RaasAhsan had an interesting idea for doing the resumption state check (currently achieved with `wasWaiting` and `finalizing`) in a less stateful way. We should try that.

**Comment by vasilmkd** [comment]
Any updates on this, in light of the new changes right up to `3.0.0` final?

**Comment by djspiewak** [comment]
I wish I had written down what the actual idea was, rather than this opaque reference. :-P

**Comment by RaasAhsan** [comment]
Ill try to remember what the details of this were
