### ISSUE TITLE
Snapshot artifacts for 3.0 being published in `releases` repository

### ISSUE THREAD

**Issue by alejandrohdezma** [typelevel/cats-effect#1269]
It seems that the new snapshot artifacts for cats-effect are being published to the [`releases` repository](https://oss.sonatype.org/#nexus-search;gav~org.typelevel~cats-effect_2.13~~~~kw,versionexpand) instead of the snapshot one, which can easily fill [the list in Maven Repository](https://mvnrepository.com/artifact/org.typelevel/cats-effect) with snapshot versions.

Also this creates a problem when using [Maven version ranges](https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html) since these versions will be picked even if a range like `[2.2.0, 3.0)` is used.

This can be easily checked using [coursier's `resolve` command](https://get-coursier.io/docs/cli-resolve):

```bash
cs resolve -t "org.typelevel::cats-effect:[2.2.0,3.0)"

Result:
└─ org.typelevel:cats-effect_2.13:[2.2.0,3.0) -> 3.0-f471c52
   ├─ org.scala-lang:scala-library:2.13.3
   ├─ org.typelevel:cats-effect-concurrent_2.13:3.0-f471c52
   │  ├─ org.scala-lang:scala-library:2.13.3
   │  └─ org.typelevel:cats-effect-kernel_2.13:3.0-f471c52
   │     ├─ org.scala-lang:scala-library:2.13.3
   │     └─ org.typelevel:cats-core_2.13:2.2.0-RC2
   │        ├─ org.scala-lang:scala-library:2.13.2 -> 2.13.3
   │        └─ org.typelevel:cats-kernel_2.13:2.2.0-RC2
   │           └─ org.scala-lang:scala-library:2.13.2 -> 2.13.3
   └─ org.typelevel:cats-effect-kernel_2.13:3.0-f471c52
      ├─ org.scala-lang:scala-library:2.13.3
      └─ org.typelevel:cats-core_2.13:2.2.0-RC2
         ├─ org.scala-lang:scala-library:2.13.2 -> 2.13.3
         └─ org.typelevel:cats-kernel_2.13:2.2.0-RC2
            └─ org.scala-lang:scala-library:2.13.2 -> 2.13.3
```

## Possible workaround

Use a higher boundary that is unlikely to be reached, like `2.99`:

```bash
cs resolve -t "org.typelevel::cats-effect:[2.2.0,2.99)"

Result:
└─ org.typelevel:cats-effect_2.13:[2.2.0,2.99) -> 2.2.0
   ├─ org.scala-lang:scala-library:2.13.3
   └─ org.typelevel:cats-core_2.13:2.2.0
      ├─ org.scala-lang:scala-library:2.13.3
      └─ org.typelevel:cats-kernel_2.13:2.2.0
         └─ org.scala-lang:scala-library:2.13.3
```

**Comment by djspiewak** [comment]
There are a couple entangled issues here. :-)

First off, I would *love* to use the Sonatype Snapshots repository. However, that repository only accepts `-SNAPSHOT` versions. This is a problem because `-SNAPSHOT` versions themselves are not guaranteed to be stable. Obviously I'm not planning on overwriting anything, but there's no actual infrastructural guarantee of it, which makes the whole process quite rickety. Thus, in order to achieve stability in the ecosystem, we're forced to publish to the releases repository.

This has some unfortunate follow-on impacts, including the search page (as you pointed out). This is mostly cosmetic, though it certainly can yield some confusion and I don't mean to undersell that. The impact on version ranges is more interesting, but examining the impact, the problem is really being caused by an incorrect range.

The range `[2.2.0,3.0)` is implicitly asserting that "there is nothing between `2.x` and `3.0`", for some high value of `x`. That's not really how maven versioning works though; these aren't integers. Instead, it would be better to use a version range which more directly asserts the desired semantic: retrieving the latest artifact within the 2.0 major line. This is expressible:

```
$ coursier resolve -t 'org.typelevel::cats-effect:2.+'

  Result:
└─ org.typelevel:cats-effect_2.13:2.+ -> 2.2.0
   ├─ org.scala-lang:scala-library:2.13.3
   └─ org.typelevel:cats-core_2.13:2.2.0
      ├─ org.scala-lang:scala-library:2.13.3
      └─ org.typelevel:cats-kernel_2.13:2.2.0
         └─ org.scala-lang:scala-library:2.13.3
```

I'm definitely open to discussion on this issue. I haven't really seen any alternatives which maintain the properties we need though. (also it's worth noting that Cats Effect has been using this snapshot strategy since the very beginning, it's just that we have a lot more snapshots now than we used to)

**Comment by alejandrohdezma** [comment]
> There are a couple entangled issues here. :-)
> 
> First off, I would _love_ to use the Sonatype Snapshots repository. However, that repository only accepts `-SNAPSHOT` versions. This is a problem because `-SNAPSHOT` versions themselves are not guaranteed to be stable. Obviously I'm not planning on overwriting anything, but there's no actual infrastructural guarantee of it, which makes the whole process quite rickety. Thus, in order to achieve stability in the ecosystem, we're forced to publish to the releases repository.
> 
> This has some unfortunate follow-on impacts, including the search page (as you pointed out). This is mostly cosmetic, though it certainly can yield some confusion and I don't mean to undersell that. The impact on version ranges is more interesting, but examining the impact, the problem is really being caused by an incorrect range.

That's a pity :( 

But as you have said, I believe there is no other possibility while maintaining stability.

> The range `[2.2.0,3.0)` is implicitly asserting that "there is nothing between `2.x` and `3.0`", for some high value of `x`. That's not really how maven versioning works though; these aren't integers. Instead, it would be better to use a version range which more directly asserts the desired semantic: retrieving the latest artifact within the 2.0 major line. This is expressible:
> 
> ```
> $ coursier resolve -t 'org.typelevel::cats-effect:2.+'
> 
>   Result:
> └─ org.typelevel:cats-effect_2.13:2.+ -> 2.2.0
>    ├─ org.scala-lang:scala-library:2.13.3
>    └─ org.typelevel:cats-core_2.13:2.2.0
>       ├─ org.scala-lang:scala-library:2.13.3
>       └─ org.typelevel:cats-kernel_2.13:2.2.0
>          └─ org.scala-lang:scala-library:2.13.3
> ```
> 
> I'm definitely open to discussion on this issue. I haven't really seen any alternatives which maintain the properties we need though. (also it's worth noting that Cats Effect has been using this snapshot strategy since the very beginning, it's just that we have a lot more snapshots now than we used to)

Thanks for the suggestion, I totally forgot that syntax existed! 😅 That is indeed easier to use and I think it would also work for our case: a library dependency added as `Provided`, so we don't enforce any specific version (and avoid eviction issues).

What I don't fully understand is the `"there is nothing between `2.x` and `3.0`"`. Extracting from Maven's own documentation `[2.2.0,3.0)` should work (if there were no x.x-XXXX releases), right?

| Range         | Meaning                                                                                                       |
|---------------|---------------------------------------------------------------------------------------------------------------|
| [1.5,)        | x >= 1.5                                                                                                      |
| [1.2,1.3]     | 1.2 <= x <= 1.3                                                                                               |
| [1.0]         | Hard requirement on 1.0                                                                                       |
| **[1.0,2.0)**     | **1.0 <= x < 2.0**                                                                                                |
| (,1.1),(1.1,) | This excludes 1.1 if it is known not to work in combination with this library                                 |
| (,1.0],[1.2,) | x <= 1.0 or x >= 1.2. Multiple sets are comma-separated                                                       |
| (,1.0]        | x <= 1.0                                                                                                      |
| 1.0           | "Soft" requirement on 1.0 (just a recommendation - helps select the correct version if it matches all ranges) |

**Comment by rintcius** [comment]
Just thinking out loud: maybe snapshots can publish using another group or something, e.g. `org.typelevel.snapshot`?

**Comment by djspiewak** [comment]
That would break eviction. ☹️ It's a really interesting idea though. Honestly, this is exactly what separate repositories are designed for, but Sonatype's artificial restrictions on their snapshots repo (and lack of a third option) basically ties our hands.

**Comment by rintcius** [comment]
Ah yes, maybe https://github.com/scalacenter/sbt-eviction-rules can be tweaked to fix that, but that's also not ideal.

Another thought is to publish snapshots to another repository (like github), which isn't synced with sonatype.
