### ISSUE TITLE
Remove constraints on Resource#mapK

### ISSUE THREAD

**Issue by IndiscriminateCoding** [typelevel/cats-effect#1292]
Existing implementation have `Applicative` and `Defer` constraints on `Resource#mapK` method.

This is problematic when used in effect-polymorphic setting - for example, it is impossible to create an instance of `FunctorK` (from cats-tagless), which in turn creates obstacles converting effect-polymorphic algebras which use `Resource`.

One possible solution would be to suspend `mapK` in a separate constructor and defer it interpretation to a `Resource#fold`, where this constraints are already available.

Given that CE3 is not released yet, I think it is a great chance to improve this situation, as it would be harder to make later (this change is binary incompatible).

**Comment by djspiewak** [comment]
This is now done!
