### ISSUE TITLE
Consider removing possibility to widen effect in `Resource#useForever`

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#1336]
Because of a mix of variance, widening and `Nothing`, this code doesn't compile:

```scala
object Demo extends IOApp.Simple {

  val run: IO[Unit] = {
    val resource: Resource[IO, Unit] = ???

    resource.useForever
  }

}
```

```
polymorphic expression cannot be instantiated to expected type;
 found   : [G[x] >: cats.effect.IO[x]]G[Nothing]
 required: cats.effect.IO[Unit]
```

If you annotate it as `useForever[IO]`, it works. A possible solution to this might involve removing the `G[x] >: F[x]` parameter in `useForever`.

**Comment by RaasAhsan** [comment]
I've ran into this problem with other functions like `allocated` as well (though surprisingly they were all on Dotty). Almost every `Resource` function widens `F` to `G`, but how useful is that in practice? Maybe there's something in fs2, but I've never actually seen or used it before.

**Comment by kubukoz** [comment]
Resource was made covariant in https://github.com/typelevel/cats-effect/pull/731, I think it might be useful when someone's `F` is `IO[SpecificException, *]` and they want to automatically upcast it to `IO[Throwable, *]`, for example. See https://github.com/typelevel/cats-effect/issues/617

I think we *can* remove the type annotation in `useForever` for some reason (the REPL allowed me to do it) but not for `allocated`. If we keep that variance, that is.

**Comment by RaasAhsan** [comment]
Ahh, that makes sense, thanks for the context. I'm one of those `IO`-only users :) I'll post some of the failing Dotty snippets here later because I think it's related but it _does_ typecheck in 2.13.
