### ISSUE TITLE
Create a benchmark for Dispatcher

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1344]
`Dispatcher` is going to have some additional overhead that `UnsafeRun` didn't have, so we should probably try to quantify what that overhead is, though I'm not entirely sure what a comparison would look like.

**Comment by djspiewak** [comment]
Yeah I think this is worth checking. Just comparing calling `unsafeRunSync()` directly on `IO` vs doing it within `Dispatcher`, imo. All in all, I don't suspect the added overhead is all that significant, but it *does* exist, so it's worth measuring.

**Comment by ashwinbhaskar** [comment]
Can I give this a shot? If it's okay, please assign the issue to me.

**Comment by djspiewak** [comment]
Go for it!

**Comment by ashwinbhaskar** [comment]
@djspiewak I have done a very basic benchmarking wrapping a large loop inside an IO and calling `unsafeRunSync` using ce2 and ce3. 
ce2 result
```
Time taken in milliseconds: 47
```
ce3 result
```
Time taken in milliseconds: 345
```

[This](https://github.com/ashwinbhaskar/ce2-vs-ce3-benchmark) is the repo. Please correct me if I am not in the right direction.

**Comment by RaasAhsan** [comment]
For microbenchmarks, usually it's a good idea to use a framework like JMH (both series/2.x and series/3.x should have it set up), but I think it's probably safe enough to take those measurements at face value for now

That's quite a hit! I think the margin would be even larger if there were multiple, concurrent threads submitting effects (the multiplexed Dispatcher may probably help out there). That being said, I doubt people writing Scala will notice a change

**Comment by djspiewak** [comment]
I was thinking about this, and I think `unsafeRunSync` is a bit deceptive by its very nature. CE2's `unsafeRunSync` is unshifted, and running it naively within `Dispatcher` (in CE3 obviously) entails blocking a compute thread.

I think it might be more useful to try to benchmark `Dispatcher` against itself. Basically, try to see how it scales with load by using `unsafeToFuture()`, accumulating those `Future`s in some external mutable thingy, then using `Await` *in the benchmark thread* to time the results.

As a second benchmark, I think it would be interesting to benchmark `IO.fromFuture(IO(dispatcher.unsafeToFuture(ioa)))` vs `ioa` (literally sequencing it), again at different parallel loads. This would give us an idea of the overhead involved and how that overhead scales.

**Comment by ashwinbhaskar** [comment]
>I think it might be more useful to try to benchmark Dispatcher against itself. Basically, try to see how it scales with load by using unsafeToFuture(), accumulating those Futures in some external mutable thingy, then using Await in the benchmark thread to time the results.

@djspiewak  apologies for the delay. Where would this differ from when calling `unsafeRunSync` on an IO? `unsafeRunSync` itself converts the IO to future and then calls `Await`
