### ISSUE TITLE
Rework AutoCedeK into FlattenK

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1352]
It occurred to me that `AutoCedeK` is really just a specialized variant of `FlattenK`, but the only specialization is the name. We should rename it, group it with `FlatMapK` and `MapK`, and special-case the `IO#flatten` operation, since that will result in a noticeable performance win in such scenarios (relative to running through `flatMap`).

This is a run loop task, but a very straightforward one (mostly just renaming stuff) and a decent-ish introduction to how the implementation works. Someone who hasn't worked on the run loop yet (but wants to!) please take this one!

**Comment by stephen-lazaro** [comment]
If no one else has interest, I'd be interested in looking at this.

**Comment by djspiewak** [comment]
Take it!
