### ISSUE TITLE
New Maintener(s)

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#136]
@LukaJCB expressed his desire to help maintain `cats-effect`.

@larsrh can you please add him to the repository's collaborators, granting him merge permissions for the repo? And I think he already has publishing rights on Sonatype, right?

Thanks,

**Comment by larsrh** [comment]
Done.

**Comment by alexandru** [comment]
@larsrh so @SystemFw also wants to join, can you grant him permissions as well?

He's been very active in reviews, so he's doing the job already 🙂

**Comment by larsrh** [comment]
Also done.

**Comment by alexandru** [comment]
Thanks 🙂
