### ISSUE TITLE
CE3 Feature: realTimeInstant to get current java.time.Instant

### ISSUE THREAD

**Issue by jatcwang** [typelevel/cats-effect#1373]
https://gitter.im/typelevel/cats-effect?at=5f9d303b8d286f20767e64ab

Feels like this belong to `cats.effect.syntax.ClockOps`?

**Comment by djspiewak** [comment]
I think it should be in `Clock`. Or rather, `ClockPlatform` (which doesn't currently exist). Nothing should be in any of the `Ops` classes without directly peering to something in the main typeclass.

To be clear, this function would be JVM-specific (just like the one in CE2) so as to avoid the `Instant` dependency on ScalaJS.

**Comment by aeons** [comment]
I think this should use the same name as CE2: `instantNow`

See here: https://github.com/typelevel/cats-effect/blob/94440cdd500db509bd87b0688708bfbc18d2a9ef/core/jvm/src/main/scala/cats/effect/internals/ClockPlatform.scala#L33-L34

**Comment by jatcwang** [comment]
@aeons thanks I'll change it. (Though I think `now*` has better discoverability. Not sure how I'll name the js Date one either.. `jsDateNow`? :grimacing: )

**Comment by djspiewak** [comment]
Looping around to this… I do see a lot of migration advantages to using the same name as in CE2, but honestly I think the `realTime` prefix makes this a lot more discoverable and creates a more scalable convention. Thus, `realTimeInstant`

**Comment by jatcwang** [comment]
#1382 has been merged. Thanks :)
