### ISSUE TITLE
Inline require usage within Queue and PQueue

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1395]
Follow up to https://github.com/typelevel/cats-effect/pull/1361#discussion_r514485777

**Comment by TimWSpence** [comment]
I think this also needs to be done for `Queue` as well?

**Comment by djspiewak** [comment]
I believe so!

**Comment by DomWos** [comment]
Hey @djspiewak, I can take care of this one ;)

**Comment by djspiewak** [comment]
@DomWos go for it!

**Comment by jyoo980** [comment]
Is this still being worked on? I could push a branch with this change right now.

**Comment by djspiewak** [comment]
I'm guessing it isn't being worked on at present; take it!
