### ISSUE TITLE
Extract co- and contravariant parents from Queue, PQueue, Ref, and Deferred

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1396]
Follow up on https://github.com/typelevel/cats-effect/pull/1361#discussion_r514490030

**Comment by mbore** [comment]
if it's still open, i'd like to try this one.

**Comment by mpilquist** [comment]
https://github.com/typelevel/fs2/pull/2174 deprecates `fs2.concurrent.Queue` in favor of `cats.effect.std.Queue`, but the former had `fs2.concurrent.{Enqueue, Dequeue}` as supertypes. It would be nice to have similar for `cats.effect.std.Queue`, along with `map`/`contramap` functions.

More specifically, `Stream.fromQueue*` should take a `Dequeue` and there should be a `Functor[Dequeue[F, *]]` instance, while `Stream#enqueue*` should take an `Enqueue` and there should be a `Contravariant[Enqueue[F, *]]` instance.

**Comment by RaasAhsan** [comment]
Slightly related, should we implement batching calls on `Queue`? i.e. `takeAll` or `takeN`. FS2 had these in the API (http4s relies on these a little bit)

**Comment by mpilquist** [comment]
[`Stream.fromQueueNoneTerminated`](https://github.com/typelevel/fs2/blob/adee17b9579bad2a355af6ed1c2eee849862d05e/core/shared/src/main/scala/fs2/Stream.scala#L3217-L3264) pumps the queue via `tryTake` to get this behavior back
