### ISSUE TITLE
Add Async#never

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#141]
We should add this helper to `Async`:

```scala
trait Async[F[_]] extends Sync[F] {
  // ...

  def never[A]: F[A] = async(_ => ())
}
```

Instances then can return the same reference. An optimisation like `Applicative.unit`.

Scheduled for 1.0.0-RC, because it breaks binary compatibility.

**Comment by kubukoz** [comment]
As https://github.com/typelevel/cats-effect/pull/168 is merged, shouldn't this be closed?
