### ISSUE TITLE
MVar state acquisition fairness

### ISSUE THREAD

**Issue by ghost** [typelevel/cats-effect#1425]
It's not mentioned in the [MVar documentation](https://github.com/typelevel/cats-effect/blob/series/2.x/core/shared/src/main/scala/cats/effect/concurrent/MVar.scala#L25) if `MVar.take` fair or unfair.

Is it reliable to count on MVar being fair?

**Comment by djspiewak** [comment]
It is fair, though I would separately caution you to use Deferred and Red rather than MVar, since they're a lot simpler to use and perform the exact same function. 😃 MVar is a bit of a footgun due to the way it combines two concerns.

**Comment by SystemFw** [comment]
> you to use Deferred and Red rather than MVar, since they're a lot simpler to use and perform the exact same function. 😃 MVar is a bit of a footgun due to the way it combines two concerns.


and therefore, we have removed MVar in CE3 :) Feel free to ask if you need help replacing your use of MVar
