### ISSUE TITLE
Delays when using Stream.awakeEvery

### ISSUE THREAD

**Issue by adamw** [typelevel/cats-effect#1433]
This is a follow-up to https://github.com/http4s/http4s/issues/3879

I've got the following simple program:

```scala
import cats.effect.{ExitCode, IO, IOApp}
import fs2._

import scala.concurrent.duration.DurationInt

object Test extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = {
    Stream.awakeEvery[IO](1.seconds).map(d => println(s"Ping! ${d.toMillis}ms")).compile.drain.map(_ => ExitCode.Success)
  }
}
```

*sometimes* this produces results as follows:

```
Ping! 4987ms
Ping! 5992ms
Ping! 13921ms
```

This happens locally, and on travis & jenkins (though on CI I only observed it indirectly through http4s & websockets). The jenkins jobs run pods on top of a GCP-managed k8s. Locally a system restart (macos 11) helps, at least for some time; the CPU is quite idle. I've tried both java8 and java11.

Any hints where to look / how to debug? :)

**Comment by djspiewak** [comment]
Follow up: I let this run on my laptop for about 5 hours, during which time it was under intermittent extreme load (enough to trigger thermal throttling), as well as longer downtime periods. I even put it to sleep at one point. The maximum tick differential was 1018 milliseconds. (macOS 11.0.1, GraalVM CE 20.3.0 targeting JDK 8, Scala 2.13.3, 16 physical threads over 8 cores)

**Comment by adamw** [comment]
Thanks, I even didn't know that you can transfer issues ;)

I've got similar hardware: macos 11.0.1, 6-core i9, using either java `8.0.232-zulu`, `11.0.5-zulu` or `20.2.0.r11-grl` (from sdkman).

But I suppose this is neither a cats-effect nor even a scala issue - if it's an issue at all. Running this code using pure java:

```java
class Test {
  public static void main(String[] args) throws Exception {
    long last = System.currentTimeMillis();

    while(true) {
      Thread.sleep(1000);
      long now = System.currentTimeMillis();
      System.out.println(now - last);
      last = now;
    }
  }
}
```

while the build is running in the background, gives the same results (that is - large delays). So I suppose this is the way OS-level thread scheduling works. I'm still a bit surprised that everything else works normally (well, maybe a bit slower, but rather normal), so I'd expect the processes to be scheduled more fairly, but there's always something new to learn :)

(btw. I think I originally got mislead into thinking that I'm observing problems with http4s without any load, but the load was there - however artificially generated by a rogue `kernel_task` which disappeared after restarting the laptop)

**Comment by vasilmkd** [comment]
I've heard folklore about `kernel_task` on macOS, but please don't laugh about this. It shows up when the system is thermally throttling, and can slightly be mitigated if you plug in the laptop in the usb c ports on the right hand side, for whatever reason. I haven't been able to scientifically verify this, but I do _feel_ I have seen this happen with my own computer. :laughing:

**Comment by adamw** [comment]
@vasilmkd Yes, I know that's for cooling reasons, but I blame this particular case on the recent BigSure upgrade ;) However, I've got power plugged in on the left-hand side, so maybe that's it :D

**Comment by vasilmkd** [comment]
@adamw I have to reiterate that this is _extreme_ folklore and I'm not sure if I believe in it myself. 🤣

**Comment by djspiewak** [comment]
I think this ultimately comes down to the fact that we aren't using a real time operating system, language, or even hardware. :-) 18 seconds is a *huge* variance and I honestly wouldn't have expected anything close to that, but it's still technically within the bounds of what the OS and language and runtime and such consider acceptable.

**Comment by adamw** [comment]
@djspiewak yes, these huge numbers definitely took me by surprise as well. Thanks for helping in the investigation :)
