### ISSUE TITLE
Easy laws testing in downstream projects

### ISSUE THREAD

**Issue by mpilquist** [typelevel/cats-effect#1438]
We need a way for projects like fs2 & monix to test compliance with CE3 typeclasses, without requiring those projects to define a bunch of machinery. We had this in CE2 via some combination of imports. This currently lives in CE3's test suite under the `Runners` trait, but that's dependent on specs2. The support should be in the laws or testkit JAR and should interoperate with popular test frameworks including munit (via munit-cats-effect), specs2, and ScalaTest.

As a benchmark, we need something with no more boilerplate than this: https://github.com/typelevel/fs2/blob/develop/core/shared/src/test/scala/fs2/StreamLawsSuite.scala#L33

**Comment by djspiewak** [comment]
This is tricky because **core** contains the tests for `IO`. I rather like the ergonomics of that, but it does make it difficult to publish an `IO`-dependent testkit without code duplication. One possibility here might be symlinks into another project. Will think about this.

**Comment by mpilquist** [comment]
Maybe we need a new core-testkit project and then move the IO tests in to the tests source of that?

**Comment by djspiewak** [comment]
That's just a pain though. I hate having tests not in the same project as the sources they're testing. I know we already do that a bit but I hate to make it even worse.

**Comment by mpilquist** [comment]
FYI, I'm working on this in https://github.com/typelevel/cats-effect/compare/series/3.x...mpilquist:topic/new-testkit?expand=1
