### ISSUE TITLE
enhancedExceptions can remove exception origin from stack trace

### ISSUE THREAD

**Issue by scf37** [typelevel/cats-effect#1447]
cats-effect 2.2.0

Expected: printed stack trace contains file and line of `require` invocation.

Actual: it is stripped

https://scastie.scala-lang.org/XH9jhuuRTWSAAFlh01QqBQ

```scala
import cats.effect._

def foo: IO[Unit] = IO {
  require(false, "some message")
}
IO(()).flatMap(_ => foo).unsafeRunSync()
```

```
java.lang.IllegalArgumentException: requirement failed: some message
	at flatMap @ Playground$.delayedEndpoint$Playground$1(main.scala:9)
```

**Comment by scf37** [comment]
Same issue with `Predef.???`

**Comment by djspiewak** [comment]
Interesting. Looks like it's stripping one too many frames? @RaasAhsan?

**Comment by RaasAhsan** [comment]
I recall there being weird interactions with functions that were annotated
with @inline, can you verify that? Also I think we should just enable
cached tracing for delay

**Comment by scf37** [comment]
I believe the problem is in `val prefix = dropRunLoopFrames(stackTrace)`

It is supposed to preserve exception raise point by taking stack frames until `scala.*` or `cats.effect.*` encountered. 
Obviously that does not work if exception is thrown by standard scala library.

Another example:
```scala
def foo: IO[Unit] = IO {
  Nil.head
}

IO(()).flatMap(_ => foo).unsafeRunSync()
```

**Comment by RaasAhsan** [comment]
good catch, we should be more precise about which packages we are filtering in the `scala.*` namespace. there are some very specific ones, will pull them out in a bit
