### ISSUE TITLE
Add value forwarders for *Throw aliases

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1456]
…which we will promptly deprecate once typelevel/cats#3696 finds its way into a stable release. :-) They'd be very nice for now though.

**Comment by TimWSpence** [comment]
Is this not already done? https://github.com/typelevel/cats-effect/blob/series/3.x/core/shared/src/main/scala/cats/effect/package.scala#L51-L52

**Comment by djspiewak** [comment]
Those are the type forwarders, but it would be nice to have `object`s as well to allow for summoning. I want to be able to do something like `ApplicativeThrow[F].raiseError(e)` :-)

**Comment by TimWSpence** [comment]
https://github.com/typelevel/cats-effect/pull/1662
