### ISSUE TITLE
Rely on Instant.now instead of System.currentTimeMillis() inside of Clock

### ISSUE THREAD

**Issue by sergeykolbasov** [typelevel/cats-effect#1460]
Hello there

At the moment, `Clock[F].realTime` is platform-independent and relies on `System.currecurrentTimeMillis()`. It means, that the maximum precision for getting wall-clock time is limited to milliseconds.

I'd suggest having a JVM-specific implementation that relies on `java.time.Instant.now()` instead, as starting from Java 9 it's up to the nanoseconds precise time resolution.

An example, where such precision might matter, is OpenTracing API that operates in microseconds.

**Comment by djspiewak** [comment]
I like this idea!

**Comment by sergeykolbasov** [comment]
I can land a PR later if it's okay

**Comment by djspiewak** [comment]
And I can merge said PR, if that's okay. 😉

**Comment by SystemFw** [comment]
Shouldn't we add an additional op that returns Instant?

**Comment by sergeykolbasov** [comment]
~@SystemFw I think it would mean some troubles with scala.js and lack of `Instant` type there~

It already does 🤔 , although it builds it from millis

**Comment by SystemFw** [comment]
Yeah I'm thinking whether it's worth introducing a platform specific op.
But maybe not :)

**Comment by RaasAhsan** [comment]
IIRC the trouble there was that it bloats the scala.js builds because it pulls in some pretty heavy dependencies ?
