### ISSUE TITLE
Generalize interruptible hints to overlap with blocking rather than implying it

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1471]
Interruptibility of a blocking action is a useful feature to have even when that action is *not* meant to be on the blocking thread pool. An example of this is `Selector#select()`, which is a blocking call which can and should be interrupted when the server is to be shut down. This use-case is not currently possible within Cats Effect 3 (without a ton of manual work that basically replicates `interruptible`).

This implies, at least to me, that the `interruptible` API is wrong.

I believe the answer here is to generalize `suspend` slightly so that interruption and blocking are not mutually exclusive and can (or can not) overlap. Thus, the matrix would be blocking `true`/`false` and interruptibility `none`/`once`/`many`.

**Comment by TimWSpence** [comment]
I'll have a go at this
