### ISSUE TITLE
Multiplexed Dispatcher

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#1497]
`Dispatcher` hasn't yet been benchmarked but I had an idea that could reduce contention on the singular queue. Basically, the idea is to create another `Dispatcher` implementation which itself dispatches to one of N `Dispatcher`s in a roundrobin fashion. I'm having a hard time reasoning about how performance would change. On one hand, there is less contention and waiting in the queue, but on the other, batch sizes become smaller. The other concern is what would the ideal N be?

**Comment by djspiewak** [comment]
I've done some general measurements of this in fs2-netty and the conclusion I've come to is: it's more than fast enough the way it is. :-) It's still worth benchmarking and playing around with this idea, so I'll leave this open, but the performance seems extremely good in practice.
