### ISSUE TITLE
Configure Typelevel's Cloudflare account for website

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#150]
@larsrh I know you're traveling, just leaving this here for when you get back and have time for it...

We need to configure the Cloudflare account to forward https://typelevel.org/cats-effect/ to https://typelevel.github.io/cats-effect/

I believe that's what is currently done for the Cats website.

Thanks,

**Comment by larsrh** [comment]
Pending automatic deploy by Netlify: https://github.com/typelevel/typelevel.github.com/commit/96697ba9fe802193f7d33926bccb4d9e8944363a
