### ISSUE TITLE
Consider renaming methods in Fiber

### ISSUE THREAD

**Issue by SystemFw** [typelevel/cats-effect#1500]
The current naming is descriptive, but a bit longwinded and maybe scary, I propose to replace

```scala
trait Fiber[F[_], E, A] {
   ....
  def join: F[Outcome[F, E, A]]
  def joinAndEmbed(onCancel: F[A])(implicit F: MonadCancel[F, E]): F[A] 
  def joinAndEmbedNever(implicit F: GenSpawn[F, E]): F[A]
}
```

with

```scala
trait Fiber[F[_], E, A] {
   ....
  def join: F[Outcome[F, E, A]]
  def joinWith(onCancel: F[A])(implicit F: MonadCancel[F, E]): F[A] 
  def joinWithNever(implicit F: GenSpawn[F, E]): F[A]
}
```

The work would involve renaming those methods, and changing the relevant tests, docs, and scaladoc. A pretty easy first contribution for someone :) (assuming the naming gets agreement)

**Comment by djspiewak** [comment]
I think this is a decent naming convention, and certainly a lot less scary. 😃
