### ISSUE TITLE
Remove self-cancelation from SyncIO

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1501]
We actually don't need it! `SyncIO` forms a lawful `MonadCancel` even without short-circuiting on `canceled`. All we need to do is define `canceled = unit`.

**Comment by vasilmkd** [comment]
Always down to delete my own code.

**Comment by mpilquist** [comment]
@djspiewak We tried this originally: https://github.com/mpilquist/cats-effect/blob/9381478e70f1e5168e24be867fa4d5008c57c6b9/core/shared/src/main/scala/cats/effect/SyncIO.scala#L534-L543

That failed a couple of laws tests. I don't remember which ones exactly but I'm curious what we were missing back then?

**Comment by djspiewak** [comment]
So it seems likely that @wemrysi's work on the generators will re-expose whatever you previously saw in the earlier attempt. However, I have a contingency plan there. 😃 It's possible to formalize the nature of the root scope, which would allow us to declare, rigorously, that certain cancelation semantics simply don't apply to SyncIO. This would be represented optionally in the types, but invisibly by default.

**Comment by wemrysi** [comment]
I can confirm that the following tests fail on my branch with the fixed generators when redefining `SyncIO.canceled` to be `SyncIO.unit`:

```
[error]   x preserve monad right identity on uncancelable
[error]   x cancel flatMap continuations following a canceled uncancelable block
[error]   x cancel map continuations following a canceled uncancelable block
[error]   x sequence onCancel when canceled before registration
[error]   x break out of uncancelable when canceled before poll
[error]   x not invoke onCancel when previously canceled within uncancelable
[error]   x ignore repeated polls                                                                                                                                                                                  
...
[error] x monadCancel.canceled associates left over flatMap
...
[error] x monadCancel.uncancelable canceled associates right over flatMap
```

**Comment by djspiewak** [comment]
Looking at the laws, this is intuitive. Those laws only hold in the root scope. So in order to resolve this ticket, we'll need to existentially parameterize scope. I think that's doable.
