### ISSUE TITLE
GuaranteeCase syntax doesn't seem to type infer in general

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1564]
```scala
def foo[F[_], A](fa: F[A])(implicit F: MonadCancel[F, Throwable) =
  fa guaranteeCase {
    case Outcome.Canceled() => ...
    // ...
  }
```

In the above, the compiler will give an error like `missing parameter type for expanded function` or something similar related to type inference. Directly invoking the function on `MonadCancel` by way of `F.guaranteeCase` circumvents this problem entirely. We should try to find a way to smooth this over for users if possible.

Scala 2.13

**Comment by joroKr21** [comment]
That's a bit tricky. I guess other type classes might have the same problem. I can take a look.
