### ISSUE TITLE
Investigate replacing ScheduledExecutorService with a HashedWheelTimer

### ISSUE THREAD

**Issue by mpilquist** [typelevel/cats-effect#1580]
Netty, Akka, Blaze, and other libraries all use a variant of a hash wheel timer for scheduling lots of non-blocking tasks:

- [Netty's HashWheelTimer](https://github.com/liaokailin/netty/blob/master/common/src/main/java/io/netty/util/HashedWheelTimer.java)
- [Akka's LightArrayRevolverScheduler](https://github.com/akka/akka/blob/a4acf23d0541471ecf81b9ba5dd97c2e97670814/akka-actor/src/main/scala/akka/actor/LightArrayRevolverScheduler.scala)
- [Blaze's TickWheelExecutor](https://github.com/http4s/blaze/blob/main/core/src/main/scala/org/http4s/blaze/util/TickWheelExecutor.scala)

https://stackoverflow.com/questions/17276393/hashedwheeltimer-vs-scheduledthreadpoolexecutor-for-higher-performance

We should consider adopting something similar for CE3, measured against ScheduledExecutorService to see which is better. At the very least, we should ensure there are no API changes necessary if we later want to swap in a custom scheduler.

**Comment by djspiewak** [comment]
Based on what I can find, this is definitely something that is worth doing. If we can get it in for 3.0, it would be ideal, but it's technically something that can land afterward if necessary.

**Comment by TimWSpence** [comment]
This looks fun! Happy to have a stab at it at least

**Comment by He-Pin** [comment]
I think this is really needed. I was fired an issue https://github.com/reactor/reactor-core/issues/2965 and switch to Akka just because of this.

**Comment by armanbilge** [comment]
@He-Pin see the following discussions regarding plans for 3.5.0:
- https://github.com/typelevel/cats-effect/discussions/3101
- https://github.com/typelevel/cats-effect/discussions/3070

**Comment by armanbilge** [comment]
Not a hashwheel timer, but still a replacement for `ScheduledExecutorService`.
- https://github.com/typelevel/cats-effect/pull/3219

**Comment by He-Pin** [comment]
@armanbilge @djspiewak  I think this need renmaed to add a HashedWheelTimer to cats-effect

because the current integrated timer is O(log N), not O(1)
