### ISSUE TITLE
Proposed Unique class in the hierarchy

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1587]
```scala
trait Unique[F[_]] {
  def applicative: Applicative[F]

  type Token

  // (unique, unique).mapN(_ === _) <-> F.pure(false)
  def unique: F[Token]
  def tokenHash: Hash[Token]
}
```

Then, `Spawn <: Unique` and `Sync <: Unique`. Note that `Spawn` already has a notion of uniqueness in evaluation due to the existence of `start` and the fact that `join`s on distinct `Fiber`s yield distinct results. Uniqueness, fundamentally, implies lazy evaluation and non-memoization. Note that this is a stronger implication than `Defer`, which really just implies safe recursion indirectly via laziness.

Much like `Clock`, this is simply a safe way of exposing functionality which is already primitive in the runtime. Namely: the fact that `new` produces a distinguishable chunk of memory on each invocation.

Names subject to bikeshedding.

![cats-effect 3 0 hierarchy](https://user-images.githubusercontent.com/752/104106894-f0d3dd80-5275-11eb-97c7-7dfd9eb941f8.png)

**Comment by SystemFw** [comment]
## Unique in cats.effect.std

This is an alternative proposal that keeps `Unique` outside of the hierarchy, without introducing any cheating.

It would be identical to https://github.com/typelevel/cats-effect/pull/1477, except for the fact that the concurrent constructor wouldn't rely on lazy `map` to do `().map(_ => Token`), but rather `F.deferred.map(WrapperThatDoesEqualityOnTheDeferred)`, therefore side-stepping the `Defer` problem

**Comment by djspiewak** [comment]
As a note: making `Token` fully abstract is basically pointless. It's pleasing from a theoretical point of view, but it does cause some ergonomics issues (it means every implicit has to be `val`), and it doesn't gain anything because of boxing. Like in theory, it would be nice if some implementation could choose to instantiate `Token = Long`, but even if we make that possible, it doesn't *gain* anything because all call-sites would box `Token` because it would be fully existential, meaning you get the same number of allocations as if `Token` is just a `final class`.
