### ISSUE TITLE
Roll back ScalaJS version for compatibility

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1629]
As we're an upstream library, we should always default to the oldest major/minor ScalaJS line on which we can run successfully.

**Comment by djspiewak** [comment]
@sjrd If you have a moment can you weigh in on whether or not this issue is the right thing to do? I can see arguments both ways.

**Comment by sjrd** [comment]
Did you ever have any complaint from a user of cats-effects that you use a too recent version of Scala.js? If not, then don't roll back.

Are you mindlessly upgrading to minor versions of libraries that you depend on? If yes, this is literally no different, and there's no rational reason to roll back either.

**Comment by djspiewak** [comment]
Okies. Then I'll close this and we'll continue tracking the upstream version.
