### ISSUE TITLE
Add Resource#race

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1652]
Mostly we want to add this to the `Resource` class and companion object (similar to `IO`) for discoverability reasons. The implementation is already available on the `Concurrent` instance, and thus the methods added here would just delegate to that implementation, similar to what `IO` does.

**Comment by patseev** [comment]
I'd like to take this one. Should I target 2.x or 3.x or both?

**Comment by patseev** [comment]
To save time, here's a sketch of implementation. Do I understand correctly that we're racing allocations? Implementation is very similar to `Resource.both` but relies on `race` instead of `parTupled`

```
def race[B](that: Resource[F, B])(implicit F: Concurrent[F]): Resource[F, Either[A, B]] = {
    def allocate[C](r: Resource[F, C], storeFinalizer: (F[Unit] => F[Unit]) => F[Unit]): F[C] =
      r.fold(
        _.pure[F],
        release => storeFinalizer(MonadCancel[F, Throwable].guarantee(_, release))
      )

    val bothFinalizers = Ref.of[F, (F[Unit], F[Unit])](().pure[F] -> ().pure[F])

    Resource.make(bothFinalizers)(_.get.flatMap(_.parTupled).void).evalMap { store =>
      val leftStore = (f: F[Unit] => F[Unit]) => store.update(_.leftMap(f))
      val rightStore = (f: F[Unit] => F[Unit]) => store.update(t => (t._1, f(t._2)))

      F.race(allocate(this, leftStore), allocate(that, rightStore))
    }
  }
  ```

**Comment by djspiewak** [comment]
> I'd like to take this one. Should I target 2.x or 3.x or both?

Just 3.x! :-) It would run into a bunch of problems on 2.x as far as I can tell.

Regarding the implementation, I think you can actually just delegate straight to the `Async` for `Resource` the same way that `IO` does with *its* `race` implementation. So really all that is needed here is a forwarder.

**Comment by patseev** [comment]
Sweet. Then I propose I'll simplify the existing `both` via delegate as well
