### ISSUE TITLE
Extract polyfill executor into a separate project

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1664]
This is the Cats Effect side of scala-js/scala-js#4129. We need to pull it out into a separate (typelevel?) project. Honestly this is mostly just infrastructure work, untangling the Firefox build machinery and stuff.

**Comment by vasilmkd** [comment]
Unfortunately the firefox CI is still broken due to no fault of our own...

**Comment by djspiewak** [comment]
Two birds with one stone then! 😒
