### ISSUE TITLE
 Add `versionScheme` to build.sbt

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#1690]
Note: this is a direct copy of https://github.com/typelevel/cats/issues/3780 by @majk-p. It's merged in cats, and I think we should have it in CE too.

---

With the release of sbt 1.4.0 the versionScheme has been added.
With sbt 1.5.0 (which is on the way) a plugin called sbt-eviction-rules will be integrated into the tool.

In one of my projects I'm already playing with the plugin, and the project fails to compile due to following eviction:

org.typelevel:cats-core_2.13:2.3.1 is selected over {2.1.0, 2.1.0, 2.2.0, 2.2.0, 2.2.0, 2.1.1, 2.1.1, 2.1.0, 2.1.1, 2.2.0}

Those versions should not be a problem as they are compatible, but the sbt-eviction-rules (and in future sbt itself) is looking for versionScheme in cats-core. If it fails, it has to guess if those versions are compatible or not.

Can we please specify version scheme for cats to avoid monkey patching like evictionRules += "org.typelevel" %% "cats-*" % "semver-spec" on the client side?

**Comment by djspiewak** [comment]
We actually get this for free! https://github.com/djspiewak/sbt-spiewak/blob/2ffe707f6dd271cc79eb4090174bec8c51310c36/core/src/main/scala/sbtspiewak/SpiewakPlugin.scala#L172-L178

**Comment by kubukoz** [comment]
Nice!
