### ISSUE TITLE
Version 2.3.2 not compatible with JDK8

### ISSUE THREAD

**Issue by jakubjanecek** [typelevel/cats-effect#1699]
The latest release `v2.3.2` does not seem to be compatible with JDK8: https://github.com/avast/scala-server-toolkit/runs/1918114288?check_suite_focus=true#step:5:159

I was looking and the sbt and Actions setup but was not able to find the problem but I think it's probably not expected to be compatible with only JDK11 and higher. Am I right?

**Comment by mpilquist** [comment]
Yeah -- fix incoming in a bit as v2.3.3.
