### ISSUE TITLE
Missing `Align[IO]` in CE3

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#1726]
I'm not sure if this is intentional, but CE2 IO has an `Align` instance, which doesn't seem to be there in CE3.

```scala
implicit val ioAlign: Align[IO] = new Align[IO] {
  def align[A, B](fa: IO[A], fb: IO[B]): IO[Ior[A, B]] =
    alignWith(fa, fb)(identity)

  override def alignWith[A, B, C](fa: IO[A], fb: IO[B])(f: Ior[A, B] => C): IO[C] =
    fa.redeemWith(
      t => fb.redeemWith(_ => IO.raiseError(t), b => IO.pure(f(Ior.right(b)))),
      a => fb.redeem(_ => f(Ior.left(a)), b => f(Ior.both(a, b)))
    )

  def functor: Functor[IO] = Functor[IO]
}
```

**Comment by djspiewak** [comment]
I can't remember if this was intentional or not. Try and see?

**Comment by alexandrustana** [comment]
I could give this a try if nobody minds :)
I've looked a bit and saw that there already is an `Align` instance for `ParallelF`(#957).
So I guess to only places where this should be added is `IO` and `SyncIO`.
