### ISSUE TITLE
Add withFilter to IO

### ISSUE THREAD

**Issue by Daenyth** [typelevel/cats-effect#174]
I was converting some code from Futures, and found that I couldn't directly translate `for { (foo, bar) <- IO(blah) }` due to the lack of `withFilter`

**Comment by alexandru** [comment]
`withFilter` is reportedly unsafe. You might find this discussion interesting: https://github.com/scalaz/scalaz/pull/728

I'm on the fence about adding it and I'm leaning towards 👎 

The reason is that you can live just fine without it:

```scala
for {
  r <- IO(blah)
  (foo, bar) = r
} yield ???
```

**Comment by Daenyth** [comment]
I did use that fix for the record; my desire to have this is purely because it makes the transition to using IO more smooth for people with less experience. On the surface, using `(foo, bar) <- IO(blah)` getting a compile error about IO not having withFilter is one I expect to be confusing to newcomers.

Worst case I could always add an implicit to my codebase

**Comment by Daenyth** [comment]
Reading the Maybe discussion was fairly enlightening, thanks
