### ISSUE TITLE
Add support for UUIDs to cats.effect.std

### ISSUE THREAD

**Issue by mpilquist** [typelevel/cats-effect#1741]
Christopher's [fuuid](https://github.com/davenverse/fuuid) project is great. I'd love to have this built in to CE3, where we're encouraging folks to use capability traits and NOT pass `Sync` constraints around.

At minimum, we'd need a capability trait:
```scala
trait UUIDGen[F[_]]:
  def randomUUID: F[UUID]

object UUIDGen:
  given [F[_]: Sync] UUIDGen[F] with
    def randomUUID: F[UUID] = Sync[F].delay(UUID.randomUUID)
```

Some additional design decisions:
- Should we have our own wrapper class like `cats.effect.std.UUID`, which elides the unsafe constructors and operations?
- If so, should we name that `UUID` or `FUUID` or something else?
- Do we skip things like literal macros and integrations with libraries?

**Comment by Wosin** [comment]
Happy to take a look at that.

**Comment by mpilquist** [comment]
@Wosin Awesome, I assigned to you. Feel free to ask any questions here or on cats-effect-dev on Gitter.

**Comment by chuwy** [comment]
Just a random (pun not intended) thought on this - it would be great to have a more general `Random` capability rather than UUID-specific, like [rng](https://github.com/NICTA/rng/), but more TF-like.

**Comment by Wosin** [comment]
Hey @mpilquist, just a few things to clarify :) 
Were any such wrappers introduced in the past ? IMHO, this shouldn't be needed, but happy to discuss here, also IMHO if we were to introduce one I think we should keep the naming consistent and just call it `UUID`.
As for the last question, does the original lib have the literal macros ? I haven't seen that in the docs, but I may be wrong here. Adding that shouldn't be too big problem though.

**Comment by djspiewak** [comment]
@chuwy We already have `Random` in the std module. :-)

**Comment by chuwy** [comment]
Thanks @djspiewak, it looks awesome. I urgently need to get on CE3 train.

I'm wondering though why we'd have a separate `UUIDGen` capability then, if it's just a subset of `Random`

**Comment by djspiewak** [comment]
Technically `Random` is more complex than `UUID`, meanwhile `UUID` offers some guarantees that `Random` doesn't.

**Comment by Wosin** [comment]
@mpilquist What do You think about this comment ? https://github.com/typelevel/cats-effect/pull/1772#discussion_r593868748

I generally agree with that `UUIDGen` may not be the best name if we want to implement wider capabilities like `fromString` or `fromByteArray` which I think we should implement.
