### ISSUE TITLE
Ticker works not as expected

### ISSUE THREAD

**Issue by catostrophe** [typelevel/cats-effect#1779]
There are 2 cases:

```scala
import cats.effect.{IO, Ref}
import cats.effect.testkit.TestInstances
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

import scala.concurrent.duration._
import scala.util.Success

class HangingTest extends AnyFlatSpec with Matchers with TestInstances {

  it should "sleep" in {
    implicit val ticker = Ticker()

    val io = for {
      _ <- IO(println("mark1"))
      _ <- IO.sleep(100.seconds)
      _ <- IO(println("mark2"))
    } yield ()

    //this finishes but should sleep?
    val result = io.unsafeToFuture()
    ticker.ctx.tickAll(1.second)
    result.value shouldEqual Some(Success(()))
  }

  it should "not hang" in {
    implicit val ticker = Ticker()

    val io = for {
      r <- Ref[IO].of(0)
      _ <- IO(println("mark1"))
      _ <- fs2.Stream.fixedRate[IO](1.second).evalMap(_ => r.getAndUpdate(_ + 1)).compile.drain.start
      _ <- IO.sleep(5.seconds)
      _ <- IO(println("mark2"))
      x <- r.get
    } yield x

    //this hangs but should not?
    val result = io.unsafeToFuture()
    ticker.ctx.tickAll(10.second)
    result.value.map(_.map(x => x > 0)) shouldEqual Some(Success(true))
  }

}
```

**Comment by djspiewak** [comment]
The first one here is definitely expected. I'm not so sure about the second.

Let's start with the first. `tickAll` is slightly different from `tick` in that it continually loops on the task queue until that queue is empty, provided that the task queue has any entries which are scheduled within the given time parameter. In the first one, you said `tickAll(1.second)` and your only sleep is `100.seconds`, which means that you're going to power all the way through the sleep and return right away. The clock will advance between ticks though, which means that *internally* within the `IO` things will appear to behave correctly. If you want the old semantic, use the old function: `tick`. Note though that `tick` exposes internal implementation details of `IO`'s runtime, including auto-yielding and other elements, so it's not necessarily going to be what you want in most cases.

In the second example, you created an infinite runtime, but of course it isn't actually blocking the final result from being produced. I still think that `tickAll` is probably not what you want, but I would normally have expected this to complete with a value of either `4` or `5` (it's non-deterministic).

That last point is one of the things that I think people are overlooking a lot: `TestContext` is still nondeterministic in general, and a lot of the things that people are trying to do with it assume determinism. It's useful, but it's also a very tricky tool that isn't as general-purpose as it *seems* from the outside.

**Comment by catostrophe** [comment]
Thanks
