### ISSUE TITLE
Dual-effect Dispatcher constructor?

### ISSUE THREAD

**Issue by oleg-py** [typelevel/cats-effect#1780]
Not sure if it's possible, but would be nice if there was way to construct a `Resource[F, Dispatcher[G]]`. Having a hypothetical constructor like this would trivialize conversion between different `Async` effect types.

**Comment by djspiewak** [comment]
It's not possible. The best you could do would be to add a `mapK` to `Dispatcher`, which I *believe* is something that works, but you still have to provide the function `F ~> G`. Ultimately, `Dispatcher` boils down to an impure non-blocking bounded queue of type (roughly speaking) `Queue[(F[E], E => Unit) forSome { type E }]` where `F` is the type under evaluation. These `F[E]` values are then picked up by satisfying a waiting `async`, which originally stems from an `Async[F]` instance. That `async` then evaluates the `F[E]` by simply running `flatMap`, which is the sticky bit: you can't have the outer `Async[F]` mismatch with the inner `F[E]`. For this reason, I'm not even convinced that `mapK` is possible, and you might need `imapK`. At the very least, a general dual-effect constructor is out of the question.
