### ISSUE TITLE
`SyncIO` -> `IO` conversion missing

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#1790]
In CE2, there used to be a `.toIO` method on `SyncIO`, but now it's gone. I  think we should add it.

**Comment by kubukoz** [comment]
Because SyncIO shouldn't block, I think this is just a matter of `IO(this.unsafeRunSync())`. Can someone confirm?

**Comment by djspiewak** [comment]
There's some subtlety here unfortunately. What should `Sync[SyncIO].blocking(thunk).toIO` do?

**Comment by kubukoz** [comment]
uhhh. so I guess we need to interpret the algebra? Shouldn't be *too* difficult... should it?

**Comment by vasilmkd** [comment]
Not sure if it needs to be expanded. E.g. there's no `SyncIO.blocking`, there's just `SyncIO.delay`.

**Comment by kubukoz** [comment]
Had me worried for a sec. I can see `suspend` ignores the hint too.
