### ISSUE TITLE
Add `IORuntime#dispatcher`?

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#1791]
I encountered this while upgrading a ScalaJS application: there's no default way to start a fiber and get it synchronously, which might sometimes be desirable (e.g. aforementioned JS land, as well as tests in frameworks like scalatest).

For this reason, I would've suggested adding a `.startSync` method on IO (cross-compiled, because why not), but prompted by @vasilmkd's mention of Dispatcher thought it would be even nicer to have a global Dispatcher that works directly with IORuntime - the right place to put it would likely be `IORuntime` itself, as it already has a dependency on `std`.

This would allow direct usage of `unsafeToFutureCancelable` / `unsafeRunCancelable` without `IO`/`Resource`.

**Comment by djspiewak** [comment]
Wouldn't just adding `unsafeRunCancelable` to `IO` also achieve this same purpose?

**Comment by kubukoz** [comment]
It would :)

**Comment by kubukoz** [comment]
So there's one thing - [Odin's slf4j interop](https://github.com/valskalla/odin/pull/273) requires you to provide a `Dispatcher[IO]` statically. This means pretty much that users need to do `Dispatcher[IO].allocated.unsafeRunSync()`... this conversion would be very helpful there.

**Comment by vasilmkd** [comment]
A `Dispatcher[IO]` can always delegate to the `unsafe` methods on `IO` itself. Are we comfortable exposing a `Dispatcher` not wrapped in a `Resource`? I guess that's fine because the `unsafe` methods on `IO` don't have a lifecycle associated to them. @djspiewak Thoughts?

```scala
final class IORuntimeDispatcher(runtime: IORuntime) extends Dispatcher[IO] {
  def unsafeToFutureCancelable[A](ioa: IO[A]): (Future[A], () => Future[Unit]) =
    ioa.unsafeToFutureCancelable(runtime)
}
```

**Comment by kubukoz** [comment]
yep, that's what I was thinking about. Users can do this on their own I suppose, but I think this will be a popular enough pattern eventually that we might just bake it in.

**Comment by djspiewak** [comment]
> A Dispatcher[IO] can always delegate to the unsafe methods on IO itself

This isn't safe though. :-) A major element of `Dispatcher` is the fact that it binds the fiber lifecycles together, rather than just throwing it over the wall. The `IO` methods have no real lifecycle binding, so a `Dispatcher[IO]` which just delegates to the methods directly on `IO` would have pretty dramatically different semantics.

**Comment by vasilmkd** [comment]
It's as safe as holding onto an `IORuntime` reference...

**Comment by vasilmkd** [comment]
I guess we should just educate people that this is possible. But I'm not sure if this belongs in the documentation, it's not something we want to encourage. 😕
