### ISSUE TITLE
Add `errorln`, `error` directly on IO's companion?

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#1792]
`errorln` is probably the less painful one, but `error` without any extra characters would likely confuse the hell out of users mixing it with `raiseError`. Let's bikeshed over this.

**Comment by djspiewak** [comment]
The reason these *aren't* on the companion is confusion with `raiseError`. If this isn't really deemed a serious problem then we can go ahead with it, but I'm skeptical. :-)

I'm going to take this out of the 3.0.0 milestone since it isn't a blocker, but we should come to a conclusion on it.

**Comment by kubukoz** [comment]
Makes sense, let's forget it.
