### ISSUE TITLE
Console.readLine is not interruptible due to `InputStream#read`

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#1793]
The produced effect should not use `IO.interruptible` but `IO.blocking` instead.

`InputStream#read` is not always an interruptible action, so our previous assumption was incorrect.

Some more details[here](https://stackoverflow.com/questions/3843363/thread-interrupt-not-ending-blocking-call-on-input-stream-read), for anyone interested, but not necessary.

**Comment by alexandrustana** [comment]
I could try and fix this if nobody minds

**Comment by vasilmkd** [comment]
Here's a small reproduction in Java that confirms this
```java
import java.io.IOException;

public class Main {
    public static void main(String[] args) throws Exception {
        final var thread = new Thread(() -> {
            final int n;
            try {
                n = System.in.read();
                System.out.println(n);
            } catch (IOException e) {
                e.printStackTrace();
            }
        });
        thread.start();
        System.out.println("Interrupting thread");
        thread.interrupt();
        System.out.println("Joining thread");
        thread.join();
        System.out.println("Done");
    }
}
```

This waits forever at `thread.join()`.

**Comment by djspiewak** [comment]
This is really disappointing, honestly. Does it hold true for every platform?

**Comment by vasilmkd** [comment]
You mean ScalaJS?

**Comment by djspiewak** [comment]
No I mean like Windows/Mac/Linux

**Comment by vasilmkd** [comment]
Sure, but I think we need to err on the side of caution. There is no mention of support for interruption in the Java [documentation](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/io/InputStream.html#read()).

**Comment by djspiewak** [comment]
Well, my point is that `blocking` and `interruptible` are equivalent for anything which ignores interruption, there's just a minor performance difference between the two. If we try to interrupt something and it ignores it, we don't do anything different than we would have done otherwise. So that implies to me that if there's *any* platform for which `System.in.read()` is interruptible, then we should keep the `interruptible` combinator.

**Comment by vasilmkd** [comment]
I've never thought of the issue that way. Ok, sorry for the confusion. Thank you for the discussion, it was very helpful.

**Comment by vasilmkd** [comment]
> Well, my point is that `blocking` and `interruptible` are equivalent for anything which ignores interruption, there's just a minor performance difference between the two. If we try to interrupt something and it ignores it, we don't do anything different than we would have done otherwise. So that implies to me that if there's _any_ platform for which `System.in.read()` is interruptible, then we should keep the `interruptible` combinator.

Sorry, but I think there's a bit more than just a minor performance difference. `interruptible` runs on the `compute` pool and thus hogs a `WorkerThread`, while `blocking` is shifted on the blocking thread pool. I think that still warrants a change. Wdyt?

**Comment by djspiewak** [comment]
> interruptible runs on the compute pool and thus hogs a WorkerThread

It runs on the blocking pool. :-D Or at least… I think it does? If it doesn't we need to change it

**Update:** Confirmed it's on the blocking pool

**Comment by vasilmkd** [comment]
Ok, let's keep `readLine` as is.
