### ISSUE TITLE
Properly deal with InterruptedException on the JVM

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#181]
We have our own [NonFatal](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/internals/NonFatal.scala) implementation because the standard one also filters things like `ControlThrowable`, which is pretty dumb.

However this means we are no longer catching `InterruptedException`, which is a problem.

The problem is that on top of the JVM, when you catch an `InterruptedException`, you can't just swallow it like any other exception. This is a problem:

```scala
try {
  operation()
} catch {
  case ignored: InterruptedException => /* BIG PROBLEM! */
}
```

What needs to happen is that we need to "restore the interrupted status". This can be done like this:

```scala
try {
  operation()
} catch {
  case ignored: InterruptedException =>
    // Restores interrupted status
    Thread.currentThread().interrupt()
}
```

So we need a `NonFatal` specific to the JVM that, upon catching `InterruptedException`, it restores its interrupted status.

**Comment by mpilquist** [comment]
@alexandru It's not clear to me that `NonFatal` should reset thread interruption status. I can see an argument for making that the responsibility of the user. Have you given any thought to the tradeoffs of auto-propagating interruption status vs current behavior? Seems like this is a very use case specific issue.

**Comment by akilegaspi** [comment]
I agree with @mpilquist , I think it's a matter of how what kind of operation the user actually spawned in the thread hence the responsibility of handling the thread interruption falls on the user's responsibility since not all operation being spawned in that context may be interrupted.

Also maybe the user might want to do something if they interrupt the thread on purpose.

**Comment by alexandru** [comment]
@mpilquist @akilegaspi it's not the responsibility of the user.

This issue is about the interoperability of Java libraries — the interruption protocol for Java threads is to:

1. let the thread die by re-throwing the exception, or ...
2. resetting the interrupted signal, such that the next call to `interrupt()` can re-throw the `InterruptedException` again

Consider this `ExecutionContext`:

```scala
class SingleThreadContext extends ExecutionContext {
  private val queue = new LinkedBlockingQueue[Runnable]()
  val thread: Thread = 
    new Thread(new Runnable {
      def run(): Unit =
        while (true) {
          val r = queue.poll()
          try r.run() 
          catch { case NonFatal(e) => e.printStackTrace() }
        }
    })
  
  locally(thread.start())

  def execute(runnable: Runnable): Unit =
    queue.offer(runnable)
  def reportFailure(cause: Throwable): Unit =
    cause.printStackTrace()
  def shutdown(): Unit =
    thread.interrupt()
}
```

```scala
implicit val ec = new SingleThreadContext()

// The user's responsibility ...

val io1 = IO.shift *> IO {
  // some slow processing
  while (true) {}
}

// NOT the user's responsibility ...

ec.shutdown()
```

Why I'm saying that this isn't the user's responsibility is because the environment is often provided for you.

Now I don't care about Java's interruption mechanism, I don't want us to cancel the computation in case an `InterruptedException` occurs (although this is always a possibility). But we need to play nice with other Java libraries and reset the interrupted flag, because apparently other Java libraries expect it.

And the change is simple really:

```scala
object NonFatal {

  def apply(t: Throwable): Boolean = t match {
    case _: VirtualMachineError => false
    case _: InterruptedException =>
      // resets interrupted status
      Thread.currentThread().interrupt()
      false
    case _ => true
  }

  def unapply(t: Throwable): Option[Throwable] =
    if (apply(t)) Some(t) else None
}
```

**Comment by mpilquist** [comment]
Ah, I thought you wanted `NonFatal` to return true on `InterruptedException`, and hence I felt the user should decide what to do with the exception -- e.g., rethrowing, reinterrupting, or ignoring. Based on your change above, I see that you are suggesting the opposite -- that `NonFatal` does *not* catch `InterruptedException`. In that case I'm totally on board with the suggested change.

**Comment by alexandru** [comment]
@mpilquist actually that was a typo 😀 

The current custom `NonFatal` catches `InterruptedException`.

So we have three choices:

1. we don't catch it, like Scala's standard `NonFatal`
2. we catch it and stream it as an error, like we currently do, but we reset its interrupted status
3. we catch it and treat it as cancelation

So what would be your vote?

**Comment by mpilquist** [comment]
My vote is 1 -- don't catch it at all and be consistent with `scala.util.control.NonFatal`.

How `IO` behaves when an `InterruptedException` is thrown is orthogonal though, right? That is, we can still treat an `InterruptedException` as cancelation in `IO` by adding an additional match?

**Comment by mpilquist** [comment]
Okay I see. I guess 3 then. :)

**Comment by kubukoz** [comment]
If https://github.com/monix/monix/pull/655 gets merged, I'll follow up with a PR here as well ;)

**Comment by durban** [comment]
Should this really be closed? As far as I can tell, the "deal with InterruptedException" part is not done yet ...

**Comment by durban** [comment]
> every line of code can throw, including lines of code not under our control

I don't think that's true. Lines not under our control, yes they can throw anything. But code like `1 + 1` won't magically throw `InterruptedException`, only the interrupted thread state is set magically.

But anyway, I don't really care if this specific issue is closed or not; I only commented because I thought it might've been closed unintentionally.
