### ISSUE TITLE
Cancelation deadlock in `IO.race`

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#1816]
Just as soon as #1814 was merged, the `AsyncBenchmark.race` benchmark is deadlocking. We had this exact same issue when we had a specialized implementation of `RacePair` and `Race`. Last time we chalked it up to a bad implementation of the specialized `Race` combinator, but now I'm suspecting that something fundamental is buggy in IO.

The only idea I can think of is that somehow fibers which are started but canceled before they've had the chance to run don't propagate their `Canceled` outcome to the outside world. If we look at the fix from today:
```scala
back <- onCancel(
  poll(result.get), {
    for {
      doneA <- deferred[Unit]
      doneB <- deferred[Unit]
      _ <- start(guarantee(fibA.cancel, doneA.complete(()).void)) // <- the guarantee is never called with an `Outcome`
      _ <- start(guarantee(fibB.cancel, doneB.complete(()).void)) // <- or here
      _ <- doneA.get
      _ <- doneB.get
    } yield ()
  }
)
```

I'm sorry if my intuition is wrong.

Wild speculation at 3:30 AM and I hope I'm wrong. What if the finalizer in guarantee is never even registered as a finalizer?

**Comment by vasilmkd** [comment]
These two code segments look strange to me, but I tried reordering the `done` and `cb(RightUnit)` and achieved nothing. My intuition here is that we should notify an external canceler of a successful cancel only when everything has been acknowledged inside the fiber (i.e. `done` is called with `OutcomeCanceled`).

```scala
  private[this] def asyncCancel(cb: Either[Throwable, Unit] => Unit): Unit = {
    // System.out.println(s"running cancelation (finalizers.length = ${finalizers.unsafeIndex()})")
    finalizing = true

    if (!finalizers.isEmpty()) {
      objectState.push(cb)

      conts = new ByteStack(16)
      conts.push(CancelationLoopK)

      /* suppress all subsequent cancelation on this fiber */
      masks += 1
      // println(s"$name: Running finalizers on ${Thread.currentThread().getName}")
      runLoop(finalizers.pop(), 0)
    } else {
      if (cb != null)
        cb(RightUnit)

      done(OutcomeCanceled)
    }
  }
```

```scala
  private[this] def cancelationLoopSuccessK(): IO[Any] = {
    if (!finalizers.isEmpty()) {
      conts.push(CancelationLoopK)
      runLoop(finalizers.pop(), 0)
    } else {
      /* resume external canceller */
      val cb = objectState.pop()
      if (cb != null) {
        cb.asInstanceOf[Either[Throwable, Unit] => Unit](RightUnit)
      }
      /* resume joiners */
      done(OutcomeCanceled)
    }

    IOEndFiber
  }
```

**Comment by vasilmkd** [comment]
Or is it maybe as simple as a situation like this:

```scala
object Example extends IOApp.Simple {

  def run: IO[Unit] =
    for {
      latch1 <- Deferred[IO, Unit]
      latch2 <- Deferred[IO, Unit]
      fiber <- IO(println("waiting for latch 2")) *> (latch2.get *> IO(println("blah")).guarantee(latch1.complete(()).void)).start
      _ <- fiber.cancel
      _ <- IO(println("waiting for latch 1"))
      _ <- latch1.get
    } yield ()
}
```

where the `guarantee` hasn't had a chance to run yet and this is a deadlock.

**Comment by vasilmkd** [comment]
Are these two code snippets functionally equivalent?
```scala
back <- onCancel(
  poll(result.get), {
    for {
      doneA <- deferred[Unit]
      doneB <- deferred[Unit]
      _ <- start(guarantee(fibA.cancel, doneA.complete(()).void)) // <- the guarantee is never called with an `Outcome`
      _ <- start(guarantee(fibB.cancel, doneB.complete(()).void)) // <- or here
      _ <- doneA.get
      _ <- doneB.get
    } yield ()
  }
)
```

and

```scala
back <- onCancel(
  poll(result.get), {
    for {
      fca <- start(fibA.cancel)
      fcb <- start(fibB.cancel)
      _ <- fca.joinWithNever
      _ <- fcb.joinWithNever
    } yield ()
  }
)
```

For the first one I can understand how it would be a user error, not anticipating that the `guarantee` may not even get a chance to run. But for the second one, I have no clue, and it also deadlocks.

**Comment by vasilmkd** [comment]
Not even this works:
```scala
back <- onCancel(
  poll(result.get), {
    for {
      fca <- start(fibA.cancel)
      fcb <- start(fibB.cancel)
      _ <- fca.join
      _ <- fcb.join
    } yield ()
  }
)
```

**Comment by djspiewak** [comment]
I think the very first thing we should do here is try to move the benchmark semantics into a unit test. It's kind of annoying that we keep discovering this in the benchmarks rather than in the test suite. Beyond that point, I think the next step would be to figure out if this is some weird race condition (probably) or if it's just a semantic issue (unlikely, but scary if so).

**Comment by vasilmkd** [comment]
Yes, I'm trying to reproduce this deterministically.
