### ISSUE TITLE
Global runtime installation mechanism not working in Scastie

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#1818]
Reported by @oleg-py [here](https://gitter.im/typelevel/cats-effect-dev?at=605af4e7f07ffa1eb5608da3).

![image](https://user-images.githubusercontent.com/7115459/112316039-05d3e080-8cab-11eb-8874-ac6f3e8dc7c4.png)

https://scastie.scala-lang.org/gLdvaPQsRpu9Gokfz9D7FA

**Comment by djspiewak** [comment]
My guess is that Scastie isn't classloader-isolating applications as completely as it should be. Any ideas, @OlegYch?

**Comment by OlegYch** [comment]
scastie is just doing `sbt run` with `turbo` on
the example seems to work with `turbo` off https://scastie.scala-lang.org/LZX9fcYXSjuaNh1mHswV9Q
`turbo` is supposed to improve `run` performance by reusing already loaded library jars, but i'm not sure how useful it actually is
would be nice if cats could work with it though

**Comment by djspiewak** [comment]
Hmm, how exactly does turbo work in this context? This may be something we need to explicitly detect. It would be concerning though if there was any sharing or IORuntime instances across runs.

**Comment by armanbilge** [comment]
Tried the scastie with CE v3.4.10  and v3.5.0-RC5. The good news is that it no longer crashes on the second invocation but it does log a warning that the global runtime is already installed. The bad news is that it then proceeds to hang 😅 

Update: seems to be hanging here.
https://github.com/typelevel/cats-effect/blob/c430fceceee128fdd91a4976c5b67893c607eef1/core/jvm/src/main/scala/cats/effect/IOApp.scala#L442
