### ISSUE TITLE
`IO.as`

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#1824]
In CE2, `IO.as` took a by-name parameter. In CE3, it's eager (like in the functor syntax). This might have an impact on the performance of users' applications due to the eager (and sometimes unnecessary) evaluation, should we change it back?

**Comment by kubukoz** [comment]
Sorry to add things to the milestone at this point, but it's potentially a BC-incompatible change after 3.0 😅

**Comment by kubukoz** [comment]
@djspiewak

**Comment by oleg-py** [comment]
I think it's better to have a by-value parameter there, so that there's no change if you migrate to/from `F[_]` and cats syntax.

**Comment by kubukoz** [comment]
I'll submit the fix.

**Comment by kubukoz** [comment]
Or not. Let's keep it as is, and we can add a similar method later.
