### ISSUE TITLE
Dispatcher docs don't say how to get one

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#1838]
(on the `docs` branch)

**Comment by LLCampos** [comment]
Some feedback from someone who has been struggling to understand `Dispatcher`.

For example, the **Motivation section** basically says "this does what this other thing did in cats-effect 2" which is is not really useful for people who are not experienced in CE2. :crying_cat_face: 

I think that having an example of a practical problem that can be solved with Dispatcher would be excellent!

And also a little explanation of exactly **how** it works in the inside - right now, it fells like magic to me. :)

**Comment by kubukoz** [comment]
Personally I think none of the docs should refer to CE2 except the migration guide 😅

**Comment by LLCampos** [comment]
We can close this one? https://github.com/typelevel/cats-effect/pull/2515 already merged.

**Comment by armanbilge** [comment]
And live! :)
https://typelevel.org/cats-effect/docs/std/dispatcher
