### ISSUE TITLE
Provide a way to unsafeRun IO synchronously without shifting until the async boundary

### ISSUE THREAD

**Issue by oleg-py** [typelevel/cats-effect#1862]
I'd like to have something like `def unsafeRunSyncStep(): Either[A, IO[A]]` on IO.

My particular scenario: in my react interop library, I'd like to get initial state for rendering from fs2 Stream as soon as possible as to not require two render passes if the state is available immediately (e.g. it's a constant stream). This is an optional optimization, but a nice one (e.g. lets library users not care about putting a placeholder for 1 frame if they're just using a `SignallingRef` or two)

This wasn't needed in CE2 IO since every run method blocked until the first boundary, but CE3 IO will forcibly auto-shift to the compute pool, meaning it can't get anything done during a first render call. Pretty sure the dispatcher can't be made helpful there either.

**Comment by djspiewak** [comment]
Maybe something like `def syncStep: SyncIO[Either[IO[A], A]]]` instead?

**Comment by oleg-py** [comment]
Well, doesn't matter really if it serves the same purpose. I thought making it unsafe would deter people from using it as it's arguably not something you should do unless you know what you're doing :)

**Comment by djspiewak** [comment]
Well, I guess what I'm getting at is it's probably not an entirely unsafe thing to do, though it would potentially result in very different evaluation semantics (when run iteratively) than just running the IO directly.

**Comment by vasilmkd** [comment]
But it is still side effecting right? I think that's Oleg's concern about `unsafe`.

**Comment by oleg-py** [comment]
Not if you translate to SyncIO

**Comment by vasilmkd** [comment]
Actually there might be a technical limitation behind this issue that we're not properly considering. As soon as a fiber is started, the runloop is coded in a way which reschedules the fiber on the runtime whenever it needs to execute an asynchronous shift. On top of that, the `outcome` of a fiber is _always_ reported asynchronously. I'm now starting to wonder if anything can be achieved without adding a significant amount of code and whether or not that will result in a performance impact on the normal execution of the runloop.

**Comment by djspiewak** [comment]
Basically we would need to create an alternative runloop which translates synchronous prefixes into `SyncIO`. This is part of why I hinted that the semantics might not be the same as just allowing `IO` to run it.
