### ISSUE TITLE
Unsigned tags and other strange things

### ISSUE THREAD

**Issue by durban** [typelevel/cats-effect#187]
Tags `v0.10` and `v1.0.0-RC` are not signed.

The commits currently marked by these tags are signed: `v0.10` is by which seems to be GitHub's key, and `v1.0.0-RC` is by a key `971E 5587 E7ED A30A E2F0  C230 397C 67E2 8DFD 7BB4` (the JAR too), which at first glance seems to belong to @alexandru, however, I couldn't find any indication that that is indeed the case. (GitHub seems to think so, but I don't know which checks they do. Keybase points to another key ` 0FB0CC008FF4FAD2 `.)

The tag `v0.10.1` is signed by a key `904C 1537 33DB B010 6915  C0BD 975B E5BC 29D9 2CA5`, which at first glance seems to belong to @rossabaker, but I also couldn't find any proof that it does. (The JAR is also signed by this key.)

(I did not check older tags.)

Ideally these things should be publicly verifiable (to some extent) :slightly_smiling_face:
(See also https://github.com/typelevel/cats-effect/blob/master/verifying-releases.md.)

**Comment by alexandru** [comment]
@durban you're right, I believe it is my mistake when creating those tags.

I think I can recreate them.

**Comment by alexandru** [comment]
@durban can you recheck the tags? 

Signature should be:

- email: noreply [at] alexn.org (it's not an active email address, as protection against spam 😉)
- key: 971E5587E7EDA30AE2F0C230397C67E28DFD7BB4

N.B. [keybase.io](https://keybase.io/) is useless for the purposes of verifying keys because they do not accept multiple email addresses. I'm not exposing my personal email address in GitHub commits or signatures.

**Comment by rossabaker** [comment]
I am now on [keybase.io](https://keybase.io/rossabaker).

**Comment by alexandru** [comment]
I also updated my keybase account with the aforementioned PGP key I'm using for publishing stuff: 
https://keybase.io/alexelcu

**Comment by durban** [comment]
@alexandru Thanks, I can confirm that the tags are now signed with `971E 5587 E7ED A30A E2F0  C230 397C 67E2 8DFD 7BB4` (which is now indeed on keybase).

@rossabaker Thanks! :slightly_smiling_face:
