### ISSUE TITLE
`Sync.interruptible` `many` parameter does the reverse of what's expected?

### ISSUE THREAD

**Issue by m50d** [typelevel/cats-effect#1883]
def interruptible[A](many: Boolean)(thunk: => A): F[A] =
      suspend(if (many) InterruptibleOnce else InterruptibleMany)(thunk)

Apologies if I'm missing something, but surely the boolean condition should be the other way round?

**Comment by vasilmkd** [comment]
Sorry where is this exactly? I'm looking at the code [here](https://github.com/typelevel/cats-effect/blob/60362ad77fdfb0ac83832eed11b9aa1966dcfb49/core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala#L33) and it seems fine.

**Comment by m50d** [comment]
The one in `Sync`, https://github.com/typelevel/cats-effect/blob/60362ad77fdfb0ac83832eed11b9aa1966dcfb49/kernel/shared/src/main/scala/cats/effect/kernel/Sync.scala#L95

**Comment by vasilmkd** [comment]
Shoot, that is most definitely a bug. Feel free to open a PR. :)

**Comment by djspiewak** [comment]
Yeah that's definitely backwards :-P
