### ISSUE TITLE
`IORuntimeConfigCompanionPlatform` type is visible

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#1899]
We forgot to hide this trait unfortunately.

**Comment by djspiewak** [comment]
Actually this is *binary* breaking too. I'm not sure we can change it. Depends on how religiously we want to hold onto that constraint in this case though

**Comment by vasilmkd** [comment]
I was missing a label.

**Comment by kubukoz** [comment]
Why is this binary breaking? Making a class `private[somePackage]` is probably fine... or is it?

**Comment by vasilmkd** [comment]
For mima, it actually might be fine (because it might be the same in terms of Java visibility), but the Scala compiler will reject to compile already written code from now on.

**Comment by kubukoz** [comment]
That's source breaking then :)

**Comment by djspiewak** [comment]
Let's just fix this. :-) It's pretty obviously an internal API that is leaking out. We'll privatize it and apologize to anyone who's code is broken.

**Comment by vasilmkd** [comment]
I found out why this code was written like this in the first place. This is a companion object, and therefore a type. Because the companion object is publicly visible, its superclasses need to be too. If we still want to get rid of the internal type, we have to move the companion object definition from the `shared` sources to the `jvm`/`js` sources separately, i.e. have a concrete platform specific implementation.

I'm still in favor of removing these unnecessary types.
