### ISSUE TITLE
Experiment with -Xasync

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1907]
According to @retronym it works with Cats Effect. Let's like… actually do it. I would very much like it if users could opt-in to this syntax for interacting with at least `IO`, and ideally any effect type.

**Comment by Baccata** [comment]
I've got something working. IOs are executed sequentially, and I haven't figured out why yet : 

* [implementation](https://github.com/Baccata/ce3-async/blob/main/src/main/scala/cats/effect/std/IOAsync.scala) 
* [example call](https://github.com/Baccata/ce3-async/blob/main/src/test/scala/com/example/HelloWorldSuite.scala#L15)

**Comment by renghen** [comment]
https://github.com/rssh/cps-async-connect

Have same goal as async await, hope you can take some ideas

**Comment by Baccata** [comment]
@renghen thanks for sharing, that's pretty cool ! 

Unfortunately in scala-2 land the integration point is much less straightforward (if you want to tap into the mechanism enabled by the `-XAsync` flag and not write complex AST transformations from scratch, that is). I really hope that if the flag gets ported to scala-3, the underlying mechanism will be similar to the one you offer in `dotty-cps-async`, and that if the flag wasn't ported for whatever reason, your library would be used as a point of reference to obtain feature parity. 

On an unrelated note, I was thinking that at some point I'd try implementing arrow-comprehensions (similar to https://github.com/manatki/volga) in Scala 3, and you work seem like it'd be a good starting point (the macro examples on dotty's website lack depth) 

Thanks again for sharing 😄

**Comment by renghen** [comment]
one note this is not my work (https://github.com/rssh/cps-async-connect) I am just interested in Continuation passing style.
So I follow that repo and hope for something like suspend like in kotlin will get into scala.

I will also look into the git repo you mentioned.

cheers

**Comment by Baccata** [comment]
Hah my bad. Still, thanks for sharing 😄

**Comment by b-studios** [comment]
I just want to mention that similar things can be achieved building on [monadic reflection](https://doi.org/10.1145/174675.178047)  and project loom: https://github.com/b-studios/cats-reflect

- The advantage is that you do not need a translation and it "just" works. In particular with higher-order functions like `map`.
- The disadvantage is that you need a Loom runtime -- it is much easier now since pre-release binaries are available, but it is still not the standard.

**Comment by djspiewak** [comment]
@b-studios That is really really cool

**Comment by b-studios** [comment]
Thanks @djspiewak! FYI, we moved our experiments here: https://github.com/lampepfl/monadic-reflection
