### ISSUE TITLE
SyncIOSpec has a flaky JVM specific test

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#1940]
Here's the flaky test, in a slow environment, the time difference between the two time snapshots can be larger than 30 milliseconds.

https://github.com/typelevel/cats-effect/blob/35c9e1ea45dec014e4dd4fe22f35e83de87fdd37/tests/jvm/src/test/scala/cats/effect/SyncIOPlatformSpecification.scala#L24

**Comment by vasilmkd** [comment]
Duplicate of #2022.

**Comment by djspiewak** [comment]
Actually I think mine was the duplicate :-P
