### ISSUE TITLE
Suggestion: override Functor's `as` and `void` for `IO` and `SyncIO`

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#1957]
Cats's `Functor` provides the following utilities:

```scala
def void[A](fa: F[A]): F[Unit] = as(fa, ())

def as[A, B](fa: F[A], b: B): F[B] = map(fa)(_ => b)
```

I think these should be overridden to log a warning (via whatever means) in case the value being ignored is an `IO` value.

For a motivating sample — this happened to me, and was not caught by tests 😒

```scala
F.delay(dropMessage(id)).as(())

// ....
def dropMessage(id: ID): F[Boolean] = ???
```

**Comment by alexandru** [comment]
Feels like an issue that could be solved by a linter. But I don't know of any linter with a rule that does this.

**Comment by alexandru** [comment]
I think I need to think about this for a while, brb 😅 closing the issue in the meantime to not clutter the issue tracker.

**Comment by djspiewak** [comment]
I think a linter might be a better approach in any case. :-D I actually use these methods *absolutely* all the time! Definitely wouldn't want them to just blindly warn.

What you're getting at here is the issue of linearity. You want to be able to declare that, in this particular `F[A]`, the `A` *must* be consumed, and there's simply no way to do that in Scala.

**Comment by alexandru** [comment]
I think the issue is that we don't see what we are ignoring.

```scala
implicit class Utils[F[_], A](self: F[A]) extends AnyVal {

  def ignoreResult[R](implicit F: Functor[F], r: R =:= A): F[Unit] = self.as(())
}
```

And then when using it, this would lead to a compile-time error:

```scala
F.delay(dropMessage(id)).ignoreResult[Boolean]
```
