### ISSUE TITLE
CE2 concurrency Overview docs have bad links to subtopics

### ISSUE THREAD

**Issue by arosien** [typelevel/cats-effect#1982]
https://typelevel.org/cats-effect/docs/2.x/concurrency/overview has links to "Basics", "Deferred", etc., but the links point to https://typelevel.org/cats-effect/docs/2.x/concurrency/basics.md (which is incorrect). The links in this doc should point to https://typelevel.org/cats-effect/docs/2.x/concurrency/basics.

<img width="1121" alt="Overview_·_Cats_Effect" src="https://user-images.githubusercontent.com/31163/118842928-713ac880-b87e-11eb-88e9-913bf3d99cc7.png">

**Comment by vasilmkd** [comment]
I believe this is tackled in #1965.

**Comment by arosien** [comment]
@vasilmkd ah thanks! Issue search failed me :(.

**Comment by vasilmkd** [comment]
It's fine, I have to work with the PR author to help them out. 😄

**Comment by vasilmkd** [comment]
Addressed in #1985.
