### ISSUE TITLE
Kill IOApp when SIGINT repeatedly

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1992]
At present, `IOApp` waits for finalizers to complete before allowing exit on <kbd>Ctrl</kbd>-<kbd>C</kbd>. This is generally a good default, but it should be overridable without having to resort to `SIGKILL` if the application is hung. Something like three INT signals within a one second time window should trigger an immediate shutdown, regardless of finalizer status.

**Comment by rossabaker** [comment]
Wait, what?  <kbd>Ctrl</kbd>-<kbd>C</kbd>shouldn't change behavior just because we're angry.  This is why we have different signals that yield different exit codes.

**Comment by djspiewak** [comment]
Interested as to thoughts on this. The scenario here is that the user wants to kill the application, but a finalizer (or uncancelable block) is stuck and thus the application cannot be terminated. The point is that rapidly repeated TERM is likely to indicate direct user input and is almost certainly a signal that they don't care about graceful release, they just want the process to die.

**Comment by rossabaker** [comment]
Well, I guess that's fair for `SIGINT`, which is what <kbd>Ctrl</kbd>-<kbd>C</kbd> sends.  You're only communicating an intent to interrupt the process, and I suppose there's room to detect user rage.  But `SIGTERM`, the default signal of `kill`, ought to remain graceful.

Objection withdrawn.

**Comment by aeons** [comment]
Terraform attempts graceful shutdown on the first ctrl-c and forcefully aborts on the second, with a warning about what might happen. I think that's a pretty good way of doing it.

**Comment by djspiewak** [comment]
> Well, I guess that's fair for SIGINT, which is what Ctrl-C sends. You're only communicating an intent to interrupt the process, and I suppose there's room to detect user rage. But SIGTERM, the default signal of kill, ought to remain graceful.

In which I betray the fact that I always forget which signal is which.

**Comment by ChristopherDavenport** [comment]
In case others needed reference like I just needed to follow this conversation: 

Gnu Termination Signals - https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html

**Comment by rossabaker** [comment]
My CE2 `IOApp` experience is coming back to me.  Even though the JVM exits with the expected code (signal value + 128), there's no way to distinguish `SIGTERM` (which should be graceful) from `SIGINT` within the application.  The only way (at least on Java 8) was JNI quagmire.

Furthermore, I'm not sure that repeated signals will be detectable: the shutdown hooks are triggered by the first `SIGINT` or `SIGTERM`, and I don't think it's re-entrant.  Experiment and see, but I doubt this can be implemented by a plain JVM, even if we wanted `SIGINT` and `SIGTERM` to do the same thing.

**Comment by djspiewak** [comment]
> My CE2 IOApp experience is coming back to me. Even though the JVM exits with the expected code (signal value + 128), there's no way to distinguish SIGTERM (which should be graceful) from SIGINT within the application. The only way (at least on Java 8) was JNI quagmire.

`sun.misc` has an API for this. I believe Java 11 introduced a replacement (it may have been in Java 9). But tldr we can capture actual signals.

**Comment by rossabaker** [comment]
It's `jdk.internal.misc.Signal` as of Java 9, which seems imprudent for a bedrock dependency.  Before that was `sun.misc.Signal`, which is banished to the unsupported module in modern JVMs.  There's always runtime reflection, but it all seems like a lot of magic to avoid `^Zkill -9 %`.

**Comment by vasilmkd** [comment]
Caveats https://docs.oracle.com/en/java/javase/17/troubleshoot/handle-signals-and-exceptions.html#GUID-D8754420-3A1F-4D93-A877-1FE041E50081.
