### ISSUE TITLE
Weird fairness/scheduling issue

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1995]
Still not sure what's going on here. I've been poking at this for a little while:

```scala
object InefficientProducerConsumer extends IOApp {

  def producer[F[_]: Spawn: Console](queueR: Ref[F, Queue[Int]], counter: Int): F[Unit] =
    for {
      _ <- if (counter % 10000 == 0)
        Console[F].println(s"Produced $counter items")
      else
        Applicative[F].unit

      _ <- queueR.getAndUpdate(_.enqueue(counter + 1))
      _ <- producer(queueR, counter + 1)
    } yield ()

  def consumer[F[_]: Monad: Console](queueR: Ref[F, Queue[Int]]): F[Unit] =
    for {
      _ <- Console[F].println("attempting to consume")
      iO <- queueR modify { queue =>
        queue.dequeueOption.fold((queue, Option.empty[Int])) {
          case (i, queue) => (queue, Option(i))
        }
      }

      _ <- if (iO.exists(_ % 10000 == 0))
        Console[F].println(s"Consumed ${iO.get} items")
      else
        Applicative[F].unit

      _ <- consumer(queueR)
    } yield ()

  override def run(args: List[String]): IO[ExitCode] =
    for {
      queueR <- Ref.of[IO, Queue[Int]](Queue.empty[Int])
      cf <- consumer(queueR).start
      pr <- producer(queueR, 0).start

      cfR <- cf.join
      _ <- IO.println(s"!!! found cfR = $cfR")

      prR <- pr.join
      _ <- IO.println(s"!!! found prR = $prR")
    } yield ExitCode.Success
}
```

If you run this, you'll see a ton of `attempting to consume`, followed by infinite `Produced` printlns, which honestly doesn't make any sense. It's like the first fiber hogs the thread for a while, then the second fiber takes over and never lets it go.

**Comment by vasilmkd** [comment]
@djspiewak I don't have a great explanation for this, but hear me out.

```scala
import cats._
import cats.effect._
import cats.effect.std._
import cats.syntax.all._
import scala.collection.immutable.Queue
import scala.concurrent.duration._

object InefficientProducerConsumer extends IOApp {

  def producer[F[_]: Spawn: Temporal: Console](queueR: Ref[F, Queue[Int]], counter: Int): F[Unit] =
    for {
      _ <- if (counter % 10000 == 0)
        Console[F].println(s"Produced $counter items")
      else
        Applicative[F].unit

      _ <- queueR.getAndUpdate { q =>
        q.enqueue(counter)
      }
      // _ <- Temporal[F].sleep(100.millis)
      _ <- producer(queueR, counter + 1)
    } yield ()

  var blah = 0

  def consumer[F[_]: Monad: Sync: Console](queueR: Ref[F, Queue[Int]]): F[Unit] =
    for {
      _ <- Console[F].println("attempting to consume")
      iO <- queueR modify { queue =>
        println(s"blah $blah")
        queue.dequeueOption.fold((queue, Option.empty[Int])) {
          case (i, queue) =>
            (queue, Option(i))
        }
      }

      _ <- Sync[F].delay { blah += 1 }

      _ <- if (iO.exists(_ % 10000 == 0))
        Console[F].println(s"Consumed ${iO.get} items")
      else
        Applicative[F].unit

      // _ <- Temporal[F].sleep(10.millis)
      _ <- consumer(queueR)
    } yield ()

  override def run(args: List[String]): IO[ExitCode] =
    for {
      queueR <- Ref.of[IO, Queue[Int]](Queue.empty[Int])
      cf <- consumer(queueR).start
      pr <- producer(queueR, 0).start

      cfR <- cf.join
      _ <- IO.println(s"!!! found cfR = $cfR")

      prR <- pr.join
      _ <- IO.println(s"!!! found prR = $prR")
    } yield ExitCode.Success
}
```

After a while, the `blah` counter never gets incremented, which to me signals that the evaluated function in the consumer (after the C2 compiler kicks in) is just much slower than the producer function, which wins the super tight CAS loop in `Ref`. Does this make any sense?

**Comment by djspiewak** [comment]
> After a while, the blah counter never gets incremented, which to me signals that the evaluated function in the consumer (after the C2 compiler kicks in) is just much slower than the producer function, which wins the super tight CAS loop in Ref. Does this make any sense?

I've been thinking along the same lines. In theory, `dequeueOption` should actually be *faster* than `enqueue`, but perhaps it isn't. I haven't looked closely at `scala.collection.immutable.Queue` in many years.

**Comment by djspiewak** [comment]
It'd be interesting to try to verify this in some way. Tricky though. Maybe literally adding a `Thread.sleep` in the enqueue side. Hilariously though, that would imply that `IO` itself is so fast that this example is bounded by the fairness (or rather, *unfairness*) of `AtomicReference`!

**Comment by vasilmkd** [comment]
I'd love to hear some thoughts on how to better verify the behavior.

**Comment by djspiewak** [comment]
Okay I think I verified it:

```scala
_ <- queueR.getAndUpdate({q => Thread.sleep(10); q.enqueue(counter + 1)})
```

If you make that change, then the *consumer* wins every time.

Basically I think this might just be a really bad example. :-) `Ref` isn't fair because `AtomicReference` itself isn't fair, so if you slam on it hard enough, you're going to get situations like this.

**Comment by vasilmkd** [comment]
Come on Daniel, say what you really mean, no reason to hide it! 😄😆🥳

**Comment by djspiewak** [comment]
> Come on Daniel, say what you really mean, no reason to hide it! 😄😆🥳

lol Our runtime is legitimately so fast that it breaks examples like this. So for anyone following along at home, this wasn't a problem before because the runtime *used* to be slow enough that the overhead dominated the race on both sides and things were somewhat fair. Now the `Queue` operations dominate by a significant margin, meaning that it's just a pure race between two different `Queue` operations thrown on a naive scheduler that doesn't support fairness (`AtomicReference`).

Or, if you want a tldr: our runtime is too fast for this
