### ISSUE TITLE
IO error message contain the runtime class

### ISSUE THREAD

**Issue by fommil** [typelevel/cats-effect#200]
Typical output is currently

```
[info]   IO failed with 
[info]   Message: Remotely closed
[info]   CausedBy: None
```

it would be useful to include the runtime class of the `Throwable` in here as often the `Message` is `null`.

**Comment by mpilquist** [comment]
@fommil Could you paste more? E.g. a stack trace or some context as to where you are seeing that output? I don't see anything in cats-effect that would output that.

**Comment by fommil** [comment]
Hmm, i wonder if perhaps it is some rendering code that is custom to our codebase. I'll check that out and get back when I've investigated.
