### ISSUE TITLE
Support GraalVM native image on Scala 3

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#2032]
To build a cats-effect 3 app with Scala 3 and GraalVM native image, one currently has to set some configuration options, otherwise the build falls back to a version that requires a JDK.

This is what the native-image agent generated for me:

```json
[
{
  "name":"cats.effect.unsafe.IORuntimeCompanionPlatform",
  "fields":[{"name":"0bitmap$1", "allowUnsafeAccess":true}]
},
{
  "name":"cats.effect.unsafe.WorkStealingThreadPool",
  "fields":[{"name":"0bitmap$1", "allowUnsafeAccess":true}]
},
{
  "name":"java.lang.invoke.VarHandle"
},
{
  "name":"sun.misc.Unsafe",
  "allDeclaredFields":true
}
]
```

(passed with `-H:ReflectionConfigurationFiles`)

Maybe we can include some version of this in the jar itself, so users don't need to bother with these options: https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/

Here's a sample app built with this config: https://github.com/kubukoz/graalvm-native-ce3/ (note that the options aren't necessary when building with Scala 2.13.6)

**Comment by vasilmkd** [comment]
Wait what, we absolutely do not use any Unsafe, and bitmap fields are autogenerated by the Scala compiler. There is no way we can influence them. I'm confused.

**Comment by kubukoz** [comment]
I think that one might be irrelevant. Probably just the first two are important, I'm just pasting what the program generated :) 

even if that's generated by the compiler, someone needs to provide this config, and apparently dotc itself isn't capable of that

**Comment by smarter** [comment]
The lazy val runtime code uses Unsafe: https://github.com/lampepfl/dotty/blob/master/library/src/scala/runtime/LazyVals.scala

**Comment by kubukoz** [comment]
Maybe some of this could be attached to the dotty runtime? :D

**Comment by smarter** [comment]
We'd have to include all fields with `bitmap$` in their name, can we use wildcards in the graal native configuration file? Oẗherwise it sounds like something that could be hardcoded in graal itself.

**Comment by djspiewak** [comment]
@kubukoz Is there a way we could do this with some sort of wildcard? I'm definitely in favor of making it as easy as possible to use native-image with CE, so entirely amenable to tossing something in the JAR distributables if it is helpful.

**Comment by vasilmkd** [comment]
https://github.com/sshark/text-draw

This setup seems fairly straightforward.

**Comment by djspiewak** [comment]
Agreed. I think this works fine.
