### ISSUE TITLE
Add `Dispatcher#toIO`

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#2036]
This is going to be helpful for people migrating from CE2 and `Effect.toIOK`.

An example implementation:

```scala
new (F ~> IO) {
  def apply[A](fa: F[A]): IO[A] = IO.defer {
    val (future, cancel) = dispatcher.unsafeToFutureCancelable(fa)
    IO.fromFuture(IO(future)).onCancel(IO.fromFuture(IO(cancel())))
  }
}
```

Perhaps there's a more efficient way.

**Comment by kubukoz** [comment]
see, I'm so tired it took two renames for a proper fix.

**Comment by djspiewak** [comment]
I think the real danger of this is it might lead someone to write `OptionT[IO, *] ~> IO`, with predictable heartache. There are ways around the problems with that function, of course, but the implementation in the OP makes the bear traps really hard to avoid.

**Comment by vasilmkd** [comment]
Also, `Dispatcher` lives in `std`, which cannot point to `IO`. 😕

**Comment by kubukoz** [comment]
😭

extension method in `cats.effect.implicits`?

`OptionT[IO, *] ~> IO`

wait. How does that even end up working?

edit: ah, it deadlocks on empty options.
