### ISSUE TITLE
Add MVar and CircuitBreaker

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#206]
I can contribute these data types to Cats-Effect, from Monix.

MVar needs some changes and can't be imported directly because in Monix I've got this design where the Task version is built on top of an unsafer variant that can work with Future.

Plus it's currently not cancelable and we need to keep the convention that when using `Concurrent`, it needs to be. But that's not a problem, I can reuse the `LinkedMap` implementation we are importing from fs2.

If nobody minds I'd like to take care of these. Unless somebody was already working on it 🙂

**Comment by luisspringernature** [comment]
Hi Alexandru,
we were having a discussion about introducing a circuit breaker for http4s client and then we realize about this ticket.
What the plan for this work is at the moment?

**Comment by alexandru** [comment]
Hi Luis,

We have a good Circuit Breaker implementation in Monix that I planned to port to Cats-Effect.

However I’ve been caught up with work and the upcoming Monix 3.0, so I haven’t managed to do it.

So the answer is that it is planned to ship in Cats-Effect 1.0.0, if you can have a little patience until then :-)

— 
Alexandru Nedelcu
https://alexn.org

**Comment by luisdeltoro** [comment]
Hi Alexandru,

that sounds good. I would probably write something custom for the time being and replace it with your implementation when cats-effect 1.0.0 is released. 

Thanks very much for the info,

Luis

**Comment by kubukoz** [comment]
Hi @alexandru, what's the status on this? Is CircuitBreaker still in scope of cats-effect?

**Comment by alexandru** [comment]
No, `CircuitBreaker` is no longer in scope for cats-effect, being added to `monix-catnap`.
