### ISSUE TITLE
Initiate Gitter channel

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#21]
Folks, lets initiate a Gitter channel for `cats-effect`.

The general Cats channel is too noisy. I'd like our own channel because we can talk about implementation details among ourselves and also because I could keep notifications on for users seeking help.

The Cats channel is so noisy that I keep it on mute and I don't participate much in discussions there, happens only once in a blue moon.

So it won't be too popular, but so what? That's a good thing.

**Comment by rossabaker** [comment]
I'd probably rather general support remain in cats, especially with the proposal that this moves into the cats repo when both are 1.x.  If we think we can get this stabilized faster with chat, I'd be happy to be in a temporary dev channel.

**Comment by alexandru** [comment]
So lets do a temporary dev channel.

Btw, I know that I proposed for this to be pushed in Cats, but I'm not so sure about it now.

The problem is that we'll lose history - commits, issues, etc. When a user asks for why a certain feature is implemented in a certain way, or missing, we should be able to point to the issue or to the PR that made it happen.

Losing history isn't cool.

**Comment by rossabaker** [comment]
Git history can be preserved if the merging of the repos is done via a merge commit of the two heads.  Issues of course don't migrate quite so well.

**Comment by mpilquist** [comment]
:+1: for dev channel.

I feel fairly strongly that cats-effect should be in its own repository. Embrace modularity. :)

**Comment by djspiewak** [comment]
:+1: to both of @mpilquist's points.

Let's create a dev channel, typelevel/cats-effect, but we'll keep the readme badge pointing to typelevel/cats.  That gets the noise out of typelevel/cats, without fragmenting the community.
