### ISSUE TITLE
Write documentation for `IOLocal`

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2117]
What it says on the tin. It needs both scaladoc and should also have a page in the site (**docs/** subdirectory).

**Comment by manufacturist** [comment]
I'd like to tackle this one 😄

**Comment by manufacturist** [comment]
Unfortunately I lack the time to invest into this task 😭 I've unassigned myself. If it'll still be open in the mid future, I'll be able to pick it up again.

**Comment by vasilmkd** [comment]
No worries.
