### ISSUE TITLE
Add tracing configuration to `IORuntimeConfig`

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#2144]
Probably every configurable aspect except `cats.effect.stackTracingMode` which we need to be statically available at JVM startup.

**Comment by djspiewak** [comment]
@vasilmkd Race you! :-) I literally just started a branch on this

**Comment by vasilmkd** [comment]
Wait a minute, in light of #2146, I think we should postpone this issue after that one has been implemented.

**Comment by djspiewak** [comment]
Let me push a branch for you to look at. Tldr I think we'll be okay.
