### ISSUE TITLE
Add `IO.trace`

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2161]
Should return something like `IO[Trace]`, which should be an immutable data type containing methods like `enhanceException(Throwable): Throwable`, `pretty: String`, `oneline: String` (or maybe just `toString`), etc. This handles use-cases like ad-hoc debugging and external exception handlers (like Sentry).

I'm labeling this as a **good first issue** even though it's going to be a *bit* involved. I would label it as "intermediate first issue" if I could. :-) This is a good one if you like something chewy to work on which doesn't require a *ton* of context but which will introduce you to a lot of internal details, including the `IO` run-loop.

**Comment by alexandrustana** [comment]
If nobody minds, I could try and tackle this one.

If I understood correctly, when we have the following snippet
```scala
IO.pure(1).map(_ + 1) >> IO.trace.flatMap(t => IO.println(t.pretty))
```
the trace should look something  like this
```scala
map @ Example$.run
>> @ Example$.run
run$ @ Example$.run
```
Calling `trace` should create a copy of the current `TracingEvents` and store it in the `immutable structure` mentioned in  the description, so the `flatMap` call will not be observed in `t`.

Are these assumptions correct?

**Comment by vasilmkd** [comment]
Yes and also feel free to look in the CE2 code, but I need to warn you, we're not looking to replicate that API, I would try to design something along the lines of what Daniel described in the first comment of this issue.

**Comment by alexandrustana** [comment]
I was thinking of extending `IO` with `TraceIO` and in the run-loop handle the newly created tag and construct a `Trace` object using the events from the `RingBuffer`.  
I wasn't aware of the `trace` from CE2 😄

**Comment by djspiewak** [comment]
:+1: to all of the above. And go for it, @alexandrustana!
