### ISSUE TITLE
Add `IOLocal.unsafeApply`

### ISSUE THREAD

**Issue by milanvdm** [typelevel/cats-effect#2178]
I would like to add the following code to `IOLocal`:

```scala
def unsafeApply[A](default: A): IOLocal[A] =
      new IOLocal[A] { self =>
        override def get: IO[A] =
          IO.Local(state => (state, state.get(self).map(_.asInstanceOf[A]).getOrElse(default)))
        override def set(value: A): IO[Unit] =
          IO.Local(state => (state + (self -> value), ()))
        override def reset: IO[Unit] =
          IO.Local(state => (state - self, ()))
        override def update(f: A => A): IO[Unit] =
          get.flatMap(a => set(f(a)))
        override def modify[B](f: A => (A, B)): IO[B] =
          get.flatMap { a =>
            val (a2, b) = f(a)
            set(a2).as(b)
          }
        override def getAndSet(value: A): IO[A] =
          get <* set(value)
        override def getAndReset: IO[A] =
          get <* reset
      }
```

It would be useful for me as I use `IOLocal` creation to do byte-instrumentation to add tracing to `IO`. And I would like to prevent running an `unsafeRunSync` in the injected code.

If this makes sense, I'll gladly make the PR :)

**Comment by armanbilge** [comment]
Ah, we've had a couple PRs proposing similar things. None of which got merged 😅 

- https://github.com/typelevel/cats-effect/pull/2482
- https://github.com/typelevel/cats-effect/pull/2827
- https://github.com/typelevel/cats-effect/pull/2828

The good news is, you can workaround this by using `IO#syncStep`. Even though it's not guaranteed by the type signature, in practice the `SyncIO` returned should always resolve to a `Right`.
