### ISSUE TITLE
Cats Effect 2.5.2 is slightly botched

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#2195]
We have not included the `SyncIO.defer` and `IO.defer` additions.

The `v2.5.2` tag is made at this [commit](https://github.com/typelevel/cats-effect/commit/cfb40e69810f586b227fd9db17e99e9839ef421f), but the aforementioned changes landed in a PR _after_ it.

@djspiewak You are my only hope.

**Comment by vasilmkd** [comment]
The scalafix tests are understandably [angry](https://github.com/typelevel/cats-effect/runs/3240386094?check_suite_focus=true).

**Comment by djspiewak** [comment]
Uh oh. I think we need a 2.5.3 and a corresponding bump in the scalafix tests.

**Comment by vasilmkd** [comment]
Yes. Unfortunately.

**Comment by djspiewak** [comment]
Okay, on it :-)

**Comment by djspiewak** [comment]
Okay 2.5.3 is now propagating. I'm not totally sure which elements of the scalafix I need to update.

**Comment by vasilmkd** [comment]
Just to be safe find/replace every `2_5_2` reference with `2_5_3`, `252` with `253`, `2.5.2` with `2.5.3` including renaming files and directories. I wish this comment that I'm typing at the moment was a joke.

We also need to amend release notes.

**Comment by vasilmkd** [comment]
Confirming that with `2.5.3`, the scalafix tests all pass properly.
