### ISSUE TITLE
Improve `sbt test` experience for JS

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#2201]
- [ ] check for required dependencies (geckodriver etc.) and fail with nice error messages
- [x] auto-generate the CI command, see https://github.com/typelevel/cats-effect/pull/2191#discussion_r681273946
- [x] Add `scalafmtSbtCheck` to platform specific CIs (`ciJVM`, `ciJS` and friends)

**Comment by armanbilge** [comment]
Can we close this? Although we couldn't make it go away browser testing is a minor part of the suite now.

**Comment by djspiewak** [comment]
I think this is good :-)
