### ISSUE TITLE
Loss of the ability to mock Clock in version 3 

### ISSUE THREAD

**Issue by rehanone** [typelevel/cats-effect#2220]
I am currently in a process of upgrading a relatively large code base that uses Cats Effect and FS2 as building blocks for implementing many micro-service. One thing that is causing too much trouble is the changes made to Clock in the version 3. We have a large number of unit tests that mock the Clock in version 2 to control the timing and test various aspects of the code.

Now it might be my lack of knowledge but so far I have not found a way to mock Type class Clock provided by version 3. This is a complete deal breaker as we are absolutely not going to give up the tests in question. So far, it seams I have only 2 options:

1 - Stay on v2 for foreseeable future and abandon the upgrade effort.
2 - Create a local copy of the Clock trait from version 2 and replace all use of it in the code base.

The first option seams easy at first but that deprives us from taking advantage of any new improvements that come with version 3 especially the IO as I was hoping to replace the Monix Task with it. Also there is a fear of being left behind as the entire eco-system moves on.

The second one seams more logical at this point to me as it might just be very easy replacement. However, it leave a bad taste as it is constant reminder of something that used to work and now doesn't!

I hope I am not overly critical and I want to be absolutely clear that I love working on the code base using these 2 great libraries that make defining very complicated systems a breeze. But I am seriously stuck on this issue for some time now. I see an issue mentioning something similar to this problem (https://github.com/typelevel/cats-effect/issues/1678). But there is no serious activity on that for some months and it is not clear what the scope of that issue is. That is why I decided to open a new issue here.

Thanks in advance for any guidance that can help me solve this issue.

**Comment by djspiewak** [comment]
Yeah this is an excellent point to raise, and I agree the current experience is highly suboptimal. One approach to this that can help, though it's extremely manual, is to bring in the **testkit** project and use `TestContext`. This *works*, but it's not the most ergonomic thing. I would like us to implement a smoother approach, more tightly integrated into the runtime, but I haven't had time to work on it.

**Comment by vasilmkd** [comment]
Indeed, please do not think that anyone is against it. We also think that it's a very important and welcome feature and we will support it, we just don't have a firm timeline as to when.

Staying on Cats Effect `2.x` is also fine in the foreseeable future, I'm personally taking care of bug fixes and updates for the project, of course, without any guarantees of new feature development, which only happens on `3.x`

**Comment by djspiewak** [comment]
Btw for anyone following along, a good way to help would be to add ideas here (or on the other issue if you prefer) for how you would imagine time mocking would work in CE3. The CE2 approach of just providing a new instance of `Clock` definitely isn't coming back, but imagine something more integrated into the `IORuntime`.

**Comment by rehanone** [comment]
Thanks for the feedback @djspiewak, @vasilmkd!

I have not used or looked at testkit so perhaps that is what I would do in the fullness of time. In the meanwhile, Since I have already made good progress in conversion, it feels right to just conclude this CE2 to CE3 conversion asap as getting time allocated for tech debt is hard to comeby. I am currently using a copy of the CE2 Clock and it seams to work fine so far.

Coming back to addressing this issue in the CE3 for the future, I think it would help if we can clearly outline the disadvantages of Clock in CE2 as a starting point (Maybe that would just help me understand this issue better but I feel like others would benifit from that as well). I see that it is not following the cats laws but to me it seams to provide a great opportunity for testing all sorts of time related code that would not have otherwise be possible if we were still at the mercy of System.currentTimeMillis().

**Comment by tomverran** [comment]
Hi, I ran into this issue today migrating to CE3 and ended up with this temporary workaround to allow tests to manipulate the global time (We're still using Scalatest currently): https://gist.github.com/tomverran/0615a73ccd2d1eaf005f348b956a9512. I'm very sure that what I've done is a bad idea though and do feel free to tell me why! :sweat_smile: I've never really touched the internals of Cats Effect before.

I just thought I'd post it to illustrate that some kind of `TestIORuntime` whose lifecycle could be managed by the test framework would be a nice interface I think, it could then have some functions to allow the time to be manipulated.
