### ISSUE TITLE
Cached tracing for `IO.delay` is broken in Scala 3

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#2225]
As uncovered by a [discord discussion](https://discord.com/channels/632277896739946517/839263556754472990/875532566508212294) with @vasilmkd.

[Code in question](https://github.com/typelevel/cats-effect/blob/series/3.x/core/shared/src/main/scala/cats/effect/IO.scala#L932-L935): 
```scala
def apply[A](thunk: => A): IO[A] = {
  val fn = () => thunk
  Delay(fn, Tracing.calculateTracingEvent(fn.getClass))
}
```

On Scala 3, `fn.getClass` is a constant regardless of the value of `thunk`. Thus, all uses of `delay` end up with the same cached trace.

On Scala 2, `fn.getClass` returns a different value for different `thunk`s (AFAICT, it returns the class of the `Function0` that the `thunk` is syntax sugar for) and thus cached tracing works as expected.

This issue can be observed in [this scastie](https://scastie.scala-lang.org/CyYasg6cR9eSfFCLIrsI9Q) particularly by toggling between Scala 2 and Scala 3. Update: a more precise test demonstrating this problem is now in #2226.

Not sure how to fix this, other than perhaps disabling caching/doing full tracing for every `delay`?

**Comment by vasilmkd** [comment]
Fixed in #2226.
