### ISSUE TITLE
Parallel map2/map2Eval fails to short-circuit on error

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2238]
```scala
(F.never, F.raiseError(e)).parTupled
```

I believe the above hangs forever. It (correctly) aborts early if we invert the order of the operands.

The problem here is the implementation is done in terms of `Spawn[F]` rather than `Concurrent[F]`, meaning that it boils down to:

1. Start first fiber
2. Start second fiber
3. Join first fiber
4. Join second fiber

If the first fiber never returns, then we can't observe the completion of the second fiber. The only way to resolve this is to use a `Deferred` for each of the two fibers so that their completion handlers can be *within* the body of the fibers themselves, as opposed to happening post-`join`. There might be a fancy way of doing this with extra fibers but I'm not totally sure, and it would probably be less efficient than doing a pair of `Deferred`s.

**Comment by armanbilge** [comment]
Just a random idea, could you use `racePair` then join with the losing fiber?

Edit:

> The problem here is the implementation is done in terms of Spawn[F] rather than Concurrent[F]

Ah, is this what prevents that?

**Comment by djspiewak** [comment]
> Ah, is this what prevents that?

Not quite. We *could* `racePair` but then we take on a lot of the performance costs of the old implementation. :-P I have a different idea actually involving separate supervisory fibers, though it *will* cost more than the current implementation. It will probably also cost more than using `Deferred`, but I'm not totally certain.

**Comment by djspiewak** [comment]
Confirming that the following test fails:

```scala
      "short-circuit on error" in ticked { implicit ticker =>
        case object TestException extends RuntimeException

        (IO.never[Unit], IO.raiseError[Unit](TestException)).parTupled.void must failAs(TestException)
        (IO.raiseError[Unit](TestException), IO.never[Unit]).parTupled.void must failAs(TestException)
      }
```
