### ISSUE TITLE
`timeout` eagerly creates `TimeoutException`

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2244]
This imposes a relatively significant cost (due to the stack trace construction) despite the common case where the timeout is *not* hit and thus the exception is not needed.

**Comment by ixthe0** [comment]
hey @djspiewak, is it OK if I work on this issue?

**Comment by vasilmkd** [comment]
Go for it. Feel free to ask for pointers here or in the Discord.
