### ISSUE TITLE
IOTimer builder does not use parameter passed

### ISSUE THREAD

**Issue by ajaychandran** [typelevel/cats-effect#225]
[Line](https://github.com/typelevel/cats-effect/blob/f0b1847bbe1d21272e22786c1088b501ea630b66/core/jvm/src/main/scala/cats/effect/internals/IOTimer.scala#L61)

```scala
  /** Builder. */
  def apply(ec: ExecutionContext, sc: ScheduledExecutorService): Timer[IO] =
    new IOTimer(ec, scheduler)
```

**Comment by rossabaker** [comment]
Fixed by #226
