### ISSUE TITLE
Deprecate `interruptible(boolean)` and replace with `interruptible`/`interruptibleMany`

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2268]
By "deprecate" I mean "set to `private[effect]` and undo the currying". We need to maintain binary compatibility but we can break source compatibility with this change. The goal should be for `IO.interruptible(...)` to be equivalent to what `IO.interruptible(false)(...)` is *today*, while `IO.interruptibleMany(...)` should be equivalent to `IO.interruptible(true)(...)`. This change should also be applied to `Sync`.

### Discussed in https://github.com/typelevel/cats-effect/discussions/2248

<div type='discussions-op-text'>

<sup>Originally posted by **etspaceman** August 19, 2021</sup>
I'm wondering if we should create an alias around this. For example,  `interruptible(false)` reads like it isn't interruptible. Perhaps we should consider `interruptibleOnce` and `interruptibleMany`. </div>

**Comment by alexandrustana** [comment]
I could pick this up if nobody minds.

**Comment by djspiewak** [comment]
Go for it! The only tricky part will be pleasing binary compatibility while you go about it. Always feel free to ask questions!
