### ISSUE TITLE
NPE in catsEffect3RuntimePingPong

### ISSUE THREAD

**Issue by senia-psm** [typelevel/cats-effect#2269]
With the latest (3.2.4) version of cats-effect there is an NPE in catsEffect3RuntimePingPong benchmark, published by @djspiewak 

I'm getting NPE (see below) on this fork (all other benchmarks removed, version updated) https://github.com/senia-psm/async-runtime-benchmarks.

Env: 
 - Linux
 - openjdk version "1.8.0_302"
 - AMD Ryzen 5 2600 Six-Core

Log:
> $ sbt jmh:run
> ...
> [info] # Benchmark: benchmarks.Benchmarks.catsEffect3RuntimePingPong
> [info] # Run progress: 0,00% complete, ETA 00:04:30
> [info] # Fork: 1 of 3
> [info] # Warmup Iteration   1: 824,686 ops/s
> [info] # Warmup Iteration   2: 965,760 ops/s
> [error] Exception in thread "io-compute-2" java.lang.NullPointerException
> [error]         at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:392)

**Comment by djspiewak** [comment]
Oh that's fun. I noticed the first iterations passed; I'm assuming it's a bit inconsistent on when it fails?

**Comment by djspiewak** [comment]
My guess would be that there's a race condition in `drainBatch` which results in corrupting the batched queue. It's getting late so I can't dig into it today, but it seems probable.

**Comment by senia-psm** [comment]
> I'm assuming it's a bit inconsistent on when it fails?

@djspiewak yes, in this case there were 2 successful iterations. In some ceases it fails on the first iteration. I've failed to make a better reproducer - it's quite a heisenbug.

**Comment by vasilmkd** [comment]
This is my mistake. I have a fix incoming.

**Comment by djspiewak** [comment]
Thanks for the reproduction, @senia-psm! These kinds of things are usually quite bonkers to narrow down.
