### ISSUE TITLE
FS2 compilation failures due to change in signature of fromPromise

### ISSUE THREAD

**Issue by mpilquist** [typelevel/cats-effect#2271]
#2237 changes `fromPromise` to take an `IO[Thenable[A]]` instead of an `IO[Promise[A]]`. As a result, fs2-io has 61 compilation errors when using expressions of the form `F.fromPromise(F.delay(somethingThatReturnsPromise))`. The compiler doesn't know the infer `somethingThatReturnsPromise` as a `Thenable[X]`.

**Comment by djspiewak** [comment]
I think we probably have to roll that change back. That's honestly unexpected. I'll take care of it.
