### ISSUE TITLE
Document tracing on JavaScript

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2286]
Should be similar to the JVM tracing docs and in the same section. Basically we just need to know how to configure it, and users also need to be aware that it's there.

**Comment by armanbilge** [comment]
You can assign this to me.

**Comment by armanbilge** [comment]
By in the same section, I assume you mean the same page? Do we want JS tracing to be its own section on that page ("btw here's how you do all this on JS") or should it be interleaved with the JVM docs ("here's how you do on JVM, here's how do you the same thing on JS")? I think it would be nice to interleave, and then maybe add a brief footnote-ish section explaining different ways to use `process.env` for JS (Node.js, webpack, etc.)
