### ISSUE TITLE
Clear the `tracingEvents` ring buffer when a fiber ends

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#2317]
Feel free to ask me for pointers.

**Comment by djspiewak** [comment]
This is a pretty straightforward one! Requires touching the internals of `IOFiber`, but only in one very self-contained location.

**Comment by milanvdm** [comment]
Im trying to pick this one up.

I initially thought about changing the `IOFiber.tracingEvents` to a `var` and clear it together with all other internals in `def done`.

But then I was doubting the fact that other parts of the code would still need some reference to the `tracingEvents` even after an `IOFiber` has finished? If so, then my initial thought is probably incorrect.

**Comment by vasilmkd** [comment]
@djspiewak Thoughts on this?

I initially envisioned it as adding a `clear()` method on `RingBuffer` which would be similar to the clear method on `ArrayStack`, but I guess I also don't mind changing the `tracingEvents` to a `var`.

Leaving up to Daniel.
