### ISSUE TITLE
Documentation: Dependency conflict resolution example not working

### ISSUE THREAD

**Issue by don41382** [typelevel/cats-effect#2386]
Hi guys,

I am stucked with the exact example in the cats documentation (https://typelevel.org/cats-effect/docs/migration-guide#which-modules-should-i-use) on how to handle dependency conflicts.

My project shows me (almost) the same output as the documentation:

```
sbt:demo> update
[error] stack trace is suppressed; run last commons / update for the full output
[error] (commons / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.typelevel:cats-effect_2.13:3.1.1 (early-semver) is selected over 2.5.1
[error] 	    +- org.tpolecat:doobie-free_2.13:1.0.0-RC1            (depends on 3.1.1)
[error] 	    +- co.fs2:fs2-core_2.13:3.0.3                         (depends on 3.1.1)
[error] 	    +- io.monix:monix-catnap_2.13:3.4.0                   (depends on 2.5.1)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] Total time: 1 s, completed 04.10.2021, 10:36:50
```

In the documentation it says: "Just update monix-catnap to a never version". The problem is, there is no newer version which supports cats-effect above 2.5.1.

Is the only solutions to wait until monix-catnap is updated to a higher cats-effect version?

Thanks for your help in advance.

**Comment by armanbilge** [comment]
> Is the only solutions to wait until monix-catnap is updated to a higher cats-effect version?

I'm afraid so, where "wait" would mean continue using CE2 and libraries compatible with it. Last I checked, monix itself is still only available for CE2, although that may have changed.

**Comment by don41382** [comment]
Hi @armanbilge,

Thanks for your support. We really wanted to use Doobie, but Monix is preventing it from happening. Such a shame. I was hoping there is another way, because it was explicitly quoted in the documentation. I guess, it's (currently) just a bad example.

**Comment by rossabaker** [comment]
doobie-0.13.4 is built on cats-effect-2.x and should work with that Monix.
