### ISSUE TITLE
`TraceSpec` is broken on WSLv2

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2425]
```
[info] TraceSpec
[info] IO should
[error]   x have nice traces
[error]    false (file:1)
[info] Total for specification TraceSpec
[info] Finished in 71 ms
[info] 1 example, 1 failure, 0 error
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         tracing.TraceSpec
[error] (testsJS / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 9 s, completed Oct 17, 2021, 7:40:30 PM
```

Not entirely clear to me why this is the case.

**Comment by armanbilge** [comment]
What is WSLv2?

**Comment by armanbilge** [comment]
Also I've been having similarly obtuse issues with traces in https://github.com/typelevel/cats-effect/pull/2413#issuecomment-944489932.

**Comment by vasilmkd** [comment]
Windows Subsystem for Linux version 2. It's pretty new, maybe only in Windows 11.

**Comment by djspiewak** [comment]
It's new but it's been in Windows 10 for about a year now. It's basically a more general version of WSLv1.

**Comment by vasilmkd** [comment]
Also, I'm assuming you're using a Linux JDK?

**Comment by djspiewak** [comment]
Yep!

**Comment by vasilmkd** [comment]
Ah, this is actually a JS test failure. I couldn't reproduce it on WSLv2, Ubuntu 20.04, JDK 17, Node 14.18.1, both JVM and JS tests pass without issues.

@djspiewak Can you provide your setup please?

**Comment by armanbilge** [comment]
This test also runs in the browsers, try those?

**Comment by vasilmkd** [comment]
WSL is a headless environment, I doubt people install the browsers in it. I tried switching to Node 16, also no problems. This is on Windows 10. I cannot install Windows 11 due to hardware incompatibilities. If this is indeed a Windows 11 issue, @djspiewak you're on your own. 😆
