### ISSUE TITLE
Unexpected finalization of uncancelable resource

### ISSUE THREAD

**Issue by iRevive** [typelevel/cats-effect#2472]
**Scala version:** 2.13.6
**Cats-effect version:** 3.2.9

**Minimal example:**
```scala
import cats.effect.{IO, IOApp, Resource}
import cats.effect.syntax.monadCancel._

object Main extends IOApp.Simple {

  def resource(prefix: String): Resource[IO, Unit] =
    Resource.makeCase(IO.unit) {
      case (_, Resource.ExitCase.Succeeded) => IO.println(s"[$prefix]. Release. Success")
      case (_, Resource.ExitCase.Errored(e)) => IO.println(s"[$prefix]. Release. Error: $e")
      case (_, Resource.ExitCase.Canceled) => IO.println(s"[$prefix]. Release. Canceled")
    }

  def run: IO[Unit] =
    for {
      r1 <- resource("general").use(_ => IO.raiseError(new RuntimeException("oops"))).attempt

      // emulate error
      r2 <- resource("uncancelable").uncancelable.use(_ => IO.raiseError(new RuntimeException("oops"))).attempt

      // emulate cancelation
      d <- IO.deferred[Unit]
      fiber <- resource("uncancelable cancel").uncancelable.use(_ => d.complete(()) >> IO.never).start
      _ <- d.get // wait till `use` hit `never`
      _ <- fiber.cancel
      
      _ <- IO.println("r1: " + r1)
      _ <- IO.println("r2: " + r2)
    } yield ()

}
```

The output:
```
[general]. Release. Error: java.lang.RuntimeException: oops
[uncancelable]. Release. Success
[uncancelable cancel]. Release. Success

r1: Left(java.lang.RuntimeException: oops)
r2: Left(java.lang.RuntimeException: oops)
```

For some reason, a resource that has been marked as `uncancelable` always has `ExitCase.Succeeded` during the release stage. Even though it has been canceled or completed with an error.

`Resource.uncancelable[IO, Unit](_ => resource("uncancelable"))` has the same behavior.

**Comment by vasilmkd** [comment]
Thanks for the report!

**Comment by vasilmkd** [comment]
Some thoughts on this code.

I believe 3. makes sense to me. In terms of the "bracket" operation that `Resource` encodes, canceling the use of an `uncancelable` `Resource` should not signal to the `Resource` (its `ExitCase`) that it was canceled, so intuitively it seems correct to me that the `Resource` succeeded.

I do think that 2. is confusing. We probably have a bug there, but I will wait for other maintainers to weigh in on the issue.

**Comment by djspiewak** [comment]
Btw `IO.canceled` is an easier way to emulate cancelation. :-)

At any rate, the error suppression seems like a bug to me. The rest seems reasonable though. The semantics of `uncancelable` are such that it doesn't *prevent* cancelation, only prevents it from being observed until the end of the block.

**Comment by vasilmkd** [comment]
So a question here.

> only prevents it from being observed until the end of the block.

If a whole `resource` is marked `uncancelable` the end of the block is after the resource? What should the `ExitCase` be in that situation?

**Comment by djspiewak** [comment]
> If a whole resource is marked uncancelable the end of the block is after the resource? What should the ExitCase be in that situation?

Either `Errored` or `Succeeded`.

**Comment by djspiewak** [comment]
I can confirm that the OP found a bug. In particular, it's the fact that `allocated` is not directly dual to `applyFull`, which results in the scopes being closed too soon. The solution is to create an `allocatedFull` which directly inverts. Chat thread where Fabio and I discussed the solution: https://discord.com/channels/632277896739946517/839263556754472990/903693244708298812

**Comment by djspiewak** [comment]
Also this test reproduces the issue:

```scala
    "uncancelable" >> {
      "does not suppress errors within use" in real {
        case object TestException extends RuntimeException

        for {
          slot <- IO.deferred[Resource.ExitCase]
          rsrc = Resource.makeCase(IO.unit)((_, ec) => slot.complete(ec).void)
          _ <- rsrc.uncancelable.use(_ => IO.raiseError(TestException)).handleError(_ => ())
          results <- slot.get

          _ <- IO {
            results mustEqual Resource.ExitCase.Errored(TestException)
          }
        } yield ok
      }
    }
```

Can also be reproduced without `use`. Really it's any time you're relying on scope extension beyond an `applyFull`/`allocated` nesting (an encoding which is used heavily in the `Async` for `Resource`, including in `uncancelable`).

**Comment by TimWSpence** [comment]
If nobody objects, I'm going to have a go at this. I haven't really dealt with `Resource` internals before so it should be interesting 😅

**Comment by djspiewak** [comment]
Give it a shot! :-) Really this is about implementing an `allocatedFull` that is dual to `applyFull`
