### ISSUE TITLE
Refresh `Dispatcher` scaladocs 

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#2519]
As of https://github.com/typelevel/cats-effect/pull/2515 they are a bit out-of-sync with the microsite docs, and possibly with the implementation (?).

**Comment by vasilmkd** [comment]
I actually made a mistake w.r.t. the `Supervisor` sentence in the docs. It was correct in the PR and we need to restore it. The scaladoc for `Dispatcher` is correct.

You can find more details [here](https://discord.com/channels/632277896739946517/632278585700384799/907186574993809418).

**Comment by armanbilge** [comment]
What about my comment/confusion about completion vs cancellation of the submitted effects? Can we get additional clarity on that as well?

https://github.com/typelevel/cats-effect/pull/2515#issuecomment-962634856

**Comment by vasilmkd** [comment]
Can you please scroll to the bottom of the discussion I linked? Is that answer satisfactory?

**Comment by armanbilge** [comment]
Thanks. So can my take-away be that `Dispatcher` and `Supervisor` have identical behaviour wrt to this? I guess this is more an issue with the `Supervisor` docs, which say:
> When this scope exits, all supervised fibers will be finalized.

whereas the `Dispatcher` scaladocs say:

> Once the resource scope exits, all active effects will be canceled.

Can we say cancellation for Supervisor too?

**Comment by vasilmkd** [comment]
> Can we say cancellation for Supervisor too?

Short answer, yes, `Supervisor` is used to implement `Dispatcher`.

Long answer, you can imagine `Dispatcher` as a pure consumer of items produced by impure producers. There is a processing queue connecting the two. The producers are appending elements (in this case effects to be executed) on one end and the `Dispatcher` is popping them from the same queue on the other end. All of the effects that have been popped are started as fibers and supervised by the wrapped `Supervisor`. For these effects, the behavior is vanilla `Supervisor` in the sense that, if the scope is closed, the supervised fibers are finalized (canceled and awaited). However, currently nothing is done for the unfortunate effects which are still on the queue that haven't been started and supervised. These are currently silently dropped when the `Dispatcher` scope is closed. Nothing is done to those effects, is as if they never existed.

**Comment by armanbilge** [comment]
Thanks. Awesome explanation.

**Comment by armanbilge** [comment]
Not completely sure if it's related, but I was reminded of https://github.com/typelevel/fs2/issues/2497. The common question being, should you finalize an effect that wasn't run and if so, how?

> Nothing is done to those effects, is as if they never existed.

I actually think this might be the "right" behavior here, or "consistent", or something.

**Comment by vasilmkd** [comment]
In the end we might not need to actually change any behavior, just make the developer experience better through logging or something.

**Comment by armanbilge** [comment]
Idk if it's possible/makes sense, but an alternative API where closing backpressures until completion (rather than cancellation) could be interesting? It could reject new submissions, but wait until old ones are all done.

**Comment by vasilmkd** [comment]
Addressed in #2515 and #2535.
