### ISSUE TITLE
NPE when running IOFiber

### ISSUE THREAD

**Issue by hughsimpson** [typelevel/cats-effect#2527]
I am occasionally seeing an error with cats-effect 3.2.9 that I can't yet reproduce locally. The following is the full stacktrace:

```
java.lang.NullPointerException: null
    at cats.effect.internals.Utils.setThreadTokenAndRefCount(Utils.java:57)
    at cats.effect.IOFiber.run(IOFiber.scala)
    at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:435)
```

I'm not sure where `cats.effect.internals.Utils.setThreadTokenAndRefCount` comes from, or what's setting this off. Will continue make some attempts to minimise, but in the meantime the stacktrace makes it look like there's some error in the heart of cats-effect. If there's anything anyone can think of trying to help me produce a more useful report, please let me know - I am currently mystified by pretty much every aspect of the error

**Comment by vasilmkd** [comment]
Ok, this is weird. We literally do not have an `internals` package, nor a `Utils.java` source file.

Can you please provide the operating system, any hardware specs and maybe even the classpath of the application. Thanks.

**Comment by hughsimpson** [comment]
Somehow that confirmation was everything I needed to nail down the actual culprit - newrelic. https://github.com/newrelic/newrelic-java-agent/blob/5882b996e14aabc1ef57661573dc539719bb906f/instrumentation/cats-effect-3/src/main/java/cats/effect/IOFiber.java#L33
That certainly explains why I'm unable to replicate it locally. Thanks very much for the 🦆 , I'll close this since it's clearly not a bug in cats-effect itself

**Comment by vasilmkd** [comment]
Can we be of any more assistance?

**Comment by hughsimpson** [comment]
I don't think so, thanks very much though. I'll raise an issue against new relic.

**Comment by hughsimpson** [comment]
Forgot to post the linked issue 🤦 https://github.com/newrelic/newrelic-java-agent/issues/544
