### ISSUE TITLE
`std.Env[F]` for cross-platform environment variables?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#2532]
Currently there is no JVM/JS cross-platform API for accessing environment variables. @bpholt and I wonder whether this might makes sense to include in CE3 `std`. 

Why:
* `IOApp` already provides cross-platform command line args via a shim for JS. It doesn't seem too much of a stretch to also provide cross-platform env.
* We've actually already internally shimmed env for JS, to configure tracing etc. at runtime. So it would just be a matter of exposing that code in a public API.
* `Console[F]` might also be a precedent for this kind of thing?

Why not:
* Dubious whether reading environment variables is an effect. @ChristopherDavenport had some thoughts about this.
* Just generally out-of-scope for CE3.

**Comment by armanbilge** [comment]
For anyone who needs this today, @ChristopherDavenport just microlib-ed the implementation in https://github.com/typelevel/cats-effect/pull/2650.
https://github.com/davenverse/env

**Comment by rossabaker** [comment]
Environment variables can be set within the current process on a POSIX system.  Java doesn't provide that in a public API, but I don't see why JNI couldn't do it, or Scala Native if we ever supported that.  If the point is to be cross-platform, it's absolutely an effect.  (For more prior art, so does Haskell.)

**Comment by rossabaker** [comment]
Another reason it's an effect is that it can throw a `SecurityException` on the JVM.
