### ISSUE TITLE
Explain what a "FFI" is or use other term?

### ISSUE THREAD

**Issue by LLCampos** [typelevel/cats-effect#2536]
The term "FFI" is sprinkled around the website and scaladocs, but is never explained. Googling doesn't help ([1](https://discord.com/channels/632277896739946517/632278585700384799/882933023530684467), [2](https://discord.com/channels/632277896739946517/632278585700384799/904304276833177641)).

I know this sounds like a small thing, but cats-effect is already full of potentially new concepts - introducing a unknown, unnecessary and unexplained new one in the docs might be really frustrating for people on the learning journey. 

Should "FFI" be changed to a more understandable term? Or should it be explained, maybe in the [concepts page](https://typelevel.org/cats-effect/docs/concepts)? 

I would say changing the term is better, at least in the website, since its not a concept you really need to know to learn how to use the library

**Comment by armanbilge** [comment]
> I would say changing the term is better, at least in the website, since its not a concept you really need to know to learn how to use the library

I agree. From what I can tell, "FFI" is not a need-to-know like you say, but rather a quick/familiar analogy that's supposed to help _explain_ Cats Effect. You can see this dating back to the original [blog post](https://typelevel.org/blog/2017/05/02/io-monad-for-cats.html) introducing CE:
> You can think of this sort of like an FFI that converts impure code (like println) into pure code (like putStrLn)

Except, for those of us who _don't_ readily know what an FFI is, we're left out in the cold. I'd vote to minimize use of FFI as the primary analogy.

**Comment by otto-dev** [comment]
I ran into this - googled what FFI stands for while reading the docs, and still don't know to this day.

**Comment by timshen24** [comment]
So what does FFI really stand for?

**Comment by otto-dev** [comment]
By now I know it's **Foreign Function Interface**. However, from what I can see, the term is not used true to definition, or at least used very loosely.

An FFI bridges the barrier between two different programming languages (according to Wikipedia, Python, PHP, Go, stackoverflow etc). E.g. `C` bindings in `Python` or `Go`. In Cats Effect, however, it merely bridges the gap between different API's or paradigms in the same host language.

I think the term should replaced. Maybe just scrap the `Foreign` and spell it out. Eg. `Sync/Blocking/Async/Future/Callback/... Function Interface`.

(Edited for brevity)
