### ISSUE TITLE
`Dispatcher` that backpressures on completion (not cancellation)

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#2537]
Spinning out of https://github.com/typelevel/cats-effect/issues/2519#issuecomment-963620976, which will be closed shortly.
> Idk if it's possible/makes sense, but an alternative API where closing backpressures until completion (rather than cancellation) could be interesting? It could reject new submissions, but wait until old ones are all done.

Not sure if this applicable to `Supervisor` itself.

**Comment by armanbilge** [comment]
One possible flaw with this idea is that if you start a never-completing fiber (e.g. a server) with dispatcher and don't have any way to cancel it, then unless your dispatcher cancels it on close are you are stuck :)

**Comment by djspiewak** [comment]
This is actually done in 3.4.0
