### ISSUE TITLE
Verify that 3.3.0 scalafix rules are picked up by Scala Steward

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2573]
Honestly I have no idea how to check this. @fthomas?

**Comment by fthomas** [comment]
The rule has been added to Scala Steward's list in https://github.com/scala-steward-org/scala-steward/pull/2270 and I just verified that `sbt scalafixEnable; scalafix github:typelevel/cats-effect/v3_3_0?sha=series/3.x` works. It should pick it up.

**Comment by djspiewak** [comment]
Thanks!
