### ISSUE TITLE
`Console` on Node.js is underpowered and probably blocks

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#2588]
This was first reported by @ChristopherDavenport in [Discord](https://discord.com/channels/632277896739946517/632278585700384799/900962949374550027).

1. `System.out.print` delegates to `console.log` which is standard JS but has various limitations. Node.js has a more featured `process.stdout`.
2. Furthermore, `process.stdout` is async so `console.log` on Node.js is almost definitely a blocking op.
3. I'm actually not sure what `readLine` does right now, but it definitely doesn't do what we want :)

This requires a source-breaking change to obtain the additional `Async` constraint. For browsers and bincompat we will also keep the old `Sync` based implementation.

I actually started a branch to fix this at the time but didn't follow-through 😅
https://github.com/armanbilge/cats-effect/tree/feature/nodejs-console

**Comment by armanbilge** [comment]
Btw, the reason I stalled on my branch is b/c `readLine` is fairly annoying to implement on Node.js. As with many things in Node.js `process.stdout` and `process.stdin` are stream-based and would be trivial to implement in fs2-io.js.

So here's an idea: maybe we should just deprecate `Console#readLine` on JS, since it's not supported on browsers anyway, and suggest users on Node.js use fs2-io instead.

We can merge the printing fixes in my branch in CE3 since at least that is a universal API even if it's a bit underpowered in the browser.

**Comment by djspiewak** [comment]
Should be possible to fix this in a binary-compatibly (but source-incompatible) fashion, but we would need to make the SJS version take an `Async` while the JVM one only needs a `Sync`. I wonder if that's okay…

**Comment by armanbilge** [comment]
Yup, that's exactly what I had in mind. Actually, whenever there are mismatched constraints across platforms I think this is a perfect case for capability traits like `Console` which lets you push these constraints to the edge of your app :)

We have a similar situation in http4s where JVM crypto only needs `MonadError` but JS crypto needs fullblown `Async`.
https://github.com/http4s/http4s-crypto/

**Comment by djspiewak** [comment]
I think that moving `Console.make` up into a `ConsoleCompanionPlatform` trait, then overloading the scala.js version to take an `Async` while marking the `Sync` version `private[std]` is probably the right way to go. That should give us what we need, and will properly produce errors on scala.js if we don't have an `Async` available.
