### ISSUE TITLE
Some IOAppSpec tests can be executed on all platforms

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#2601]
Currently, most of the example `IOApp` tests are not executed on Windows, because it doesn't support proper interruption of processes through the `java.lang.Process` API. These tests are the ones calling the `Handle#term` method. However, some tests do not call this method and instead wait for the monitored app to finish by itself. These should be run on Windows too.

The solution to this issue looks at `IOAppSpec.scala` and tries to run as much of the tests marked with `skipped("cannot observe graceful process termination on Windows")` unconditionally on all platforms. This probably means moving the tests from the `else` block above the `if/else` and removing the `skipped` tests. Feel free to reorganize the file as you see fit.

I'm tagging this issue as a "good first issue" so that new or less experienced people can pick it up, but I must warn them. Dealing with processes is annoying and tedious. Please do not get frustrated if something doesn't work on first try. Feel free to open a PR and the CI will do most of the testing.

That being said, this shouldn't be hard to do, but if you're stuck, we'll help you.

**Comment by lurenhaothu** [comment]
Hi! I would be happy to help with this issue!
