### ISSUE TITLE
Expose a tickFor(time: FiniteDuration) in TestControl

### ISSUE THREAD

**Issue by atnoya** [typelevel/cats-effect#2615]
In some cases the logic you are trying to test might not be adequate for manually ticking and advancing directly.

An simplified example:

```scala
def functionToTest[A](sleep: FiniteDuration, calc: => IO[A], emit: A => IO[Unit]): IO[Unit] = {
    calc.flatMap(emit) <* IO.sleep(sleep)
}
```
If I want to test how many times `emit` is called in a given period of time, I would need to understand exactly how and when fibers are scheduled (not only in the `functionToTest` but also if anything is scheduled in `calc` or `emit`.

I would propose to add some utilities to advance the clock and tick, e.g.:

```scala
  def advanceFor(duration: FiniteDuration): IO[Unit] = {
    Monad[IO].iterateWhileM(Option(0.millis)) { cur => 
      control.nextInterval.attempt.map(_.toOption)
        .flatMap {
        case Some(n) if n > 0.millis => (control.advance(n) <* control.tick).as(Some(cur.getOrElse(0.millis) + n))
        case Some(_) => control.tick.as(cur)
        case None => IO.pure(None)
        }
    } { cur => 
      cur.nonEmpty && cur.exists(_ < duration) 
    }.void
  }
```

```scala
//The test now becomes rather simple:

val expected = 60
Ref.of[IO,Vector[Int]](Vector.empty).flatMap { ref =>
    val test = functionToTest(1.second, IO.pure(1), (a: Int) => ref.modify(cur => (cur.appended(a, ()))).timeout(1.minute).attempt
    TestControl.execute(test).flatMap { control =>
      for {
          _ <- control.tick
          _ <- control.advanceFor(1.minute)
          _ <- ref.get.map(acc => assert(acc.forall(_ == 1) && acc.size == expected))
        } yield ()
    }
  }
```

Not sure if this makes sense, or there is a better way to achieve the same with the current API.

**Comment by djspiewak** [comment]
Maybe I'm missing something, but doesn't simply calling `advance` and then `tick` do very nearly what `advanceFor` does? The only difference I could see would be if there's some time interval less than the full advance wherein some new `sleep` is enqueued. Alternatively, this is a bit like `tickAll` but with a limit on how far you advance in time.

**Comment by atnoya** [comment]
>Alternatively, this is a bit like tickAll but with a limit on how far you advance in time. 

Yes, this is exactly it :)

> The only difference I could see would be if there's some time interval less than the full advance wherein some new sleep is enqueued

This is exactly the issue indeed, perhaps the example I provided is too simplistic. The usecase in which I have had to implement this helper function was for an e2e test of a fs2 streams app that pulls elements forever and pushes to a http endpoint in limited batches at a regular pace (there are several `IO.sleep` with different duration at different parts of the application. And this IO.sleeps will happen in parallel (one as a timeout in the Pull to emit partial batches after some linger time, another one to attempt to fill batches before calling the API or emit after some lingering, another one to set the pace before calling the API.)

It's very hard to know how many times I have to advance and tick and in what order. But I do know that at a given time offset X I should get A for input B. Does this make sense?

P.D. the name `advanceFor` isn't great, I think `tickFor(duration: FiniteDuration)` might be more in line with the similarities with `tickAll`

**Comment by djspiewak** [comment]
What about `tickUntil`?

**Comment by djspiewak** [comment]
Actually `tickFor` is probably a better name for it. I think something like this?

```scala
def tickFor(time: FiniteDuration): IO[Unit] =
  tick *> nextInterval flatmap { next =>
    val next2 = time.min(next)
    val time2 = time - next2

    advance(next2) *> {
      if (time2 <= 0)
        IO.unit
      else
        tickFor(time2)
    }
  }
```

**Comment by atnoya** [comment]
that's more elegant indeed, however, I tested this in my project and got a couple of issues:

- `nextInterval` can throw an `UnsupportedOperationException: empty.min` (I believe this happens if there is no next interval available, as in, nothing pending to be scheduled)
- `advance` throws an `IllegalArgumentException: requirement failed` if `next2` is `0`

This slightly modified version works:

```scala
  def tickFor(time: FiniteDuration): IO[Unit] =
    tick *> nextInterval.handleError(_ => 0.millis) flatMap { next =>
      val next2 = if (next == 0.millis) time else time.min(next)
      val time2 = time - next2

      advance(next2) *> {
        if (time2 <= 0.millis)
          IO.unit
        else
          tickFor(time2)
      }
    }
```

Both issues should probably be handled within the `nextInterval` and `advance` respectively, so your original suggestion would just work.

**Comment by djspiewak** [comment]
> nextInterval can throw an UnsupportedOperationException: empty.min (I believe this happens if there is no next interval available, as in, nothing pending to be scheduled)

Oh derp. That's an oversight in the API. I believe you are correct and it probably should be fixed

**Comment by atnoya** [comment]
If you are happy with the implementation suggested, It would be my first contribution to cats-effect, so i'll need guidance, but it doesn't seem too complicated and, perhaps, I can give it a go, wdyt?

**Comment by djspiewak** [comment]
@atnoya Sorry for the delay in getting back to you! Had a really busy few weeks. You should definitely jump on this if you're interested! Contributing isn't too fancy: just make a fork, push your change to a branch, and PR it back to `series/3.x` (the default base). Make sure to run `sbt prePR` before you push to avoid annoying scalafmt issues.
