### ISSUE TITLE
Indicate if fiber is completed in dump/toString

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#2628]
If a fiber hasn't been GCed (either due to non-determinism or some strong reference) or we are directly calling `toString` on it, we should indicate if it is complete.

**Comment by armanbilge** [comment]
I think this is an easy one by adding a getter to `IOFiber` to check for `DoneR` indicating the fiber is complete.
https://github.com/typelevel/cats-effect/blob/2ad8b8024eb1beb4e5d6e9746dcfbd47d8ff1d02/core/shared/src/main/scala/cats/effect/IOFiber.scala#L992

Then, update all the places printing fiber status (fiber dump and toString) to use this info.

**Comment by armanbilge** [comment]
https://github.com/typelevel/cats-effect/pull/2829 has some follow-up work to do :)

**Comment by iRevive** [comment]
I wasn't able to work under some circumstances.
I am still willing to finish this task. 

I will filter out completed fibers from the dump.

**Comment by vasilmkd** [comment]
@iRevive I follow you on Twitter and I know what you're referring to. I'm so sorry. Please take all the time in the world you need. We appreciate your work immensely. Thank you.
