### ISSUE TITLE
[3.3.0] Performance regression

### ISSUE THREAD

**Issue by iRevive** [typelevel/cats-effect#2634]
_This issue was originally created in fs2, so version numbers below refer to fs2_.

I've observed a performance degradation in some scenarios on **3.2.3** version. 

The throughput on small byte streams remained the same. 
The throughput on bigger byte streams is decreased roughly by ~20%.  
The memory allocation decreased by 10-15% on bigger byte streams.  

See the benchmarks below for more details.

#### Stream usage

The project utilizes a TCP socket from the fs2-io module. I cannot share many details due to NDA, but the generalized usage of the socket is the following one:
```scala
val streamDecoder: StreamDecoder[Structure] =
  StreamDecoder.many(StructureDecoder)

socket.reads
  .through(streamDecoder.toPipeByte)
  .evalMap(structure => queue.offer(Right(structure)))
  .compile
  .background
```

#### Consumed bytes per single invocation:
- createOne: 167 bytes
- returnRandomUUID: 135 bytes
- return100Record: 2683 bytes

## 3.2.2 

Operation average time:
```
Benchmark                           Mode  Cnt   Score        Error   Units
DriverBenchmark.createOne           avgt   25   4.725 ±      0.396   ms/op
DriverBenchmark.return100Records    avgt   25   8.613 ±      0.488   ms/op
DriverBenchmark.returnRandomUUID    avgt   25   3.542 ±      1.156   ms/op
```

Memory allocation:
```
DriverBenchmark.return100Records:·gc.alloc.rate                        201.323 ±     11.576  MB/sec
DriverBenchmark.return100Records:·gc.alloc.rate.norm               3117144.635 ±  13036.746    B/op
DriverBenchmark.return100Records:·gc.churn.G1_Eden_Space               199.083 ±     23.093  MB/sec
DriverBenchmark.return100Records:·gc.churn.G1_Eden_Space.norm      3076695.652 ± 283692.848    B/op
DriverBenchmark.return100Records:·gc.churn.G1_Old_Gen                    0.074 ±      0.113  MB/sec
DriverBenchmark.return100Records:·gc.churn.G1_Old_Gen.norm            1266.657 ±   1981.461    B/op
DriverBenchmark.return100Records:·gc.churn.G1_Survivor_Space             0.484 ±      0.444  MB/sec
DriverBenchmark.return100Records:·gc.churn.G1_Survivor_Space.norm     7614.493 ±   6998.312    B/op
DriverBenchmark.return100Records:·gc.count                              72.000               counts
DriverBenchmark.return100Records:·gc.time                              300.000                   ms
```

## 3.2.3

Operation average time:
```
Benchmark                           Mode  Cnt   Score        Error   Units
DriverBenchmark.createOne           avgt   25   4.862 ±      0.414   ms/op
DriverBenchmark.return100Records    avgt   25  11.008 ±      0.356   ms/op
DriverBenchmark.returnRandomUUID    avgt   25   3.068 ±      0.299   ms/op
```

Memory allocation:
```
DriverBenchmark.return100Records:·gc.alloc.rate                        169.961 ±      6.376  MB/sec
DriverBenchmark.return100Records:·gc.alloc.rate.norm               3383113.516 ±  12432.017    B/op
DriverBenchmark.return100Records:·gc.churn.G1_Eden_Space               175.288 ±     24.073  MB/sec
DriverBenchmark.return100Records:·gc.churn.G1_Eden_Space.norm      3484911.125 ± 432781.648    B/op
DriverBenchmark.return100Records:·gc.churn.G1_Old_Gen                    0.061 ±      0.075  MB/sec
DriverBenchmark.return100Records:·gc.churn.G1_Old_Gen.norm            1224.015 ±   1529.533    B/op
DriverBenchmark.return100Records:·gc.churn.G1_Survivor_Space             0.484 ±      0.566  MB/sec
DriverBenchmark.return100Records:·gc.churn.G1_Survivor_Space.norm     9489.291 ±  11071.370    B/op
DriverBenchmark.return100Records:·gc.count                              56.000               counts
DriverBenchmark.return100Records:·gc.time                              433.000                   ms
```

**Comment by djspiewak** [comment]
Thanks to the tabular formation, it's easier to see that I'm probably wrong on the compute bound but. Notice how tracing enabled/disabled makes very little difference on 3.2.9, but it matters a lot on 3.3. That suggests the fiber dump mechanism is primarily at fault. Absolutely fascinating.

Can you open an issue on CE for this? I think this is a meaningful performance regression.

**Comment by armanbilge** [comment]
We can transfer this one actually.

**Comment by vasilmkd** [comment]
https://github.com/typelevel/cats-effect/pull/2368#issuecomment-925306033

**Comment by rpiaggio** [comment]
We seem to be hitting this issue particularly hard in Scala.js (dev environment), with a performance degradation by a whole order of magnitude. For example, an iteration over ~100 IO calls which took between 1 and 2 seconds in `3.2.9`, now takes around 30 in `3.3.0`.

So far, I've been unable to avoid the issue by setting `process.env.CATS_EFFECT_TRACING_MODE="none"`. Even though it's set when the application starts (before invoking any Scala.js code), the performance degradation persists.

<img width="500px" src="https://user-images.githubusercontent.com/1895643/145623943-bd3431b9-b8b7-4b8e-9beb-d2a152029eda.png"/>

Any pointers for further exploring solutions would be welcome.

**Comment by armanbilge** [comment]
@rpiaggio thanks for reporting and sorry for your troubles. Yes, unfortunately tracing does have a far more severe impact on JS than JVM for reasons we are still trying to understand. This is why it is only enabled in development mode. Which browser are you using?

However, setting `CATS_EFFECT_TRACING_MODE` as you've done _should_ for the most part disable it, I'm not sure why that's not working for you. I'm assuming this related to the explore project linked above, so I'll take a look there.

See also:
- https://github.com/typelevel/cats-effect/issues/2284
- https://github.com/typelevel/cats-effect/issues/2558
- https://github.com/typelevel/cats-effect/pull/2207#issuecomment-909306546
- https://github.com/typelevel/cats-effect/pull/2207#issuecomment-903199828

**Comment by armanbilge** [comment]
@rpiaggio one idea, to check that `CATS_EFFECT_TRACING_MODE` is working—can you raise an exception from inside CE and report the stacktrace? If it's enhanced then that means tracing is still enabled.

**Comment by rpiaggio** [comment]
@armanbilge Thank you for the links.

> Which browser are you using?

Chrome Version 96.0.4664.93 (Official Build) (x86_64)

> I'll take a look there.

Thank you!

**Comment by rpiaggio** [comment]
> @rpiaggio one idea, to check that `CATS_EFFECT_TRACING_MODE` is working—can you raise an exception from inside CE and report the stacktrace? If it's enhanced then that means tracing is still enabled.

Good idea. I tried your suggestion and I'm actually not getting enhanced stacktraces.

This is what I get when setting `CATS_EFFECT_TRACING_MODE: "none"`: 
![image](https://user-images.githubusercontent.com/1895643/145630262-368a79c2-2fba-4c54-86c3-1499682fee6b.png)

vs what I get when not setting `CATS_EFFECT_TRACING_MODE`:
![image](https://user-images.githubusercontent.com/1895643/145630321-43b16dcc-a28b-47f6-9abd-30d3b676cb1b.png)

**Comment by armanbilge** [comment]
Aha, that is helpful. So now that we've confirmed tracing is off, you _are_ definitely still seeing a significant performance regression? That is concerning!

**Comment by vasilmkd** [comment]
The `FiberAwareEC` is still being constructed in this case because presumably Chrome supports weak maps? If yes, then we have a lot of wrapping and unwrapping of `Runnables` and it needs to be measured.

I would be really surprised if that's a 15x regression though, that doesn't quite seem right.

**Comment by armanbilge** [comment]
Ah, @vasilmkd is right, my bad 😅 we need one more conditional there to check if tracing is disabled. Thanks, this is an easy fix!

**Comment by djspiewak** [comment]
So I *think* that we're probably putting just a bit more strain than we should be on the GC. This doesn't show as problematic in our benchmarks since we don't stress the heap too much, but in scenarios like the one in OP it becomes more problematic. A 20% hit for a feature which is intended to be lossless in terms of performance is a bit too much, IMO. At the very least it would merit allowing some more granular configurability, since clearly the scenario here is not sensitive to the performance hit of tracing itself, but *is* sensitive to the weak tracking.

I think a good action item here would be to try to replicate something like this in our own performance tests. If we can create a benchmark which reproduces the problem, we can try to iterate on the implementation more effectively. My guess is that we may have to back away from the weak thread-local striping, but maybe there's a way we can be creative to keep that optimization intact.

**Comment by vasilmkd** [comment]
We can always replace the `WeakHashMap` with your original idea, I don't think the thread locality is the problem.

`WeakHashMap` does allocate on every use and does a bit of management on every access (to remove expired keys) and both of these things are not something we ideally want. Another alternative is to develop our own weak hash map with features that are more desirable for Cats Effect, like fewer allocations, faster access.

**Comment by djspiewak** [comment]
@vasilmkd This would need some measurement, but *if* I correctly understand the way the GC works, `WeakReference` itself is more the problem. I actually wonder if we can batch the weak references to avoid having one per fiber.

I mostly brought up the thread locality because, if we don't leverage the GC to perform the cleanup, we have to find some other way to solve the problem of an `IOCont` resuming on a different thread than the one which suspended it.

**Comment by vasilmkd** [comment]
I don't see how `WeakReferences` can be avoided and/or not be 1:1 with what you're trying to hold in a data structure. If you don't use a `WeakReference` and you still hold a reference to an object, then that reference is strong and the object is not eligible for collection.

**Comment by vasilmkd** [comment]
@iRevive If you could try the following snapshot, that would be amazing. Thank you.
```scala
"io.vasilev" %% "cats-effect" % "3.3-87-1d1f0ff"
```

**Comment by iRevive** [comment]
That's what I got today:

```
                             3.3-87-1d1f0ff -     3.3-87-1d1f0ff +             3.3.0 -             3.3.0 +
throughput/avgt                         9.096               10.316               9.083              10.790      ms/op
gc.alloc.rate                         198.949              180.254             198.430             174.146     MB/sec
gc.alloc.rate.norm                3250096.228          3364384.042         3246550.722         3390473.917       B/op
gc.churn.G1_Eden_Space                198.509              183.132             203.094             177.976     MB/sec
gc.churn.G1_Eden_Space.norm       3250850.493          3415242.285         3321291.087         3474275.752       B/op
gc.churn.G1_Old_Gen                     0.152                0.074               0.121               0.079     MB/sec
gc.churn.G1_Old_Gen.norm             2612.132             1460.794            2061.829            1577.063       B/op
gc.churn.G1_Survivor_Space              0.599                0.620               0.486               0.555     MB/sec
gc.churn.G1_Survivor_Space.norm     10117.412            11649.115            7970.496           10718.606       B/op
gc.count                               68.000               66.000              67.000              62.000     counts
gc.time                               325.000              364.000             343.000             448.000         ms
```

**Comment by vasilmkd** [comment]
What about the throughput results? The GC time is lower with the fix.

**Comment by iRevive** [comment]
The `3.3-87-1d1f0f` is roughly 5% faster than `3.3.0`.

**Comment by vasilmkd** [comment]
How does that compare to `3.2.9`? Is that still not sufficient?

**Comment by iRevive** [comment]
I did several measurements yesterday. I've increased the measurement time to decrease the margin of error for the score. 

`-` - without tracing, `+` - with tracing:

```
                                 3.2.9 -           3.2.9 +           3.3.0 -            3.3.0 +     3.3-87-1d1f0ff -     3.3-87-1d1f0ff +
op average time (ms)               6.738             7.914             7.272             9.387                  7.220                9.191

gc.alloc.rate                    415.267           359.753           383.671           309.012                384.822              312.819
gc.alloc.rate.norm           3133369.005       3186737.717       3120760.158       3240605.996            3108259.130          3218716.403
gc.churn.G1_Eden_Space           419.880           363.964           387.659           313.066                388.866              315.969
gc.churn.G1_Eden_Space.norm  3168091.608       3224107.625       3153284.906       3283367.318            3140929.511          3251105.574
gc.churn.G1_Old_Gen                0.010             0.006             0.009             0.051                  0.012                0.009
gc.churn.G1_Old_Gen.norm          74.127            57.027            76.633           542.592                 95.361               89.211
gc.count                         779.000           675.000           668.000           486.000                721.000              586.000
gc.time                          648.000           575.000           578.000          1844.000                609.000              837.000
```

The GC time is lower with the fix. And the `3.3-87-1d1f0ff ` works slightly faster when tracing is enabled (~2-3%) compared to `3.3.0`. 

From what I see, enabled tracing affects throughput of the library by ~15% on `3.2.9` and ~22% on `3.3-87-1d1f0ff`. 

If we compare `3.2.9` with `3.3-87-1d1f0ff` we have the following:
- without tracing: `3.3-87-1d1f0ff` is ~7% slower
- with tracing: `3.3-87-1d1f0ff` is ~14% slower

**Comment by djspiewak** [comment]
The newly-released 3.3.2 includes the fixes tested here. One thing I would really like to do is figure out why tracing *disabled* has more overhead in this release than in previous ones. We'll leave this issue open to track that problem.

Regarding the increase in overhead with tracing *enabled*, I think we can definitely continue to iterate on that case, but I expect that the scenario described in the OP is always going to be sub-optimal. From what I can tell, @iRevive is describing an application which `evalMap`s over a `Stream[F, Byte]`, or rather something relatively close to it. The problem with these types of workloads is they innately produce an enormous amount of heap pressure, meaning they end up entirely GC-bound, which is why the weak bag overhead starts to dominate.

Cats Effect is fundamentally optimized around the following assumption: the number of `IO` instances constructed is *O(kn)*, where *n* is the number of network/file I/O operations, and *k* is some (probably large, possibly amortized) constant factor. Running `evalMap` on a `Stream[F, Byte]` violates this assumption because `evalMap` must produce at least one (and actually many more than one) `F` instance *per `Byte`*, and thus *k* is proportional to the size of the stream and not itself a constant. On some level, Cats Effect (and indeed, all JVM frameworks, effect-system or otherwise) will always do quite poorly in these types of workloads.

Fwiw, the way to avoid this and recover the constant-factor *k* is to use `.chunks` (or similar) on the `Stream` and only allocate `IO`s *around* the chunk boundaries, rather than within them. Maintaining this pattern throughout your application cleanly separates your hot path (which will contain no `IO` allocations) and should dramatically improve performance with or without tracing.

Anyway, I'm making a few assumptions about the OP case, but I think I'm at least *close* to the mark. :-) The point I'm making is that we probably *can't* make OP's scenario fast, just because the JVM is… the JVM. What we can do though is fix the tracing-disabled performance regression (which is still open), and ensure that tracing-enabled performance overhead is kept to a minimum (which is what was done in 3.3.2).

**Comment by iRevive** [comment]
@djspiewak thank you for the details. 

According to the  [StreamDecoder L56](https://github.com/typelevel/fs2/blob/main/scodec/shared/src/main/scala/fs2/interop/scodec/StreamDecoder.scala#L56), `socket.reads.through(streamDecoder.toPipeByte)` should operate on a chunk rather than a single byte. 

On the other hand, StreamDecoder [reevaluates](https://github.com/typelevel/fs2/blob/main/scodec/shared/src/main/scala/fs2/interop/scodec/StreamDecoder.scala#L97) the decoding part if current bytes are not enough to parse the packet.  I can assume it happens quite often, especially in the scenario I did a benchmark with.

I will experiment with the given suggestion: 
> the way to avoid this and recover the constant-factor k is to use .chunks (or similar) on the Stream and only allocate IOs around the chunk boundaries, rather than within them

Perhaps a custom accumulating stage (before decoding) will do the trick.

**Comment by djspiewak** [comment]
> Perhaps a custom accumulating stage (before decoding) will do the trick.

I think that's a good idea! This should also result in less backtracking in scodec. It's tricky though because you have to try to predict the "right" chunk size. Hard to give good advice here without seeing your problem space, but accumulating into larger chunks is definitely what I would try, particularly if it can be done on the *sending* side rather than on the receiving side.

**Comment by He-Pin** [comment]
@iRevive Have you test the most recent release?

**Comment by iRevive** [comment]
@He-Pin not really, to be honest. 

I guess I can run some benchmarks this weekend to see the difference.

**Comment by iRevive** [comment]
Quite a lot of things have changed: internal implementation and optimization, testing platform (apple intel -> apple m1), JVM (11 -> 17). But the pattern is still there.

## Testing platform

VM version: JDK 17.0.3, OpenJDK 64-Bit Server VM, 17.0.3+7-LTS
Machine: Apple M1 Pro, 32 RAM
OS: MacOS 13.5.1 (Ventura) 

## Benchmarks 

### CE 3.2.9, FS2 3.2.2, tracing

```
Benchmark                                             Mode  Cnt        Score       Error   Units
DriverBenchmark.return100Records                      avgt   25        3.108 ±     0.069   ms/op
DriverBenchmark.return100Records:·gc.alloc.rate       avgt   25      852.355 ±    21.231  MB/sec
DriverBenchmark.return100Records:·gc.alloc.rate.norm  avgt   25  3141439.919 ± 16541.680    B/op
DriverBenchmark.return100Records:·gc.count            avgt   25      107.000              counts
DriverBenchmark.return100Records:·gc.time             avgt   25       66.000                  ms
```

### CE 3.2.9, FS2 3.2.2, no tracing

```
Benchmark                                             Mode  Cnt        Score       Error   Units
DriverBenchmark.return100Records                      avgt   25        3.041 ±     0.139   ms/op
DriverBenchmark.return100Records:·gc.alloc.rate       avgt   25      869.532 ±    43.311  MB/sec
DriverBenchmark.return100Records:·gc.alloc.rate.norm  avgt   25  3135138.349 ± 17124.071    B/op
DriverBenchmark.return100Records:·gc.count            avgt   25      100.000              counts
DriverBenchmark.return100Records:·gc.time             avgt   25       67.000                  ms
```


### CE 3.3.0, FS2 3.2.2, tracing

```
Benchmark                                             Mode  Cnt        Score       Error   Units
DriverBenchmark.return100Records                      avgt   25        3.895 ±     0.334   ms/op
DriverBenchmark.return100Records:·gc.alloc.rate       avgt   25      689.632 ±    61.692  MB/sec
DriverBenchmark.return100Records:·gc.alloc.rate.norm  avgt   25  3196648.931 ± 16613.670    B/op
DriverBenchmark.return100Records:·gc.count            avgt   25       54.000              counts
DriverBenchmark.return100Records:·gc.time             avgt   25      347.000                  ms
```

### CE 3.3.0, FS2 3.2.2, no tracing

```
Benchmark                                             Mode  Cnt        Score       Error   Units
DriverBenchmark.return100Records                      avgt   25        3.062 ±     0.099   ms/op
DriverBenchmark.return100Records:·gc.alloc.rate       avgt   25      853.968 ±    29.860  MB/sec
DriverBenchmark.return100Records:·gc.alloc.rate.norm  avgt   25  3104378.022 ± 12574.350    B/op
DriverBenchmark.return100Records:·gc.count            avgt   25      101.000              counts
DriverBenchmark.return100Records:·gc.time             avgt   25       67.000                  ms
```

### CE 3.5.1, FS2 3.9.1, tracing

```
Benchmark                                             Mode  Cnt        Score       Error   Units
DriverBenchmark.return100Records                      avgt   25        3.377 ±     0.077   ms/op
DriverBenchmark.return100Records:·gc.alloc.rate       avgt   25      766.447 ±    18.633  MB/sec
DriverBenchmark.return100Records:·gc.alloc.rate.norm  avgt   25  3068305.840 ± 23767.470    B/op
DriverBenchmark.return100Records:·gc.count            avgt   25       98.000              counts
DriverBenchmark.return100Records:·gc.time             avgt   25       61.000                  ms
```

### CE 3.5.1, FS2 3.9.1, no tracing

```
Benchmark                                             Mode  Cnt        Score       Error   Units
DriverBenchmark.return100Records                      avgt   25        3.198 ±     0.315   ms/op
DriverBenchmark.return100Records:·gc.alloc.rate       avgt   25      795.719 ±    70.716  MB/sec
DriverBenchmark.return100Records:·gc.alloc.rate.norm  avgt   25  2996199.095 ± 27658.703    B/op
DriverBenchmark.return100Records:·gc.count            avgt   25      104.000              counts
DriverBenchmark.return100Records:·gc.time             avgt   25       68.000                  ms
```

## Conclusions

- Tracing, in general, leads to worse performance and higher GC pressure across all versions (expected)
- Tracing in `3.5.1` is less noticeable ~5.3%; vs ~15-21% in `3.3.0`

## Bonus point: comparison with Java driver

There is also an official driver, written in Java, that utilizes Netty under the hood. The numbers are the following:

```
Benchmark                                                 Mode  Cnt      Score       Error   Units
JavaDriverBenchmark.return100Records                      avgt   25      2.666 ±     0.532   ms/op
JavaDriverBenchmark.return100Records:·gc.alloc.rate       avgt   25     20.940 ±     7.373  MB/sec
JavaDriverBenchmark.return100Records:·gc.alloc.rate.norm  avgt   25  57620.287 ± 18067.576    B/op
JavaDriverBenchmark.return100Records:·gc.count            avgt   25        ≈ 0              counts
```

Scala driver is 13-18% slower, but the allocation rate is completely different. There are several reasons for that: Scala driver utilizes immutable structures, refined types, extra levels of abstraction, and the FS2 NIO socket layer; while Netty is doing Netty things :) 

Also, a while ago, I was experimenting with the Netty socket layer instead of the FS2 NIO (mostly the code adjusted from https://github.com/typelevel/fs2-netty), and the allocation rate dropped by 2-2.5x. The allocation rate was never an issue for the project (at least for my team), so I didn't progress far with that.

**Comment by armanbilge** [comment]
@iRevive thanks for that update!



> * Tracing in `3.5.1` is less noticeable ~5.3%; vs ~15-21% in `3.3.0`

Interesting, I'm not sure what's significantly changed between those releases besides the integrated timers.

Along those lines ...

> Bonus point

If you have any extra bandwidth, it might be interesting to try out the JDK polling system (https://github.com/typelevel/cats-effect/issues/3692#issue-1757703692) and also the io_uring polling system (https://github.com/typelevel/cats-effect/issues/3692#issuecomment-1696481951)

> Scala driver is 13-18% slower

The io_uring polling system gave Ember a significant speedup, would be cool if it makes a difference here.

**Comment by djspiewak** [comment]
This feels like it has essentially quiesced, so I'm going to close it. Please feel free to poke if you feel it should be reopened.
