### ISSUE TITLE
joinWithUnit for Fibers

### ISSUE THREAD

**Issue by etspaceman** [typelevel/cats-effect#2636]
We have `joinWithNever`, in which a cancelled fiber is suspended and never finished. This mimics the behavior of CE2 from what I understand.

I would like to see a `joinWithUnit`, in which a cancelled fiber's result is ignored. Something like this:

```scala
  def joinWithUnit(implicit F: GenSpawn[F, E]): F[A] =
    joinWith(F.unit)
```

**Comment by armanbilge** [comment]
I think for this to work you'd need need an implicit `ev: A <:< Unit` (i.e., the `Fiber` itself has to be of `Unit` return type. Edit: `Unit <:< A` actually 🤔
