### ISSUE TITLE
Queue: take for more than one record

### ISSUE THREAD

**Issue by etspaceman** [typelevel/cats-effect#2637]
FS2 Queue's had methods that would allow you to take a chunk of records, which were really convenient. The behavior would be that we would run the `tryTake` method until N was hit, or None was returned. I would like to see the same in the Cats Effect queue. Something like this:

```scala
def tryTakeChunk(
        maxN: Int
      )(implicit A: Async[F]
      ): F[List[A]] = {
      A.tailRecM[(List[A], Int), List[A]](
        (List.empty, 0)
      ) { case (list, i) =>
        if (list.size === maxN) list.reverse.asRight.pure[F]
        else {
          queue.tryTake.map {
            case None => Right(list.reverse)
            case Some(x) => Left((list.prepend(x), i + 1))
          }
        }
      }
    }
```

**Comment by armanbilge** [comment]
Related?
- https://github.com/typelevel/cats-effect/pull/2164

**Comment by etspaceman** [comment]
It was related, yes, though that PR was messy and not well thought through. 😅

**Comment by armanbilge** [comment]
Seems it might be worth a take 2 then? :)

**Comment by etspaceman** [comment]
Absolutely! I opened this issue after discussing w/ @djspiewak offline in a related matter, just to track the effort.

**Comment by armanbilge** [comment]
Hmm, looking at back that PR it seemed there was some overlapping scope with fs2? I think I proposed an fs2-solution for this in https://github.com/typelevel/cats-effect/pull/2164#issuecomment-903209604.

**Comment by etspaceman** [comment]
Maybe!

**Comment by etspaceman** [comment]
After thinking about this more, I think this should live in cats-effect. A user shouldn't have to make an FS2 Stream to get more than 1 record from a queue.

**Comment by vasilmkd** [comment]
I propose that we break compatibility here and do this properly, if possible.

**Comment by armanbilge** [comment]
I don't have enough experience to know when it's ok to break bincompat, so I err on conservatism especially as CE3 gets more established in the ecosystem. So 👎 but happy to be overriden by someone who knows better :)

OTOH, can we implement these as implicit syntax?

**Comment by armanbilge** [comment]
Also linking to https://github.com/typelevel/cats-effect/issues/2639 which would need some breaking changes I think.

**Comment by vasilmkd** [comment]
Yeah, #2639 cannot be done without breakage, unfortunately.

**Comment by armanbilge** [comment]
Well, you could "cheat" by taking something out and putting it back to implement peek.

Edit: nope, nevermind, there's no control over head/tail.

**Comment by vasilmkd** [comment]
That's not a concurrently safe solution. Please don't give people ideas. 😆

**Comment by armanbilge** [comment]
I mean, "peek" is funky too when there's concurrency. I.e. there's no guarantee that you can take what you just peeked. So I am a bit dubious about that.

**Comment by vasilmkd** [comment]
`cats-effect-std` was put together haphazardly and without much thought. It has a lot of growing up to do. Also think about how `Resource` is going to evolve. I don't know. I dislike `std`, it was an afterthought.

**Comment by SystemFw** [comment]
> cats-effect-std was put together haphazardly and without much thought.

I disagree with this and I think you're being far too harsh (including to yourself).

> It has a lot of growing up to do

Potentially, yes. The discussions in this wave of feature requests are good.

> Also think about how Resource is going to evolve

_If_ Resource is going to evolve. The importance of having stable `std` is far greater than relaxing constraints here and there.

> I dislike std, it was an afterthought.

It certainly wasn't an afterthought, we debated both the general strategy of a `std` module and the specific components for quite a long time in CE2. I think the current situation with a richer std is miles better for end users than the scattered approach we used to take. It's always hard to figure out what to include in a `std` module, but not providing one is very defeatist (lots of precedent in all directions from stdlib in any language)

**Comment by vasilmkd** [comment]
Thanks @SystemFw and sorry. To everyone offended by my previous comment, I apologize. I don't think `std` is bad as an idea or that it shouldn't exist. I feel that not enough care was put in (starting from me, I have written a lot of code for it) to make the implementation more flexible in terms of evolution. I see it as a personal failure and every feature request that I read reminds me of it.

**Comment by djspiewak** [comment]
Philosophically, I'm okay with std being a bit less "pristine" than what we have in core or especially kernel. Cats Effect is a relatively long-lived and stable project, which means that the way in which it is used is going to shift over time, and so any "standard utilities" are going to ultimately age out of common use while new ones come in. We can either decide to just not have anything at all (i.e. CE2) or we can accept that there will be a few `java.util.Date`s hanging around. I think, in the end, the latter is preferable and the maintenance burden is modest enough that it shouldn't be a long-term drag (we benefit from our own compatibility here!).

Regarding the OP… I'm in favor of this so long as it is made very clear that it is a *convenience* method and there is no particular performance benefit. To that end, it may be helpful if the `maxN` bound were an `Option[Int]` rather than an `Int` to allow for `tryTakeAll`.
