### ISSUE TITLE
Reference equality usage in eqThrowable makes cats-effect-laws very difficult to use

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#271]
The dependence on reference equality in `eqThrowable` is quite problematic in a lot of cases. I have some pretty simple examples (when working on testing an `Effect[Task]` instance) using ScalaCheck's built-in `Arbitrary[Throwable]` which fail the laws because of this.  This is exacerbated by the fact that the provided `Eq[IO[A]]` (use of which is a near-requirement to use `EffectLaws`) forcibly delegates to `eqThrowable`.

So this either means that I can't use ScalaCheck to generate my `Throwable` values, or `eqThrowable` needs to stop using reference equality, or `Eq[IO[A]]` needs to be parameterized. It's not difficult to define an equality instance for `Throwable` which is reliable and more forgiving of these sorts of situations (e.g. by comparing stack trace and message string), so it sort of surprises me that `eqThrowable` doesn't do this. But if `eqThrowable` isn't going to admit this situation, then it *at least* needs to be parameterized onto `eqIO` so that downstream users can override it.

**Comment by johnynek** [comment]
I think you can make the case that all two Throwables are equal. Or maybe `x.getClass == y.getClass`. Asking the stacks to be the same, seems pretty intense for these laws.

**Comment by alexandru** [comment]
Throwables aren't values anyway, because throwable objects are mutable.

**Comment by djspiewak** [comment]
@alexandru That is very true, though in practice all of the mutations are treated as single-assignment and considered strictly finalized upon `throw`, so I don't think it's too much of a concern.

**Comment by djspiewak** [comment]
Point 2 makes sense, and that's fair. Point 1 is generally more concerning. I've only seen that with `Future`, and in general I consider it to be an artifact of poor design in `Future`'s error handling semantics. Though I suppose that it doesn't actually matter, since we have to deal with it either way. 😕

I'll close this, since the new `Eq` is a lot more forgiving and should broadly admit the sorts of things that are necessary when testing a third-party `Effect[F]` instance.
