### ISSUE TITLE
live fiber snapshot test is flaky on JVM

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#2722]
ubuntu-latest, 2.13.7, graalvm-ce-java11@21.3

https://github.com/typelevel/cats-effect/runs/4681567043?check_suite_focus=true#step:9:3480

```
[error]   x live fiber snapshot
[error]     doesn't contain 'cats.effect.IOFiber' (IOAppSpec.scala:271)
```

**Comment by armanbilge** [comment]
Nope, not just graal.

ubuntu-latest, 2.13.7, adoptium@11

https://github.com/typelevel/cats-effect/runs/4724298794?check_suite_focus=true#step:9:3480

```
[error]   x live fiber snapshot
[error]     doesn't contain 'cats.effect.IOFiber' (IOAppSpec.scala:278)
```

**Comment by djspiewak** [comment]
Well at least it's not just Graal…
