### ISSUE TITLE
Memoized effect hangs for `Concurrent` instances of monad transformers

### ISSUE THREAD

**Issue by ornamental** [typelevel/cats-effect#2728]
The default implementation of `memoize` inherited by `OptionTGenConcurrent`, `EitherTGenConcurrent`, `IorTGenConcurrent`, and `WriterTGenConcurrent` does not take the contexts added by the corresponding transformers into account.
For `OptionT`, `EitherT`, `IorT` this results in freezes.
For `IorT` and `WriterT` this results in data loss.

Example:
```
val computation = OptionT[IO, Unit](IO.pure(None))
val memoization = Concurrent[OptionT[IO, *]].memoize(computation)
val test = for {
  memoized <- memoization
  unwrapped = memoized.value
  _ <- OptionT.liftF(unwrapped)
  second <- OptionT.liftF(unwrapped)
} yield second

test.value.flatMap(IO.println) // expected to print None, hangs instead
```

`memoize` has to be overridden accordingly for these `Concurrent` instances.

**Comment by durban** [comment]
I don't think it has to be overridden, it just needs to be more careful; see #2729.
