### ISSUE TITLE
App + cats-effect hangs on 3.1.0 but works fine in 2.13.7

### ISSUE THREAD

**Issue by jmgimeno** [typelevel/cats-effect#2748]
This code
```scala
import cats.effect._
import cats.implicits._
import cats.effect.unsafe.implicits.global

object IOComposition extends App {
  val hello = IO(println(s"[${Thread.currentThread.getName}] Hello"))
  val world = IO(println(s"[${Thread.currentThread.getName}] World"))
  val hw1: IO[Unit] = for {
    _ <- hello
    _ <- world
  } yield ()
  val hw2: IO[Unit] =
    (hello, world).mapN((_, _) => ())
  hw1.unsafeRunSync()
  hw2.unsafeRunSync()
}
```
hangs with Scala 3.1.0 after printing only "Hello"
```
Compiling project (Scala 3.1.0, JVM)
Compiled project (Scala 3.1.0, JVM)
[io-compute-2] Hello
```
but works perfecty with Scala 2.13.7
```
Compiling project (Scala 2.13.7, JVM)
Compiled project (Scala 2.13.7, JVM)
[io-compute-2] Hello
[io-compute-4] World
```

**Comment by djspiewak** [comment]
Try using `def`s. I'd be willing to bet this is caused by the issues with `MethodHandle` linking to `null` during class load.

**Comment by SethTisue** [comment]
I'd also be interested in knowing if the problem goes away if you avoid using `App`. `App` is not recommended in Scala 3, as per https://docs.scala-lang.org/scala3/reference/changed-features/main-functions.html

**Comment by djspiewak** [comment]
I suspect that, if you avoid using `App`, the source of the problem will actually become a hair more obvious. Or you can just push the `val`s into the body of the `main` method (which is effectively what Scala 2 is doing with the same code but Scala 3 is not), and that should *also* resolve the deadlock.

**Comment by jmgimeno** [comment]
> I'd also be interested in knowing if the problem goes away if you avoid using App

Yes, if I create a regular `main` method instead of extending `App`, it works perfectly 

Changing the definitions of `hello` and `world` from `val` instead to `def` also solves the problem in Scala 3.1.0 even when using `App`.

**Comment by djspiewak** [comment]
Sweet! So this is definitely the `MethodHandle` concurrent initialization issue then. It's actually part of the JVM itself and not really anything that either Scala or Cats Effect can address. In fact, you can reproduce this issue using bare Java.
