### ISSUE TITLE
Add source links to scaladoc

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#28]
Can probably just link to master for now, but eventually we'll want to link to the hash if at all possible. I'm not sure if it's possible to do that in scaladoc without source file templating though, which wouldn't be worth it IMO.

**Comment by rossabaker** [comment]
Why not?  As long as sbt knows the branch or hash you're trying to link to, it just gets interpolated into something like [this](https://github.com/typelevel/cats/blob/93a4bd0ddffe6f79282f272ccd1623038417cf37/build.sbt#L155), no?

**Comment by alexandru** [comment]
In my Unidoc PR, what I'm doing is to link to the `version`.

So for example this page https://monix.io/api/2.2/monix/eval/Task.html links to this source: https://github.com/monix/monix/blob/v2.2.4/monix-eval/shared/src/main/scala/monix/eval/Task.scala

**Comment by alexandru** [comment]
Here's the `build.sbt` line that does that: https://github.com/typelevel/cats-effect/pull/29/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR103

**Comment by djspiewak** [comment]
@rossabaker Oh, you're right!  I forgot that it was a switch and not a source directive.

@alexandru I would rather link to the git hash, since we're using those as versions and github offers stable hash urls.  If the hash corresponds to a version, we could link to the version tag for a prettier url.

**Comment by alexandru** [comment]
Well, I'm not sure how we can hack that, but it is doable.

**Comment by djspiewak** [comment]
I'll take care of it.  I have an implementation in mind.
