### ISSUE TITLE
[1.0.0-RC2] could not find implicit value for evidence parameter of type cats.temp.par.Par[cats.effect.IO]

### ISSUE THREAD

**Issue by guizmaii** [typelevel/cats-effect#280]
Hi everyone,

I have a little project I use to learn how Cats-Effect and Monix work, here: https://github.com/guizmaii/async_and_scala

Since I tried to upgrade to Cats-Effect v1.0.0-RC2, I have the following error:
```
could not find implicit value for evidence parameter of type cats.temp.par.Par[cats.effect.IO]
```

(The `Par` typeclass comes from the https://github.com/ChristopherDavenport/cats-par project)

Here's the PR where I've done the upgrade: https://github.com/guizmaii/async_and_scala/pull/2

Here's what I tested to fix the problem:

  - Update the `cats-par` project to Cats-Effect v1.0.0-RC2, publish it locally, update my project with the local version: my project still doesn't compile
  - Rollback my project to Cats-Effect v1.0.0-RC: my project compiles

The code that doesn't compile is here: https://github.com/guizmaii/scala-distances/blob/benchmarks/tests/src/test/scala/com/guizmaii/distances/DistanceApiSpec.scala#L50

Is there a new import to add since RC2 ? What am I missing ?

Thanks for your help.
Jules

**Comment by alexandru** [comment]
@guizmaii Monix hasn't been released for Cats 1.0.0-RC2 yet and 1.0.0-RC2 is binary incompatible with 1.0.0-RC1. Being release candidates, both are actually unstable.

Sorry for the wait.

**Comment by oleg-py** [comment]
@guizmaii since RC2, you need a `Timer[IO]` in scope to get Parallel instance.

**Comment by mpilquist** [comment]
Closing this since @oleg-py described the fix.
