### ISSUE TITLE
mock start time in cats-effect-testkit?

### ISSUE THREAD

**Issue by ShahOdin** [typelevel/cats-effect#2851]
i understand how the tick mechanism evolves the time and it's pretty neat. It doesn't look like I can mock the time at the start of the program tho. is that not possible/desirable?

**Comment by Daenyth** [comment]
Begin the test with a `Clock[IO].sleep(startTime)`, you just need a `FiniteDuration` for the epoch timestamp of `startTime`

**Comment by ShahOdin** [comment]
thanks @Daenyth 

Thats not quite what I meant. Let's say I have a bunch of records and I have an interface that looks at the time, and it filters the list and gives you the records with a timestamp within say 1 day of the current time. I want to test that time-based functionality. 

currently I have a hardcoded record and hardcoded clock with matching times. I was hoping to be able to refactor my tests to move away from a custom clock, without doing a massive change to how I test the code, ie a having a dynamically created record as opposed a static one etc. 

it doesn't look like I can do that now. I could have possibly been able to do this however, if I could have initialized the start time at the beginning of the program. hence the question.

**Comment by Daenyth** [comment]
The `sleep` should work fine as long as you are executing the code with `TestControl` - see the [test runtime](https://typelevel.org/cats-effect/docs/core/test-runtime) docs on that.

Using the `IORuntime` it provides, you can write your test like:

```scala
import scala.concurrent.duration._
import java.time._
val startTime = LocalDateTime.of(2022, 3, 1, 0, 0).toEpochSecond(ZoneOffset.UTC).seconds
val myTest = for {
  _ <- Clock[IO].sleep(startTime)
  myLogic <- MyLogic.create[IO]
  result <- myLogic.run
} yield result

TestControl.execute(myTest).flatMap { control =>
  for {
    _ <- control.nextInterval.flatMap(control.advanceAndTick)
    ...
```

**Comment by ShahOdin** [comment]
ah so the TestControl starts with the time being epoch! makes sense! Excellent. thanks can confirm it works. 
minor thing. 

```scala
  for {
    _ <- control.nextInterval.flatMap(control.advanceAndTick)
```

should be:


```scala
  for {
    _ <- control.tick 
    _ <- control.nextInterval.flatMap(control.advanceAndTick)
```
