### ISSUE TITLE
Generalize `timeout` and friends to take a `Duration`

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2855]
Right now, every flavor of this method takes a `FiniteDuration`, which is *correct* but less convenient. We should expand them to `Duration` and silently degrade to identity when it's `Duration.Inf`. This can be done trivially on `IO` because of contravariant expansion, but it might requires some bincompat shenanigans on `Temporal`.

**Comment by Daenyth** [comment]
I'm not sure if this can be done in a bincompatible way, or at least it might require some trickery.
Any downstream implementors of `Temporal` etc would be unable to instantiate if the signature changed in the interface to become wider, because they'd still have the narrower signature

**Comment by armanbilge** [comment]
I'm pretty confident it can be done, but I have not really thought about it. Happy to help anyone along :)
