### ISSUE TITLE
Make Sync extend Defer

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats-effect#286]
now that Defer has landed in cats 1.2.0, I think Sync should extend `Defer[A]` with `def defer[A](fa: => F[A]): F[A] = suspend(fa)`.

Defer is not about side effects, but suspend can also handle those, so it seems only more general, since if side effects are allowed to happen, it can't have evaluated before returning.

**Comment by alexandru** [comment]
👍 can you do a PR?

**Comment by alexandru** [comment]
Would be cool if this made it in 1.0.0-RC3.

Who's up for a PR?

**Comment by Avasil** [comment]
I guess I can take a look at it today @alexandru

**Comment by alexandru** [comment]
👍 @Avasil go for it
