### ISSUE TITLE
UUIDGen does not use Random[F]

### ISSUE THREAD

**Issue by Daenyth** [typelevel/cats-effect#2865]
> I have seen `UUID.randomUUID` kill more than one service in the years BCE (Before Cats Effect).  The synchronization isn't obvious until you start profiling why you're getting single-threaded performance.

_Originally posted by @rossabaker in https://github.com/typelevel/cats-effect/issues/2852#issuecomment-1059801110_

Given this, we probably want to offer a `Random[F] => UUIDGen[F]` implicit that's higher-priority than the `Sync`-based one, and consider deprecating the `Sync` instance, or at least making it *explicitly* summoned rather than implicit so the user has to opt-in to using the less-safe implementation

**Comment by armanbilge** [comment]
Actually, I interpreted that point differently. Rather, that UUID generation should be treated as potentially blocking.

I'm not sure we want to offer a `Random[F] => UUIDGen[F]` instance, either implicitly or possibly at all. The Javadoc for `randomUUID` say:
> Static factory to retrieve a type 4 (pseudo randomly generated) UUID. The UUID is generated using a cryptographically strong pseudo random number generator.

Given that `Random[F]` has no cryptographic guarantees, it wouldn't really be the same thing.

**Comment by ChristopherDavenport** [comment]
1. You want the sync one. Use cryptographic random. Second random has a time component in randomness on the jvms creation which we would need to account for.
2. Newer versions of the JVM are better behaved. This was a java 7 problem.
3. There is a time to avoid JVM implementations, I don't think this is the place to do so.
4. Upgrade your jvms

**Comment by Daenyth** [comment]
So in that case, this is a question of, do we use `F.delay` or `F.blocking`? (or `interruptible`?)

**Comment by ChristopherDavenport** [comment]
We do not want to use blocking on new versions which are not blocking.

**Comment by Daenyth** [comment]
Do we want to do any runtime tricks to pick an implementation based on jre?

**Comment by armanbilge** [comment]
> Newer versions of the JVM are better behaved. This was a java 7 problem.

Do we even support any of the bad JVMs?

**Comment by rossabaker** [comment]
`SecureRandom.nextBytes` may still block on JDK17, and it's still even synchronized for some `SecureRandomSpi`.  `UUID.randomUUID`, depending on platform and configuration, will still eat your face.

**Comment by armanbilge** [comment]
Yeah, I think we should just wrap this in `F.blocking` and be grateful that the WSTP can running blocking ops in-place now. `F.interruptible` seems like overkill.

**Comment by rossabaker** [comment]
While `UUID.randomUUID` is blocking, we can do better:

* Try to create a `SecureRandom.getInstance("NativePRNGNonBlocking")`.  `"NativePRNG"` appears to be equivalent on `nextBytes` on Unix, but that's platform specific. 
* Until Java 9, there's still a mutex, but [a pool](https://github.com/f4b6a3/uuid-creator/blob/dbc54155c6cb2893eff99876b75ead20382fe331/src/main/java/com/github/f4b6a3/uuid/factory/function/impl/DefaultRandomFunction.java) fixes that.

Unfortunately, falling through to `UUID.randomUUID` still requires `F.blocking`, which we can't do from `Sync`.

**Comment by djspiewak** [comment]
> still requires F.blocking, which we can't do from Sync

`blocking` is a method on `Sync`. :-)

**Comment by rossabaker** [comment]
I couldn't remember which and the docs say:

> CE3 has a builtin blocking which will shift execution to an internal blocking threadpool and shift it back afterwards using Async

I should have looked at the API!

**Comment by ChristopherDavenport** [comment]
Did anyone confirm this is a still a problem on newer jvms. Its my understanding this is fixed on newer jvms.

**Comment by rossabaker** [comment]
In practice, usually.  On Unix, starting with Java 9, if `/dev/urandom` is readable, and nobody altered the default providers from `SunEntries`, yes.

In edge cases, certainly not:

* There is still a [mutex around thread-unsafe instances](https://github.com/openjdk/jdk/blob/002e3667443d94e2303c875daf72cf1ccbbb0099/src/java.base/share/classes/java/security/SecureRandom.java#L760).  Most are threadsafe.
* Even threadsafe ones [can block](https://github.com/openjdk/jdk/blob/002e3667443d94e2303c875daf72cf1ccbbb0099/src/java.base/share/classes/java/security/SecureRandom.java#L760).    Some are [installed by default](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/security/provider/SunEntries.java#L105-L108). 
* Windows has a [NativePRNG that falls through](https://github.com/openjdk/jdk/blob/002e3667443d94e2303c875daf72cf1ccbbb0099/src/java.base/windows/classes/sun/security/provider/NativePRNG.java), perhaps to a synchronized [Windows-PRNG](https://github.com/openjdk/jdk/blob/002e3667443d94e2303c875daf72cf1ccbbb0099/src/jdk.crypto.mscapi/windows/classes/sun/security/mscapi/PRNG.java#L94).

Blocking everyone is suboptimal for most users, but not blocking will be catastrophic for some.  I laid out a compromise above ("we can do better"), from which I renounce only my ignorant comment about `Async`.

**Comment by armanbilge** [comment]
Cool, the immediate fire is out as of https://github.com/typelevel/cats-effect/pull/2880. We can keep this issue open to implement Ross's ideas in https://github.com/typelevel/cats-effect/issues/2865#issuecomment-1062567227.

**Comment by armanbilge** [comment]
Eh, scratch that. I say this issue has done its course. Created https://github.com/typelevel/cats-effect/issues/2882 to track the performance improvements.
