### ISSUE TITLE
MBean `BlockedWorkerThreadCount` can be negative

### ISSUE THREAD

**Issue by iRevive** [typelevel/cats-effect#2871]
I found that `BlockedWorkerThreadCount` can be negative:
<img width="674" alt="Screenshot 2022-03-11 at 13 33 20" src="https://user-images.githubusercontent.com/6395483/157860091-1d36cc83-a175-4dc7-bd16-d2c02470e5c0.png">

The counter is defined in `WorkStealingThreadPool`:
https://github.com/typelevel/cats-effect/blob/3f4afca16d64c35c969dc26ca77f11df68ba26e8/core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala#L103

This variable is updated in **one** place and it's only decremented:
https://github.com/typelevel/cats-effect/blob/3f4afca16d64c35c969dc26ca77f11df68ba26e8/core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala#L339

**Comment by vasilmkd** [comment]
That's a bug I introduced when adding blocking support directly in the work stealing pool. Probably it can be found in this PR https://github.com/typelevel/cats-effect/pull/2687/files#diff-39be61d66e2d383880df331b0680d708076fbb70eb5e265a3950806b55782e4a. Sorry I don't have a more precise location for a fix. I will take a look.
