### ISSUE TITLE
Bring in `Saga`?

### ISSUE THREAD

**Issue by Fristi** [typelevel/cats-effect#288]
I've just coded this together over the past weeks and it's up on a separate repo here: 

https://github.com/vectos/goedverhaal

Any feedback is welcome, and would it be nice to have `Saga` to in cats-effect or is it better to have it as a separate library?  

Something similar as seen here: https://docs.microsoft.com/en-us/previous-versions/msp-n-p/dn589804%28v%3dpandp.10%29

**Comment by oleg-py** [comment]
What advantages does it have over bracket/Resource? 🤔

**Comment by Fristi** [comment]
It's different. `Saga.recoverable` stores a compensating action as `F[Unit] : Sync`. This action is _only_ executed when the `Saga` crashes at a later (default behaviour, you can also change that by using `decide`, useful when you want to use a `EitherT` with `Saga`). Whereas `Bracket` and `Resource` will always execute a action to allocate and deallocate a resource.

**Comment by djspiewak** [comment]
Is this useful outside the context of `MonadPlus[F]`? (by which I mean, `EitherT`, `OptionT`, and such)

**Comment by Fristi** [comment]
I'm not sure if I get the question, I lack to see the relation with `MonadPlus[F]`. 

Without the use of `EitherT` and `OptionT` it's still pretty useful. It will accumulate all the compensating actions while running ordinary actions, if something breaks it will use all accumulated compensating actions to reverse the effects. I think when you mix database and API interactions and you cannot use transactions this can be pretty useful :-)

**Comment by djspiewak** [comment]
@Fristi What I'm getting at is, what is a failure when your `F` is *not* a `MonadPlus`? You mean like an exception in the `Sync` itself?

**Comment by goedelsoup** [comment]
I love the concept of this but its abuse seems limitless with this implementation. I think a proper rollback would need to be properly integrated with the consistency semantics of the underlying system and, as such, this seems outside of the scope of cats-effect. That said, I think this is an awesome idea for a project of its own where transaction semantics across various blends of CAP systems can be resolved through a systematic and transparent method.

**Comment by Fristi** [comment]
I agree you could abuse it for anything :-)

>  I think a proper rollback would need to be properly integrated with the consistency semantics of the underlying system and, as such, this seems outside of the scope of cats-effect. That said, I think this is an awesome idea for a project of its own where transaction semantics across various blends of CAP systems can be resolved through a systematic and transparent method.

Could you elaborate on that a bit more. Like a sketch, papers or a direction. Would you encode that in the type system? Or would enforce only using a certain rollback 'effect' for certain actions?

**Comment by alexandru** [comment]
This is a nice project @Fristi,

It's basically implementing the [Command pattern](https://en.wikipedia.org/wiki/Command_pattern) for describing actions that can be undone should the "transaction" fail.

It is this project's policy however:

1. to keep the API surface small, because Cats-Effect is supposed to be a standard library of sorts and a large API surface has a negative impact on stability
2. to encourage micro-libraries

In the project's `README` which also gets published as the front page of the website we now have a list of related projects. So why not add this micro library there?

https://github.com/typelevel/cats-effect/blob/master/README.md#related-projects
