### ISSUE TITLE
Add `Spawn` syntax for `race` and `both`

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2916]
Should be able to do something like `fa.race(fb)` and similarly with `both`, just like we can with `IO`.

**Comment by leusgalvan** [comment]
Hi guys. Am I missing something or we can already do this? https://scastie.scala-lang.org/uq23EFWFQLCW5aL924lRDw

**Comment by djspiewak** [comment]
Uh. Weird. It seems that we can. I tried it in another context and it didn't seem to be working. Thank you!
