### ISSUE TITLE
trait AllSyntax has non-class parent: val <none>

### ISSUE THREAD

**Issue by peter-jerry-ye** [typelevel/cats-effect#2923]
Hi,

I was trying the cats effect today and I wrote a simple piece of program:
```scala
import cats.Monad
import cats.effect.IO
import cats.effect.implicits._

val t = summon[Monad[IO]]
```

and the compiler crashed with:
```
ERROR Unexpected error when compiling root: 'assertion failed: trait AllSyntax has non-class parent: val <none>'
```

Could anyone help me out, please? Thank you.

P.S.
The dependencies were:
```scala
"org.typelevel" %% "cats-core" % "2.7.0"
"org.typelevel" %% "cats-effect" % "3.3.9"
```
with Scala 3.1.1, sbt 1.6.2

**Comment by djspiewak** [comment]
Well that seems fun. I'm guessing this is a bug with unpickling the tasty generated by the 3.0.x compiler? Pinging @smarter

**Comment by smarter** [comment]
I can't reproduce this (also I'm in the middle of writing my thesis and can't really respond to every bug report on my own, sorry)

**Comment by peter-jerry-ye** [comment]
Hi,

I retried to reproduce it and it seems might have something to do with the JDK.

With sbt 1.6.2 (GraalVM Community Java 17.0.1), the problem doesn't exist.
With sbt 1.6.2 (BellSoft Java 18), the problem exist.
With sbt 1.6.2 (Oracle Corporation Java 17.0.2), the problem exist.
With sbt 1.6.2 (Oracle Corporation Java 18), the problem exist.

**Comment by smarter** [comment]
I suggest opening an issue at https://github.com/lampepfl/dotty/issues, but please provide a github repo and step-by-step instructions for reproduction.

**Comment by peter-jerry-ye** [comment]
Ok. In that case I shall close this issue unless the relation with cats-effect is found.
