### ISSUE TITLE
`IO#unsafeRunAsync` and `unsafeRunAndForget` eat fatal errors

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#2961]
What happens here is `unsafeRunFiber` sets up the fatal error callback relocation thing, but then `unsafeRunAsync` has to box the error into a `Left`. This *may* work, but even if it works, `unsafeRunAndForget` is just going to drop it on the floor and the `IORuntime` silently dies. That seems like a bad experience.

I think what should probably happen here is we should register the callback as usual, but then in these kinds of cases where can't reliably continue the error relocation, we should just give up and dump the exception to stderr. Note that `unsafeToFuture` doesn't have this problem because the `Promise` is already allocated, so the fatal errors *can* be safely relocated into the resultant `Future` (and processed upon) without running into the cases where the JVM no longer functions.

**Comment by sbly** [comment]
I'm interested in picking this up! I'll take a look and see if I'm able to figure it out on my own

**Comment by djspiewak** [comment]
Give it a shot!
