### ISSUE TITLE
Release v2.5.5 and EOL 2.x?

### ISSUE THREAD

**Issue by rossabaker** [typelevel/cats-effect#2988]
I [drafted release notes](https://github.com/typelevel/cats-effect/releases/edit/untagged-430fad767ab1ced3d968).  There are a couple bugfixes there that someone cared enough to PR against 2.x.  I propose we get those fixes out there, turn off Steward on that branch, and leave it for security fixes and other tales of woe.

**Comment by rossabaker** [comment]
I'm willing to turn the crank, but I've stepped back from maintenance on this project and don't know what it's going to do to the documentation.  I'd like to get it in for http4s-0.22's sendoff.

**Comment by armanbilge** [comment]
Updating the site is not an automatic part of the release process, so should be fine. In any case it hasn't been updated even for 2.5.4 anyway.
https://typelevel.org/cats-effect/docs/2.x/getting-started

**Comment by rossabaker** [comment]
Then fuck it.  I'm turning the crank.

**Comment by armanbilge** [comment]
Btw, there is no CI release here, in case that was part of turning the crank 😅

**Comment by rossabaker** [comment]
The plugin is obstinately overwriting my change to the credentials host.  I'll try again later today, but I'm on it.

**Comment by armanbilge** [comment]
Ah, shoot. Plopping in this autoplugin will help:
https://github.com/typelevel/fs2/blob/1ac0af74301cdb305115ebc6b96a75a1177bf228/project/Publish.scala

And probably good to set sbt-sonatype to 3.9.11 (3.9.12 has been broken for months ...)
https://github.com/typelevel/fs2/blob/1ac0af74301cdb305115ebc6b96a75a1177bf228/project/plugins.sbt#L10

**Comment by rossabaker** [comment]
I already tagged it, but I was able to publish changing the credential host and then running a `+clean; +publish; sonatypeBundleRelease`.
