### ISSUE TITLE
Cats Effect + scala-cli example

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#2989]
It's annoying that we need this, but this trips everyone up, most recently @TimWSpence. We should add something to the docs demonstrating how to use CE with scala-cli by explicitly creating an `IOApp` in a `.scala` file, since stuff like `unsafeRunSync()` at the top-level of a `.sc` file will just hang.

**Comment by Daenyth** [comment]
Somebody wrote this, idk seems pretty good ;)

https://github.com/armanbilge/http4s-cli

**Comment by TonioGela** [comment]
There's the [FAQ](https://typelevel.org/cats-effect/docs/faq#scala-cli) section of the documentation that contains an example. Is it worth extracting in its own subsection? And maybe adding a section that shows the usage of decline-effect + CE to write a command-line tool. What do you think?
