### ISSUE TITLE
runSyncStep usefulness is limited

### ISSUE THREAD

**Issue by mpilquist** [typelevel/cats-effect#299]
`IO.bracket` and `IO.cancelBoundary` both introduce trampolines encoded via an `Async` node, and hence result in `runSyncStep` returning `Left`, even for synchronous computations.

```scala
scala> val t = IO(println("start")).bracket(_ => IO(println("use")))(_ => IO(println("end")))
t: cats.effect.IO[Unit] = IO$1233931676

scala> val res = Effect[IO].runSyncStep(t).unsafeRunSync
res: scala.util.Either[cats.effect.IO[Unit],Unit] = Left(IO$584426434)
```

Given this limitation, `runSyncStep` is drastically less useful IMO. So much so that I'm not sure it makes sense keeping.

**Comment by jdegoes** [comment]
It should be deleted because it’s meaningless (“dynamically typed synchronicity”). A proper SyncIO is a much saner way to accomplish the same thing IMO. 👍

**Comment by alexandru** [comment]
OK
