### ISSUE TITLE
Plan for 1.0

### ISSUE THREAD

**Issue by cb372** [typelevel/cats-effect#306]
Just wondering if there is some GitHub issue/other doc somewhere to track how close we are to a 1.0 release.

I have a couple of libraries that are in limbo waiting for 1.0, and I imagine a lot of other people are in the same situation. I'd appreciate some kind of timeline so I can decide whether to release things based on RC's or just wait it out.

If there is a clear list of things that still need to be done before 1.0, I think it would be useful to document them. Even if the answer is "we're not sure yet", just confirming that is also fine.

**Comment by LukaJCB** [comment]
We've got a [milestone for RC3](https://github.com/typelevel/cats-effect/milestone/6), which (if everything goes well)  is going to be the last RC and we're probably going to release 1.0 14 days after (correct me if I'm wrong).

**Comment by cb372** [comment]
Cool, thanks for the clarification.

**Comment by gvolpe** [comment]
Adding to @LukaJCB 's comment, [here](https://github.com/typelevel/cats-effect/milestones)'s the other milestone due for September 3 (if everything goes well) :)

**Comment by alexandru** [comment]
`1.0.0-RC3` should be the last release candidate before `1.0.0` and will be released this Monday.

Today I also published `1.0.0-RC2-3433449`, as a snapshot of the upcoming RC3, if you're interested in taking it for a test drive.

Tentatively this should be the code for `1.0.0`, hopefully we won't discover any more problems, but until `1.0.0` is actually released the release candidates are not considered stable.
