### ISSUE TITLE
Upgrade to cats-1.3.0 when it's out

### ISSUE THREAD

**Issue by rossabaker** [typelevel/cats-effect#312]
We're expecting cats-1.3.0 to fall between RC3 and 1.0.0.  Bumping that version before we release will eliminate version conflict warnings downstream.

I expect it's as simple as changing the version in the build.

**Comment by gvolpe** [comment]
As reported on the `http4s` Gitter channel, the version `1.3.0` of `cats-core` breaks compatibility. I think that's also a problem for `cats-effect`.

**Comment by alexandru** [comment]
😞 yeah
