### ISSUE TITLE
WorkStealingThreadPool#shutdown interrupts a calling thread

### ISSUE THREAD

**Issue by blondacz** [typelevel/cats-effect#3125]
`WorkStealingThreadPool#shutdown` interrupts a calling thread by calling `Thread.currentThread().interrupt()` as a last call in the method. 

This might not be an issue if the main class is an `IOApp` but when called outside of it, It sets an interrupted flag of the calling thread which might not be desirable as the pool does not own it. 
The interrupt for instance wakes up any latches later on.

**Comment by armanbilge** [comment]
The change was made in https://github.com/typelevel/cats-effect/commit/a7f3c97b64edffab1fa8ee527d303606a6a6028d as part of https://github.com/typelevel/cats-effect/pull/1764. Perhaps @vasilmkd can shed some light?
