### ISSUE TITLE
Custom `IOApp#runtime` is not installed as `IORuntime.global`

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#3140]
The scaladoc specifically says that `IOApp#runtime` is guaranteed to be equal to `IORuntime.global`.

https://github.com/typelevel/cats-effect/blob/3da61a59438da30f9bb01192fec9e690aacc3ce4/core/jvm/src/main/scala/cats/effect/IOApp.scala#L157-L159

However, if `runtime` is overridden by the user, then it will _not_ be installed as the global `IORuntime`.

https://github.com/typelevel/cats-effect/blob/3da61a59438da30f9bb01192fec9e690aacc3ce4/core/jvm/src/main/scala/cats/effect/IOApp.scala#L307-L310

It's not clear to me if this is a documentation bug, or a code bug.

Context:
- https://github.com/armanbilge/epollcat/pull/44

**Comment by djspiewak** [comment]
Oh, this seems like a code bug to me. Should be fixed.
