### ISSUE TITLE
Scala Native. Document platform limitations

### ISSUE THREAD

**Issue by iRevive** [typelevel/cats-effect#3146]
I'm experimenting with Scala Native and cats-effect. @armanbilge thank you for your work to make it possible!

~TLDR: `unsafeRunSync()` is missing~
The Scala Native platform has limitations, for example, the runtime is single-threaded. It would be nice to document that.

**scala-cli**: 0.1.12
**Scala**: 3.2.0, 3.1.3
**CE**: 3.1.3
**Scala Native**: 0.4.7

The snippet:
```scala
//> using scala "3.2.0"
//> using lib "org.typelevel::cats-effect::3.3.14"

import cats.effect.*
import cats.effect.unsafe.implicits.global

@main
def hello() = {
  IO.println("hello world").unsafeRunSync()
}
```

`compile` and `run` commands are working fine:
```bash
$ scala-cli run main.scala
hello world
```

But `scala-cli --native --native-version 0.4.7 main.scala` does not work:
```bash
$ scala-cli --native --native-version 0.4.7 main.scala
Compiling project (Scala 3.2.0, Scala Native)
[error] ./main.scala:9:3: value unsafeRunSync is not a member of cats.effect.IO[Unit] - did you mean cats.effect.IO[Unit].unsafeRunAsync?
[error]   IO.println("hello world").unsafeRunSync()
[error]   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error compiling project (Scala 3.2.0, Scala Native)
Compilation failed
```

`IOApp.Simple` works fine:
```scala
//> using scala "3.2.0"
//> using lib "org.typelevel::cats-effect::3.3.14"

import cats.effect._
import cats.effect.unsafe.implicits.global

object Main extends IOApp.Simple {
  def run: IO[Unit] = IO.println("hello world")
}
```

```bash
$  scala-cli --native --native-version 0.4.7 main.scala
[info] Linking (1163 ms)
[info] Discovered 1522 classes and 9336 methods
[info] Optimizing (debug mode) (1441 ms)
[info] Generating intermediate code (1300 ms)
[info] Produced 8 files
[info] Compiling to native code (1991 ms)
[info] Linking native code (immix gc, none lto) (131 ms)
[info] Total (6074 ms)
hello world
```

I assume, there is something wrong with the linkage of `unsafeRunSync()` method?

**Comment by armanbilge** [comment]
I'm afraid `unsafeRunSync()` is simply not possible :) like Scala.js, the Scala Native runtime is currently single-threaded (due to limitations of Scala Native itself).

`unsafeRunSync()` is implemented by blocking the current thread while the `IO` is run on other threads in the compute pool. With only one thread this simply is not an option.

**Comment by iRevive** [comment]
Makes sense to me. Is it worth mentioning this somewhere in the documentation? I can add a paragraph

**Comment by armanbilge** [comment]
Good point. This is applicable to JavaScript as well. Do you think it may make a good FAQ?

https://typelevel.org/cats-effect/docs/faq

I also thought of this page, which should be updated for Native.

https://typelevel.org/cats-effect/docs/schedulers

If you open a PR, please target the `series/3.3.x` branch. Thanks! :)

**Comment by armanbilge** [comment]
The live website should sync in the next ~24 hours.
