### ISSUE TITLE
Specialize primitive `Ref`s during construction

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3181]
If we check `getClass` on the initial value passed to the constructor, we should be able to sort out whether it's actually a primitive ref, and then use `AtomicInteger`/`AtomicLong`/`AtomicBoolean`/etc instead. Once we do *that*, we can further specialize operations like `update` since `Function1` is specialized on primitives, meaning that we can get fully unboxed `Ref` operations in the normal case.

Whoever does this should add some benchmarks.

**Comment by durban** [comment]
I might misunderstood this, but then if I do this:

```scala
Ref.of[F, Any](42).flatMap { ref => ref.getAndSet("boom") }
```

it will try to store a `String` in an `AtomicInteger`, doesn't it?

**Comment by djspiewak** [comment]
This is a good point. Subtyping ruins lives. I wonder if there's a sneaky way we can avoid this?

**Comment by armanbilge** [comment]
Why don't we just do overloads, the good old-fashioned way?

We can implement it directly on `Concurrent` with a default implementation that delegates to the reference based implementation. But on implementations we control we can actually return an `AtomicInteger`-backed ref.

**Comment by mpilquist** [comment]
Or an alternative that takes a class tag constraint.

**Comment by djspiewak** [comment]
> Why don't we just do overloads, the good old-fashioned way?

I really like this tbh. The `ClassTag` also works but actually doesn't work *as well* since the overload allows us to avoid the boxing even in the constructor.
