### ISSUE TITLE
Kamon traces aren't connected for 3.4.0-RC1

### ISSUE THREAD

**Issue by m50d** [typelevel/cats-effect#3191]
This is probably not really an "issue" on the cats side since Kamon is using AOP joinpoints in the cats-effect internals, but reporting here for completeness: we recently put together an implementation for propagating kamon tracing spans through cats-effect IO https://github.com/kamon-io/Kamon/pull/1196 and this does not work under 3.4.0-RC1, presumably because of changes to the `IOFiber` internals that mean the AOP no longer happens in the right place. Any help/advice about how these internals have changed would be very welcome, although by no means expected. I've filed https://github.com/kamon-io/Kamon/issues/1210 on the Kamon side and will try to look in more detail when I get time.

**Comment by armanbilge** [comment]
I don't know what AOP is, but here's the `IOFiber` diff.
https://github.com/typelevel/cats-effect/compare/v3.3.14...v3.4.0-RC1#diff-dae47b1f42daf4824416a2d89b3f610f460a6af01d2c974e924de13f4279e85a

**Comment by armanbilge** [comment]
If you need to narrow it down, maybe you can try bisecting?

**Comment by m50d** [comment]
Sure - hopefully it'll be something simple/obvious when I get a chance to look in detail, just wanted to flag it up early.

**Comment by djspiewak** [comment]
My guess is that this should be pretty easy to update. Taking a quick glance at the join points, it actually surprises me a bit that this broke in 3.4.

**Comment by ivantopo** [comment]
Indeed, it is a simple update. Just a tiny change on the number of arguments in IOFiber's constructor. We got it covered :muscle:

**Comment by djspiewak** [comment]
Given that kamon-io/Kamon#1214 is now merged, I think we can close this issue!
