### ISSUE TITLE
Proposal: make IO.fail name consistent with Cats Eval or ApplicativeError

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#32]
This is a pet peeve of mine, but the naming of failing data constructors isn't consistent across the board, so we've got:

- `Eval.raise`
- `Applicative.raiseError`
- `IO.fail`
- `Future.failure`
- in Scalaz: `Task.fail`
- in Monix: `Task.raiseError`

So either we rename `IO.fail` to `raise` or `raiseError`, or we push an issue in Cats for renaming of `Eval.raise` to `Eval.fail`. Personally I don't like `raise`. 

And if we have `raiseError` in `ApplicativeError`, I see no reason to not use it everywhere.

EDIT: just did a PR in Cats - https://github.com/typelevel/cats/pull/1634

**Comment by anthonyjoeseph** [comment]
Please update the docs which still reference [`fail`](https://tpolecat.github.io/doobie/docs/09-Error-Handling.html#monaderror-and-derived-combinators)
