### ISSUE TITLE
Remove Ref#lazySet and Ref#compareAndSet

### ISSUE THREAD

**Issue by pchlupacek** [typelevel/cats-effect#320]
I would strongly suggest to remove above mentioned from the Ref before 1.0. 

Reasoning: 
- Both of them are replicating just implementation, so its hard do get them implemented if AtomicRef is not implementation of Ref
- compareAndSet has built-in equality based on identity equality, having as so very limited usability.

**Comment by mpilquist** [comment]
:+1: from me. `comapreAndSet` in particular is really hard to reason about -- e.g., imagine an `Invariant[Ref[F, ?]]` instance and the behavior of the derived `compareAndSet`.

**Comment by SystemFw** [comment]
Agreed.

- They are implementation leeks: one shouldn't really be concerned CAS and AtomicReference to use `Ref`.
- They expose reference equality in the API, which isn't great (even though it's obviously indispensable for the implementation)
- Make new implementations harder: `Ref` is now a trait, and we'd like our `Signal` to also implement that.

**Comment by alexandru** [comment]
We can always re-add them later, so if you think they should go, that's fine by me.

But make the PR happen before Monday 🙂

**Comment by pchlupacek** [comment]
:-)cool. Who will do PR?

**Comment by SystemFw** [comment]
I can do it, I also have another one to do for `once`

**Comment by johnynek** [comment]
can't you derive `compareAndSet` from `tryUpdate`? Should we remove that as well? If not, how does it tie our hands on implementation?

**Comment by mpilquist** [comment]
Kind of but (1) you have to downcast to `AnyRef` in order to use reference equality and (2) an `Invariant` instance doesn't likely work since given an isomorphism `f: A => B, g: B => A`, ref.imap(f, g)` would result in `compareAndSet` failing due to use of reference equality.
