### ISSUE TITLE
`WorkerThreadNameSpec` is sometimes flaky in CI

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3216]
```
WorkerThreadNameSpec
WorkerThread should
  x rename itself when entering and exiting blocking region
   the value is false (WorkerThreadNameSpec.scala:73)
Total for specification WorkerThreadNameSpec
```

**Comment by armanbilge** [comment]
https://github.com/typelevel/cats-effect/blob/1c6d348ff33beabc86bcec44c4ff0b0933bf5890/tests/jvm/src/test/scala/cats/effect/unsafe/WorkerThreadNameSpec.scala#L70-L73

**Comment by armanbilge** [comment]
Actually, I'm not sure if this is testing a valid thing. I thought that @vasilmkd said somewhere that a blocking thread never rejoins the compute pool 🤔

**Comment by armanbilge** [comment]
Ah nevermind, I had an incorrect recollection of this comment.
> Cached threads that blocked at one time can be used as replacements for compute threads again, but not directly as blocking threads.

https://github.com/typelevel/cats-effect/pull/3012#discussion_r887038768

**Comment by aeons** [comment]
I created #3217 to maybe help figuring out which part it is that fails.

**Comment by armanbilge** [comment]
Ok, finally that extra debug bore fruit!
```
[info] WorkerThread should
[error]   x rename itself when entering and exiting blocking region
[error]    blocker thread not found after reset (WorkerThreadNameSpec.scala:74)
```
https://github.com/typelevel/cats-effect/actions/runs/3862591875/jobs/6584256496#step:23:3028

**Comment by aeons** [comment]
I guess that is ok, actually? Is there any guaranteee that the thread actually sticks around?

**Comment by armanbilge** [comment]
Probably? The threads have some time limit (1 minute IIRC) for how long they idle.

**Comment by aeons** [comment]
Should I rework that check, so that it fails if the thread exists and has the wrong name, but it's ok if the thread has disappeared?
