### ISSUE TITLE
Improve code coverage for cats.effect.concurrent

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#324]
We've got some function implementations not being tested in `Ref` and `Semaphore` and we have to cover them:

- [Ref](https://codecov.io/gh/typelevel/cats-effect/src/master/core/shared/src/main/scala/cats/effect/concurrent/Ref.scala)
- [Semaphore](https://codecov.io/gh/typelevel/cats-effect/tree/master/core/shared/src/main/scala/cats/effect/concurrent)

**Comment by SystemFw** [comment]
WDYT about a `good first issue` label for things like this?

**Comment by satansk** [comment]
I will add tests for `Semaphore` :)

**Comment by CucumisSativus** [comment]
@satansk are you still working on it? If not I will be super happy to take it over form you, if you are still working on it please let me know - i'll find other issue to solve :)

**Comment by satansk** [comment]
@CucumisSativus it's yours :)

**Comment by CucumisSativus** [comment]
Looks like `MVar` is missing quite a lot of tests, I'll take this possibility and write tem
