### ISSUE TITLE
Update `Standard Library` section

### ISSUE THREAD

**Issue by iRevive** [typelevel/cats-effect#3249]
There are a few missing and outdated pages in the [Standard Library](https://typelevel.org/cats-effect/docs/std/countdown-latch) section on the site.

Missing:
- [x] AtomicCell
- [x] Backpressure
- [x] Console
- [x] Env
- [x] MapRef
- [x] Mutex

Outdated:
- [x] Supervisor - `await` strategy is not described

**Comment by iRevive** [comment]
I will add some pages over the week.

**Comment by djspiewak** [comment]
This would be great thank you!

On a broader note, we should probably be stricter about ensuring that standard library additions also add their corresponding documentation page, so it doesn't drift like this in future.
