### ISSUE TITLE
Update Concurrency and Cancellation Documentation

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/cats-effect#327]
Recently it has come to light that there is a general need to be clearer in our documentation on cancellation semantics and their relationship to concurrency. #326 

Updating the documentation to reflect the information shared in that thread would be a useful addition.

https://typelevel.org/cats-effect/datatypes/io.html#concurrency-and-cancellation

**Comment by Avasil** [comment]
I'm going to write something today.
