### ISSUE TITLE
Make runtime metrics publicly available

### ISSUE THREAD

**Issue by iRevive** [typelevel/cats-effect#3270]
As discussed on Discord, having a public interface that provides access to the runtime metrics would be nice.

Who would benefit:
- Third-party libraries. E.g., https://github.com/typelevel/otel4s
- Users with established monitoring tools (Prometheus, Datadog, OpenTelemetry)

**Comment by iRevive** [comment]
I can work on this one.

**Comment by djspiewak** [comment]
Am very much in favor!

**Comment by iRevive** [comment]
Closed via https://github.com/typelevel/cats-effect/pull/3317, https://github.com/typelevel/cats-effect/pull/4209, https://github.com/typelevel/cats-effect/pull/4187.
