### ISSUE TITLE
Specialize `Deferred` for `IO` to use `CallbackStack`

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3271]
The `get` function on `Deferred` relies on notifying listeners of the fulfillment of a write-once memory slot. This is startlingly similar to the implementation of `join` in `IOFiber`, except that `IOFiber` uses a dramatically more optimized data structure than what we find in `Deferred`. In theory, it should be possible for us experiment with overriding `Concurrent[IO].deferred` with a custom implementation (`IODeferred`?) which in turn uses the `CallbackStack` data structure from `IOFiber` itself. We should benchmark whether this is actually faster (it should be!) and by how much.

**Comment by armanbilge** [comment]
Is there a reason we can't / shouldn't move `CallbackStack` into `cats-effect-kernel` and use it in the default `Deferred` implementation?

**Comment by djspiewak** [comment]
It increases the public API unnecessarily. There isn't really any benefit to it in most cases, anyway, since the construction always indirects through the typeclass anyway, so we can ensure this always applies for IO.
