### ISSUE TITLE
AtomicCell issue

### ISSUE THREAD

**Issue by chenharryhua** [typelevel/cats-effect#3279]
code: (version 3.4.1)
https://scastie.scala-lang.org/vU5FLiLoRQqwp4ZgGw02TQ

difference between cell and cell2 is I add a dummy IO(()). 
cell output 1 which is not what I expect.
cell2 output 3 which looks good. 
```
import cats.effect.IO
import cats.effect.std.AtomicCell
import cats.effect.unsafe.implicits.global

val cell =
  AtomicCell[IO].of(0).flatMap(r => r.update(_ + 1).replicateA(3) >> r.get)

cell.flatMap(IO.println).unsafeRunSync()

val cell2 =
  AtomicCell[IO].of(0).flatMap(r => IO(()).flatMap(_ => r.update(_ + 1)).replicateA(3) >> r.get)

cell2.flatMap(IO.println).unsafeRunSync()
```

**Comment by armanbilge** [comment]
Thanks for the report. This is a bug because of an unsuspended access:
https://github.com/typelevel/cats-effect/blob/3c27ad9fe5ac5387b332491da41651c1459b65c8/std/shared/src/main/scala/cats/effect/std/AtomicCell.scala#L171 

That should be wrapped in `F.delay(...)`.

**Comment by chenharryhua** [comment]
Thank you. so quick.
