### ISSUE TITLE
Blocked worker thread detector

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3288]
Vert.x does something a bit like this.

The starvation detector added by @TimWSpence does a really good job of detecting when the compute runtime is starving for *some* reason, but that reason could be anything from poor task granularity to hard-blocked threads and anything in between, and there simply is not enough information to take action. There is no way to drive to a root cause, much less a solution.

In general, *most* such starvation cases need to be solved in one of two ways:

- If it's a CPU bound task, additional `cede`s and smaller task granularity (breaking a single `delay` into multiple) is likely to help
- If it's a hard-blocking task, `blocking` or `interruptible` are the solution

In both cases, this may not be enough, since some semantic gating or batching (such as a semaphore or queue) will likely also be required, but this is the first step. Determining which step to take, and where to take it, is where we should be concentrating our efforts.

To that end, it would be beneficial to have an off-by-default blocked thread detector. This should be controlled with a boolean in `IOApp` which in turn is passed to the `WorkStealingThreadPool`. When `true`, any worker thread which enters state `0`, in addition to polling the external queue, should call `Thread#getStatus` on a random *other* worker thread in the pool. If that thread is blocked, call `getStackTrace()` and print a warning to stderr reporting the blocked state along with the stack trace. Additionally, it would be helpful to add some informative text. Telling users that they should swap a `delay` for `blocking`/`interruptible` is almost always going to be the right course of action.

This implementation is going to impose meaningful overhead on the workers, which is part of why it should be *disabled* by default. We can add to the existing starvation checker's informational text to instruct users to try enabling this mode as a diagnostic tool.

**Comment by TimWSpence** [comment]
@djspiewak You assume that the problem isn't just excessive GC and nobody noticed 😅 Hpyothetically peaking of course 😉 I can have a go at this if people want? It would be super useful for us as we wrap a load of Java libraries for various things and its not always obvious when they block

**Comment by djspiewak** [comment]
Go for it!

**Comment by TimWSpence** [comment]
So sorry for the delay @djspiewak! Finally got to looking at this and wanted to check that [this](https://github.com/typelevel/cats-effect/compare/series/3.x...TimWSpence:cats-effect:thread-blocking-detection?expand=1) is roughly what you envisioned?
