### ISSUE TITLE
`flatModify` should be uncancelable

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#3306]
This has binary-compat implications but fortunately has not been released yet. Opened an issue so we don't forget. h/t @bpholt

https://github.com/typelevel/cats-effect/blob/52b5a3ba1623ff40fc48318c9a0bfae558f0e5ed/kernel/shared/src/main/scala/cats/effect/kernel/Ref.scala#L106

**Comment by djspiewak** [comment]
Shouldn't this be user choice? It has semantic implications that vary a bit depending on the use case.

**Comment by armanbilge** [comment]
Hmm, I was thinking about the border between completing the `modify` and beginning the effect. Of course, the effect itself might be cancelable. Something like this:

```scala
def flatModify[B](f: A => (A, F[B]))(implicit F: MonadCancel[F]): F[B] =
  F.uncancelable { poll =>
    modify(f).flatMap(fb => poll(fb))
  }
```

**Comment by armanbilge** [comment]
Eh, I'll just make a new issue.
