### ISSUE TITLE
`DispatcherSpec` flake

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#3312]
```
[error]     x wait for the completion of the active fibers
[error]      the value is false (DispatcherSpec.scala:303)
```

**Comment by samspills** [comment]
I also noticed this while working on the dispatcher errors. Since the tests are somewhat fresh in my head, I can take a look at this :)

**Comment by armanbilge** [comment]
Sorry, another flake 😕 this one in d0c6d3d6df79dfc004d1bdc82bbb5a2aef89d9ea

```
[info] sequential dispatcher should
[error]     x reject new tasks while shutting down
[error]      the value is true (DispatcherSpec.scala:348)
```

**Comment by samspills** [comment]
Ah rats. Thanks for letting me know, I'll try to get a fix up tomorrow!
