### ISSUE TITLE
[Feature request] Add a wrapper for Properties

### ISSUE THREAD

**Issue by massimosiani** [typelevel/cats-effect#3313]
Hi! Thinking about adding a wrapper for system props, similar to what `Env` is for env vars.
I came up with
```
trait Prop[F[_]] {
  def get(name: String): F[Option[String]]
  def modify(name: String, f: String => (String, String)): F[Option[String]]
  def set(name: String, value: String): F[Unit]
  def update(name: String, f: String => String): F[Unit]
}
```
(don't really like the name).

I can provide a PR if it sounds useful.

**Comment by bpholt** [comment]
I could have used this today. It seems like a helpful addition.

**Comment by iRevive** [comment]
Same. I have several use cases where `Prop` would be helpful.
