### ISSUE TITLE
Disable starvation warning on fullOptJs

### ISSUE THREAD

**Issue by cquiroz** [typelevel/cats-effect#3319]
Would it be possible to disable the starvation warning on fullOptJS
Our scala.js webapp is showing these with some frequency and while it maybe useful on development it only makes our users worry unnecessarily.

**Comment by armanbilge** [comment]
The tricky thing is that the performance profiles between `fastOptJS` and `fullOptJS` are so different, especially if tracing is enabled. So `fullOptJS` is really the only time you can get an accurate measure of whether starvation is indeed a problem in production.

https://github.com/typelevel/cats-effect/discussions/3282 demonstrates how to manually disable the check.

**Comment by armanbilge** [comment]
As of https://github.com/typelevel/cats-effect/pull/3355 browser applications are encouraged to seek alternative ways to define the application entrypoint instead of using `IOApp`. This will also circumvent the starvation checker.
