### ISSUE TITLE
Make Starvation Checking opt-in

### ISSUE THREAD

**Issue by cquiroz** [typelevel/cats-effect#3320]
We have been finding quite many starvation checking warnings and while they may point to real problems, they induce problems with the users that check the logs or see the problem on the browser console.

In some cases, there is no practical solution, for example, in our frontend app with scala.js react may execute code blocks that will take a while to execute (and take and undefined time which will also be dependent on the user system) but that are out of control of the application. In my particular case I can't update react to behave differently.

I'd suggest that the starvation check be made opt-in rather than enabled by default. For users that can benefit and actually can act on this feature, they can enable it. 

IMHO the side effect of suprious messages on logs or consoles should be avoided or made opt-in.

**Comment by djspiewak** [comment]
In those sorts of cases, is it not appropriate to update the tolerance threshold to some factor above the maximum time you expect?

In a sense, the starvation checker is an assertion that there is no condition under which it should take more than _x_ milliseconds to respond to an async event. If that assertion cannot be made for a deterministic _x_, then the checker should be disabled. If the default _x_ is wrong, its value should be adjusted.

My fear with making it opt-in is most people will simply never find it. CPU starvation is extremely difficult to detect outside of tail latency metrics.

**Comment by djspiewak** [comment]
I think, with the adjustments we've made, this can now be closed.
