### ISSUE TITLE
Disable starvation checking by default in browsers

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3321]
Due to factors like timer clamping, background tabs, and such, I'm not sure the starvation checker as currently formulated makes that much sense in a web browser environment. It's still *useful*, but it's going to yield false negatives under reasonably expected circumstances, so it seems better to default it to "off".

To be clear, I think it should still default to "on" for other environments, including Node.js

Related to #3320

**Comment by armanbilge** [comment]
Well, maybe. I'd like to hear more from users about it first. So far in https://github.com/typelevel/cats-effect/issues/3320#issue-1505471485 it actually identified a legitimate issue, although it was unclear what mitigating action can be taken.

**Comment by djspiewak** [comment]
Doesn't timer clamping in background scenarios make it almost a guarantee that *every* Cats Effect browser application will hit the warning, though?

**Comment by armanbilge** [comment]
Hmm, fair point.

https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#timeouts_in_inactive_tabs

> Firefox Desktop and Chrome both have a minimum timeout of 1 second for inactive tabs.

Which coincidentally matches our default :)

But also:

> Firefox for Android has a minimum timeout of 15 minutes for inactive tabs and may unload them entirely.

So, yeah, fair point ...

**Comment by armanbilge** [comment]
We might also dynamically enable/disable the checker depending on if the window/tab is active or not.

https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Comment by armanbilge** [comment]
Following https://github.com/typelevel/cats-effect/issues/1959#issuecomment-1379266594 my suggestion is that most browser applications probably don't want to use `IOApp` anyway, so there will be no starvation checker.
