### ISSUE TITLE
`memoize` doc and implementation out of sync

### ISSUE THREAD

**Issue by Jasper-M** [typelevel/cats-effect#3348]
The `memoize` doc says

> If all gets are canceled prior to fa completing, it will be canceled and evaluated again the next time get is sequenced.

But that's not what `memoize` really does. It will reevaluate `fa` if the first `get` that started is cancelled before completion.

```scala
scala> (IO.println("START") *> IO.sleep(2.seconds) *> IO.println("FINISH")).memoize.flatMap(io =>
     |   io.start.flatMap(f => f.cancel.delayBy(1.second)).start *> IO.sleep(200.millis) *> io.start *> IO.sleep(3.seconds)
     | ).unsafeRunSync()
START
START
FINISH
```

**Comment by armanbilge** [comment]
Thanks. I vote to fix the implementation 😁
