### ISSUE TITLE
Resource docs are outdated 

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#336]
In https://typelevel.org/cats-effect/datatypes/resource.html

`def allocate: F[(A, F[Unit])]` isn't present in the current definition of Resource:

https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Resource.scala#L96

**Comment by alexandru** [comment]
@kubukoz thanks, yeah, that would be awesome. 

I'm the one that upgraded its encoding in #278, if you have questions, I'll gladly answer.

**Comment by kubukoz** [comment]
No idea why, but this should've been closed by #516 being merged and wasn't.
