### ISSUE TITLE
NullPointerException when `blockedThreadDetectionEnabled` is set to `true`

### ISSUE THREAD

**Issue by L7R7** [typelevel/cats-effect#3427]
I just tried the `3.5.0-RC1` version in one of our services, mainly to test the thread blocking detection introduced in #3387  and I see the following error in the logs:

```
Exception in thread "io-compute-1" java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicBoolean.get()" because the return value of "cats.effect.unsafe.WorkerThread.parked()" is null
 	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:430)
```

I can only guess, but it sounds to me like it could relate to the thread blocking detection

**Comment by L7R7** [comment]
I don't see the exception with thread blocking detection disabled.
So it's probably this line? https://github.com/typelevel/cats-effect/blob/ed89f2231e07a4ea62d5c7718442d25f2b01f2b5/core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala#L430

**Comment by durban** [comment]
It's definitely that line. I think this is a race condition when a cached thread returns to the pool, and is not re-initialized yet. (Or it may be, but `thread.parked` is a racy read, so we don't necessarily see it.)

**Comment by durban** [comment]
I see 2 options to fix this:

1. We say that this blocking detection is a best-effort thing, and simply check for `null` (and do nothing if it's `null`).
2. We get the parked `AtomicBoolean` from `pool.parkedSignals` (I think we always see those).
