### ISSUE TITLE
Global scheduler leaks threads in tests and consoles

### ISSUE THREAD

**Issue by rossabaker** [typelevel/cats-effect#347]
Every time we run tests with a `Timer[IO]` created from the default scheduler, up to 2 cats-effect threads are left running.  The scheduled thread pool in `IOTimer#scheduler` does not allow core threads to time out.  This is sensible for production, but causes a leak in tests.

We can work around this in tests by vigilantly using a scheduler that times out core threads, but one call to `IO.timer(ec)`, and we're back where we're started.

**Comment by alexandru** [comment]
Can we configure it to timeout the threads?

**Comment by rossabaker** [comment]
The configuration might be a fair solution.  I'm putting a scheduler and a timer in a base suite, and saying anyone creating one with the single argument is a bug, but that's equivalent to saying the global is a bug, and I'm also not ready to go that far.

**Comment by rossabaker** [comment]
In the interim, an expiring test scheduler looks about like this:

```scala
    val s = new ScheduledThreadPoolExecutor(2,
      threadFactory(i => "http4s-test-scheduler", true))
    s.setKeepAliveTime(10L, TimeUnit.SECONDS)
    s.allowCoreThreadTimeOut(true)
    s
```

**Comment by djspiewak** [comment]
@rossabaker Now that we have control over the scheduler, what do you feel is the best approach here?

**Comment by rossabaker** [comment]
I don't think our options are substantially improved from the above discussion.  `IOApp.WithContext` shows how to hook a resource into `main`, swapping in a stub context in case the scheduler is used outside main.  Short of adding a contextual scheduler like that, which is not cats-effect's crowning achievement, I think @alexandru's suggestion of environment variables is the best we can do.
