### ISSUE TITLE
Failing task in cirrus doesn't fail the github status

### ISSUE THREAD

**Issue by durban** [typelevel/cats-effect#3507]
Example: https://cirrus-ci.com/build/5225830406684672 (but #3499 shows commit 9b24c58 as green).

Edit: But sometimes it works as expected: https://cirrus-ci.com/build/5044337302568960 and 843a1d0.

**Comment by armanbilge** [comment]
Thanks, good eye. I think the problem is that the job names for 2.12/2.13/3 are the same and its only reporting one of those. I bet if we fix that then we'll get more jobs listed. My bad 😇
