### ISSUE TITLE
Close inactive issues and PRs, older than 1 month

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#354]
We need a close issues and PRs policy.

Inspired by reading these blog posts:

- https://www.hanselman.com/blog/AlwaysBeClosingPullRequests.aspx
- https://blog.jessfraz.com/post/the-art-of-closing/

Rules:

1. close issues or PRs for which there exists some consensus, but that have more than one month of inactivity (no discussions, no commits)
2. close even earlier issues or PRs for which there exists no consensus

Lets keep the issue tracker clean, such that we can focus on the important ones.
What do you say?

**Comment by rossabaker** [comment]
What happens if this issue passes a month without comment? :thinking:

I think the principle is good, but a warning might nudge a few more across the finish line. 
 I haven't tried it, but what about something like [Stale](https://probot.github.io/apps/stale/) bot?

**Comment by alexandru** [comment]
A bot to give a warning might be cool. I always feel bad about closing people's unsolved issues.

**Comment by Avasil** [comment]
Is there something like this but for signaling stale issues waiting for maintainers' response? Sometimes it's easy to miss or forget about something

**Comment by alexandru** [comment]
Yes, I'm guilty of ignoring issues and PRs 🙂

**Comment by SystemFw** [comment]
I guess another category is: this is cool, but we can't do it right now, which happens a lot when bincompat guarantees come into play

**Comment by djspiewak** [comment]
In the process of cleaning stuff up right now.
