### ISSUE TITLE
In theory, waiters can be lost in `Mutex`

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3554]
If a waiter is notified at the exact moment that it is canceled, it's possible for that wake-up to be lost, which can leave the overall mutex in an inconsistent state.

**Comment by armanbilge** [comment]
I'm not sure if this is all theory, we still have the unexplained non-deterministic Skunk hanging.

**Comment by djspiewak** [comment]
The Skunk hanging isn't consistent with a failure in `Mutex` of this nature. The heap dump you gave me from the Skunk failure is *internally* inconsistent w.r.t. WSTP state. A `Mutex` failure in this fashion would have resulted in an entirely normal WSTP in a quiescent state, which isn't what we see.

**Comment by armanbilge** [comment]
The heap dump I gave you wasn't from Skunk at all :) that was experimental polling system stuff hanging in FS2.

I narrowed down the Skunk issues to Mutex in https://github.com/typelevel/skunk/issues/852#issuecomment-1519192258.

**Comment by durban** [comment]
Definitely not theory, see #3555 at an attempt to fix.
