### ISSUE TITLE
`Async` mutex corrupts FIFO on happy(ish) path

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#3564]
I want to capture this test from https://github.com/typelevel/cats-effect/pull/3562 as a separate issue.

What this tests is, if you have a bunch of waiters queued up on an unavailable mutex, what happens if one of those waiters cancels?

In the current implementation, the next waiter will be moved to the back of the queue. More specifically, in this test when waiter 0 cancels, waiter 1 is moved after waiter 10 (!!). Arguably this is all happy(ish) path: there are no race conditions at play, just a cancelation, but the result is a significant corruption of FIFO, IMHO.

https://github.com/typelevel/cats-effect/blob/2c355db7162894faa58923cf9e196753f02e1193/tests/shared/src/test/scala/cats/effect/std/MutexSpec.scala#L172-L195

**Comment by durban** [comment]
For what it's worth, I agree. I think this is still better than leaving the mutex in an invalid state upon cancellation, but it would be good to fix this. (Also, the link should be #3562, right?)

**Comment by armanbilge** [comment]
> I think this is still better than leaving the mutex in an invalid state upon cancellation

Oh for sure, no question! 😆 

> (Also, the link should be #3562, right?)

Woops, thanks, fixed :)
