### ISSUE TITLE
`IO.cede.foreverM.timeoutTo(...)` timeout flake

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#3568]
Observed in e61c058efae982e7716c19c2d0f8a4c69eaed985.

```
[info]     timeoutTo should
[info]       + succeed
[error]       ! use fallback
[error]        cats.effect.TestTimeoutException: null (Runners.scala:109)
[error] cats.effect.Runners.$anonfun$timeout$1(Runners.scala:109)
[error] cats.effect.unsafe.WorkStealingThreadPool.$anonfun$sleep$1(WorkStealingThreadPool.scala:647)
[error] cats.effect.unsafe.WorkStealingThreadPool.$anonfun$sleep$1$adapted(WorkStealingThreadPool.scala:647)
[error] cats.effect.unsafe.WorkStealingThreadPool.stealTimers(WorkStealingThreadPool.scala:238)
[error] cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:599)
```

https://github.com/typelevel/cats-effect/actions/runs/4811306795/jobs/8565136011?pr=3565#step:23:3612

Is it just me, or I don't see a reasonable explanation for why this test should timeout after several seconds 🤔 

https://github.com/typelevel/cats-effect/blob/e61c058efae982e7716c19c2d0f8a4c69eaed985/tests/shared/src/test/scala/cats/effect/IOSpec.scala#L1783-L1793

**Comment by djspiewak** [comment]
I think it's just that the runners are very slow and we're starting to see it a lot now. Honestly I want to just bump up the global timeout.

**Comment by armanbilge** [comment]
Still flaking :(

https://github.com/typelevel/cats-effect/actions/runs/4839630759/jobs/8625021373?pr=3579#step:23:3613
