### ISSUE TITLE
Add mention in the ScalaDoc of Bracket#bracket

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#357]
Based on feedback from https://github.com/scalaz/scalaz-zio/pull/247 ...

We need to add a mention in the ScalaDoc of `Bracket#bracket` and of `bracketCase` that `release` SHOULD NOT throw in generic code, because if it does, then the behavior is _undefined_.

This is an important point to make. If `release` throws, we cannot have any laws for it, as the behavior is implementation specific.

**Comment by CucumisSativus** [comment]
Since #394 is merged i think this one can be closed
