### ISSUE TITLE
Round timer durations up to 0

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3585]
`IO.sleep(-1.millis)` should equal `IO.sleep(0.millis)`, which in turn should equal `IO.cede`. It's probably easiest to play this trick in `IOFiber` rather than tracking down all the various places we call `sleep`.

**Comment by manuelcueto** [comment]
I can take this one 👍

**Comment by djspiewak** [comment]
@manuelcueto Any updates on this? I think this is the last issue remaining before 3.5.0.
