### ISSUE TITLE
Update migration guide for newer CE3 stuff

### ISSUE THREAD

**Issue by Daenyth** [typelevel/cats-effect#3589]
For example, https://typelevel.org/cats-effect/docs/migration-guide#where-does-the-blocking-pool-come-from
mentions stuff that isn't correct in the current CE3, because of the WSTP

**Comment by durban** [comment]
- Another thing which is not true any more is the `Option[F[Unit]]` in `async`: "Passing None here is equivalent to Some(F.unit)" -> it is not.
- `Dispatcher` now has an `await` parameter, so cancelling is not the only behavior available.
- "Currently, improved stack traces are not implemented" -> they are.
