### ISSUE TITLE
New Release on cats 1.4.0

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/cats-effect#359]
Cats just released 1.4.0 so it may be wise to get a release out with the new upstream dependency. 

https://github.com/typelevel/cats/pull/2489

**Comment by alexandru** [comment]
We need to wait for another week or so to watch out for bug reports, since I see there are some new features added.

**Comment by etspaceman** [comment]
What's the status of this?

**Comment by catostrophe** [comment]
Resolved with #379
May be closed
