### ISSUE TITLE
Add `SharedResource` data class to `cats.effect.concurrent`

### ISSUE THREAD

**Issue by seigert** [typelevel/cats-effect#368]
This is a proposal to add simple `Key -> F[Resource]` allocator of shared resources.

Possible implementation:
```scala
import cats.effect.concurrent.{ Deferred, MVar }
import cats.effect.{ Concurrent, Resource }
import cats.implicits._

import scala.language.higherKinds

abstract class SharedResource[F[_], K, R] {
  def apply(key: K): Resource[F, R]
}

object SharedResource {
  def apply[F[_], K, R](f: K => F[(R, F[Unit])])(
      implicit F: Concurrent[F]
  ): Resource[F, SharedResource[F, K, R]] = Resource[F, SharedResource[F, K, R]] {
    MVar[F].of(Map.empty[K, Either[List[Deferred[F, R]], (Int, R, F[Unit])]]).map { mvr =>
      def allocate(k: K): F[R] =
        mvr.take.flatMap { str =>
          str.get(k) match {
            case Some(Right((c, r, ct))) => 
              mvr.put(str.updated(k, (c + 1, r, ct).asRight)).as(r)
            case Some(Left(dfs)) =>
              Deferred[F, R]
                .flatTap { dfr =>
                  mvr.put(str.updated(k, (dfr :: dfs).asLeft))
                }
                .flatMap(_.get)
            case None =>
              f(k)
                .flatTap {
                  case (r, ct) => mvr.put(str.updated(k, (1, r, ct).asRight))
                }
                .map(_._1)
          }
        }

      def free(k: K): F[Unit] = mvr.take.flatMap { str =>
        str.get(k).foldMapM {
          case Right((1, _, ct)) => mvr.put(str.updated(k, Nil.asLeft)) *> ct *> free(k)
          case Right((c, r, ct)) => mvr.put(str.updated(k, (c - 1, r, ct).asRight))
          case Left(dfs)         => mvr.put(str - k) *> dfs.foldMapM(allocate(k) >>= _.complete)
        }
      }

      val shared = new SharedResource[F, K, R] {
        def apply(key: K): Resource[F, R] = Resource.make(allocate(key))(_ => free(key))
      }
      val release = mvr.take.flatMap { str =>
        str.values.foldLeft(F.unit) {
          case (fu, Right((_, _, ct))) => fu *> ct
          case (fu, _)                 => fu
        }
      } *> mvr.put(Map.empty)

      shared -> release
    }
  }
}
```

I believe that such data class, while relatively simple to implement, will be especially useful if provided by `cats-effect`. Also, `K => F[(R, F[Unit])]` could be more easily be replaced with `K => Resource[F, R]` w/o need to reimplement `Resource[F]#use` loop (by exposing loop to `cats-effect` internals).

If this proposal is accepted, I think I can provide a pull request in about a week.

**Comment by djspiewak** [comment]
Hmm, so the concept here is a sort of atomic lazy map? That's interesting, though I've never needed one that is primitive at this level. When I've run into this case, I've also needed higher level operations, such as what are in fs2 or Monix. I'll leave this open for a little while longer to see if it gets traction, but if no one else weighs in with interest, I think we may have to skip it in the interest of keeping the API small.

**Comment by seigert** [comment]
Not only it's lazy, it also keeps track of used allocations of `Resource`, so actual values could be released as soon as every user released it's own handle.

For example, HTTP client could use it to keep track of pooled keep-alive connections to a different sites with hostname as key. As soon as some site is no longer used, it's connections will be closed.

**Comment by SystemFw** [comment]
Have you looked at https://github.com/ChristopherDavenport/keypool ?

Imho, when you actually consider making this code fully production ready (e.g. all the work needed to make it interruption safe) and then the different choices in semantics, it belongs in its own library

**Comment by rossabaker** [comment]
https://github.com/christopherdavenport/keypool is worth comparing and contrasting.

**Comment by seigert** [comment]
@SystemFw No, I did not as the issue is almost 9 month old and I don't think `keypool` was a thing back then. :)

After a quick glance I think that my proposal is more lightweight: there is no notion of reusability and resource itself is simply granted to all accessors and discarded after. Chances are that it won't be useful that way.
