### ISSUE TITLE
OOPify the `PollingSystem` encoding

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#3683]
Well, Daniel wants us to anyway 😝 for some reason I'm not crazy about this idea, but I won't die on this hill.

Basically, we should make an `abstract class Poller` or something, and move these methods onto that.

https://github.com/typelevel/cats-effect/blob/58f695fbc25a2f7bef5d04427ec5d03e94212e8d/core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala#L38-L56

Follow-up to:
- https://github.com/typelevel/cats-effect/pull/3332

**Comment by djspiewak** [comment]
Wontfix
