### ISSUE TITLE
Polling system metrics

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#3686]
We should figure out what kinds of metrics we want to collect and how to expose them in the API. cc @iRevive

A couple ideas:

1. libuv reports an "idle time" metric. we could measure this per-thread, and actually this is not specific to the polling system at all, this is a general property of the WSTP.
    > Retrieve the amount of time the event loop has been idle in the kernel’s event provider (e.g. epoll_wait).

    https://docs.libuv.org/en/v1.x/metrics.html#c.uv_metrics_idle_time

2. number of outstanding channels/file descriptors/interest events, also per-thread. would be interesting to see if this balances across threads. on the JVM, we could break this into additional categories: # TCP sockets, # server sockets, etc.

Linking to:
- https://github.com/typelevel/cats-effect/pull/3317

Follow-up to:
- https://github.com/typelevel/cats-effect/pull/3332

**Comment by iRevive** [comment]
This one should remain open I believe
