### ISSUE TITLE
Make `cats.effect.std.PQueue` share `cats.effect.std.Queue` trait

### ISSUE THREAD

**Issue by skedlukecollier** [typelevel/cats-effect#3721]
Currently `PQueue` extends [PQueueSource](https://typelevel.org/cats-effect/api/3.x/cats/effect/std/PQueueSource$.html) and [PQueueSink](https://typelevel.org/cats-effect/api/3.x/cats/effect/std/PQueueSink.html) ran into a problem where trying to use [fs2.Stream#fromQueueUnterminating](https://www.javadoc.io/doc/co.fs2/fs2-docs_2.13/3.7.0/fs2/Stream$.html#fromQueueUnterminated[F[_],A](queue:cats.effect.std.QueueSource[F,A],limit:Int)(implicitevidence$36:cats.Functor[F]):fs2.Stream[F,A]) led to a type error on a `PQueue` so following a [convo on discord](https://discord.com/channels/632277896739946517/632310980449402880/1123583354281922581) the trait's be linked or unified

**Comment by armanbilge** [comment]
Sorry, now that I think about it: I can see an argument that `PQueue` should not extend/implement the `Queue` trait, depending on what the `Queue` trait is promising. For example, if it is promising FIFO, then passing a `PQueue` could observably violate that expectation.

_However_, `QueueSink` and `QueueSource` specifically don't offer sufficient API surface to assert these sorts of laws. So in that case, it wouldn't seem unreasonable for `PQueue{Source,SInk}` to extend `Queue{Source,Sink}`. Their APIs are identical, both in terms of methods and semantics.

Actually, this makes me wonder if a better hierarchy might have been `QueueSource`, `QueueSink`, and `Queue`, with marker interfaces `FifoQueue` and `PQueue`. Then calling code could declare precisely what it does or doesn't need to work correctly.

Thoughts?

**Comment by skedlukecollier** [comment]
For the specific problem I had I think extending `PQueueSource` and `PQueueSink` with the `QueueSink` and `QueueSource` seems like the solution we're after!

For the next part would the `Queue` remain as is, then `PQueue` and a new `FifoQueue` extend `Queue`?

If I'm following then it would give types hints [for these types of questions](https://stackoverflow.com/questions/12692479/is-priorityqueue-a-fifo-queue) that Java faces due to its shared [queue](https://docs.oracle.com/javase/8/docs/api/java/util/Queue.html) interface. 

For me, the difference between a `PQueue` and `Queue` seems like a happy level of detail for most use cases here, 9/10 a Queue is _probably_ fifo.

**Comment by armanbilge** [comment]
> For the specific problem I had I think extending `PQueueSource` and `PQueueSink` with the `QueueSink` and `QueueSource` seems like the solution we're after!

Yes, I think so too! I think we can definitely make this change.

> For the next part would the `Queue` remain as is, then `PQueue` and a new `FifoQueue` extend `Queue`?

Well, ideally we'd do this, but due to compatibility constraints we probably no longer can. i.e. the expectation is that `Queue` _is_ a FIFO queue, so actually we need to add something "above" it in the hierarchy which may not be FIFO.

**Comment by skedlukecollier** [comment]
> Yes, I think so too! I think we can definitely make this change.

Created https://github.com/typelevel/cats-effect/pull/3733 for this, will update it to not be failing when I get chance

> Well, ideally we'd do this, but due to compatibility constraints we probably no longer can. i.e. the expectation is that Queue is a FIFO queue, so actually we need to add something "above" it in the hierarchy which may not be FIFO.

I can't think of a word for an `AbstractQueue` perhaps that's a sign it's an unnecessary abstraction? 🤔

**Comment by armanbilge** [comment]
> it's an unnecessary abstraction

true, at the moment we don't have a usecase for it.

**Comment by neomaclin** [comment]
added a PR #3930 to follow up on this

**Comment by durban** [comment]
Fixed by #3930.
