### ISSUE TITLE
Is TestControl expected to work with Dispatcher and Async[F].fromCompletableFuture?

### ISSUE THREAD

**Issue by bpholt** [typelevel/cats-effect#3722]
I have some code where I've faked a Java interface that returns `CompletableFuture`, and I want to capture the arguments passed into the fake using a `Ref`. I'm running 
```scala
dispatcher.unsafeToCompletableFuture(ref.complete(…))
```
in the fake, and then in the code that uses the Java interface, I use
```scala
Async[F].fromCompletableFuture(Sync[F].delay(javaInterface.foo(…))
```
to bring it back into cats-effect. 

When I run it this way I pretty consistently get `None` from the `TestControl`'s `results` after (AFAICT) I've ticked it as much as it can go.

If I swap out the `dispatcher.unsafeToCompletableFuture.…` in the impure code with 
```scala
dispatcher.unsafeRunSync(deferred.complete(i).void)
CompletableFuture.completedFuture(())
```
it all seems to consistently work on my machine.

<details>
<summary>Scala CLI demonstration of the problem</summary>

If you toggle `shouldItWork` you should see the two behaviors.

```scala
//> using scala 2.13
//> using dep org.typelevel::cats-effect-testkit:3.5.1
//> using dep com.eed3si9n.expecty::expecty:0.16.0

import cats.effect._
import cats.effect.kernel.Outcome
import cats.effect.std.Dispatcher
import cats.effect.testkit.TestControl
import cats.syntax.all._
import com.eed3si9n.expecty.Expecty._

import scala.concurrent.duration._

import java.util.concurrent.CompletableFuture

trait JavaInterface {
  def foo(i: Int): CompletableFuture[Unit]
}

class CodeUnderTest[F[_]: Async](ji: JavaInterface) {
  def useFoo: F[Unit] =
    Temporal[F].sleep(1.second) >> Async[F].fromCompletableFuture(Sync[F].delay(ji.foo(42)))
}

object MyApp extends IOApp.Simple {
  val shouldItWork: Boolean = true

  def run: IO[Unit] =
    Dispatcher.sequential[IO].use { dispatcher =>
      for {
        deferred <- Deferred[IO, Int]

        ji = new JavaInterface {
          def foo(i: Int): CompletableFuture[Unit] = {
            if (shouldItWork) {
              dispatcher.unsafeRunSync(deferred.complete(i).void)
              CompletableFuture.completedFuture(())
            } else
              dispatcher.unsafeToCompletableFuture(deferred.complete(i).void)
          }
        }

        control <- TestControl.execute(new CodeUnderTest[IO](ji).useFoo)
        _ <- IO.println("pre tick")
        _ <- control.tick

        _ <- IO.println("pre initial deferred.tryGet")
        initialValue <- deferred.tryGet

        _ <- IO.println("pre tickFor(1.second)")
        _ <- control.tickFor(1.second)

        _ <- IO.println("pre get results")
        results <- control.results

        _ <- IO.println("pre final deferred.get")
        finalValue <- deferred.get

        _ <- IO.println("done… control.results should be Some(())")

        output <- IO {
          assert(initialValue == None)
          assert(finalValue == 42)
          assert(results == Option(Outcome.succeeded[cats.Id, Throwable, Unit](())))
        }.attempt
        _ <- IO.println(output)
      } yield ()
    }
}
```
</details>

**Comment by armanbilge** [comment]
I'd say yes, it is expected to work. We have some similar tests for this here. So would be interesting to get to the bottom of this :)

https://github.com/typelevel/cats-effect/blob/86b65a99bcdfe7ffc6f1b8074a6e38a7a4e10cd1/tests/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala#L122-L148

**Comment by djspiewak** [comment]
I didn't get a chance to reply in Discord! This is better though because more permanent…

The answer is that yes this works, but it doesn't work the way you think it does. The problem is that `TestControl` is going to tick until its work queue is empty, at which point it looks to see if a result has been produced. If no result was produced, then you get `None`. If a result has been produced, you get it within the `Some`. The problem here is that you're putting some work onto an *external* work queue (the `CompletableFuture`'s thread pool), which `TestControl` can't see, which in turn leads it to a situation where its work queue is empty and it terminates.

You can work around this by using `execute` rather than `executeEmbed`. Tick up to the point at which you expect the work to be pushed off to the `CompletableFuture`, then use some other mechanism (such as a latch or simply polling) to figure out when the `CompletableFuture` has delivered its results back to `TestControl`, then you can start ticking again until completion.

**Comment by armanbilge** [comment]
> the `CompletableFuture`'s thread pool

Well, this is what's bothering me. Why does `CompletableFuture` have its own threadpool? I'd understand if it's somebody else's `CompletableFuture`, but if this is a `CompletableFuture` we are building ourselves with  `unsafeToCompletableFuture` then shouldn't it be 100% running on our own threadpool? If it's not, then I say that's a bug that we should fix.

**Comment by bpholt** [comment]
> You can work around this by using execute rather than executeEmbed.

🤔 The example already uses `execute`:

> ```scala
> control <- TestControl.execute(new CodeUnderTest[IO](ji).useFoo)
> ```

> Tick up to the point at which you expect the work to be pushed off to the CompletableFuture, then use some other mechanism (such as a latch or simply polling) to figure out when the CompletableFuture has delivered its results back to TestControl, then you can start ticking again until completion.

Naïvely, I would have thought the `CompletableFuture` should have already delivered its results back to the cats-effect part of the app. The only thing it's doing is completing a `Deferred`, and the assertions prove that it was completed. Is there something else I should be checking?

**Comment by armanbilge** [comment]
I figured out what the problem is 🙂 and maybe this is what Daniel was getting at!

The problem is you are building the `Dispatcher` _outside_ of `execute`, so it's not using the test runtime. Therefore it's using the actual compute pool, and not the test EC, which is why things seem broken.

For this to work, you have to run _everything_ inside of `execute` or `executeEmbed`, including the creation of the `Dispatcher`.

**Comment by bpholt** [comment]
That makes sense, thanks @armanbilge @djspiewak!

Here's the updated snippet, that works when `useUnsafeRunSync` is `false`:

```scala
//> using scala 2.13
//> using dep org.typelevel::cats-effect-testkit:3.5.1
//> using dep com.eed3si9n.expecty::expecty:0.16.0

import cats.effect._
import cats.effect.kernel.Outcome
import cats.effect.std.Dispatcher
import cats.effect.testkit.TestControl
import cats.syntax.all._
import com.eed3si9n.expecty.Expecty._

import scala.concurrent.duration._

import java.util.concurrent.CompletableFuture

trait JavaInterface {
  def foo(i: Int): CompletableFuture[Unit]
}

class CodeUnderTest[F[_]: Async](ji: JavaInterface) {
  def useFoo: F[Unit] =
    Temporal[F].sleep(1.second) >> Async[F].fromCompletableFuture(Sync[F].delay(ji.foo(42)))
}

object MyApp extends IOApp.Simple {
  private val useUnsafeRunSync: Boolean = false

  def run: IO[Unit] =
    for {
      deferred <- Deferred[IO, Int]
      control <- TestControl.execute {
        Dispatcher.sequential[IO].use { dispatcher =>
          val ji = new JavaInterface {
            def foo(i: Int): CompletableFuture[Unit] = {
              if (useUnsafeRunSync) {
                dispatcher.unsafeRunSync(deferred.complete(i).void)
                CompletableFuture.completedFuture(())
              } else
                dispatcher.unsafeToCompletableFuture(deferred.complete(i).void)
            }
          }

          new CodeUnderTest[IO](ji).useFoo
        }
      }

      _ <- IO.println("pre tick")
      _ <- control.tick

      _ <- IO.println("pre initial deferred.tryGet")
      initialValue <- deferred.tryGet

      _ <- IO.println("pre tickFor(1.second)")
      _ <- control.tickFor(1.second)

      _ <- IO.println("pre get results")
      results <- control.results

      _ <- IO.println("pre final deferred.get")
      finalValue <- deferred.get.timeout(2.seconds)

      _ <- IO.println("done… control.results should be Some(())")

      output <- IO {
        assert(initialValue == None)
        assert(finalValue == 42)
        assert(results == Option(Outcome.succeeded[cats.Id, Throwable, Unit](())))
      }.attempt
      _ <- IO.println(output)
    } yield ()
}
```

Notably, this hangs when `useUnsafeRunSync` is `true` (to the point where I have to `kill -9 {scalacli java process}` to stop it; `⌃c` is not enough). This makes sense when you think about it: previously, the `Dispatcher` instance wasn't part of the `TestControl` runtime, meaning it was running on the normal JVM runtime, where `unsafeRunSync` is available. Now it runs on the `TestControl` runtime, which is single-threaded, so `unsafeRunSync` can never terminate.
