### ISSUE TITLE
`IO.raiseError(...)` doesn't immediately surface fatal errors

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#3767]
Consider:
```scala
//> using dep "org.typelevel::cats-effect::3.5.1"

import cats.effect.*

object App extends IOApp.Simple:
  def run = IO.raiseError(new VirtualMachineError {}).voidError
```

Even though a `VirtualMachineError` is a fatal error, that program completes normally.

If we change it to:
```scala
  def run = IO(throw new VirtualMachineError {}).voidError
```

then the fatal error is surfaced immediately as expected.

h/t @kamilkloch

**Comment by scott-thomson239** [comment]
Hi, I'd like to help with this if it's not already being worked on

**Comment by armanbilge** [comment]
@scott-thomson239 thanks! You can target your PR to `series/3.5.x` branch.

**Comment by armanbilge** [comment]
@scott-thomson239 are you still working on this one? let us know if you have any questions!

**Comment by scott-thomson239** [comment]
Sorry for my silence on this. I've raised a PR with what I think is the fix now.
