### ISSUE TITLE
EffectLaws.repeatedCallbackIgnored

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#38]
So we've got this law:

```scala
  def repeatedCallbackIgnored[A](a: A, f: A => A) = {
    var cur = a
    val change = F.delay(cur = f(cur))
    val readResult = IO { cur }

    val double: F[Unit] = F async { cb =>
      cb(Right(()))
      cb(Right(()))
    }

    val test = F.runAsync(double >> change) { _ => IO.unit }

    test >> readResult <-> IO.pure(f(a))
  }
```

This is fine, however I hope you don't intend that implementations synchronize on those callback calls. As I mentioned before, in Monix I prefer to treat this by convention + error reporting by means of the EC and I do have a check in place, but it's a simple unsynchronised `var` and not an `AtomicBoolean`. So it takes care of simple cases, like in the sample above, but if access is not synchronised, then all bets are off.

**Comment by djspiewak** [comment]
The thing I'm concerned about w.r.t. removing this law (as opposed to the "throw in `async` is `fail`" one) is that this sort of behavior fundamentally affects the set of guards you have to bake in while writing code which uses the `Async` typeclass.  If you can't assume that the underlying implementation is taking care of this (relatively common) problem for you, then you have to defensively do it yourself, even if the underlying implementation *might* do it!  That limits the flexibility of the abstraction, and forces people to push concrete implementation-specific logic into their "abstract" functions.

**Comment by alexandru** [comment]
The law is fine, I was just commenting that it shouldn't get stronger than this.

**Comment by djspiewak** [comment]
Yeah, I think I agree with that.  I mean, one can argue that it's insufficiently specified in its current form, but the laws aren't meant to catch all possible bugs.  Making it stronger would be somewhat complicated (especially considering JS compatibility), and obviously would rule out some implementations.
