### ISSUE TITLE
Prevent `Hotswap#get` from acquiring a lock when there is no `Resource` present

### ISSUE THREAD

**Issue by tibetansingingcat** [typelevel/cats-effect#3802]
Currently:

https://github.com/typelevel/cats-effect/blob/290f49864236d73f10d2b60d546158b5c1d845e1/std/shared/src/main/scala/cats/effect/std/Hotswap.scala#L143-L149

Every time `get` is called, we acquire a permit from the `Semaphore[F]` inside of `Hotswap`. If any permits are currently acquired, `Hotswap#swap` will be blocked.

Conceivably, a long running operation could occur inside of `Hotswap#get` despite no `Resource` being present, resulting in blocking to prevent replacing a non-existent `Resource` and during that time, any other invocations of `Hotswap#get` will also be forced to operate on `None`, despite any possible invocations of `swap` waiting in the wings with a real, live `Resource`.

**Comment by josgarmar28** [comment]
I would like to help resolve this issue.

**Comment by armanbilge** [comment]
Thank you @josgarmar28 ! You can target this PR at the `series/3.5.x` branch. Let us know if you have any questions and please put up a draft PR early so we can follow your progress :)
