### ISSUE TITLE
Add `def warnOnNonMainThreadDetected: Boolean` configuration to `IOApp`

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#3806]
Follow-up to:
- https://github.com/typelevel/cats-effect/pull/3774#discussion_r1313875233

**Comment by diogocanut** [comment]
I want to take this one if not taken

**Comment by armanbilge** [comment]
@diogocanut thanks!

**Comment by diogocanut** [comment]
Should we have the same logic as in `onNonMainThreadDetected`, like:

```scala
def warnOnNonMainThreadDetected: Boolean =
  Option(System.getProperty("cats.effect.warnOnNonMainThreadDetected"))
    .map(_.equalsIgnoreCase("true"))
    .getOrElse(true)
```

or default it as disabled?

```scala
java.lang.Boolean.getBoolean("cats.effect.warnOnNonMainThreadDetected")
```

**Comment by armanbilge** [comment]
I think the default should be enabled.

**Comment by armanbilge** [comment]
- https://github.com/typelevel/cats-effect/pull/3815
