### ISSUE TITLE
Add unsafeRunAsync with a Try？

### ISSUE THREAD

**Issue by He-Pin** [typelevel/cats-effect#3807]
Motivation: 
I want to have better integration in Akka/Pekko with cats-effect where `mapAsync` or `mapAsyncUnordered` is invoked.
I want to create a new operator, eg: `unsafeMapAsync[F[_]] (...)` where I can then make use of the cat-efect without convert it to `Future`

as  ```def unsafeRunAsync(cb: Either[Throwable, A] => Unit)```
But
``` def unsafeRunAsyncTry(cb: Try[A] => Unit)```

Or make the `unsafeRunAsyncFiberRef` public:)

Convert from `Either` to `Try` will add an allocation.

**Comment by satorg** [comment]
Would the `Either`'s `toTry` method work for you? I.e. to me it looks like
`unsafeRunAsyncTry(cb) <=>  unsafeRunAsync(res => cb(res.toTry))`

**Comment by He-Pin** [comment]
> Would the `Either`'s `toTry` method work for you? I.e. to me it looks like
> `unsafeRunAsyncTry(cb) <=>  unsafeRunAsync(res => cb(res.toTry))`

Or just make unsafeRunFiberRef public.

**Comment by He-Pin** [comment]
@satorg @armanbilge I have updated the use case, thanks

**Comment by satorg** [comment]
@He-Pin could you elaborate a bit more on it, why do you need `Try` there in the first place?
Honestly, I am not familiar with akka/pekko code base to reason about it.

**Comment by He-Pin** [comment]
@satorg I was want to reduce the allocation, but that's not a problem now.

**Comment by djspiewak** [comment]
> that's not a problem now

I suspect that the extra allocation here really isn't going to hurt. You already have at least one allocation with the function value, and almost certainly several more allocations and other even more expensive things. At any rate, it sounds like you worked around the issue, so I'm going to close this. Please feel free to correct me if I'm mistaken!
