### ISSUE TITLE
Deadlocking with Parallel[IO]?

### ISSUE THREAD

**Issue by tpataky** [typelevel/cats-effect#3819]
I've got a little example that (given a large enough problem) goes into some sort of busy loop and never completes.

The problematic method (`def processFoo[F[_]](foo: Foo)(implicit F: Async[F], P: Parallel[F]): F[Unit]`)  is parametric in the effect type. Running it with `IO` is OK, but `EitherT[IO, E, *]` sends it into a busy loop. 

I tried to reduce the problem a little further to eliminate the `EitherT` from the picture, the result of that is in 
the method `def processFooWithEitherTInlined(foo: Foo): IO[Either[String, Unit]] `. This one doesn't complete either.

Please let me know if you need any help reproducing the problem!

```Scala

import cats.data.{EitherT, Nested}
import cats.{Applicative, Parallel}
import cats.effect.{Async, ExitCode, IO, IOApp, Ref}
import cats.syntax.all._

case class Foo(id: Int, dependencies: Vector[Int])

object Bug extends IOApp {

  val graphSize = 8 // the problem does not manifest with a graphsize less than 8!!!

  // problem generation
  val nodes: Map[Int, Foo] =
    Iterable
      .tabulate(graphSize, graphSize)({ (n, m) =>
        val nodeId = n * graphSize + m
        val node = if (n == graphSize - 1) {
          Foo(nodeId, Vector.empty) // leaf node, no dependencies
        } else {
          // a node in a middle layer, depends on all nodes of the layer below it
          Foo(nodeId, Vector.tabulate(graphSize)(i => (n + 1) * graphSize + i))
        }
        (nodeId, node)
      })
      .flatten
      .toMap
      .updated(-1, Foo(-1, Vector.tabulate(graphSize)(identity)))

  // placeholder
  def processOne[F[_]](foo: Foo)(implicit F: Async[F]): F[Unit] =
    F.blocking {
      // this is where we'd do some real work
      println(s"${foo.id}")
    }

  // processes the DAG defined by nodes, memoizing results using a Map[Int, F[Unit]],
  // where the F[Unit] values are created with F.memoize
  def processFoo[F[_]](foo: Foo)(implicit F: Async[F], P: Parallel[F]): F[Unit] = {
    def loop(cache: Ref[F, Map[Int, F[Unit]]], foo: Foo): F[Unit] = {
      val action =
        Parallel
          .parTraverse(foo.dependencies)(dependencyId => loop(cache, nodes(dependencyId))) // recursively process all dependencies
          .flatMap(processedDependencies => processOne(foo)) // now we perform some calculation on the node

      for {
        memoized <- F.memoize(action)
        toRun <- cache.modify[F[Unit]]({ cache =>
          cache.get(foo.id) match {
            case Some(value) =>
              // some other fiber has already been here, we'll use that task definition
              (cache, value)
            case None =>
              // we're the first one, we put in our memoized task, and will return that from here
              (cache.updated(foo.id, memoized), memoized)
          }
        })
        out <- toRun // now evaluate the memoized task
      } yield out
    }

    Ref[F].of(Map.empty[Int, F[Unit]]).flatMap(cache => loop(cache, foo))
  }

  // Here I tried to inline the parTraverse method from EitherT's Parallel instance
  // I think this is potentially more interesting since this eliminates one some abstractions
  // unfortunately I don't know how to reduce this any more
  def processFooWithEitherTInlined(foo: Foo): IO[Either[String, Unit]] = {
    def loop(cache: Ref[IO, Map[Int, IO[Either[String, Unit]]]], foo: Foo): IO[Either[String, Unit]] = {
      val action = {
        IO.parallelForIO.sequential(
          foo.dependencies
            .traverse[Nested[IO.Par, Either[String, *], *], Unit](dependencyId =>
              Nested(IO.parallelForIO.parallel(loop(cache, nodes(dependencyId))))
            )(
              Nested.catsDataApplicativeForNested[IO.Par, Either[String, *]](
                IO.parallelForIO.applicative, implicitly[Applicative[Either[String, *]]])
            ).value
        )
          .flatMap({
            case Left(e) => ???  // IO.pure(Left(e)), but we never produce a Left in this example
            case Right(processedDependencies) => processOne[IO](foo).map(Right(_))
          })
      }

      for {
        memoized <- action.memoize
        toRun <- cache.modify[IO[Either[String, Unit]]]({ cache =>
          cache.get(foo.id) match {
            case Some(value) =>
              // some other fiber has already been here, we'll use that task definition
              (cache, value)
            case None =>
              // we're the first one, we put in our memoized task, and will return that from here
              (cache.updated(foo.id, memoized), memoized)
          }
        })
        out <- toRun // now evaluate the memoized task
      } yield out
    }

    Ref[IO].of(Map.empty[Int, IO[Either[String, Unit]]]).flatMap(cache => loop(cache, foo))
  }

  override def run(args: List[String]): IO[ExitCode] = {
    for {
      _ <- IO.println(nodes)
      // _ <- processFoo[IO](nodes(-1)) // works
      _ <- processFoo[EitherT[IO, String, *]](nodes(-1)).value // doesn't work, goes into a busy loop
      _ <- processFooWithEitherTInlined(nodes(-1)) // same as processFoo[EitherT[IO, String, *]]
    } yield ExitCode.Success
  }
}

```

My build.sbt
```

scalaVersion := "2.13.11"

addCompilerPlugin("org.typelevel" %% "kind-projector" % "0.13.2" cross CrossVersion.full)

libraryDependencies ++= Seq("org.typelevel" %% "cats-effect" % "3.5.1")
```

**Comment by tpataky** [comment]
This one is busy looping too:
```Scala
  def processFooWithNested(foo: Foo): IO[Unit] = {
    def loop(cache: Ref[IO, Map[Int, IO[Unit]]], foo: Foo): IO[Unit] = {
      val action = {
        IO.parallelForIO.sequential(
          foo.dependencies
            .traverse[Nested[IO.Par, Id, *], Unit](dependencyId =>
              Nested[IO.Par, Id, Unit](IO.parallelForIO.parallel(loop(cache, nodes(dependencyId))))
            )
            .value
        )
          .flatMap(_ => processOne[IO](foo))
      }

      for {
        memoized <- action.memoize
        toRun <- cache.modify[IO[Unit]]({ cache =>
          cache.get(foo.id) match {
            case Some(value) =>
              // some other fiber has already been here, we'll use that task definition
              (cache, value)
            case None =>
              // we're the first one, we put in our memoized task, and will return that from here
              (cache.updated(foo.id, memoized), memoized)
          }
        })
        out <- toRun // now evaluate the memoized task
      } yield out
    }

    Ref[IO].of(Map.empty[Int, IO[Unit]]).flatMap(cache => loop(cache, foo))
  }

```

Without the `Nested` wrapping and unwrapping all is well.

**Comment by armanbilge** [comment]
Are you sure it's dead-locking? At a glance it looks to me like you are creating an enormous amount of work and it's just taking a long time to complete. When you use `EitherT` or `Nested` that's a lot more allocations which will make it even slower.

```
_ <- processFoo[IO](nodes(-1)) // works
```

For example, I don't know what "works" means for you, but for me this is also appears to be "deadlocked" (running for several minutes) and issues several warnings before finally crashing due to out-of-memory.

```
2023-09-11T17:20:33.634Z [WARNING] Your app's responsiveness to a new asynchronous event (such as a new connection, an upstream response, or a timer) was in excess of 100 milliseconds. Your CPU is probably starving. Consider increasing the granularity of your delays or adding more cedes. This may also be a sign that you are unintentionally running blocking I/O operations (such as File or InetAddress) without the blocking combinator.
Exception in thread "io-compute-blocker-13" java.lang.OutOfMemoryError: Java heap space
```

I'm not sure how the amount of work grows proportionally to the graph size, but it sounds like this is the tipping point for you :)

```
val graphSize = 8 // the problem does not manifest with a graphsize less than 8!!!
```

I already see some quadratic growth here:
```
tabulate(graphSize, graphSize)
```

**Comment by tpataky** [comment]
First of all, thank you very much for taking the time to look into this!

No, actually I'm no longer sure there is any deadlocking/busy waiting happening here. I have to admit, I did not look at the memory profile at all before you mentioned the OOM. When I initially ran into this problem I found a workaround: replacing the `Parallel.parTraverse` with `Concurrent.parTraverseN`. I've only tested larger graphs with the workaround in place. With that workaround in place, I can easily run this example with `graphSize = 100`, whether there is an `EitherT` or not. (With `Concurrent.partTraverseN`, both running time and memory consumption behaving nicely, growing at a reasonable rate. The theoretical rate is probably cubic, given that the number of edges in the graph is approx. `graphSize^3` and in this example we don't do any actual work on the nodes).

It never occurred to me that the memoization I used isn't enough to avoid the exponential explosion, and a problem defined by `graphSize = 8` (64 nodes, 512 edges) didn't seem too big. So the program must be stuck I concluded.

The best explanation I have right now is that `Parallel.parTraverse` isn't sufficiently lazy and does a whole lot of unnecessary work?

I think the issue can be closed.

**Comment by armanbilge** [comment]
> The best explanation I have right now is that `Parallel.parTraverse` isn't sufficiently lazy and does a whole lot of unnecessary work?

The difference between `parTraverse` and `parTraverseN` is that `parTraverse` immediately starts running _all_ the work in parallel. It will create a fiber for each task, which adds some memory overhead. So the bigger the collection is that you are traversing over, the more memory it will use.

Meanwhile `parTraverseN` will only run `N` tasks in parallel at a time. So no matter how big the collection is, the memory overhead will be fixed.

In general, `parTraverse` makes sense for I/O-bound work, particularly network-bound work. It is plausible to be waiting on thousands of network connections at the same time.

For compute / CPU bound work (as you have here), your parallelism is fundamentally limited by the number of cores you have on your system. So `parTraverseN` is more appropriate, so that you can keep the number of tasks running in parallel not exceeding the number of cores. In fact, when you limit work like this then Cats Effect can activate codepaths intended to maximize throughput, further reading in https://github.com/typelevel/cats-effect/issues/3445#issuecomment-1437711763.

**Comment by tpataky** [comment]
Thanks, I wasn't aware of the potentially different codepaths!

I only want to add one thing, because the differences you mentioned don't fully explain the observations.

Looking at the actual implementations in `Parallel` and `GenConcurrent` it is now clear that `parTraverse` immediately processes the traversable in order to produce the return value. On the other hand `parTraverseN` only creates an effect value that creates a semaphore and the actual traversal is suspended in a subsequent `flatMap`.

To prove that this is the really important detail I tried wrapping the `parTraverse` with a `Defer.defer`, and tried to use `parTraverseN(Int.MaxValue)`. Both of these work with huge inputs (even if they're suboptimal)!
