### ISSUE TITLE
Hotswap#get scaladoc/impl mismatch

### ISSUE THREAD

**Issue by durban** [typelevel/cats-effect#3840]
The scaladoc of `Hotswap#get` says that "_The returned resource is guaranteed to be available for the duration of the returned resource_". I don't think this is true: if the whole `Hotswap` is finalized, the "returned resource" will be finalized too (here: https://github.com/typelevel/cats-effect/blob/a6c5b155be3b729af49eb26204e101f2d527fa80/std/shared/src/main/scala/cats/effect/std/Hotswap.scala#L116).

I think either the scaladoc or the implementation should be changed. (Probably the scaladoc, although I've never used `Hotswap`.)

**Comment by armanbilge** [comment]
Thanks, that's actually a bug. We should make sure to acquire an exclusive lock before finalizing.

**Comment by durban** [comment]
Fixed by #3841.
