### ISSUE TITLE
Deferred.unsafe[IO, A] not using IODeferred

### ISSUE THREAD

**Issue by durban** [typelevel/cats-effect#3875]
This might be an unsolvable problem (and also might be not a big deal), but since there is an optimized `IODeferred`, the implementation behind `Deferred.apply[IO, A]` and `Deferred.unsafe[IO, A]` is different: `IODeferred` vs. `AsyncDeferred`. Thus, users of `Deferred.unsafe` do not benefit from the optimized implementation.

**Comment by armanbilge** [comment]
Yep, this was known at time of implementation and is not solvable ... unless we do the optimization in kernel.

Something we did discuss was deprecating the unsafe constructors precisely for this (among other) reasons.

**Comment by durban** [comment]
Okay, cool.

**Comment by armanbilge** [comment]
> Yep, this was known at time of implementation

Discussed in https://github.com/typelevel/cats-effect/issues/3271#issuecomment-1321034798.
