### ISSUE TITLE
Leaky `fromFutureCancelable`

### ISSUE THREAD

**Issue by TimWSpence** [typelevel/cats-effect#3891]
https://github.com/typelevel/cats-effect/blob/series/3.x/kernel/shared/src/main/scala/cats/effect/kernel/Async.scala#L268 has the potential to leak the future on cancelation due to the lack of `uncancelable`/`poll`

**Comment by armanbilge** [comment]
Thanks, good catch. I think `fromFuture` also needs an `uncancelable`, and we should also check the `js.Promise` variants as well ...

**Comment by TimWSpence** [comment]
> Thanks, good catch. I think `fromFuture` also needs an `uncancelable`, and we should also check the `js.Promise` variants as well ...

I have a vague of fixing things like this before by floating the `async` to the top as the `async` registration at least used to be uncancelable. I'll push a draft PR to demonstrate and try to confirm that that still works 😅

**Comment by TimWSpence** [comment]
OK pushed. Tomorrow I'll try to confirm that it actually does what I think it does 😅

**Comment by TimWSpence** [comment]
Resolved by https://github.com/typelevel/cats-effect/pull/3892
