### ISSUE TITLE
Add IO type classes

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats-effect#4]
e.g. `MonadThrow` `MonadCatch`: https://github.com/adelbertc/aiyou/tree/master/yax/core/src/main/scala/io

**Comment by wedens** [comment]
You can do the same with things with`MonadError[F, Throwable]`, can't you?

**Comment by djspiewak** [comment]
Afaict, MonadError covers all of the same cases.

**Comment by adelbertc** [comment]
I cannot disprove your claim. You win this time, Spiewak.
