### ISSUE TITLE
Improve contributor documentation

### ISSUE THREAD

**Issue by durban** [typelevel/cats-effect#4005]
It's very good that CONTRIBUTING.md and RELEASING.md exist. However, I have some ideas for little improvements. I'm happy to do this, but I need some answers:

- It is very well spelled out, that bincompatible things can go into `series/3.5.x`, everything else into `series/3.x`. Question: what is the best branch for documentation improvements?
  - What about docs in `/docs`?
  - What about scaladocs?
- It's very good that RELEASING.md exists. However, I don't think I could do a release based on that. Some specific questions:
  - There is a point "Publish the release." What does this mean? Pushing the tag to github? Something else?
  - I know there is a way to publish a "preview" release from a branch/PR (e.g., `3.6-715a974a3` or something like that). How to do this?

**Comment by armanbilge** [comment]
> * Question: what is the best branch for documentation improvements?

The first branch to which those documentation improvements are relevant. For example, docs about polling systems should go to `series/3.x`, but most other general docs improvements can go into `series/3.5.x`.

> * There is a point "Publish the release." What does this mean? Pushing the tag to github? Something else?

If you follow the steps up to this point, you will encounter this button in the GH UI :)

<img width="258" alt="Screen Shot 2024-02-19 at 12 06 06 AM" src="https://github.com/typelevel/cats-effect/assets/3119428/4e6c7629-8b7e-4f87-94b8-f66a04180a05">

> * I know there is a way to publish a "preview" release from a branch/PR (e.g., `3.6-715a974a3` or something like that). How to do this?

Run `tlRelease` locally, assuming you have all your credentials configured correctly.

https://typelevel.org/sbt-typelevel/faq.html#how-do-i-cut-a-release

**Comment by djspiewak** [comment]
I think we should still update CONTRIBUTING, since I think it hasn't been touched since we moved to CI releases.

**Comment by durban** [comment]
Fixed by #4038.
