### ISSUE TITLE
Implicit non empty parallel and documentation

### ISSUE THREAD

**Issue by CucumisSativus** [typelevel/cats-effect#404]
Hello guys!

The documentation of `IO` in the part [dedicated to parallel](https://typelevel.org/cats-effect/datatypes/io.html#parallelism) states that having implicit `ExecutionContext` in the scope is enough to be able to run `parMapN`. Unfortunately this did not work in my case, I needed to add implicit `ContextShift` by myself for code to compile.

```scala
package my.pkg
import cats.implicits._
import cats.effect._

import scala.concurrent.ExecutionContext.Implicits.global
object Main {

  def main(args: Array[String]): Unit = {
    val a = (
      function1,
      function2
    ).parMapN(AClass.apply)

    println(a.unsafeRunSync())
  }

  def function1: IO[Int] = IO.pure(7)
  def function2: IO[String] = IO.pure("zxcvbn")

  case class AClass(int: Int, string: String)

}
```

This code fails to compile with error 

```
could not find implicit value for parameter p: cats.NonEmptyParallel[cats.effect.IO,F]
```

It took me a longer while to figure out that I need to add `    implicit val contextShift = IO.contextShift(global)` to make it compile. 

Am I missing something or documentation is incomplete there?

**Comment by kubukoz** [comment]
I believe this is some ancient docs from when `Timer[IO]` was created with an implicit EC. At this moment, you should use IOApp to get the default ContextShift, or write your own. I'm convinced this is a documentation bug :)

**Comment by alexandru** [comment]
Indeed, the actual dependency is for `ContextShift` and we were building `ContextShift` implicitly by taking an `ExecutionContext` implicitly.

That no longer works, the `ContextShift` now has to be built explicitly.

**Comment by kubukoz** [comment]
I thought it was from the time before ContextShift :) but I guess it wasn't
