### ISSUE TITLE
Default constructor for `MapRef`

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#4136]
We currently have many `MapRef` implementations, based on `Ref[Map]`, sharding, `ConcurrentHashMap`, etc. We should have an `apply` constructor that chooses a reasonable default implementation, _probably_ `ConcurrentHashMap`.

**Comment by yisraelU** [comment]
@armanbilge I'd like to pick this up

**Comment by armanbilge** [comment]
@BalmungSan raised a good point that this default constructor should only require a `Concurrent` constraint. We can pattern-match for `Async` to use `ConcurrentHashMap` implementation, otherwise maybe we can fallback to the sharded `Ref[Map]` with the number of shards determined by the number of processors.

**Comment by Jasper-M** [comment]
While we're at it, a nicer API for `defaultedMapRef` would also be welcome. E.g. a constructor that directly takes a default value, or an instance method on trait `MapRef`. `MapRefOptionOps` is probably a good place for it too.

**Comment by armanbilge** [comment]
> `MapRefOptionOps` is probably a good place for it too.

Yes, I think this would be my vote. I think should be easy to chain with the constructor as well so we won't need a separate constructor?
