### ISSUE TITLE
Unexpected timeout behaviour

### ISSUE THREAD

**Issue by jacemale** [typelevel/cats-effect#420]
I've noticed a strange behaviour of the `timeoutTo` function when using it with a blocking operation. Due to how it's executing the effects (`F.race(fa, timer.sleep(duration))`), the operation on the left is executed first and if it's blocking it leads to the `sleep` not being scheduled i.e. timeout never being triggered.
However, if it's written like ` F.race(timer.sleep(duration), fa)` then the timeout is scheduled first and the `fa` will be cancelled correctly and this is the behaviour I'd expect from `timeoutTo`.
[Code in question](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Concurrent.scala#L349)

Is the assumption that effects passed into `timeoutTo` are shifted? If so, I think it should be documented somewhere.

**Comment by SystemFw** [comment]
Do you mean semantically blocking or actually blocking? If it's actually blocking, how are you canceling it?
Also, what version are you on?  `race` already shifts in `IO` in 1.0.0 (and before that as well)

**Comment by jacemale** [comment]
I've tried to reproduce it with 1.0.0 but I didn't manage to. It occured to us when we backported `timeout` into 0.10.1 and tried to use it. Here's a minimal example (with 0.10.1):
https://gist.github.com/jacemale/e19622ef29642e491b69b3ca52bc1b60

**Comment by jacemale** [comment]
Ok, thanks!
