### ISSUE TITLE
MapRef.fromSeqRefs fails on Nil

### ISSUE THREAD

**Issue by underskyer** [typelevel/cats-effect#4202]
It's possible to create instance of `MapRef` from empty list of `Ref`s, but implementation of `fromSeqRefs` gives an error `java.lang.ArithmeticException: / by zero` when attempting to use that `MapRef` instance. It probably needs to either allow `fromSeqRefs` to be called only on a non-empty list, or avoid rising `ArithmeticException` inside the `fromSeqRefs` with current signauture.

**Comment by armanbilge** [comment]
Thanks for reporting, I think we should have used `NonEmptySeq`. We can make this change and deprecate the old method. @underskyer would you be interested to make a contribution? :)

**Comment by underskyer** [comment]
@armanbilge this would be an interesting experience for me.)) What do I need to know?

**Comment by armanbilge** [comment]
@underskyer excellent, thank you! We have a contributing guide. I think this PR should be pretty straightforward, feel free to open it up as a draft so we can help out. Also if you want to join the Typelevel Discord, we can help you there as well :)

https://github.com/typelevel/cats-effect/blob/series/3.x/CONTRIBUTING.md

https://discord.gg/fVbWHp48pc

**Comment by underskyer** [comment]
@armanbilge I can't push my branch to the server. I don't have permission to do so (403 error).

**Comment by mzuehlke** [comment]
@underskyer please create a fork of the cats-effect repo and push your branch to the fork. Then create a PR using that branch.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks

**Comment by underskyer** [comment]
[Here](https://github.com/typelevel/cats-effect/pull/4208) is PR with fix of this issue.
