### ISSUE TITLE
ioConcurrentEffect: race not canceling losing fiber as expected

### ISSUE THREAD

**Issue by jbwheatley** [typelevel/cats-effect#438]
Hi,

I'm building a ConcurrentEffect that delegates `racePair` to IO's implementation. When racing two effects, if the winner produces a failure, I would like the losing fiber to cancel, and for its effect to not be carried out. However I found that that behaviour was not occuring when trying to use IO.race, or the example from the docstring for race pair that claims to do what I need:
```
* On usage the user has the option of canceling the losing task,
   * this being equivalent with plain [[race]]:
   *
   * {{{
   *   val ioA: IO[A] = ???
   *   val ioB: IO[B] = ???
   *
   *   IO.racePair(ioA, ioB).flatMap {
   *     case Left((a, fiberB)) =>
   *       fiberB.cancel.map(_ => a)
   *     case Right((fiberA, b)) =>
   *       fiberA.cancel.map(_ => b)
   *   }
   * }}} 
```

Here are two runnable examples that I would hope successfully cancel the losing fiber: 

```
object IORaceTest extends IOApp {
  def run(args: List[String]): IO[ExitCode] = {
    var p = 1
    val ioA: IO[String] = IO{
      Thread.sleep(500)
      p = 2
      println("p set to 2.")
      "A"
    }
    val ioB: IO[String] = IO{
      println("ioB completed.")
      "B"
    }

    IO.race(ioA, ioB).flatMap {
      case Left(_) => IO(ExitCode.Error)
      case Right(_) => {
        println("p is equal to " + p)
        Thread.sleep(1000)
        println("p is equal to " + p)
        IO(ExitCode.Success)
      }
    }
  }
}

object IORacePairTest extends IOApp {
  def run(args: List[String]): IO[ExitCode] = {
    var p = 1
    val ioA: IO[String] = IO{
      Thread.sleep(500)
      p = 2
      println("p set to 2.")
      "A"
    }
    val ioB: IO[String] = IO{
      println("ioB completed.")
      "B"
    }

    IO.racePair(ioA, ioB).flatMap {
      case Left((_, fiber)) => {
        fiber.cancel.map { _ =>
          ExitCode.Error
        }
      }
      case Right((fiber, _)) => {
        fiber.cancel.map { _ =>
          println("p is equal to " + p)
          Thread.sleep(1000)
          println("p is equal to " + p)
          ExitCode.Success
        }
      }
    }
  }
}
```

My hope is that in both cases `p` does not get reset to 2, but that is happening. Can anyone either offer any guidance on whether I am misusing `race` and `racePair`, or whether this is a bug?

Thanks

**Comment by SystemFw** [comment]
Not all `IO` can be canceled, and in particular we cannot cancel an `IO { ... sync side effects }` because the JVM doesn't offer tools to stop a running thread safely.
If you rewrite those `IO`s as `timer.sleep(500.millis) *> IO (...)` the loser will be cancelled.

**Comment by jbwheatley** [comment]
thank you, that looks like its fixing my tests.
