### ISSUE TITLE
Add `run` method to Resource monad transformer

### ISSUE THREAD

**Issue by schernichkin** [typelevel/cats-effect#446]
Sometimes it's handy to build resource computation with monadic syntax (for .. yield) and run it latter. Running resource computation is basically `.use(_.pure[F])`. It also similar to Haskell's implementation http://hackage.haskell.org/package/resource-simple-0.2/docs/Control-Monad-Resource.html#g:2

**Comment by SystemFw** [comment]
It's not very clear what you mean by this.

> Sometimes it's handy to build resource computation with monadic syntax (for .. yield) and run it latter. 

That's already the case: you build it with monadic combinators, then you `use`.

> Running resource computation is basically .use(_.pure[F])

Note that in 99% of cases, this is a bug. If you have `Resource[F, A]` and you `.run(_.pure[F])`, you get an `F[A]` _but_ all the finalisers have already run. So, practically speaking, you do 
```scala
(thing :Resource[F, File]).use(_.pure[F]).flatMap(f => IO(readFile(f))
```
you will get an exception because the file is already closed

**Comment by SystemFw** [comment]
Also note that `Resource` in cats-effect is the equivalent of Haskell's `Managed/Codensity`, and _not_ ResourceT

**Comment by schernichkin** [comment]
> Note that in 99% of cases, this is a bug.

I must disagree. To call `use` a `Bracket` required at the call site. So, one may want to stay inside Resource monad a bit longer for composability reasons. Let me show how more complex program may looks like:
```scala
trait ConnectionPool[F[_]] { 
   def connect(connectionString: String): Resource[F, Connection[F]] 
}

// Connection is a wrapper for a closeable resource, such as java.sql.Connection but 
// it does not implement ICloseable, because we want to rely on Resource monad transformer.
trait Connection[F[_]] { 
   def query(sql: String): Resource[F, ResultSet[F]]
}

// Same story with the ResultSet.
trait ResultSet[F[_]] {
   def getValue(columnIndex: Int): String
   def next: F[Boolean]
}

class Table(read-only data structure to represent in-memory table + accessors)

// This is small adapter which creates connection, exec statement and load results into in-memory structure.
// Note that it abstracted over target monad and does not require `Bracket`. 
class EasyQuery[F[_]: Monad](connectionPool: ConnectionPool[F]) { 
   def easyQuery(sql: String): Resource[F, Table] = for {
     connection <- connectionPool.connect(..)
     resultSet <- connection.query(sql)
     table <- Resource.liftF { some tailRecM stuff to build up in-memory Table from the ResultSet[F] }
   }  
}

// Concrete implementation. Here we have IO and hence Bracket. Finally, we can escape Resource monad.
object Main { 
   def findPepe(): IO[Pepe] = for {
      table <- easyQuery("...").use(_.pure[IO])
   } yield table.contains(Pepe)
}
```
>I think it encourages a buggy behaviour and should be avoided

Nothing can't stop user from calling _.pure[IO] :) Moreover, Resource is a monad, which encourages transformation of underlying value, so we can never be sure if A in Resource[F, A] is indeed closeable resource or not. To prevent closeable resources from escaping resource monad it should be indexed with type and runner should be similar to `runResourceT :: (forall s. Resource m s a) -> m a`

**Comment by schernichkin** [comment]
Ok, I see your concern. As for me, propagating `Bracket` and escaping `Resource` asap vs keeping `Resource` - are just two different approaches, each have its own advantages. But keeping API small and consistent vs making it diverse and possibly misleading is purely design choice. So I would stick design decisions taken by the library creators and close this issue if no objections.
