### ISSUE TITLE
Interoperability packages

### ISSUE THREAD

**Issue by sideeffffect** [typelevel/cats-effect#455]
in light of https://github.com/typelevel/cats-effect/pull/453, https://github.com/typelevel/cats-effect/issues/199 and probably other similar issues, I suggest to introduce at least 2 new `cats-effect` packages:
 * `cats-effect-interop-scalafuture`: for functionality to turn `scala.concurrent.Future` into an `Async`
 * `cats-effect-interop-javaconcurrent`: for functionality to turn `java.util.concurrent.Future` and `java.util.concurrent.CompletionStage` into an `Async`

Motivation:
turning foreign objects to `cats-effect` natives is a commonly requested and useful feature (like a `fromFuture` method which turns `scala.concurrent.Future` into an `Async`)
however, such helper methods would clutter the core `cats-effect`
therefore introducing new small interoperability package seems like a principled solution

**Comment by SystemFw** [comment]
Agree with Ross an all 3 points tbh

**Comment by sideeffffect** [comment]
hmm, ok, `scala.concurrent.Future` comes with Scala standard library and `java.util.concurrent._` with JRE
but what's the story for interoperability with other *Future-like* objects? (Twitter Future or whatever else is out there)
that stuff probably shouldn't all go to `monix-catnap` (let alone `cats-effect-core`)
aren't tiny independent `interop` packages a better solution?
