### ISSUE TITLE
Add `LiftIO.liftK`

### ISSUE THREAD

**Issue by Daenyth** [typelevel/cats-effect#465]
`object LiftIO` could have this for convenience:
```scala
def liftK[F[_]: LiftIO]: IO ~> F = λ[IO ~> F](_.to[F])
```

**Comment by Daenyth** [comment]
There could also be an `Effect.liftK` for `F ~> IO`

**Comment by Daenyth** [comment]
I could PR this in since it seems like there's support. Are there any kind of unit tests that are useful here? I'm not really sure what is important.

**Comment by nigredo-tori** [comment]
Someone should probably close this.
