### ISSUE TITLE
Proposal: Add `useKleisli` to Resource

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#468]
Given the existing:

```scala
def use[B](f: A => F[B])(implicit F: Bracket[F, Throwable]): F[B]
```

How about we add:

```scala
def useKleisli[B](f: Kleisli[F, A, B])(implicit F: Bracket[F, Throwable]): F[B]
```

While it's a minor syntactic improvement (usage goes from `res.use(foo.run)` to `res.useKleisli(foo)`), maybe it's worth having. WDYT?

**Comment by alexandru** [comment]
I think it is introducing a new verb and adding words to the vocabulary is problematic, so it has to be worth it. In this case, I don't think it is.

**Comment by kubukoz** [comment]
Fair enough :)
