### ISSUE TITLE
Split project in sub-projects

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats-effect#480]
For Cats-Effect 2.0 we need to split the project in about 3 sub-projects:

- `cats-effect-core`: the type classes
- `cats-effect-concurrent`: the data types described in `cats.effect.concurrent`
- `cats-effect-io`: the `cats.effect.IO` implementation

Note the work for this split is on-going, I'm already working on it.

Suggestions welcome.

**Comment by alexandru** [comment]
We might not be able to have type classes in a separate project from `cats.effect.concurrent`, because we depend on `Ref` at least for various instances, e.g. in `Sync`.

**Comment by jdegoes** [comment]
I think type classes for Ref + Deferred belong in core, while the data types themselves (“default implementations”) belong in concurrent, so Monix and ZIO can use their own implementations.

I’d also tweak the names to minimize redundancy:

 - cats-effect
 - cats-concurrent
 - cats-io

(That cats-concurrent and cats-io provide instances for cats-effect will come as a surprise to exactly no one.)
