### ISSUE TITLE
Add Ref#inspect

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#486]
Like get + map in one call (should be atomic as well).

**Comment by alexandru** [comment]
How would you express it in terms of available ops?

**Comment by kubukoz** [comment]
`def inspect[B](f: A => B): F[B] = get.map(f)`

I realise it's not even shorter than the implementation, but we have such methods on State and that doesn't seem to be a problem there :P

**Comment by djspiewak** [comment]
I'm a little skeptical of syntax like this, just from a minimalism standpoint, but I'm open to being convinced!
