### ISSUE TITLE
Proposal: Discard return value

### ISSUE THREAD

**Issue by ratoshniuk** [typelevel/cats-effect#493]
There are cases where we need to discard T output for IO[T]
It would be nice to have follow one:

```scala
val effect : IO[T] = ???
val discarded : IO[Unit] = effect.void
```

**Comment by LukaJCB** [comment]
This function exists as a generic function for any `Functor`: https://github.com/typelevel/cats/blob/02462464f44550d248ea76f153625aeef4a26e3c/core/src/main/scala/cats/Functor.scala#L85

Though of course this requires importing the syntax, so we could probably add it directly onto `IO` as well, like we do already for things like `map` etc.

**Comment by alexandru** [comment]
> Though of course this requires importing the syntax, so we could probably add it directly onto IO as well, like we do already for things like map etc.

Not sure if it's a good idea to add everything on top of `IO`.

Note that `map` is encoded in IO's internal ADT as an optimization and it's a pretty fundamental operation, whereas something like `void` is just a shortcut.

**Comment by ratoshniuk** [comment]
Not sure that it's okay to write down follow code each time we want to discard output

```
pgConnector.execute(someQuery).map(_ => ())
```

**Comment by ratoshniuk** [comment]
Or we could do follow: 

```scala
implicitly[Functor[F]].void(effect))
```

but this construction could be simplified in some way...

**Comment by mpilquist** [comment]
Just to elaborate, If you add `import cats.implicits._`, you can write `pgConnector.execute(someQuery).void` now.

**Comment by ratoshniuk** [comment]
@mpilquist got it. thanks
