### ISSUE TITLE
Proposal: Add `apply` function to Sync as an alias for `delay`

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#517]
Back in the eons of the mist… I used the `apply` function on the `IO` object to signify "capture of a synchronous effect" because this case is, in my experience, far and away the most common thing. This API design had the effect of taking the old idiom of `Task.delay(` and reducing it it to `IO(`, a reduction of 8 characters on something done almost incessantly.

What I *didn't* anticipate is that everyone would just use the typeclasses and almost never `IO` directly! :-D So in practice, we've replaced `Task.delay` with `Sync[F].delay`, which is actually *worse* from a syntactic standpoint. Yes, I'm picking nits.

I'd like to toss out there as a minor proposal simply adding `apply` to `Sync` as an alias for `delay`. This would mirror `IO` more closely and simplify a lot of common cases. For example:

```scala
def putStrLn[F[_]](line: String)(implicit F: Sync[F]): F[Unit] =
  F.delay(println(line))

// becomes

def putStrLn[F[_]](line: String)(implicit F: Sync[F]): F[Unit] =
  F(println(line))
```

Unfortunately, there is a bit of a gotcha to it which prevents it from being *quite* as ubiquitous as we might want:

```scala
def putStrLn[F[_]](line: String)(implicit F: Sync[F]): F[Unit] =
  Sync[F](println(line)) // doesn't work!
```

This won't work since the parentheses are actually interpreted here as being the parameters of the `Sync` *object* `apply` function, which is to say, a value of type `Sync[F]`. There's also the (remote) possibility of a user accidentally doing something really awful if the body of their effect is coercible to `Sync[F]`.

So anyway, this is small potatoes, and I can see reasons not to do it, but it's been bugging me for a while so I thought I'd throw it out there.

**Comment by alexandru** [comment]
Having an alias would be cool, but `apply` is pretty ubiquitous and can't we have conflicts with other definitions of `apply`?

I guess the question is, why isn't `apply` an alias of `pure` in `Apply` / `Applicative`?

**Comment by alexandru** [comment]
Well, if we add it as an extension method, it wouldn't hurt so 👍

**Comment by ChristopherDavenport** [comment]
I think I fall against this `F(_)` doesn't really make it clear what is happening from a readability perspective, just shortens lines of code. Actually invoking the method makes use clear. I'm more in favor of fully removing `IO.apply` in favor of needing to invoke that via `IO.delay` as well.

**Comment by djspiewak** [comment]
@alexandru I don't think there are other conflicts with `apply` in this case, aside from the aforementioned implicit parameters issue. As for why it doesn't exist in `Apply`/`Applicative`, I guess it really could, though pointing isn't the primary purpose of those typeclasses. The *primary* reason that `Sync` exists is for `delay`, and it's what users are going to do with it easily 99 out of 100 times.

@ChristopherDavenport Oh I'm definitely strongly opposed to removing `IO.apply`. :-) The concision isn't to be undervalued, IMO. The fact that you can take a curly-brace block and "add safe" (to a degree) by just adding two characters (`IO`) is actually really really nice. It subtly lowers the imposition, particularly when retrofitting it onto existing code paths.

As for `F.apply`, I think there's more argument here that perhaps it obfuscates more than it helps, given that `IO` is very recognizable and distinctive syntax in its own right, but `F` is… not. `Sync[F]` is definitely more noticeable, but then the syntax doesn't work.

**Comment by TomTriple** [comment]
Personally I'm not sure about adding `apply` to `Applicative` or `Apply' but for `Sync` I like the idea – actually I thought about _exactly_ that a few days ago. I added a PR with the alias added in case that's valueable to all.
