### ISSUE TITLE
Meta: Change copyright to "Typelevel"

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#521]
So the reason for this mostly comes down to US copyright law. The problem is that "The Typelevel Cats-effect Project Developers" is not a legal entity anywhere. In the event of a copyright claim against the source code, we as project maintainers would be compelled to formally notify over 50% of the individuals who have contributed any code. This bit Mozilla *hard* a few years ago.

The general solution to this, from a governance standpoint, is for everyone to agree to assign copyright to an actual *legally established* entity. That can be a single individual (e.g. everyone could assign copyright to "Daniel Spiewak" if that was less controversial), or more soundly it can be an LLC (e.g. "Typelevel"). This covers considerably more ground on a legal basis. Right now, the copyright declaration is essentially meaningless and exposes us all to a lot of liability, in theory.

Reassigning copyright properly is going to require a bit of paper-trail creation which I'm happy to do, but I wanted to put it out here first to see what people thought.

**Comment by mpilquist** [comment]
I am in favor of this. If done, would we need a CLA going forward or would assignment of copyright in CONTRIBUTING.md be enough?

**Comment by djspiewak** [comment]
Well, I was a bit imprecise. It's not actually "assignment of copyright" which we can't do since none of us are actively paid by Typelevel. It's actually an assignment of indefinite and unrestricted license in exchange for indemnification. A CLA is the legally prescribed way of doing this, though most projects operate under a shrink wrap agreement (also implied by ASLv2), basically making agreement to the CLA implicit in the act of opening a pull request.

The trickier thing is going back and fixing it all *now*, since we would need to get explicit documentation from everyone who has written code that this is okay.

**Comment by alexandru** [comment]
I would be fine to change the copyright header to the Typelevel organization, if such an entity exists.

I might not be fine with a copyright assignment, because that means the organization holding the copyright has the right to change the license without getting permission from the authors. That's not how open source is supposed to work and it opens the possibility for a company to close source the code in the future, as it happened with several popular open source projects.

**Comment by alexandru** [comment]
In other words, there has to be the notion of a "collective copyright" and we have to use it.

**Comment by djspiewak** [comment]
@alexandru I think the ASLv2 copyright license assignment clause prevents that possible loophole, but I'll do a more careful reading and get back to you.

**Comment by alexandru** [comment]
@djspiewak if contributors don't have to sign a copyright assignment, like what Lightbend and other companies are doing, I think we are cool.

Because you can't change the license for a piece of code if you're not the copyright holder, or without written consent, for everything.

**Comment by djspiewak** [comment]
Yeah the only way to actually sort this out retroactively is for someone to email everyone. It's just that, without someone emailing everyone, our licensing is on essentially legally-nonexistent grounds.

**Comment by djspiewak** [comment]
Okay, current thought on how to do this… (please, someone step in and correct me if you think this is a bad idea).

Based on [the contributors metrics](https://github.com/typelevel/cats-effect/graphs/contributors), the following people have contributed more than 1% of the lines of code within the project, which `cloc` defines to be a value of roughly 440 lines.

- [*] @alexandru 
- [*] @djspiewak 
- [ ] @rossabaker 
- [ ] @SystemFw 
- [ ] @Avasil 
- [ ] @oleg-py 
- [ ] @mpilquist 
- [ ] @gvolpe 
- [ ] @pchlupacek 
- [ ] @lrodero
- [ ] @sideeffffect 

I would like to have an affirmative 👍 in the form of a comment from all of the above before taking any step forward on this. Just to be clear about what we're proposing, this is just to change the copyright header from "The Typelevel Cats-effect Project Developers" to simply "Typelevel", as would be uniform with Cats and several other projects. If any of the above (or anyone else!!) has any objections to this, please weigh in below!

BTW, if you're not included in the above list, it's not because I don't think you're important. <3 you all! It's just that I set the completely arbitrary cut off at 1% to avoid including *everyone* who has ever contributed code to this project.

**Comment by rossabaker** [comment]
I affirm the copyright move to "Typelevel":

**Comment by gvolpe** [comment]
I'm fine with it as long as the point made by @alexandru holds.

**Comment by oleg-py** [comment]
👍

**Comment by SystemFw** [comment]
:+1:

**Comment by Avasil** [comment]
:+1:

**Comment by alexandru** [comment]
👍

**Comment by djspiewak** [comment]
Still waiting for @pchlupacek
