### ISSUE TITLE
IO#unsafeRunSync erroneously fails on JavaScript

### ISSUE THREAD

**Issue by mpilquist** [typelevel/cats-effect#529]
Consider this program:

```scala
def safe: Unit = IO.unit.guarantee(IO.unit).unsafeRunSync
def broken = IO.unit.bracket(_ => IO(safe))(_ => IO.unit) 
```

Calling `safe` on Scala.js correctly results in a `Unit` value. However, calling `safe` from within  another nested `IO` program (e.g. `broken` here), results in the following error:

```
[info]   java.lang.UnsupportedOperationException: cannot synchronously await result on JavaScript; use runAsync or unsafeRunAsync
[info]   at java.lang.UnsupportedOperationException.fillInStackTrace(/Users/mpilquist/Development/oss/fs2/core/js/target/scala-2.12/fs2-core-test-fastopt.js:76968:14)
[info]   at java.lang.UnsupportedOperationException.<init>(/Users/mpilquist/Development/oss/fs2/core/js/target/scala-2.12/fs2-core-test-fastopt.js:77090:10)
[info]   at java.lang.UnsupportedOperationException.<init>(/Users/mpilquist/Development/oss/fs2/core/js/target/scala-2.12/fs2-core-test-fastopt.js:132545:58)
[info]   at cats.effect.internals.IOPlatform$.unsafeResync(/Users/mpilquist/Development/oss/fs2/core/js/target/scala-2.12/fs2-core-test-fastopt.js:7111:53)
[info]   at cats.effect.IO$Async.unsafeRunTimed(/Users/mpilquist/Development/oss/fs2/core/js/target/scala-2.12/fs2-core-test-fastopt.js:47886:52)
[info]   at cats.effect.IO$Async.unsafeRunSync(/Users/mpilquist/Development/oss/fs2/core/js/target/scala-2.12/fs2-core-test-fastopt.js:47843:15)
[info]   at fs2.StreamSpec.safe$1(/Users/mpilquist/Development/oss/fs2/core/js/target/scala-2.12/fs2-core-test-fastopt.js:227516:106)
[info]   at {anonymous}()(/Users/mpilquist/Development/oss/fs2/core/js/target/scala-2.12/fs2-core-test-fastopt.js:208627:23)
[info]   at scala.scalajs.runtime.AnonFunction0.apply(/Users/mpilquist/Development/oss/fs2/core/js/target/scala-2.12/fs2-core-test-fastopt.js:97704:23)
[info]   at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(/Users/mpilquist/Development/oss/fs2/core/js/target/scala-2.12/fs2-core-test-fastopt.js:7376:25)
```

I believe the cause is related to the internal trampoline used when evaluating the outer program.

**Comment by djspiewak** [comment]
@mpilquist I believe this is fixed in 1.3.1 and 2.0.0-M2 (by #533). Can you verify?

**Comment by mpilquist** [comment]
Just ran in to this issue again with 2.0.0 final. https://github.com/functional-streams-for-scala/fs2/pull/1619#issuecomment-531754405

**Comment by alexandru** [comment]
What we are doing is to execute the `IO` with a callback that sets an internal variable on completion. However in case that internal variable is still `null`, we assume that an actual async boundary happened:

https://github.com/typelevel/cats-effect/blob/master/core/js/src/main/scala/cats/effect/internals/IOPlatform.scala#L32

The case in which this doesn't work is when this is executed in the context of our internal trampoline:

```scala
TrampolineExecutionContext.immediate.execute(new Runnable {
  def run() = {
    IO.unit.guarantee(IO.unit).unsafeRunSync
  }
})
```

Note that I haven't tested it, but off the top of my head is the only reasonable explanation for why the above doesn't work.

And ... we can't fix it. In Monix I'm not even allowing synchronous execution on top of JavaScript for `Task`. If this is about `SyncIO`, then unfortunately we'll have to rebuild `SyncIO`.

**Comment by alexandru** [comment]
So basically the implementation uses a trick, that doesn't work in case:

1. `unsafeRunSync` gets executed in the context of our internal `TrampolineExecutionContext` and
2. any internal async boundaries happen (e.g. `IO.Async` states) and in case of `bracket` we do have such boundaries

I've also looked at the fs2 issue. Note that when you say ...

> The call to s.toList calls unsafeRunSync on an internal IO value that's guaranteed to be synchronous. 

Unfortunately there's no such guarantee that `IO` is synchronous, because internal async boundaries do get generated (e.g. `IO.Async`), we have no idea in the interpreter if they'll actually fork or not and it's just that in case of `bracket` we choose to execute them on top of a trampoline, but this is still async execution and as you can see, we've got some gotchas related to our trick.

The solution is to ... never call `unsafeRunSync` on top of JavaScript and to rebuild `SyncIO` with an implementation that's not based on `IO`.

**Comment by mpilquist** [comment]
Yes it's a `SyncIO` issue -- FS2 is using `IO` internally in this case but would use `SyncIO` instead if this was supported. That is, the use of `IO` in this case is entirely an implementation detail of the way FS2 evaluates "pure" (aka non-effectful) streams.

**Comment by LukaJCB** [comment]
I feel like we could easily fix this for `SyncIO` by providing a simpler `bracketCase` implementation, instead of delegating to `IO`. Since `SyncIO` can't be cancelled `bracketCase` can easily be implemented with just `attempt`, no?

**Comment by alexandru** [comment]
> I feel like we could easily fix this for SyncIO by providing a simpler bracketCase implementation, instead of delegating to IO. Since SyncIO can't be cancelled bracketCase can easily be implemented with just attempt, no?

Yes, this might work our fine.
