### ISSUE TITLE
ContextShift not shifting after a CompletableFuture to IO conversion

### ISSUE THREAD

**Issue by prascuna** [typelevel/cats-effect#582]
Hi there,
I'm experiencing a strange behaviour in the following sample code. Apologies if it's something silly, but I'm still new to cats-effect and the code is a bit long-winded.

I have have two services. A `ScalaService` that returns an`IO` and a `JavaService` that returns a java`CompletableFuture` and I'd like to compose their results in a for-comprehension.
I also have a conversion from `CompletableFuture` to `IO`.

What'd I'd like to achieve is that both `ScalaService` an `JavaService` run inside their own ThreadPool and that any other step inside the for-comprehension is executed in the main one.

Here's the sample code:

```scala
package example

import java.util.concurrent._
import java.util.function.{BiFunction, Supplier}

import cats.effect.{Concurrent, ContextShift, ExitCode, IO, IOApp}
import example.Implicits._

import scala.concurrent.{ExecutionContext, ExecutionContextExecutor}
import scala.language.higherKinds

object TestContextShiftApp extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = {
    val res = for {
      _ <- IO.delay(debug("XXX - one"))
      _ <- ScalaService.doSomething
      _ <- IO.delay(debug("XXX - two"))
      _ <- Concurrent.delayCompletableFuture[IO, Unit](JavaService.doSomething)
      _ <- IO.delay(debug("XXX - three"))
      _ <- Concurrent.delayCompletableFuture[IO, Unit](
        JavaService.doSomethingWithBody { () =>
          debug("Body")
        }
      )
      _ <- IO.delay(debug("XXX - four"))
    } yield ()

    res.map(_ => ExitCode.Success)
  }

}

object ScalaService {
  private val executionContext: ExecutionContextExecutor =
    ExecutionContext.fromExecutor(
      Executors.newFixedThreadPool(3, new ThreadFactory {
        override def newThread(r: Runnable): Thread = {
          val t = new Thread(r)
          t.setName(s"scala-service-${t.getId}")
          t
        }
      })
    )

  def doSomething(implicit contextShift: ContextShift[IO]): IO[Unit] =
    contextShift.evalOn(executionContext) {
      IO.delay(debug("ScalaService.doSomething"))
    }
}

object JavaService {
  private val executorService =
    Executors.newFixedThreadPool(3, new ThreadFactory {
      override def newThread(r: Runnable): Thread = {
        val t = new Thread(r)
        t.setName(s"java-service-${t.getId}")
        t
      }
    })

  def doSomething: CompletableFuture[Unit] = {
    CompletableFuture.supplyAsync(new Supplier[Unit] {
      override def get(): Unit = debug("JavaService.doSomething")
    }, executorService)
  }
  def doSomethingWithBody(body: () => Unit): CompletableFuture[Unit] = {
    CompletableFuture.supplyAsync(new Supplier[Unit] {
      override def get(): Unit = {
        debug("JavaService.doSomethingWithBody")
        body()
      }
    }, executorService)
  }
}

object Implicits {
  def debug(message: String) =
    println(s"[${Thread.currentThread().getName}] $message")

  implicit class ConcurrentOps(private val concurrent: Concurrent.type)
      extends AnyVal {

    def delayCompletableFuture[F[_]: Concurrent, T](
      mkCompletableFuture: => CompletableFuture[T]
    ): F[T] = {
      debug("delayCompletableFuture: CompletableFuture => F[T]")
      Concurrent[F]
        .cancelable[T] { cb =>
          val completableFuture = mkCompletableFuture
          debug("delayCompletableFuture: Handling callback")
          completableFuture.handle[Unit](new BiFunction[T, Throwable, Unit] {
            override def apply(result: T, err: Throwable): Unit = {
              debug("delayCompletableFuture: apply")
              err match {
                case null =>
                  cb(Right(result))
                case _: CancellationException =>
                  ()
                case ex: CompletionException if ex.getCause ne null =>
                  cb(Left(ex.getCause))
                case ex =>
                  cb(Left(ex))
              }
            }
          })

          Concurrent[F].delay(completableFuture.cancel(true))
        }
    }
  }
}
```

Here there are two outputs of two different executions: Notice the last two lines: whenever JavaService has a closure, the next step of the for-comprehension randomly gets stuck on the `java-service` ThreadPool

```
[ioapp-compute-0] XXX - one
[scala-service-12] ScalaService.doSomething
[ioapp-compute-1] XXX - two
[ioapp-compute-1] delayCompletableFuture: CompletableFuture => F[T]
[ioapp-compute-1] delayCompletableFuture: Handling callback
[java-service-14] JavaService.doSomething
[ioapp-compute-1] delayCompletableFuture: apply
[ioapp-compute-1] XXX - three
[ioapp-compute-1] delayCompletableFuture: CompletableFuture => F[T]
[ioapp-compute-1] delayCompletableFuture: Handling callback
[java-service-15] JavaService.doSomethingWithBody
[java-service-15] Body
[ioapp-compute-1] delayCompletableFuture: apply
[ioapp-compute-1] XXX - four
```
```
[ioapp-compute-0] XXX - one
[scala-service-12] ScalaService.doSomething
[ioapp-compute-1] XXX - two
[ioapp-compute-1] delayCompletableFuture: CompletableFuture => F[T]
[ioapp-compute-1] delayCompletableFuture: Handling callback
[java-service-14] JavaService.doSomething
[ioapp-compute-1] delayCompletableFuture: apply
[ioapp-compute-1] XXX - three
[ioapp-compute-1] delayCompletableFuture: CompletableFuture => F[T]
[ioapp-compute-1] delayCompletableFuture: Handling callback
[java-service-15] JavaService.doSomethingWithBody
[java-service-15] Body
[java-service-15] delayCompletableFuture: apply
[java-service-15] XXX - four
```

Please note that it's only `JavaService.doSomethingWithBody` that gives me troubles, the other `doSomething` method always returns to the main ThreadPool after the execution.

Of course, if I force an `IO.shift` after invoking `JavaService.doSomethingWithBody`, that achieves my result, but I'd like to understand why is this happening, or better, why it's not happening for all methods of `JavaService`?
Briefly looking at IO's flatMap implementation I had the feeling that everything should be happening on the same thread, but if that's correct, why is the threadpool always changing after `JavaService.doSomthing`?

Many thanks

Full code here:
https://github.com/prascuna/test-cats-effect/blob/master/src/main/scala/example/TestContextShiftApp.scala

**Comment by djspiewak** [comment]
Without parsing the code in too much detail… Anything which uses `async` with `cats.effect.IO` will maintain the *continuation* of the computation on the caller's thread pool. A simpler example:

```scala
for {
  _ <- IO.async[Unit] { cb =>
    new Thread(() => cb(Right(()))).start()
  }
  _ <- IO(println(Thread.currentThread().getName()))
} yield ()
```

The `println` will print out the name of the new thread created inside that `async` block. This is caused because `async` does not auto-shift, so everything just remains on whatever pool it lands on. This was an intentional design decision, but a poor one, and it will be corrected in Cats Effect 3.0.

For now, the best solution is to force an `IO.shift` after every `async` boundary.

**Comment by prascuna** [comment]
Thanks for your prompt reply!
Yes, that's exactly my question: why is autoshifting when I invoke the first `CompletableFuture` to `IO` conversion?
```scala
_ <- Concurrent.delayCompletableFuture[IO, Unit](JavaService.doSomething)
```
and it randomly does when I invoke the second?
```scala
_ <- Concurrent.delayCompletableFuture[IO, Unit](
        JavaService.doSomethingWithBody { () =>
          debug("Body")
        }
      )
```
I would expect the same behaviour from the two, meaning that `debug("XXX - three")` should have been executed on the same thread of `JavaService.doSomething`

Is somehow that conversion wrong and messing with the ThreadPool?

**Comment by djspiewak** [comment]
My guess is that something is happening in `doSomething` which is causing it to evaluate immediately, on the calling thread. I'm really not sure. It depends on how things get scheduled and I don't know much about `CompletableFuture`. Certainly in principle, `doSomething` could shift off your desired pool, meaning that a defensive `IO.shift` is required in both cases.

**Comment by kubukoz** [comment]
@prascuna are you OK with closing this?
