### ISSUE TITLE
tut it up

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats-effect#60]
Has there been any thought regarding tut-style documentation?

At work I've had people ask me about the difference between `scalaz.concurrent.Task` and `scala.concurrent.Future` many times. I've written a tut-based doc that talks a bit about how `Task` is referentially transparent while `Future` is not and what the implications of that are. I'd be happy to adapt it to talk about `IO` instead. Would you be interested in such a doc in this project?

**Comment by djspiewak** [comment]
This would be awesome, Cody.  @tpolecat had some work done in this direction on #6, but I'm not sure what the current status of it is.  I'd love to get real tut docs, I just haven't had time (or expertise) to address the need.

**Comment by tpolecat** [comment]
I haven't had time to work on it either but @ceedubs if you want to fork my PR please feel free to do so. The machinery is set up but there's no content yet,

**Comment by ceedubs** [comment]
Oops I should have checked PRs and not just issues before creating this. I'll close this out and try to run with @tpolecat's work. No promises, but I'll give it a try.
