### ISSUE TITLE
scala 2.13 release

### ISSUE THREAD

**Issue by ThStock** [typelevel/cats-effect#602]
Can you provide a release version for scala 2.13?

**Comment by aeons** [comment]
Only the 2.0 preview releases are available for 2.13 final, since cats is only available for 2.13 in preview releases.

https://mvnrepository.com/artifact/org.typelevel/cats-effect

**Comment by rossabaker** [comment]
I'm publishing a release candidate right now, and we'll have 2.0.0 out ASAP after cats-2.0.0 is released.
