### ISSUE TITLE
Make IOApp#main final?

### ISSUE THREAD

**Issue by kevinmeredith** [typelevel/cats-effect#604]
What's the reason that [IOApp#main](https://github.com/typelevel/cats-effect/blob/v1.4.0/core/shared/src/main/scala/cats/effect/IOApp.scala#L66) isn't `final`? My incomplete understanding is that users of `IOApp` are expected to override `def run(args: List[String]): IO[ExitCode]`, but then `main` is an implementation detail, i.e. not to be modified by the `extend`-ing class/objejct.

```scala
@ import $ivy.`org.typelevel::cats-effect:1.4.0` 
https://repo1.maven.org/maven2/org/typelevel/cats-effect_2.12/1.4.0/cats-effect_2.12-1.4.0-sources.jar
  100.0% [##########] 131.4 KiB (1.3 MiB / s)
import $ivy.$                                 

@ class BadMain extends cats.effect.IOApp { 
    override def run(xs: List[String]): cats.effect.IO[cats.effect.ExitCode] = ???
    override def main(xs: Array[String]): Unit = ???
  } 
defined class BadMain
```

Should `cats.effect.IOApp#main` be `final` to avoid this potential issue?

**Comment by djspiewak** [comment]
Yes. It should be. PR! 😃

**Comment by alexandru** [comment]
Note that making `main` final will break binary compatibility.

**Comment by kevinmeredith** [comment]
I'm going to close this per @alexandru's explanation, https://github.com/typelevel/cats-effect/pull/605#issuecomment-522124710.
