### ISSUE TITLE
Resource#map shouldn't take an Applicative

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#610]
So this is just like, really surprisingly weird. `Resource#flatMap` is unconstrained, but `Resource#map` is constrained by `Applicative`. The constraint is specifically to pick up the `pure` function on the `F[_]`, so it's understandable, but also bizarre. Intuitively, `Resource` is a free `Bracket`, but it's not quite free *enough*.

The solution is to add a case to the algebra and interpret into the resulting `Bracket` in `use`, the same as we do for everything else. This can't be done in a binary compatible way though, so we've missed the train for CE2, but it'll be quite nice once we can do it.

**Comment by SystemFw** [comment]
I noticed this during the cancelable eval PR, but bincompat was the blocker, we should definitely remove that bound.

**Comment by alexandru** [comment]
Btw, I think we would have encoded it in the algebra, from what I remember what happened is that `map` was added later, because initially people were expected to `import cats.implicits._`, but then we realized that doing that just for `map` sucks.

And indeed the algebra is public, because we want to write custom interpreters if we need them.

**Comment by kubukoz** [comment]
Aren't custom interpreters a thing of the past since `allocated`? Are there other valid use cases?

**Comment by djspiewak** [comment]
> Aren't custom interpreters a thing of the past since allocated? Are there other valid use cases?

Apparently `Stream.resource` interprets the algebra. :-/

**Comment by mpilquist** [comment]
Yeah, https://github.com/functional-streams-for-scala/fs2/blob/7763ee3d0eba5eb932617e183e0fc189b203318c/core/shared/src/main/scala/fs2/Stream.scala#L3448-L3453
