### ISSUE TITLE
Setup Scalafmt

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats-effect#623]

**Comment by iRevive** [comment]
Hi all,

I took scalafmt configuration from the cats project.

<details>
<summary>.scalafmt.conf</summary>

```
version = 2.0.1
align.openParenCallSite = true
align.openParenDefnSite = true
maxColumn = 120
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
danglingParentheses = true
rewrite.rules = [AvoidInfix, SortImports, RedundantBraces, RedundantParens, SortModifiers]
docstrings = JavaDoc
```
</details>

There are two major cases that do not match to the scalafmt rules:
1) ScalaDoc-like comments.
I would say that almost half of all comments are written in ScalaDoc style.

2) Modifiers order.
The project widely uses `private[effect] final class`, while scalafmt enforces `final private[effect] class`.

Should I change the configuration or we can move forward with the original one?
