### ISSUE TITLE
Add sibling of `start` that returns a Resource

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#628]
I think we can all agree fibers are hard to work with and probably what users shouldn't use 90% of the time. There are plenty of valid usecases at this moment though, for example starting an IO in background and cancelling it in case the application wraps up, which can be implemented with something like `Resource(fa.start.fproduct(_.cancel))`.

We should support that usecase and others and expose a method that'd look roughly like this:

```
def startResource: Resource[F, Fiber[A]]
//or
//the nested F is `join` without access to the finalizer
def startResource: Resource[F, F[A]]
```

in Concurrent or (as syntax in ConcurrentOps && as method on IO).

Name suggestions welcome - I'd go for `background` or `startResource`. Once we've figured out the appropriate shape and name I can provide an implementation.

Gitter microdiscussions:

- https://gitter.im/typelevel/cats-effect?at=5d755e9a460a6f5a16eb7751
- https://gitter.im/typelevel/cats-effect?at=5d762ae43b1e5e5df17c8aa0
- https://gitter.im/typelevel/cats-effect?at=5d765279d5c7bd5794608c5d

**Comment by djspiewak** [comment]
👍 for the second variant

**Comment by kubukoz** [comment]
I think so as well. If someone wants to cancel from within, they can probably use a Deferred or something like that.

**Comment by neko-kai** [comment]
Eh, I think the first signature is a lot more intuitive and there's not much, if any, safety gained by hiding the `cancel` here. (Nah I'm not saying that because the first variant is in ZIO i swear on me mum)

**Comment by djspiewak** [comment]
The first signature does have the example of names, but I just feel it's really weird to make a resource-safe abstraction around something and then… expose the release action for that resource as a bare `F[Unit]`. I dunno. It's not too much of a problem since cancelation is idempotent, but still.

**Comment by kubukoz** [comment]
`type JoinToken`? ;)

**Comment by djspiewak** [comment]
LOL. I still really hate `CancelToken`, even though I see the value in it as a name. Confuses me every time.

**Comment by kubukoz** [comment]
For now I'll go with `background` because it's a meaningful name and it might be what people ctrl+F for (bonus points for not being `startResource` which I don't really like). We can bikeshed on the PR :)
