### ISSUE TITLE
Is there a reason not to have a recoverWith style function?

### ISSUE THREAD

**Issue by Daenyth** [typelevel/cats-effect#65]
I found myself wanting this:

```scala
object IORecoverWith {
  private def raise[A]: PartialFunction[Throwable, IO[A]] = {
    case ex => IO.raiseError[A](ex)
  }
  implicit class IORecoverWith[A](io: IO[A]) {
    def recoverWith(f: PartialFunction[Throwable, IO[A]]): IO[A] =
      io.attempt.flatMap(_.fold(f.orElse(raise[A]), IO.pure))
  }
}
```

Is there a reason that something like this isn't built in?

**Comment by djspiewak** [comment]
https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/applicativeError.scala#L35-L36

:-)  It already exists.  It just comes via `ApplicativeError`.

**Comment by Daenyth** [comment]
Documentation to that effect would be good. The typelevel blog post didn't cover it at all.

**Comment by Daenyth** [comment]
For discoverability it would be really good for that to be a method on the IO class too, so that IDE autocomplete picks it up.

**Comment by djspiewak** [comment]
There's no question that having this function on IO would help discoverability, and not just for people who use IDEs. I knew the function existed and I still had to go spelunking through a few files to find it.

There's a fine line here. Clearly it's impossible for us to document all of the dozens and dozens of functions which are materialized implicitly on IO, nor is it reasonable to put all of them directly on the type. So it's not clear to me where the line is and how we can decide one versus the other.

An easy distinction is of course performance. If we can get a higher performing implementation than the generic one, then an implementation on the type makes sense. But I don't know if just discoverability alone is strong enough, seeing as that would apply to a truly impractical number of functions which would then be very difficult to maintain.

**Comment by Daenyth** [comment]
A reasonable middle ground would be if the doc page could auto generate docs as if they were instance methods, and just a note of what to import to get it
