### ISSUE TITLE
Add 2.13 cross-build

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#66]
Depends on https://github.com/typelevel/cats/issues/1648

**Comment by SethTisue** [comment]
time to try a 2.13.0-M5 release? have all dependencies published for M5?

**Comment by SethTisue** [comment]
awesome! can someone pull the publishing levers now?

**Comment by SethTisue** [comment]
oh, I see now at https://github.com/monix/monix/issues/786 @alexandru said that would happen "soon"

**Comment by SethTisue** [comment]
it happened! https://repo1.maven.org/maven2/org/typelevel/cats-effect_2.13.0-M5/1.1.0/  thanks @alexandru
