### ISSUE TITLE
Ref.unsafe does not use "Partially Applied Type Params technique"

### ISSUE THREAD

**Issue by xuwei-k** [typelevel/cats-effect#666]
remove following comment or create new partially applied type `unsafe` method? 🤔 

https://github.com/typelevel/cats-effect/blob/26a3be12e9ef8b85195cacbb0eab76f0aa74cf1f/core/shared/src/main/scala/cats/effect/concurrent/Ref.scala#L174-L175

**Comment by kubukoz** [comment]
I believe this can be closed now.

**Comment by xuwei-k** [comment]
I have fixed only example code.

**Comment by kubukoz** [comment]
I think it's fair to keep it that way. It's an unsafe method you're not meant to call anyway, so it could be considered an internal that's only exposed for rare cases. For these rare cases, repeating the type of the value inside is probably less of a problem than the fact that you need `unsafe` at all.

**Comment by djspiewak** [comment]
I'm okay either way. I'll let some consensus emerge before acting. :-)

**Comment by quanganhtran** [comment]
> I think it's fair to keep it that way. It's an unsafe method you're not meant to call anyway, so it could be considered an internal that's only exposed for rare cases. For these rare cases, repeating the type of the value inside is probably less of a problem than the fact that you need `unsafe` at all.

I have a question that I haven't really found a clear answer for: Why is the _creation_ of a Ref effectful? From the source code comment itself:

> Like apply but returns the newly allocated ref directly instead of wrapping it in F.delay. This method is considered unsafe because it is not referentially transparent -- it allocates mutable state.
> Such usage is safe, as long as the class constructor is not accessible and the public one suspends creation in IO

Why does either Ref creation or one of its callsites up the stack need to be wrapped in an effect? Is there any example of this `unsafe` actually being an issue? Surely _it allocates mutable state_, but afaiu getting and setting this Ref are already effectful operations and should be safe.

**Comment by armanbilge** [comment]
@quanganhtran 

> Why is the _creation_ of a Ref effectful? ... Is there any example of this unsafe actually being an issue?

If something is referentially transparent, then you can substitute a symbol with its definition. So for example, consider:

```scala
val ref = new AtomicReference("fizz")
ref.getAndUpdate(_ + "buzz")
println(ref.get())
```

If we substitute `ref` for its definition `new AtomicReference("fizz")`, we have:

```scala
(new AtomicReference("fizz")).getAndUpdate(_ + "buzz")
println((new AtomicReference("fizz")).get())
```

Which is not the same program.

Further reading:
https://systemfw.org/posts/programs-as-values-II.html#referential-transparency

**Comment by kubukoz** [comment]
We should have something like this  in Ref's docs (on the website) 😅

**Comment by lenguyenthanh** [comment]
> We should have something like this in Ref's docs (on the website) 😅

I think this fits more on `concept` or a new `principle` (on the website)
