### ISSUE TITLE
Parallel instances for nested 

### ISSUE THREAD

**Issue by ShahOdin** [typelevel/cats-effect#670]
`parallel` has implicit methods for `Parallel[OptionT[M, ?], Nested[F, Option, ?]]` and a similar one for `Parallel[EitherT[M, E, ?], Nested[M, Validated[E, ?], ?]]`. I have written an implementation that does this for a generic Nested instance which obviously requires some instances from the nested context G and also some on the Parallel type Parameters, but it gives me an instance of `NonEmptyParallel[Nested[M, G, *], Nested[F, G, *]]` which would allow me to write code in the new form, instead of the old form: 

```scala
    val foo: IO[Option[Int]] = IO.pure(Some(1))
    val bar: IO[Option[Int]] = IO.pure(Some(2))

    val old = (OptionT(bar), OptionT(foo)).parMapN(_ + _).value
    val new = (foo.nested, bar.nested).parMapN(_ + _).value
```
obviously it also allows me to write the equivalent for say `IO[List[_]]` or `IO[Either[_, Option[_]]]`.
Here is the implementation:

```scala
implicit def nonEmptyParallelForNested[M[_] : Applicative, F[_], G[_]: Monad : Traverse](implicit p: NonEmptyParallel[M, F]): NonEmptyParallel[Nested[M, G, *], Nested[F, G, *]] = new NonEmptyParallel[Nested[M, G, *], Nested[F, G, *]] {

        implicit val F: Apply[F] = p.apply
        implicit val M: FlatMap[M] = p.flatMap


    override def apply: Apply[Nested[F, G, *]] = cats.data.Nested.catsDataApplyForNested[F, G]

    override def flatMap: FlatMap[Nested[M, G, *]] = new StackSafeMonad[Nested[M, G, *]] {
      override def flatMap[A, B](fa: Nested[M, G, A])(f: A => Nested[M, G, B]): Nested[M, G, B] = Nested(
        fa.value.flatMap{
          Traverse[G].flatTraverse(_)(f.andThen(_.value))
        }
      )

      override def pure[A](x: A): Nested[M, G, A] = cats.data.Nested.catsDataApplicativeForNested[M, G].pure(x)
    }

    override def sequential: Nested[F, G, *] ~> Nested[M, G, *] = new ~>[Nested[F, G, *], Nested[M, G, *]] {
      override def apply[A](fa: Nested[F, G, A]): Nested[M, G, A] = Nested(p.sequential.apply(fa.value))
    }

    override def parallel: Nested[M, G, *] ~> Nested[F, G, *] = new ~>[Nested[M, G, *], Nested[F, G, *]] {
      override def apply[A](fa: Nested[M, G, A]): Nested[F, G, A] = Nested(p.parallel.apply(fa.value))
    }
  }
```

and an almost identical implementation for `Parallel`: 

```scala
implicit def parallelForNested[M[_], F[_], G[_]: Monad : Traverse](implicit p: Parallel[M, F]): Parallel[Nested[M, G, *], Nested[F, G, *]] = new Parallel[Nested[M, G, *], Nested[F, G, *]] {

    implicit val F: Applicative[F] = p.applicative
    implicit val M: Monad[M] = p.monad

    override def applicative: Applicative[Nested[F, G, *]] = cats.data.Nested.catsDataApplicativeForNested[F, G]

    override def monad: Monad[Nested[M, G, *]] = new StackSafeMonad[Nested[M, G, *]] {
      override def flatMap[A, B](fa: Nested[M, G, A])(f: A => Nested[M, G, B]): Nested[M, G, B] = Nested(
        fa.value.flatMap{
          Traverse[G].flatTraverse(_)(f.andThen(_.value))
        }
      )

      override def pure[A](x: A): Nested[M, G, A] = cats.data.Nested.catsDataApplicativeForNested[M, G].pure(x)
    }

    override def sequential: Nested[F, G, *] ~> Nested[M, G, *] = new ~>[Nested[F, G, *], Nested[M, G, *]] {
      override def apply[A](fa: Nested[F, G, A]): Nested[M, G, A] = Nested(p.sequential.apply(fa.value))
    }

    override def parallel: Nested[M, G, *] ~> Nested[F, G, *] = new ~>[Nested[M, G, *], Nested[F, G, *]] {
      override def apply[A](fa: Nested[M, G, A]): Nested[F, G, A] = Nested(p.parallel.apply(fa.value))
    }
  }
```

- Was there a conscious decision to not have such an implementation? And if not, can we have this?

- For us to be able to use this recursively, so that we can use `parMapN` on say a tuple of `IO[Either[_, Option[_]]]`s, we need to feed it instances for `Traverse` and `Monad` of the `Nested` to get a parallel instance for `Nested[Nested,_, _]`. Traverse is easily composable and derivable through `catsDataTraverseForNested` but Monad isn't. We could have a monadForNested as below: 

```scala

  implicit def catsDataMonadForNested[F[_]: Monad, G[_]: Monad: Traverse]: Monad[Nested[F, G, *]] = new StackSafeMonad[Nested[F, G, *]]{
    override def flatMap[A, B](fa: Nested[F, G, A])(f: A => Nested[F, G, B]): Nested[F, G, B] = Nested(
      fa.value.flatMap{
        Traverse[G].flatTraverse(_)(f.andThen(_.value))
      }
    )
    override def pure[A](x: A): Nested[F, G, A] = cats.data.Nested.catsDataApplicativeForNested[F, G].pure(x)
  }

```

- on a related note, would it be a good idea to provide `catsDataMonadForNested` on its own right?

p.s. I have just noticed that the `Parallel/NonEmptyParallel` now takes only one type parameter which would change the implementation above a little bit, but I suppose the main idea stays the same.

**Comment by ShahOdin** [comment]
[here](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.138.4552&rep=rep1&type=pdf) that I came across on the related issue of composing monads which is what we are doing with `catsDataMonadForNested`. Curious to know what the cats denizens think of the general idea.

**Comment by SystemFw** [comment]
You cannot have Monads for Nested, it's fundamentally not possible. That's why monad transformers exist.

**Comment by ShahOdin** [comment]
@SystemFw I think we are aware of that. :) Here we have a composed monad for a specific set of monads though, not generic monads. We can of course put these requirements in a new data type. Haskell has a `Monad.Compose` for instance. It would basically be a generic version of `OptionT` and `EitherT` I think?

**Comment by ShahOdin** [comment]
Did some googling and it turns out this is a known issue. we can also compose monads in another way also, using `Distributive`s. creating another ticket to discuss the underlying issue there: 

https://github.com/typelevel/cats/issues/3113
