### ISSUE TITLE
OutOfMemoryError in computation performed by Blocker doesn't halt the JVM

### ISSUE THREAD

**Issue by danxmoran** [typelevel/cats-effect#692]
(I'm using CE 2.0)

This is the same bug as #515, except the code that triggered the fatal error was executing inside of a `blocker.delay`. The `Blocker` was created using `Blocker.apply`.

Should the default thread pool implementation which backs `Blocker` instances be reworked to mirror the logic of CE 2.0's default EC, introduced in #547?

**Comment by djspiewak** [comment]
> Should the default thread pool implementation which backs Blocker instances be reworked to mirror the logic of CE 2.0's default EC, introduced in #547?

Indeed it should.
