### ISSUE TITLE
Proposal: ContextPropagation typeclass

### ISSUE THREAD

**Issue by tomasherman** [typelevel/cats-effect#699]
Hey guys,

i have a proposal to make. In our workplace, we really need a typeclass that somehow represents context propagation for different effect types - instances of such typeclasss is `ThreadLocal` for monix and `FiberRef` for zio.

We currently have our own implementations (see below) but it would be great if this became part of cats-effect. I think it's useful concept for more people than just us.

What do you think?

Here is our implementation:

```scala
trait Context[F[_], T] {
  def get: F[T]
}
```

```scala
trait ContextPropagation[F[_], T] extends Context[F, T] {
  def set(v: T): F[Unit]

  def update(f: T => T): F[T]
}
```

**Comment by Avasil** [comment]
`cats-mtl` has [ApplicativeAsk](https://typelevel.org/cats-mtl/mtl-classes/applicativeask.html) and [ApplicativeLocal](https://typelevel.org/cats-mtl/mtl-classes/applicativelocal.html) type classes which cover similar functionality. 

`meow-mtl`  contains a type class instance for [TaskLocal](https://github.com/oleg-py/meow-mtl#tasklocal). ZIO instance should be straightforward to implement as well. 

Is it enough for your use case?

**Comment by tomasherman** [comment]
well, to be honest, if it was up to me i would have never found those type classes nor would i have guess they would be a fit for this use case - i think what im proposing is a bit simpler and easier to use but not sure how rest of the community feels about this

**Comment by tomasherman** [comment]
after reading some docs, im not sure if this is a good match - it seems like conceptually two different things and while the interface might suffice, it seems like i would be abusing a bit

**Comment by rossabaker** [comment]
What would be the laws for these typeclasses?  Are these equivalent?  

```scala
set(v) <-> scope(v)(ask)
update(f) <-> local(f)(ask)
```

I don't see any abuse of `ApplicativeLocal`, and it seems to be working well in Monix.  If the above relations are true, maybe they would be useful additions to `ApplicativeLocal`.
