### ISSUE TITLE
Clock[F].monotonic(...) is returning wrong time

### ISSUE THREAD

**Issue by ri-cisse** [typelevel/cats-effect#705]
![image](https://user-images.githubusercontent.com/53084954/69632148-fc9f1900-104e-11ea-8684-81b3a4c427e3.png)

**Comment by aeons** [comment]
`monotonic` is not supposed to return the current time, but a timestamp that you know will be monotonically increasing, which can be used for precise time measurements.

If you need the current time, you should use `Clock[F].realTime`.

**Comment by ri-cisse** [comment]
@aeons : Thanks for clarifying this. 

Closing this.
