### ISSUE TITLE
Blocker platform no indexed thread names

### ISSUE THREAD

**Issue by Slakah** [typelevel/cats-effect#710]
[`BlockerPlatform`](https://github.com/typelevel/cats-effect/blob/master/core/jvm/src/main/scala/cats/effect/internals/BlockerPlatform.scala) looks to be inconsistent with the [`PoolUtils`](https://github.com/typelevel/cats-effect/blob/master/core/jvm/src/main/scala/cats/effect/internals/PoolUtils.scala#L38) thread naming. In that threads in the same pool are uniquely identifiable for compute, but not for blocker.

i.e.
`ioapp-compute-0/ioapp-compute-1/ioapp-compute-2` vs `cats-effect-blocker/cats-effect-blocker/cats-effect-blocker`.

Some valid use cases for being able to identify a individual thread by name would be that many loggers will output the executing thread, with this metadata being used to determine which thread a piece of code is executing on.

**Comment by djspiewak** [comment]
Strong agree that this should be fixed.

**Comment by Slakah** [comment]
Implementation can be found with PR #722 .

**Comment by Slakah** [comment]
Fixed by #722
