### ISSUE TITLE
IO documentation is outdated wrt cancelable flatMaps

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#720]
> We should also note that flatMap chains are not auto-cancelable

and probably several other mentions.

**Comment by djspiewak** [comment]
They aren't? In `IO`?

**Comment by Avasil** [comment]
> They aren't? In `IO`?

There aren't any async boundaries introduces at flatMaps but there is auto-cancelation, e.g. https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/internals/IORunLoop.scala#L151

**Comment by kubukoz** [comment]
See for yourself:

https://scastie.scala-lang.org/kGCrZ9LcQbeUp8WzlLIvjw

**Comment by djspiewak** [comment]
Ooooh I misunderstood. I thought you were saying that `IO.flatMap` *isn't* auto-cancelable and the docs claimed otherwise. So in other words, I was exactly backwards. Strong agree that we need to update the docs.
