### ISSUE TITLE
IO's `Fiber#cancel` doesn't wait for finalizers if they already started running

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#721]
In the following code:

```scala
val finalizer = IO.sleep(5.seconds) *> IO(println("finalized"))

val exhibitA = IO.unit.guarantee(finalizer).timeout(1.second)

val exhibitB = IO.never.guarantee(finalizer).timeout(1.second)
```

Sequencing `exhibitA` will complete after one second, without waiting for the finalizer to complete (it'll keep running in the background).

Sequencing `exhibitB` will wait one second, start the finalizer, wait for it to finish and only then continue.

I think this is a bug, as I was under the impression that `cancel` always waits for the finalizers.

I'd love to help fix this, if it's possible with the current implementation of IO (given some help).

ZIO handles the case properly but Monix Task also behaves like `cats.effect.IO`.

Tested on 2.0.0

**Comment by djspiewak** [comment]
Can definitely confirm that `Fiber#cancel` should *always* await the finalizer. This is sufficiently important that I almost want to make it a law:

```scala
bracket(F.never)(_ => F.unit)(_ => F.never).start.flatMap(_.cancel) <-> F.never
```

**Comment by Avasil** [comment]
I remember @alexandru having some arguments against it but I don't remember where was the discussion

I personally agree that it should await the finalizer, it's easy to reverse behavior with `cancel.start`

**Comment by kubukoz** [comment]
@djspiewak how is `never`'s equality defined?

**Comment by Avasil** [comment]
> @djspiewak how is `never`'s equality defined?

AFAIK it runs it and [compares Future](https://github.com/typelevel/cats-effect/blob/master/laws/shared/src/main/scala/cats/effect/laws/util/TestInstances.scala#L57), ticks everything (I'm not sure if it shouldn't be something like `ec.tick(1.day)`) and checks the result. In case of `IO.never`, both values should be `None`

**Comment by kubukoz** [comment]
In that case I'm satisfied with the shape of that law :) 

Alternatively,

```scala
bracket(acquire)(_ => F.never)(release).start.flatMap(_.cancel) <-> (acquire *> release)
```

plus a latch for waiting before `cancel`.

**Comment by djspiewak** [comment]
I do like the more general law, though obviously it relies on the race condition without the latch (as does mine). We would probably do something like that.
