### ISSUE TITLE
Combination of fatal errors and async callbacks does not terminate

### ISSUE THREAD

**Issue by hwielenberg** [typelevel/cats-effect#726]
My expectation is that the following program would terminate with the fatal error.
It should not print "never makes it here" as the `attempt` should only catch non fatal errors. But the issue is that it never terminates.

```
import cats.effect.{ExitCode, IO, IOApp}

object HangsForever extends IOApp {

  val fatalError = new InternalError("some fatal error (scala.util.control.NonFatal)")

  def run(args: List[String]): IO[ExitCode] =

    for {
      _ <- asyncIdentity[Int](0)
      _ <- IO(println("made it here"))
      _ <- IO[Int](throw fatalError).attempt //attempt or not doesn't really matter
      _ <- IO(println("never makes it here"))
    } yield ExitCode.Success

  def asyncIdentity[B](b: B): IO[B] =
    IO.async[B](callback => {
      new Thread(() =>
        try{
          callback(Right(b))
        } catch {
          case e:Throwable => println("The callback function threw an error: " +e)
          throw e
        }
      ).start()
    })
}
```

As the exception in propagated from calling the callback function in the async Thread there is hardly a way to recover from the exception. You can't catch the error from the callback and then call the callback again as it is an `AsyncIdempotentCallback`. Therefore i consider this a bug in cats-effect.

**Comment by djspiewak** [comment]
This actually requires more than just fatal errors and callbacks, as the following demonstrates:

```scala
val ioa = IO.async[Unit] { k => k(Right(())); throw new InternalError("oogly boogly") }
ioa.unsafeRunSync()       // terminates and propagates the exception
```

What your case is doing is effectively throwing an exception, swallowing it, and then terminating without the callback ever having been run to completion. I'm honestly not sure if there's anything cats effect can do in that case.

Fatal errors are *very* problematic. Doing anything with them is, in general, nondeterministic. You may know for your specific case that this particular fatal error is handleable in exactly your circumstances, but Cats Effect can't know that. My advice, honestly, is to do something different in your exception handler. Something like this:

```scala
  def asyncIdentity[B](b: B): IO[B] =
    IO.async[B](callback => {
      new Thread(() =>
        try{
          callback(Right(b))
        } catch {
          case NonFatal(e) => 
            println("The callback function threw an error: " +e)
            throw e
          case e: Throwable =>
            e.printStackTrace()
            System.exit(-1)
        }
      ).start()
    })
```

As a general rule, once you've hit a fatal error, the JVM is *usually* in an undefined state. Attempting to do anything meaningful with it is going to be subject to the whims of HotSpot's internal state (though this does depend a *bit* on which fatal error you hit, and it depends a lot on your other circumstances, such as which garbage collector you're using). Doing anything with a fatal error *other* than killing the JVM is usually not a good idea.

**Comment by Baccata** [comment]
Hi, I work with Henning, who caught the bug. 

I think I understand : the `new Thread` is not supervised by the `IO.async` function in any way (nor can it), and therefore there is no way for cats-effect to know that an exception happened in the thread, and it cannot react to it / propagate it. 

@djspiewak thanks for the answer. What happened is that we're wrapping some calls to the java aws-sdk which makes extensive use of CompletableFuture. We seem to have hit an issue leading to a `NoSuchMethodError` being thrown by one of the upstream libraries we use, which lead to the application hanging. 

I suppose our `CompletableFuture ~> IO` lift function is lacking the "if fatal, then exit" protection. Is  there by any chance a cookbook somewhere with examples on how to lift async calls (and particularly java ones) info effect types without falling in this kind of pitfall  ? Or is it a case that fatal errors happen rarely enough that you're better off biting the bullet and debugging when they occur ?

**Comment by djspiewak** [comment]
> I think I understand : the new Thread is not supervised by the IO.async function in any way (nor can it), and therefore there is no way for cats-effect to know that an exception happened in the thread, and it cannot react to it / propagate it.

Yep!

> I suppose our CompletableFuture ~> IO lift function is lacking the "if fatal, then exit" protection. Is there by any chance a cookbook somewhere with examples on how to lift async calls (and particularly java ones) info effect types without falling in this kind of pitfall ? Or is it a case that fatal errors happen rarely enough that you're better off biting the bullet and debugging when they occur ?

It's probably actually the underlying thread pool itself. This is a tricky one because you may not control the pool. If you look in `PoolUtils`, you'll see how we actually get this to work: we catch `Throwable` at the root of every dispatch thread and just `exit` if it's fatal. This is to avoid the case where a thread silently dies, taking the continuation with it, while the JVM is kind of in invalid limbo land.

Honestly you may not be able to do very much here. It depends on whether or not you can customize the thread pool underlying your `CompletableFuture`s. The correct way to lift async calls is probably the way you're doing it: use `IO.async(...).guarantee(IO.shift)` (to make sure you get back to the correct thread pool).

**Comment by Baccata** [comment]
Cool, thanks for the insight. It's okay to close the ticket imho. @hwielenberg are you okay with that ?

**Comment by hwielenberg** [comment]
@djspiewak Thanks for the explanation. 
Yes I am happy to close the story.
