### ISSUE TITLE
Publish `Arbitrary[IO[A]]`

### ISSUE THREAD

**Issue by rossabaker** [typelevel/cats-effect#74]
I recently needed an `Arbitrary[IO[A]]`.  Would anybody object to moving ours into cats-effect-laws?  This would be consistent with cats, which publishes arbitraries for its data types in cats-laws.

**Comment by alexandru** [comment]
We already have `Arbitrary[IO[A]]` instances in tests, are you referring to those?

[Link](https://github.com/typelevel/cats-effect/blob/v0.4/core/shared/src/test/scala/cats/effect/Generators.scala)

**Comment by rossabaker** [comment]
Yes, I would like to see these published for use in other projects.  It would require moving our core tests into a test-only module that depends on both core and laws.  This is how it works in cats, circe, and http4s, among others, with some differing naming conventions.  (I'd go with cats' convention.)

**Comment by djspiewak** [comment]
I would be ok with that.  It's not entirely trivial to write a sound and complete `Arbitrary[IO[A]]`, and it's also a little difficult to meaningfully verify the laws if you don't have one.  We should probably do something similar with `Eq[IO[A]]` and friends.

**Comment by rossabaker** [comment]
Great.  I'll try to work on a PR tomorrow.

We already publish an [`Eq[IO[A]]`](https://github.com/typelevel/cats-effect/blob/d53a78ec3a7fe3d3a4a2241118cda91e331d5d23/laws/shared/src/main/scala/cats/effect/laws/util/TestInstances.scala#L36) in laws.  I did recently need an `IO[Boolean] => Prop`, and I'm still considering how filthy it made me feel.

**Comment by alexandru** [comment]
Given that `IO` cannot implement `Eq` since it can't be a `Comonad`, it's supposed to be dirty 😀

We cannot get rid of that `TestContext` if we want to test async stuff that can also work on top of JavaScript.

**Comment by rossabaker** [comment]
I was incorrect.  We don't need a tests module.  I was able to do this just by moving the arbitraries into laws' main.

Is there any interest in `IO[Boolean] => Prop`?
