### ISSUE TITLE
`continual` hangs if canceled before `use` in its internal`bracket`

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#793]
```scala
import cats.effect._
import cats.implicits._
import cats.effect.concurrent._
import java.{util => ju}

object Demo extends IOApp {

  def run(args: List[String]): IO[ExitCode] = {
    (IO(ju.UUID.randomUUID()), Deferred[IO, Unit]).tupled.flatMap {
      case (id, latch) =>
        val action: IO[Unit] = latch.complete(()) *> IO.never

        Concurrent.continual(action)(_ => IO.unit).start.flatMap(latch.get *> _.cancel) *>
          IO(println(s"foo $id"))
    }
  }.foreverM.as(ExitCode.Success)
}
```

This will run for a while, but eventually it'll print its final `foo` and never progress further.

I suppose this might be caused by a combination of `continual` being based on `start` and nested `start`s not getting cancelation propagated to them. But the most concerning part of it all is that it takes a couple hundred / couple thousand repeats to actually hang the program.

**Comment by kubukoz** [comment]
Reproduction test at https://github.com/typelevel/cats-effect/compare/master...kubukoz:hanging-test

**Comment by kubukoz** [comment]
```scala
/**
 * This is the default [[Concurrent.continual]] implementation.
 */
def continual[F[_], A, B](fa: F[A])(f: Either[Throwable, A] => F[B])(implicit F: Concurrent[F]): F[B] = {
  import cats.effect.implicits._
  import scala.util.control.NoStackTrace

  Deferred.uncancelable[F, Either[Throwable, B]].flatMap { r =>
    fa.start //2
      .bracket { fiber => 
        //3
        fiber.join.guaranteeCase {
          case ExitCase.Completed | ExitCase.Error(_) =>
            fiber.join.attempt.flatMap(f).attempt.flatMap(r.complete)
          case _ =>
            fiber.cancel >>
              r.complete(Left(new Exception("Continual fiber cancelled") with NoStackTrace))
        }.attempt
      }(_ => r.get.void) //1
      .flatMap(_ => r.get.rethrow)
  }
}
```

I *think* this definition doesn't really work here because in the case that hangs, we reach `//1` immediately after `2` runs, which cancels `3` and the promise is never completed. `1` is in a bracket's finalizer, so we're waiting for that infinitely.

**Comment by kubukoz** [comment]
Yep, it's #706 - the hanging began at 777ae0c2b03de2060fb51e100b12564f7e78d138 but 862baf884b0fbe54fb75846fd916d7bc090280fb works fine.

**Comment by SystemFw** [comment]
Yeah that makes sense, and arguably #706 makes sense. I'm not sure how to fix this though, as you need to detect whether the fiber has started or not

**Comment by SystemFw** [comment]
I need to think whether we can make that a `bracketCase` and go from there

**Comment by kubukoz** [comment]
I *think* I fixed it. `bracketCase` helped, indeed:

```scala
def continual[F[_], A, B](fa: F[A])(f: Either[Throwable, A] => F[B])(implicit F: Concurrent[F]): F[B] = {
    import cats.effect.implicits._

    Deferred.uncancelable[F, Either[Throwable, B]].flatMap { r =>
      fa.start.bracketCase { fiber =>
        fiber.join.guaranteeCase {
          case ExitCase.Completed | ExitCase.Error(_) => fiber.join.attempt.flatMap(f).attempt.flatMap(r.complete)
          case _                                      => F.unit //will be canceled in release of enclosing bracketCase
        }
      } {
        case (fiber, ExitCase.Canceled) => fiber.cancel //no need to complete `r` - the whole thing is canceled
        case _                          => F.unit
      }.attempt *> r.get.rethrow
    }
  }
```

The tests for `continual` pass and my example doesn't hang anymore.

**Comment by kubukoz** [comment]
So basically I moved the cancelation from the `guaranteeCase` to the enclosing bracket, which just *has* to run, and removed the part where we complete the promise with the canceled case (if the whole thing is canceled, it'll have to be before `*> r.get.rethrow`, which I think will just cancel that `get` due to an async boundary)

**Comment by kubukoz** [comment]
If the Deferred is uncancelable because it's more efficient, I can add completion of `r` with a "canceled" exception (as before) after canceling the fiber. Does it make sense?
