### ISSUE TITLE
Concurrent.memoize's effect can hang if the first one is canceled

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#802]
If you run this a couple times:

```scala
Ref[IO]
  .of(0)
  .flatMap { ref =>
    Concurrent.memoize(ref.update(_ + 1).onCancel(ref.set(0))).flatMap { get =>
      Deferred[IO, Unit].flatMap(deff => (deff.complete(()) *> get).start.flatMap(fib => deff.get *> fib.cancel)) *> get //this get hangs
    } *> ref.get
  }
```

then the program hangs at the second `get`. I thought the cause is #706, but I was able to reproduce this on 2.0.0 (when this version of `memoize` was released). I think it's the cancelable flatMap in https://github.com/typelevel/cats-effect/blob/v2.0.0/core/shared/src/main/scala/cats/effect/Concurrent.scala#L451-L460:

```scala
state
  .modify {
    case s @ Some(Fetch(Done, v, _)) =>
      s -> v.get
    case Some(Fetch(Subs(n), v, stop)) =>
      Fetch(Subs(n + 1), v, stop).some -> v.get.guaranteeCase(endState)
    case None =>
      Fetch(Subs(1), v, stop).some -> fetch.bracketCase(_ => v.get) { case (_, ec) => endState(ec) }
}
.flatten

```

Update: replaced the `flatten` with something more like this:

```scala
state
  .modify {
      case s @ Some(Fetch(Done, v, _)) =>
        s -> ((v.get, (_: Any) => F.unit))
      case Some(Fetch(Subs(n), v, stop)) =>
        Fetch(Subs(n + 1), v, stop).some -> ((v.get, endState _))
      case None =>
        Fetch(Subs(1), v, stop).some -> ((fetch *> v.get, endState _))
  }
  .bracketCase(_._1) {
    case ((_, finalizer), exit) => finalizer(exit)
  }
  .rethrow
```

but now the problem seems to be that `fetch` doesn't start at all, so the fiber's finalizer isn't installed and `fib.cancel` hangs because it's waiting for that installation (`stop.get.flatten`).

**Comment by djspiewak** [comment]
Well that's fun… Intuitively, it feels like we may need to explicitly track in the `memoize` machinery whether or not it has been canceled. If so, then one of the awaiting continuations will need to re-attempt the evaluation. This is a tricky bit of subtlety, since it means that, when canceled, *part* of the `memoize`d effect may end up being re-run. The alternative would be to propagate an error to other awaiting callers, but that seems unintuitive and bizarre. This would all be much easier if `Fiber#join` gave us real information.

**Comment by kubukoz** [comment]
@djspiewak we're already tracking the cancelation I think - if it happens and there are no more subscribers, the IO is canceled (in `endState`)

**Comment by djspiewak** [comment]
Hmm. I'll admit to having not actually opened up that code since my initial review. I wonder what's causing the OP then. :-(

**Comment by SystemFw** [comment]
Yeah I meant to go back to this we never got the time

**Comment by kubukoz** [comment]
This is probably fixed in ce3, right?

**Comment by kubukoz** [comment]
Checked 10 times and it didn't hang, and in 2.x it would do so after 2-3 runs.
