### ISSUE TITLE
Significant change in Resource's map/flatMap type with regards to variance

### ISSUE THREAD

**Issue by sideeffffect** [typelevel/cats-effect#807]
The type of the methods `map` and `flatMap` in `Resource` has changed from version `2.0.0` to `2.1.0`.
Before, the types looked like this:
```scala
def map[B](f: A => B)...: Resource[F, B] = ???
def flatMap[B](f: A => Resource[F, B]): Resource[F, B] = ???
```

Now, the types looks like this:
```scala
def map[G[x] >: F[x], B](f: A => B)...: Resource[G, B] = ???
def flatMap[G[x] >: F[x], B](f: A => Resource[G, B]): Resource[G, B] = ???
```

This change broke some code, which used used co-variance of the parameter of `F`, as in `F[+ _]`. For example:
```scala

class Base()
case class Derived() extends Base

case class Resource[F[_], A](use: F[A])(implicit F: Sync[F]) {
// the signatures before
//    def map[B](f: A => B)(implicit F: Functor[F]): Resource[F, B] = ???
//    def flatMap[B](f: A => Resource[F, B])(implicit F: Monad[F]): Resource[F, B] = ???
  def map[G[x] >: F[x], B](f: A => B)(implicit F: Functor[G]): Resource[G, B] = ???
  def flatMap[G[x] >: F[x], B](f: A => Resource[G, B])(implicit F: Monad[G]): Resource[G, B] = ???
}

def fBase[F[+ _]](implicit F: Sync[F]): F[Either[Base, Nothing]] = F.delay(Left(new Base()))
def fDerived[F[+ _]](implicit F: Sync[F]): F[Either[Derived, Nothing]] = F.delay(Left(Derived()))

def f[F[+ _]](implicit F: Sync[F]): F[Either[Base, Nothing]] =
  if (true) {
    fBase
  } else {
//      fDerived.map(identity[Either[Base, Nothing]]) // without F[+ _], one has to resort to hacks like this
    fDerived
  }

def g[F[+ _]](implicit F: Sync[F]): Resource[F, Either[Base, Nothing]] = {
  for {
    x <- Resource(f)
  } yield x
}
```

This now fails with
```
!I F (Could not find an instance of Functor for [x]F[x]): Functor[F[?]]
```

I tried to fiddle with the types a bit to find out if I could fix it, but didn't get anywhere. Do you guys have any idea how to change either the program, or the signature of `Resource`'s methods (while still keeping the benefits of the move to `G[x] >: F[x]`, which I presume is widening).
Thanks! :pray:

**Comment by neko-kai** [comment]
Oddly, this works fine with two parameter covariance `F[+_, +_]`:
```scala

  import cats.effect.{Resource, Sync}
  
  class Base()
  case class Derived() extends Base

  def fBase[F[+ _]](implicit F: Sync[F]): F[Either[Base, Nothing]] = F.delay(Left(new Base()))
  def fDerived[F[+ _]](implicit F: Sync[F]): F[Either[Derived, Nothing]] = F.delay(Left(Derived()))

  def f[F[+ _]](implicit F: Sync[F]): F[Either[Base, Nothing]] =
    if (true) {
      fBase
    } else {
      fDerived
    }

  def g2[F[+_, +_]](implicit F: Sync[F[Throwable, ?]]): Resource[F[Throwable, ?], Either[Base, Nothing]] = {
    Resource.liftF[F[Throwable, ?], Either[Base, Nothing]](f[F[Throwable, +?]])
      .map(x => x)
  }

  // this one fails, but not the above
  def g[F[+_]](implicit F: Sync[F]): Resource[F, Either[Base, Nothing]] = {
    Resource.liftF[F, Either[Base, Nothing]](f[F])
      .map(x => x)
  }
```

**Comment by neko-kai** [comment]
Writing `Lambda[A => F[A]]` instead of `F` in type ascription unborks it also:

```scala

  def g[F[+_]](implicit F: Sync[F]): Resource[F, Either[Base, Nothing]] = {
    Resource.liftF(f[F])
      .map[Lambda[A => F[A]], Either[Base, Nothing]](x => x)
  }
```

**Comment by djspiewak** [comment]
> Writing Lambda[A => F[A]] instead of F in type ascription unborks it also:

Given how `Lambda` desugars, I believe writing that is equivalent to doing something like `type G[A] = F[A]`, which is to say, simply stripping the variance from `F`. I wonder if something similar is masking the problem in the biconstructor case, since the `Sync` is defined in terms of the invariant kind projector syntax, rather than the covariant one.

**Comment by djspiewak** [comment]
BTW I haven't forgotten about this, and this issue is a really really important one considering how common this case is. I've just been hella busy with some other things… Should be able to loop back to it Soon™

**Comment by djspiewak** [comment]
There is a very strange dealiasing issue here. For example, the following works:

```scala
  def g[F[+_]](implicit F: Sync[F[+?]]): Resource[F[+?], Either[Base, Nothing]] = {
    Resource.liftF[F, Either[Base, Nothing]](f[F])
      .map(x => x)
  }
```

So… anyone who is looking for a workaround, you can try the above.

**Comment by joroKr21** [comment]
It works fine on Scala 2.13 btw

**Comment by djspiewak** [comment]
@joroKr21 It seems like a bug in scalac, so it doesn't surprise me all that much that 2.13 is fine with it. :-)
