### ISSUE TITLE
IOApp linker error with ScalaJS 1.0.0

### ISSUE THREAD

**Issue by puhli** [typelevel/cats-effect#809]
While updating a project from ScalaJS 0.6.32 to 1.0.0 I encountered a linker error for IOApp:

> [error] Referring to non-existent method static java.lang.System.exit(int)void
[error]   called from scala.sys.package$.exit(int)nothing
[error]   called from private cats.effect.internals.IOAppPlatform$.setExitCode(int)void
[error]   called from private cats.effect.internals.IOAppPlatform$.$anonfun$main$2(scala.util.Either)void
[error]   called from cats.effect.internals.IOAppPlatform$.main([java.lang.String,cats.Eval,cats.Eval,scala.Function1)void
[error]   called from cats.effect.IOApp.main([java.lang.String)void
[error]   called from test.TestApp$.main([java.lang.String)void
[error]   called from static test.TestApp.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   scala.sys.package$
[error]   cats.effect.internals.IOAppPlatform$
[error]   test.TestApp$
[error] There were linking errors

The problem boils down to the removal of java.lang.System.exit from ScalaJS with [#3520](https://github.com/scala-js/scala-js/pull/3520).

I created a minimal sample project that shows the problem [JSIOApp.tar.gz](https://github.com/typelevel/cats-effect/files/4294837/JSIOApp.tar.gz). The fastOptJS command fails with the aforementioned error.

Used library versions are cats-core 2.1.1 and cats-effect 2.1.2.

**Comment by djspiewak** [comment]
Hmm, I'm not an expert on ScalaJS, but I *think* that both of the usages of `sys.exit` can simply be removed. One of them is entirely unreferenced (the one on line 92 of `IOAppPlatform`), and the other looks like an ill-advised fallback. Any thoughts from those who know this stuff better than I?
