### ISSUE TITLE
Add documentation about IOApp not terminating in sbt without fork

### ISSUE THREAD

**Issue by arosien** [typelevel/cats-effect#831]
> IOApp shutdown uses jvm shutdown hooks, sbt doesn't terminate the jvm without fork (because it uses the same jvm for itself + your app)

(from https://gitter.im/typelevel/cats-effect?at=5e908d1a6823cb38acc1b5ae)

Add some documentation where IOApp + sbt is mentioned:
- https://typelevel.org/cats-effect/datatypes/ioapp.html#cancelation-and-safe-resource-release
- https://typelevel.org/cats-effect/tutorial/tutorial.html#copy-program-code

Perhaps a runtime check in IOApp to detect if the program is running under sbt? I don't know if this is either possible or desired.

**Comment by alexandru** [comment]
> Perhaps a runtime check in IOApp to detect if the program is running under sbt? I don't know if this is either possible or desired.

Unless `sbt` is setting some environment variable that we can easily read, we can't do that.

**Comment by rossabaker** [comment]
`sbt.Run.invokeMain` appears in the stack for apps inside sbt, but that's not a check I'd feel great about imposing on all `IOApp`s.

**Comment by djspiewak** [comment]
Another idea would be checking the classloader. That's a pretty lightweight thing to look at. My inclination is that `sbt run` is a sufficiently common use-case that it's worth making it a pleasant experience, even if it means some slightly weird checks that all applications would then have to pass through. We could pretty easily make it configurable as well.
