### ISSUE TITLE
Broken links in the HTML documentation

### ISSUE THREAD

**Issue by slouc** [typelevel/cats-effect#848]
For example, "Building cancelable IO tasks", which is referenced in the tutorial at the end of [Dealing with cancelation](https://typelevel.org/cats-effect/tutorial/tutorial.html#dealing-with-cancellation) section, points to [.md file](https://typelevel.org/cats-effect/datatypes/io.md#building-cancelable-io-tasks) instead of [.html file](https://typelevel.org/cats-effect/datatypes/io.html#building-cancelable-io-tasks) (note "io.md" vs "io.html" in the URL). 

Of course, in the Tutorial [.md file](https://github.com/typelevel/cats-effect/blob/b5b67d8737b66182fa53e34f6b2e5d579c097c8e/site/src/main/mdoc/tutorial/tutorial.md#dealing-with-cancellation) on GitHub such a link works as expected, but in the HTML version we should modify the URLs.

**Comment by rossabaker** [comment]
Have we republished since https://github.com/typelevel/cats-effect/pull/837?
