### ISSUE TITLE
Separate synchronous IO from concurrent IO documentation

### ISSUE THREAD

**Issue by Guisanpea** [typelevel/cats-effect#893]
I have been studying Cats effect for the past months, I remember that at the beginning it was a bit difficult for me to understand the fundamental foundation of the IO monad, suspending side effects and being referential transparent.

While I was thinking about why I took some time to understand it I feel that a lot of this was due to the fact that the documentation for IO has a lot of information about concurrent evaluation, cancellable and thread shifting.

I understand most programmers will look for this concurrent capabilities as it is a much preferable option than the Future which has many problems. However, I think that many people will come to cats effect just looking for a sync IO for having pure synchronous programs, and at a later point they can jump into the asynchronous part if they feel like it.

For this reason I think that the entry learning point for cats effect documentation should be an explanation of the IO monad as a method of deferring side effects evaluation in a synchronous manner and then have another section for how to use it """as a better future"""

In my opinion this would make cats effect more accessible and separate better the concerns

**Comment by benhutchison** [comment]
For this to be actionable, it should include links to the specific doc content you're referring to
