### ISSUE TITLE
Replacement for Instant in realTime?

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#895]
`java.time.Instant` doesn't exist on ScalaJS. The https://github.com/scala-js/scala-js-java-time project is intended to address this limitation, but a) it's another dependency, and b) it's not clear to me how mature it really is or if it's intended for this type of use-case (a foundational ecosystem library). Would appreciate some insight on this from @sjrd if he has a spare moment.

If we *don't* use `Instant`, we could move a little further afield. Obviously there's always `Long`, but if we're going to do that, we may as well just use `FiniteDuration`. @rossabaker had some strong opinions on this if I recall.

Floor is open. Anyone have thoughts or opinions on the appropriate signature here? To be clear, the *current* signature is as follows (which doesn't link on ScalaJS):

```scala
def realTime: F[Instant]
```

**Comment by sjrd** [comment]
> `java.time.Instant` doesn't exist on ScalaJS. The https://github.com/scala-js/scala-js-java-time project is intended to address this limitation, but a) it's another dependency, and b) it's not clear to me how mature it really is or if it's intended for this type of use-case (a foundational ecosystem library). Would appreciate some insight on this from @sjrd if he has a spare moment.

Indeed, scala-js-java-time is not very mature. It is actually mostly abandoned in favor of a more mature alternative: https://github.com/cquiroz/scala-java-time.

However, I wouldn't recommend either for foundational ecosystem libraries. Depending on a java.time implementation for Scala.js brings a *lot* of code, with issues such as TZ data taking up a lot of space in the final .js files.

**Comment by alexandru** [comment]
I don't like the semantics of `FiniteDuration`, it's not a Unix timestamp, but whatever, I'd be fine with `Long` too 🤷‍♂️

**Comment by alexandru** [comment]
Or we could define our own `newtype`.

**Comment by djspiewak** [comment]
> However, I wouldn't recommend either for foundational ecosystem libraries. Depending on a java.time implementation for Scala.js brings a lot of code, with issues such as TZ data taking up a lot of space in the final .js files.

Exactly the perspective I was hoping for! Thank you, Sebastian.

> I don't like the semantics of FiniteDuration, it's not a Unix timestamp, but whatever, I'd be fine with Long too 🤷‍♂️

Can you expand on this a bit? I don't see a difference between `FiniteDuration` and a newtype we would define around `Long`, but that's probably my ignorance.

**Comment by alexandru** [comment]
```scala
final case class UnixTimestamp(toMillisecondsSinceEpoch: Long) {

  def toFiniteDuration = toMillisecondsSinceEpoch.millis

  // These could be missing on top of Scala.js
  def toOffsetDateTime: OffsetDateTime = ???
  def toInstant: Instant = ???
}
```

**Comment by alexandru** [comment]
I don't think this belongs in Cats-Effect btw, but it's what's missing.

**Comment by djspiewak** [comment]
> FiniteDuration is a timespan, but the point of reference isn't specified.

This is true of `Long` though, also. Like if I give you a value of `1000L`, we know by convention that it's one thousand milliseconds, but… one thousand milliseconds from *when*?  This too we know by convention: one thousand milliseconds from 1970-01-01 00:00:00 UTC. Okay cool, but `FiniteDuration`'s problem is *no worse* than this.

In a more structured way, `Long` has two problems:

- Unknown unit
- Unknown reference point

`FiniteDuration` attaches a unit, but retains the unknown reference point problem. My point is that it's *no worse* than `Long`, and in fact actually has half as many issues.

**Comment by joroKr21** [comment]
Oh now I understand why CE2 returns a `Long`. I guess using `FiniteDuration` is good to signal that we are dealing with time here, but I don't see the point of attaching a unit to an instant in time.

**Comment by alexandru** [comment]
@djspiewak 

> FiniteDuration attaches a unit, but retains the unknown reference point problem. My point is that it's no worse than Long, and in fact actually has half as many issues.

I agree. It's regrettable that we don't have something in the stdlib that we can use for expressing Unix timestamps.
