### ISSUE TITLE
Add a third EC implementation to `IOApp` - Unstarted

### ISSUE THREAD

**Issue by Daenyth** [typelevel/cats-effect#907]
Right now `IOAppCompanionPlatform` on the `jvm` defines `final protected def executionContext: ExecutionContext = currentContext.get().executionContext`, and `currentContext` is initialized with `ClosedScheduler`, which implements the EC methods with `reject(): Nothing = throw new RejectedExecutionException("IOApp and its thread pools are shutdown")`

This is fine, but we've run into a pain point where code might get written like this:
```scala
object MyResource {
  def build(implicit ec: ExecutionContext): Resource[IO, MyResource] = ???
}

object BrokenIOApp extends IOApp.WithContext {
  protected def schedulerResource = MySchedule.impl[SyncIO]
  
  val resource: Resource[IO, MyResource] = MyResource.build
  // ^ Executed at static initialization time, this closes over the `ClosedScheduler`

  /* run... */
}
```

Executing that app results in something like:
```
java.util.concurrent.RejectedExecutionException: IOApp and its thread pools are shutdown
	at cats.effect.internals.IOAppCompanionPlatform.cats$effect$internals$IOAppCompanionPlatform$$reject(IOAppCompanionPlatform.scala:207)
	at cats.effect.internals.IOAppCompanionPlatform$$anon$2.schedule(IOAppCompanionPlatform.scala:151)
	at cats.effect.internals.IOTimer$$anon$1.apply(IOTimer.scala:47)
	at cats.effect.internals.IOTimer$$anon$1.apply(IOTimer.scala:40)
	[...]
```

There's no indication of what went wrong - the dev properly used the CE classes and interfaces, and didn't have any imperative code at play.

-----

Proposal: Adjust `ClosedScheduler` to implement `reject` with specific "IOApp is not yet initialized" or "IOApp has already run and terminated" messages.

I'd specifically like the "uninitialized" reject message to instruct the developer to examine their `IOApp` static body for anything that closes over `ExecutionContext` or `Concurrent[IO]` or `ContextShift[IO]`. That would help make this error easier to handle

**Comment by Daenyth** [comment]
Also, if we decided to keep the one ClosedScheduler state, and just change the message to the "uninitialized" help, then this is definitely binary-compatible. I can make a PR for that today.

**Comment by djspiewak** [comment]
Is there a particular reason that we don't just… start the pool right away? I guess the concern is that someone might initialize an `IOApp` but never run it?

**Comment by Daenyth** [comment]
It's very easy for a dev who doesn't know better to declare a public `val` on an IOApp and import it elsewhere. I've had to point it our it in code review more than once.

But maybe that's not a good enough reason (to not start the pool in the static body) - I don't know.
