### ISSUE TITLE
Implement SyncIO

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#924]
For now, we should just have `SyncIO` be a little newtype wrapper around `IO`, just so we can make forward progress. Long-term, it should be possible (and not hard) to write a synchronous-only runloop for `SyncIO` which is *much* faster than what is in `IO`, similar to what master does.

**Comment by vasilmkd** [comment]
Working on this.

**Comment by vasilmkd** [comment]
#1032 is merged. This can probably be closed.
