### ISSUE TITLE
Docs Guides Link 404

### ISSUE THREAD

**Issue by Slakah** [typelevel/cats-effect#929]
Upon clicking the guides link:

![guides-link](https://user-images.githubusercontent.com/16853/87318949-edf36c80-c520-11ea-8341-ce614b0b6bcc.png)

Results in a 404 response:

![guides-404](https://user-images.githubusercontent.com/16853/87319047-06638700-c521-11ea-88e7-8fdd2225ce72.png)

**Comment by RaasAhsan** [comment]
I think I broke this when I was adding tracing docs 😅

**Comment by RaasAhsan** [comment]
In the meantime, the tutorial should be available here (https://typelevel.org/cats-effect/guides/tutorial.html), though it'll probably change again after the PR is merged.
