### ISSUE TITLE
Add combinator inference for tracing

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#935]
The tracing implementation currently only traces a specific subset of `IO` combinators: `map`, `flatMap`, `async`, `cancelable`, `pure`, `delay`, `raiseError` and `suspend`. However, there are many *derived combinators* both within Cats Effect and also in Cats that we would rather pick when printing a compact fiber trace. Additionally, operations on concurrent data structures like `Ref` and `Deferred` should show up rather than the underlying `IO `operations that they make.

We already have the information we need in `IOTrace` and `IOEvent`, we just need to perform some more analysis on it (should this be configurable?). This is also going to give us a tiny performance boost since we're not allocating an integer on the stack or in the object headers anymore. (Also, look into having the `IOEvent` extends `Throwable` directly to avoid an extra allocation) Basically, we need to pick the last frame before hitting downstream user code, which should be pretty straightforward because we're in control of the call stack inside Cats Effect.

I'm wondering if there should also be a way for the user to specify what class prefixes to filter or ignore when trying to pick the most relevant stack frame. This should be sufficient for users who want to control the call sites that will show up in their fiber traces, but I'm not sure if this solution is going to work for a library like FS2, which effectively compiles an entire `IO` program.

**Comment by RaasAhsan** [comment]
I'd like to get this in before the 2.2.0 release, so will start working on it in a couple of days. I'm thinking we published a 2.2.0-RC2 after its merged in.

**Comment by Daenyth** [comment]
`mapN` and `parMapN` come to mind as high-value combinators to have traced.
