### ISSUE TITLE
Consider whether LinkedMap is still necessary

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#946]
As part of https://github.com/typelevel/cats-effect/pull/918, `Deferred` and `MVarConcurrent` were refactored so that callbacks are uniquely identified by a monotonically increasing long. This is in fact how `LinkedMap` tracks insertion order, so we may not actually need it anymore. If that's the case, we should remove it both on the 2.x series and the 3.x series (after https://github.com/typelevel/cats-effect/issues/942).

**Comment by djspiewak** [comment]
This is an absolutely lovely observation, and it seems likely to be true!

**Comment by SystemFw** [comment]
I'm on this btw
