### ISSUE TITLE
Idea: Change the behavior of SemigroupK.combineK for Resource

### ISSUE THREAD

**Issue by BalmungSan** [typelevel/cats-effect#949]
The current implementation of `SemigroupK.combineK` for **Resource** is the following:

```scala
def combineK[A](rx: Resource[F, A], ry: Resource[F, A]): Resource[F, A] =
  for {
    x <- rx
    y <- ry
    xy <- Resource.liftF(K.combineK(x.pure[F], y.pure[F]))
  } yield xy
```

This implies that both resources need to be successfully acquired and then it combines both of them using the **SemigroupK** instance of the effect of the resource.
This current behavior doesn't feel too useful for me _(I may be ignoring something)_ since it requires both **Resources** to be successfully acquired but then the common implementation of `combineK` for effects is to get the first one that was successful or the error of the first one.

------

I came across this while trying to implement the following use case:

I had three ways of getting some resource. And I wanted to try all these three in some order.
If the first one worked use that, if it didn't try with the second way and then the third one.

So, after checking the docs and seeing there was a **SemigroupK** instance for **Resource** I thought this would do work:

```scala
val r = r1 <+> r2 <+> r3
```

But, this ended in `r` being `r1` as long as all the three worked or failing with the exception of the first one to fail.
_(so, exactly the opposite of what I wanted)_

Hopefully, I could get what I wanted using `ApplicativeError.orElse` instead.
So, I wonder if there is really any reason or use case for this behavior.

----

Simple snippet to test the code:

```scala
import $ivy.`org.typelevel::cats-effect:2.1.4` 
  
import cats.implicits._
import cats.effect.implicits._
import cats.effect.{IO, Resource}

final case class Err(msg: String) extends Throwable(msg) 

def resource(id: Int, fail: Boolean = false): Resource[IO, Int] =
  Resource.liftF {
    if (fail) IO.raiseError(Err(s"Failed resource ${id}"))
    else IO.delay(println(s"Computing resource ${id}")).as(id)
  }

// You can play with the fail flag.
val r1 = resource(id = 1, fail = false)
val r2 = resource(id = 2, fail = false)
val r3 = resource(id = 3, fail = false)

// val r = r1 <+> r2 <+> r3
val r = r1 orElse r2 orElse r3

val program = r.use(x => IO.pure(x))
program.unsafeRunSync()
```

**Comment by djspiewak** [comment]
Just in case my 👍 wasn't clear enough… I'm *very* much in favor of this change. We should probably have a discussion about whether or not we consider it breaking for 2.x (my opinion: it's a bugfix, not a breaking change), but it should *definitely* be fixed to be as you describe for 3.x.

**Comment by BalmungSan** [comment]
@djspiewak I would like to give it a shot since it doesn't seem too hard to fix.
However, I am not sure from which branch should I start my development, and to which branch should I target the PR.

**Comment by djspiewak** [comment]
@BalmungSan Go for it! As for which branch to target, right *now* `Resource` doesn't exist on series/3.x (see #964), so it would need to be series/2.x, which is a shame because it's generally more fun to work on the ce3 stuff. :-) Once @SystemFw finishes porting `Resource`, we can make sure that your fix gets ported over so that we don't regress the functionality.
