### ISSUE TITLE
CoflatMap for Sync

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/cats-effect#97]
It appears that any [Applicative can form a CoflatMap](https://github.com/typelevel/cats/pull/2112) 

This personally strikes me as a useful value to have perhaps to generalize an Action describing an Action, but more so in effect suspension for things that implement Sync like Fs2's Stream which in order to get concurrency `Stream(1,2,3).map(i => Stream(i)).joinUnbounded` could instead utilized `Stream(1,2,3).coflatten.joinUnbounded` however I think this is a generally good thing to have available. The PR linked from cats can bring this easily for all `Sync` with the next Milestone.

Would this be something you would entertain?

**Comment by alexandru** [comment]
👍  I don't see the harm

**Comment by alexandru** [comment]
@ChristopherDavenport do you think this is still relevant, are you interested in doing some proposal or should we close it?

Spring cleaning 🙂

**Comment by ChristopherDavenport** [comment]
I think we can remove it. The consensus seems to be, if we want it for a type, it should use the method in it for cats.
