### ISSUE TITLE
Concurrent primitives tests depend on IO

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#970]
Currently the tests for the primitives living in `cats.effect.concurrent` can be found in `core`, separate from the `concurrent` subproject. I feel like this is not their proper place, considering that `concurrent` is now a separate library with no dependencies on `IO`.

(CE3)

**Comment by djspiewak** [comment]
I would tend to agree with you. The problem is that the *tests* depend on `IO`, even though the abstractions themselves do not. :-)
