### ISSUE TITLE
MVarSpec intermittent failure

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#983]
I saw this once. Not sure if it was a fluke, but it's worth investigating.

```
[error] ! modify is cancelable on take
[error]  java.util.concurrent.TimeoutException: null (Runners.scala:187)
```

**Comment by vasilmkd** [comment]
I ported these tests from CE2. Do you suspect it's the test itself or something in the runtime?

**Comment by djspiewak** [comment]
Update: also saw this just now:

```
[error] x put is cancelable
[error]  Set(1, 2) != Set(1, 3) (MVarSpec.scala:45)
[error] Added (1)
[error] 2
[error] 
[error] Missing (1)
[error] 3
[error] 
```

> Do you suspect it's the test itself or something in the runtime?

I'm not sure! I *tentatively* suspect that the test is not forcing deterministic ordering in some cases, but I haven't looked more closely. It would be much more exciting if it turns out to be a bug in `IO`!

**Comment by vasilmkd** [comment]
There's definitely non-determinism in `put is cancelable`, fixing now. I'll also take a look at the first one in this issue.

**Comment by vasilmkd** [comment]
@djspiewak I kind of made it worse now. Sometimes all tests pass, sometimes random tests hang, I can even get `take is cancelable` and `swap is cancelable` to hang. Here's the code I changed:

```scala
  "put is cancelable" in real {
    val op = for {
      mVar <- init(0)
      gate1 <- Deferred[IO, Unit]
      gate2 <- Deferred[IO, Unit]
      _ <- (mVar.put(1) *> gate1.complete(()) *> mVar.put(3)).start
      p2 <- (gate1.get *> gate2.complete(()) *> mVar.put(2)).start
      _ <- mVar.take // Take the initial 0
      _ <- gate2.get
      _ <- p2.cancel
      r1 <- mVar.take
      r3 <- mVar.take
    } yield Set(r1, r3)

    op.flatMap { res =>
      IO {
        res mustEqual Set(1, 3)
      }
    }
  }
```

**Comment by vasilmkd** [comment]
After fixing the flaky tests, I was unable to reproduce any of the other failures.
