### ISSUE TITLE
Make subsequent cancels await the first one

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#987]
```scala
    "return immediately from double cancel of sleeping thing" in real {
      IO.never
        .onCancel(IO.sleep(1.hour))
        .start
        .flatMap(f => IO.racePair(f.cancel, f.cancel))
        .as(ok)
    }
```

This test should *fail*. It passes right now because one of the two `f.cancel`s will "lose" the race and complete immediately.

**Comment by RaasAhsan** [comment]
For some more context, follow the discussion at https://gitter.im/typelevel/cats-effect-dev?at=5f1a0423c83e6242ed4e27dc. It goes on for quite awhile
