### ISSUE TITLE
Tune the async stuff

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#988]
`IO.async` and (probably by extension) `IO.racePair` are much, *much* slower than in CE2. Like, more than an order of magnitude. They offer stronger guarantees, so that's part of it, but I think we can probably do better than we are right now.

**Comment by vasilmkd** [comment]
Duplicate of #921?

**Comment by djspiewak** [comment]
Wow, I opened two duplicate issues within a few minutes of each other! Nice catch.
