### ISSUE TITLE
Preallocate the lambda in Cede

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#995]
```scala
          // Cede
          case 18 =>
            currentCtx execute { () =>
              // println("continuing from cede ")

              runLoop(succeeded((), 0), nextIteration)
            }
```

We can actually preallocate this lambda if we ignore `nextIteration`, which we can do if we use `execute(...)` to insert a `readBarrier()`, which should make `Cede` noticeably quicker. There may be a few other places where we can do this. Any lambda which doesn't close over anything other than `this` can be preallocated. Additionally, anything which *does* close over state other than `this` but which is evaluated in a deterministic timeslice can be preallocated if we leverage the `objectState` trick. This is probably part of what we need to do to optimize `start` and `racePair`.

**Comment by vasilmkd** [comment]
Issue addressed with #1004.
